### ISSUE TITLE
sccz80: incorrect float constant generated from constant expression

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#1007]
Reported in the [forum](https://www.z88dk.org/forum/viewtopic.php?pid=16964#p16964).

sccz80 is incorrectly computing the float constants in this example:

```
#include <stdio.h>
#include <stdint.h>

#define WIDTH  (40)

void do_something( uint8_t param1, uint8_t param2)
{
    printf( "param1: %u\n", param1);
    printf( "param2: %u\n", param2);
}

void main()  
{
    printf( "expect: 18, 20\n");
    do_something( WIDTH * 0.45, WIDTH * 0.5);
}
```

zcc +zx -v --list -clib=new test.c -o test -lm -create-app

The result prints param1 and param2 as zero when the expected answers are 18 and 20.

The generated code:

```
57    0031  21 2E 00    	ld	hl,i_3+0
58    0034  CD 00 00    	call	dload
59    0037  CD 00 00    	call	ifix
60    003A  E5          	push	hl
61    003B  21 2E 00    	ld	hl,i_3+0
62    003E  CD 00 00    	call	dload
63    0041  CD 00 00    	call	ifix
64    0044  E5          	push	hl
65    0045  CD 00 00    	call	_do_something
```

shows that do_something is passed the same float constant for both params and that constant is zero so there is something wrong in sccz80's float constant calculation.

```
94    002E              .i_3
95    002E              	;0.000000
96    002E  00 00 00 00 00 00 
                        	defb	0,0,0,0,0,0
```

A compile with zsdcc performs correctly:

zcc +zx -v --list -clib=sdcc_iy test.c -o test -lm -create-app

**Comment by suborb** [comment]
Obviously there's still an inefficiency here in that we load a fp constant and then convert to an integer value.

**Comment by suborb** [comment]
For reference #1011 sorted out the inefficiency mentioned above
