### ISSUE TITLE
(classic) Add Super-80 support

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#1008]
This one is about 4+ machines in one so should keep me busy for a while. 

### Super80

- Z80 @ 2MHz
- 16k, 32k or 48k RAM (0000-BFFF)
- 12k ROM (C000-EFFF)
- 3.5k RAM (F000-FDFF), comes with the "64k ram" modification
- 0.5k RAM (FE00-FFFF) for Chipspeed colour board

16x32 character mapped at 0xbe00 by default

### Super80 VDUEM

- Z80 @ 2MHz
- 16k, 32k or 48k RAM (0000-BFFF)
- 12k ROM (C000-EFFF)
- 2k Video RAM (F000-F7FF) banked with Colour RAM (modified Chipspeed board)
- 2k PCG RAM (F800-FFFF) banked with Character Generator ROM
-  MC6845 on $10 and $11

Information gathering:

- [x] Emulator is mame
- [x] Load via quickload
- [x] ROMs located

Probable features:

- [x] Mame quick load binary output
- [x] Generic console (TTL) (super80, super80d, super80m)
    - [ ] Set font on super80m to toggle character set?
- [x] Generic console (TTL colour) (super80m)
    - [x] Map colours to conio
- [x] Generic console (6845) (super80r, super80v)
    - [x] UDGs
    - [x] Custom font
    - [x] Lores graphics (2x2 matrix)
    - [x] Colour (super80v)
    - [x] Disable cursor
    - [x] Map colours to conio
- [x] Inkey keyboard driver
- [x] Lores graphics (super80e)
- [x] One bit sound (bit 3 on port 0xf0)

### Links

* https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=4031#Post4031
* http://avitech.com.au/?page_id=3088
* http://interbutt.com/mess/super80/

**Comment by UncleBod** [comment]
The Electronics Australia magazine referred to in one of the [links](http://interbutt.com/mess/super80/ ) can be found [here](https://archive.org/details/EA1981/page/n23).

**Comment by suborb** [comment]
I'm going to close this one now - the basics are there and any additional features can be new issues.
