### ISSUE TITLE
[abc80][bug?] Malformed binary? doscopy: "Error converting file "../build/xchase.bac""

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1025]
Since at least November the abc80 binary has changed and is considered malformed by 
tools used to insert it into disks such as dosgen.
It was OK on snapshots from September.

This is how I build disk images:
```
abc80:
	$(Z88DK_PATH)$(MYZ88DK) +abc80 -lm -subtype=hex -zorg=49200 \
	$(SCCZ80_OPTS) \
	-pragma-include:$(CFG_PATH)/z88dk/zpragma_clib.inc \
	-D__ABC80__ -clib=ansi -vn -DFULL_GAME \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DLESS_TEXT \
	-DSIMPLE_STRATEGY \
	-DNO_BLINKING \
	-DNO_HINTS \
	-DNO_WAIT \
	-DNO_BORDER \
	-DNO_CONTROL_INSTRUCTIONS \
	-DNO_RANDOM_LEVEL \
	-DNO_SET_SCREEN_COLORS \
	-DNO_SLEEP \
	-DFLAT_ENEMIES \
	-lndos -create-app \
	$(FULL_FILES)
	$(TOOLS_PATH)/z88dk/abc80/bin2bac2$(COMPILEDEXT) a.bin $(BUILD_PATH)/xchase.bac 49200
	$(TOOLS_PATH)/z88dk/abc80/dosgen$(COMPILEDEXT) $(BUILD_PATH)/FULL_abc80.dsk 
	$(TOOLS_PATH)/z88dk/abc80/doscopy$(COMPILEDEXT) $(BUILD_PATH)/FULL_abc80.dsk -b $(BUILD_PATH)/xchase.bac
	rm a.bin 
	mv $(BUILD_PATH)/xchase.bac $(BUILD_PATH)/FULL_abc80.bac
	mv a.ihx $(BUILD_PATH)/FULL_abc80.ihx 
```

**Comment by Fabrizio-Caruso** [comment]
@suborb
I still get a bad binary for doscopy with today's snapshot (16/12/2018).

**Comment by Fabrizio-Caruso** [comment]
The binary may be good even though dosgen complains.
I can run it with abc80sim in .ihx format.
I may need to use a hex editor to see what the difference is.

**Comment by suborb** [comment]
I've just looked at your makefile - I forgot you were using the -subtype=hex version.

I fixed the -subtype=default so that a working .bac file was generated - hence why you're not seeing any difference.

Has dosgen changed in anyway? Or have you just transitioned over a size limit?

**Comment by Fabrizio-Caruso** [comment]
@suborb, I am using the very same dosgen file

I have recompiled and rebuilt the same code with
Z88DK 16/12/2018 
Z88DK 25/09/2018 -> fails to insert .bac into disk image

Nevertheless I must admit that both .ihx files can be loaded directly and both seems to work.

Could this be related to relocatable vs fixed memory binary? Has something changed in this respect?

[OK_25092018.zip](https://github.com/z88dk/z88dk/files/2683567/OK_25092018.zip)
[KO_16122018.zip](https://github.com/z88dk/z88dk/files/2683568/KO_16122018.zip)

**Comment by Fabrizio-Caruso** [comment]
@suborb , yes, indeed that is the same error.

I have not tested the .bac files directly because I am having a problem with abc80sim emulator.

The .bac file we get now is not good for doscopy for some reason.
The .ihx are still good for abc80sim emulator. So the problem could well be on the tool but why?

**Comment by suborb** [comment]
I just appended 10 bytes to the end of the .bin file and re-ran bin2bac2 and then the file goes in without problems.

It's probably just an edge condition with the size of the file being an exact multiple of the block size or something like that.

**Comment by Fabrizio-Caruso** [comment]
@suborb, how come it worked before? Just a lucky coincidence?
If that is the case, then bin2bac2 is broken.

**Comment by suborb** [comment]
The old file was 15 bytes longer so it didn't hit whatever condition it is. So yes, I think bin2bac2 is broken.

**Comment by Fabrizio-Caruso** [comment]
@suborb as usual you are: bin2bac2 is not realiable.
Both new and old Z88DK snapshots produce good .ihx files (good enough for the abc80sim emulator)
but bin2bac2 produces a malformed .bac file with the bin produced by the new Z88DK snapshot (abc80sim can load previous .bac but not new one).
So I am now trying to get a better tool to produce .bac files.
