### ISSUE TITLE
zcc --help only shown when you also provide a +config

### ISSUE THREAD

**Issue by obiwanjacobi** [z88dk/z88dk#1045]
`zcc -h` or `zcc --help` errors out on missing a `+config` file.
That is illogical...
(nightly 31-12-2018)

**Comment by suborb** [comment]
If you don't specify any option then you get the help you want.

**Comment by obiwanjacobi** [comment]
Then there is no more use for the -h and --help options and they can be removed.... ?

**Comment by suborb** [comment]
Sorry for the silence, there was a use for that option, I just didn't get around to implementing it until now.
