### ISSUE TITLE
TI83 can't build with Plain TIOS startup flag

### ISSUE THREAD

**Issue by tccolin70** [z88dk/z88dk#1047]
i am unable to compile my code with this command line:
zcc +ti83 main.c -clib=ansi -startup=10 -o main
i am targetting Plain TI-OS
it seems to compile fine without the startup flag though

here's the console log:
`Error at file '/home/tccolin70/z80dev/z88dk/lib/config/../..//lib/target/ti83/classic/ti83_crt0.asm' line 313: symbol 'oninterrupt' not defined
Error at file '/home/tccolin70/z80dev/z88dk/lib/config/../..//lib/target/ti83/classic/ti83_crt0.asm' line 269: symbol '_runindicoff' not defined
Errors in source file /home/tccolin70/z80dev/z88dk/lib/config/../..//lib/target/ti83/classic/ti83_crt0.asm:
Error at file '/home/tccolin70/z80dev/z88dk/lib/config/../..//lib/target/ti83/classic/ti83_crt0.asm' line 313: symbol 'oninterrupt' not defined
                   ^ ----       res     oninterrupt,(iy+onflags) ; Reset [On]-flag (stops "ERR:Break")
Error at file '/home/tccolin70/z80dev/z88dk/lib/config/../..//lib/target/ti83/classic/ti83_crt0.asm' line 269: symbol '_runindicoff' not defined
                   ^ ----       call    _runindicoff    ; stop anoing run-indicator
make: *** [Makefile:2: all] Error 1
`

here's the main.c file:

#include <stdio.h>
main() {
printf("hello world\n");
}

**Comment by zx70** [comment]
I found the error cause:  the improved z80asm versions are fully case sensitive.
I'm fixing the CRT0 stub to comply with the declared function names.
Be aware you are experimenting with extremely pooroptions, don't expect much  :)

**Comment by zx70** [comment]
While I was fixing this one I noticed the dangerous way we used to boot in startup modes 2,3 and 8:
Send(9prgm..   (+extra non-ascii characters)

We might have problems also ther.
