### ISSUE TITLE
[req] z88dk-dis: parse 'addr' and 'const' comments in map file

### ISSUE THREAD

**Issue by obiwanjacobi** [z88dk/z88dk#1049]
Example of a const symbol in a map file
`STDIO_MSG_ICTL                  = $0007 ; const, local, , asm_vioctl, , config_private.inc:385`
Example of an address symbol in a map file
`loop                            = $06EA ; addr, local, , l_small_atou, code_l, l/z80/ascii/txt_to_num/small/l_small_atou.asm:26`

Example of a dis-asm file that uses const labels as address labels (RST00):
```asm
bios_interrupt_enable_count:
                    di                                      ;[0000] f3
memorymanager_bankid:
                    jp      bios_reset_init                 ;[0001] c3 74 00
debug_regs_var_base:
                    nop                                     ;[0004] 00
                    nop                                     ;[0005] 00
debug_regs_var_bc:
                    nop                                     ;[0006] 00
                    nop                                     ;[0007] 00
```

It would enhance readability of the dis-asm when constant labels are not used as address labels.

**Comment by suborb** [comment]
Can you attach the binary and .map file that's created please? - I've just checked the code and it does differentiate between the two and I can't reproduce this with the test files I'm using.

**Comment by obiwanjacobi** [comment]
Sure.
[helloworld.zip](https://github.com/z88dk/z88dk/files/2722838/helloworld.zip)
contains .c, .map, .dis.asm and the .bin files

**Comment by obiwanjacobi** [comment]
Ah, never mind.
I forgot to add my data section to the memory model when I converted my target structure/files.
The data was actually ending up at the beginning of the memory - overwriting my RST handlers.
Sorry.
