### ISSUE TITLE
xample.c (x11 demo) fails

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1064]
looks like the xample demo fails in picking the font (in sprite data format) anymore
testing on the Spectrum target shows the behavior clearly

**Comment by suborb** [comment]
The X11 code has always played very freely with pointers to say the least!

The problem is this line in XDrawString():

```
// ======= I have absolutely no idea on why this is necessary ! =======
//        gc = *gc;
// ====================================================================
```

Uncommenting it fixes the problem

**Comment by suborb** [comment]
That's ok...I've now made sccz80 complain about struct assignment/struct argument passing so that the results aren't "surprising"
