### ISSUE TITLE
(classic) TS2068 mode switching

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#1069]
The TS2068 screen driver should support switching to the Timex hires and high colour screens.

The ULA used by the Timex machines provides a number of additional screen modes. These are controlled using Port 0xff. An unfortunate side effect of this is that a few games, like Arkanoid, which expect reading 0xff to produce screen and ATTR data bytes when the ULA is reading the screen memory, will not work, since reading 0xff on the Timex returns the last byte sent to the port. It is not known if this port is fully decoded but it seems likely that it is partially decoded, as on the Spectrum. Port 0xff is also used to enable/disable the timer interrupt and select which bank of memory to use for the horizontal MMU. The byte to output will be interpreted thus:

```
  Bits 0-2: Screen mode. 000=screen 0, 001=screen 1, 010=hi-colour, 110=hi-res
  Bits 3-5: Sets the screen colour in hi-res mode.
              000 - Black on White     100 - Green on Magenta
              001 - Blue on Yellow     101 - Cyan on Red
              010 - Red on Cyan        110 - Yellow on Blue
              011 - Magenta on Green   111 - White on Black
  Bit 6:    If set disables the generation of the timer interrupt.
  Bit 7:    Selects which bank the horizontal MMU should use. 0=DOCK, 1=EX-ROM.
```

Screen 0 is the normal screen at 0x4000. Screen 1 uses the same format but at 0x6000.

The hi-res screen uses the data area of screen 0 and screen 1 to create a 512x192 pixel screen. Columns are taken alternately from screen 0 and screen 1. The attribute area is not used. In this mode all colurs, including the BORDER, are BRIGHT, and the BORDER colour is the same as the PAPER colour.

The multi-colour screen uses the data area of screen 0 for its data and the data area of screen 1 for its attributes, giving 2 colours per 8x1 pixel block. The attribute area is in the same byte order as the data area, which means MLT files, which have the attribute are in series, must be converted to be displayed.

**Comment by ped7g** [comment]
JFYI:

On ZX-Next the Timex modes and port 0xFF are supported too (including the extra post-processing of colours by ULANext), but you have to set the bit 2 in Next Reg 0x08 "Peripheral 3 setting".

Also on Next the Timex mode is recommended way for double-buffering of classic mode, as using the ZX128k shadow bank will disable Layer-2 visibility due to memory chips timings (128k bank used for shadow VRAM is slightly slower than the ZX48/Timex bank used for 0x4000..0x7FFF).

**Comment by aralbrec** [comment]
All ports are fully decoded in timex machines.
