### ISSUE TITLE
Ticks won't compile with VS2017

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [z88dk/z88dk#1081]
The error is in line 43 of ticks.c, there is whitespace after the \ in that line.
Line reads:
#define LEA(r1, r2, s1, s2, t) do { \ 

Visual Studio 2017 emits an error. Clang/LLVM issues a warning but compiles on MacOS.
Recommend establishing a policy of trimming whitespace upon file save in editors to avoid this.
(I'm a bit surprised my VS2017 instance didn't do this initially.)
Justification: ISO ISO/IEC 9899:201x n1570 5.1.1.2p2

**Comment by zx70** [comment]
hope this fixes :)

**Comment by QwazyWabbitWOS** [comment]
Indeed it does.
