### ISSUE TITLE
-subtybe=dsk zcc option failing

### ISSUE THREAD

**Issue by FlorentFlament** [z88dk/z88dk#1089]
Hello,

A couple of weeks ago, I was able to generate a `.dsk` CPC disk image using the following `zcc` command. Recently it has been failing with the following error message:

```
$ zcc +cpc -lndos -subtype=dsk -create-app -o helloc hello_c.c
cpc: Can't write disc imageBuilding application code failed
$
```

Is this a regresion ?

Here's the `hello_c.c` that has been used:
```
$ cat hello_c.c 
#include <stdio.h>

int main() {
    printf("Hello World !\n");
    return 0;
}
```

Regards.
Florent

**Comment by suborb** [comment]
Sorry, I  must have broken it when I added +3 disc support.

Hopefully repaired now, thanks for reporting.

**Comment by FlorentFlament** [comment]
Yep, this is fixed. That was fast ; )
Thanks !
