### ISSUE TITLE
sccz80: Callee cleanup of functions destroys return value.

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#109]
int run_sqrt(double x, double e) __z88dk_callee
    {
        double r = sqrt(x);
        printf("Sqrt(%f) should be %f but was %f\n",x,e,r);
        return 1;
   }

Generated function prologue:

        ld      hl,1    ;const
        pop     bc
        pop     bc
        pop     bc
        pop     de
        ld      hl,18   ;const
        add     hl,sp
        ld      sp,hl
        push    de

**Comment by aralbrec** [comment]
I don't know if this is related but some time ago I put in a fix to avoid altering the exx set when the return type is double:

https://github.com/z88dk/z88dk/commit/09fbdfcef5aaf955dd71e86d0b186bd8a561ed41#diff-29340938e68a2ca908ff6c1de35c971f

**Comment by suborb** [comment]
That looks like the cleanup after a function call.

This is for cleaning up the stack inside a function. Doubles were okay, but ints/longs were being trashed.
