### ISSUE TITLE
(classic) Attache: plotted points not visible

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#1097]
[From RobertK email]

"Everything works, but plotted points not actually seen".

I can't remember the code, but suggests that the paging (if there is any) is wrong and we're hitting main memory not VRAM.

**Comment by zx70** [comment]
Odd,  Fabrizio confirmed that the new drivers were working,  I'll check it.

**Comment by zx70** [comment]
![attache](https://user-images.githubusercontent.com/10224992/52464863-c5718100-2b7c-11e9-8197-289128df87a0.jpg)
I tried with globe.c and coswave.c.. everything works as expected: pixel drawing, line drawing and "classic" sprites,

**Comment by suborb** [comment]
That looks good, thanks for checking it out.

**Comment by zx70** [comment]
I think I understood what happened:  a missing clg(); at the beginning to enter ingraphics mode?
