### ISSUE TITLE
(classic) Pacman Tile Maker

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#1099]
[From RobertK email]

The Pacman tileset is not complete and not all graphic points are available.

It would be nice if we could convert a standard 8x8 font into a ROM suitable for the Pacman hardware.

**Comment by zx70** [comment]
I thought a little at it,  we have few interesting configurations  possible: mixed text and graphics symbols,  all monochrome graphics symbols to push the resolution at the maximum possible (not much to gain, though), and low rez graphics symbols chosen in a way permitting a bit of colour shuffling.  I think a simple static font including symbols on a 2x3 matrix will suffice, easy variants could provide coloured text.

**Comment by zx70** [comment]
![pacman-font](https://user-images.githubusercontent.com/10224992/53187249-06e54000-3603-11e9-9ac4-dcb8674bb383.png)

This was obtained by converting FONT8.BIN (2048 bytes) still present in the 'ansi' folder in libsrc

**Comment by suborb** [comment]
@zx70 thanks for doing that, now we've got the basics we can do a bit more!

**Comment by zx70** [comment]
yup, I'm extending the tool to stick the 3x2 graphics symbols in the converted font, it takes 64 characters, there's space for 2 copies encoded in different colours but I'm not sure.   I wonder if it is worth to add an option to merge two fonts in a coloured one

**Comment by suborb** [comment]
Nice. I was mulling over shifting to a standard ascii range when running with a custom font. 

I think we should be able to merge fonts - eg combine a udg style graphics with a text font and blocks as needed.

**Comment by zx70** [comment]
![untitled](https://user-images.githubusercontent.com/10224992/53347694-ef1afe00-3919-11e9-8937-cc3b87cfc531.png)

**Comment by zx70** [comment]
This is only a quick and dirty test of the font, I can leave Dominic the lib part  :P    This new rez (with a better driver than this mockup) sould be 84x72.
The 3x2 blocky graphics characters are between 192 and 255,  the conversion tool at the moment deals with fonts encoded from chr(0) to chr(127), eventual extra data is overwritten with the graphics data.

**Comment by zx70** [comment]
I put a prebuilt font in the support/pacman folder

**Comment by zx70** [comment]
I just discovered one of the limits of the driver I used in the tests:   the div3 table was too short to work on 84 values..

**Comment by zx70** [comment]
Graphics driver updated, it now works at a slightly higher resolution (84x72) but the ROM font currently present in support/pacman must be provided.

**Comment by zx70** [comment]
New graphics driver is now ready, I wouldn't waste time and energy to provide a 4x4 font.   A graphics only font covering the whole 256 characters range could push the resolution to 112*72 (4x2 pseudo-graphics character blocks), but there wouldn't be space left for text characters.    I'm not touching the console driver, probably it is easier for Dom to do the magic with the new console skeleton  :)
