### ISSUE TITLE
[px8][info] Cannot find definition for target -subtype=px32k make: *** [Makefile:2268: px8] Error 1

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1113]
Which options should I use now instead of -subtype=px32k?
I am getting this error now:
Cannot find definition for target -subtype=px32k make: *** [Makefile:2268: px8] Error 1

**Comment by zx70** [comment]
New target name is just px8, the 32K size is chosen automatically when necessary.

**Comment by Fabrizio-Caruso** [comment]
Using subtype=px8 seems to solve the compilation errors.
