### ISSUE TITLE
sccz80 generates wrong code in msys2 ...

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#1116]
... and most tests in testsuite fail.

The cause is a broken implementation of tmpfile() in msys2: it creates the temporary file in the root directory of C:\ and therefore needs elevated privileges.
It returns NULL and sets errno to EACCES when run with normal privileges.

This causes the sccz80 compiler to generate wrong code.

**Comment by pauloscustodio** [comment]
Note: tmpfile() of MinGW seems OK, it's only in msys2 that it tries to use C:\

**Comment by suborb** [comment]
Ouch. Just to confirm: the nightly builds were correct and it was just your environment that was broken?

**Comment by pauloscustodio** [comment]
> Ouch. Just to confirm: the nightly builds were correct and it was just your environment that was broken?

Yes, the nightly builds are built with mingw32, which has a good implementation of tmpfile(), using /tmp.

msys2, which is a free implementation of cygwin, has a bad tmpfile().

The reason I had so strange behavior in my environment is that sometimes I was using sccz80 built by mingw32 in a msys2 environment, and all was well.

In a wrong build, all the stack setup and stack cleanup were missing.
