### ISSUE TITLE
(classic) Create uPD7220 video driver

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#1119]
Used by:

* A5105
* QX10
* NCR DMV
* MZ3500

Datasheet: http://www.vintagecomputer.net/fjkraan/comp/qx10/doc/nec7220.pdf
CP/M driver: http://www.cpm.z80.de/roche/NCRGRAF.ASM
Design manual: http://bitsavers.trailing-edge.com/components/nec/uPD72220_GDC_Design_Manual_Version_3.pdf

Tasks:

- [x] 40/80 column printing
- [x] vpeek
- [ ] colour mapping
- [ ] inverse
- [x] scrolling
- [x] mode switching
- [ ] hires modes

Modeswitching is frustrating me at the moment.

**Comment by suborb** [comment]
Some progress (a5105/BIC), character set:

![screenshot 2019-03-07 at 20 21 26](https://user-images.githubusercontent.com/394721/53986810-17271000-4117-11e9-88be-bd3e72c08a1a.png)

And the usual gencon screen (after applying some guesses):

![screenshot 2019-03-07 at 20 23 51](https://user-images.githubusercontent.com/394721/53986833-21e1a500-4117-11e9-8e88-5c2059243e0d.png)

**Comment by zx70** [comment]
not bad really  !

**Comment by suborb** [comment]
Come back onto this one now, source code for the a5105 can be found here: https://hc-ddr.hucki.net/wiki/doku.php/homecomputer/bic

**Comment by suborb** [comment]
I didn't enjoy doing this at the time, so it's unlikely it'll ever be finished. Closing so not to raise false hope.

**Comment by zx70** [comment]
I put the original qx10 bios sources in docs/targets/epson_qx10
