### ISSUE TITLE
fake results from the nightly build

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1123]
I have the impression that the code built by 'nightly'  is outdated:

######################################################################### 
fatal: Not a git repository (or any of the parent directories): .git 
fatal: Not a git repository (or any of the parent directories): .git 
fatal: Not a git repository (or any of the parent directories): .git

**Comment by suborb** [comment]
The nightly process is:

* update to latest from git
* run make setup
* create tarballs without the .git folder
* extract tarball and build from it

It’s the 3rd stage which has reporting those comments - the top level makefile tries to determine the version. I need to pipe away the errors. 

The code is up-to-date though.
