### ISSUE TITLE
Can't open config file

### ISSUE THREAD

**Issue by sasq64** [z88dk/z88dk#1128]
After successfully running `build.sh` and adding the bin directory to my path;
```
$ zcc +abc80 -lm -o test -create-app test.c
Can't open config file /usr/local/share/z88dk//lib/config/abc80.cfg
$ which zcc
/home/sasq/projects/z88dk/bin/zcc
```
README says you can use zcc without installing it, is this no longer true ?

EDIT: If I try to install it I get lots of errors like these;
```
install: missing destination file operand after '{,//usr/local/share/z88dk/}libsrc/stdlib/l_bsearch_callee.asm'
```
And I get a local directory created called just `{,`

**Comment by suborb** [comment]
I think in the first case you're missing setting the ZCCCFG environment variable. It needs to point to {z88dk-dir}/lib/config/

And the second case came up last week. I'm guessing you're on Ubuntu, or a platform where /bin/sh is dash not bash. In which case you have to install with `make SHELL=/bin/bash install`

It looks like I've not updated the README with the latter change, but it's on the wiki here: https://github.com/z88dk/z88dk/wiki/installation
