### ISSUE TITLE
(sdcc) Pre-built sdcc.exe claims libgcc_s_seh-1.dll to be missing

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1150]
ditto

**Comment by zx70** [comment]
My fault, i was using sdcc in place of zsdcc  :(

**Comment by zx70** [comment]
nope, the zcc option "compiler=zsdcc" is not a valid workaround (probably falls back to zccz80)

**Comment by zx70** [comment]
fixed, local problem  :(

**Comment by zx70** [comment]
Still problems, sorry for reiterating the incident, my current env is a mess.

**Comment by suborb** [comment]
Hopefully the next build will have the right dependencies in the kit.

Sadly the kit size will be huge since libstdc++ is one of them and it's 15M

**Comment by zx70** [comment]
Works !   Thankyou, the ZIPed archive is only 4MB bigger.
My feeling is that the current kit is now more mature, the collider.c demo couldn't be built for quite a while after including sdcc and evolving the whole kit; now it is valid again, thus I put it in the "examples" folder.
In the spare time I'm also adjusting the demos to make them compatible with SDCC (microman is very close).
