### ISSUE TITLE
z80asm: wrong parse of expressions with parenthesis

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#1177]
Instruction: ld bc, ($2A << 8) + $ff
is assembled as ED 4B FF 2A, i.e. as LD BC,(NN) instead of the correct LD BC,NN

Adding a + before the open parenthesis solves the problem

**Comment by feilipu** [comment]
Got [tangled in this](https://github.com/feilipu/RC2014-YM2149/blob/c64341f31bafe864950fba53e1dd12d6a9178959/PS-PTxPlay.asm#L269) converting a program from `sjasm` to use `z80asm` recently.

**Comment by pauloscustodio** [comment]
Fails for test case ```ld bc,(1) + (2)```
