### ISSUE TITLE
argc corrupt when using implicit int

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1178]
Try the comp.c sample in the OSCA subdir building it for CP/M.   argc gets very big.
Everything is solved by explicitly declaring int (main)

**Comment by suborb** [comment]
For compatibility with sdcc main is always a __stdc function. 

I suspect the k&r parsing bit in sccz80 isn’t setting the appropriate flags.

**Comment by suborb** [comment]
It wasn't. It should be now!

**Comment by zx70** [comment]
I'm not sure it is solved, I still have to add "int" as a prefix to function "main" to make argc/argc work correctly.   Checked with wc.c and comp.c

**Comment by suborb** [comment]
I can't reproduce this anymore - is your sccz80 definitely up-to-date?

**Comment by zx70** [comment]
I see, I'm probably slightly out of sync.  I'll check it again as soon as "nightly" will be reachable.

**Comment by suborb** [comment]
Back up now - it looks like the router crashed this morning.

**Comment by zx70** [comment]
problem persists.  edit wc.c and remove "int" before main(.
the built program should now try to open an empty filename in place of the given parameter.

**Comment by suborb** [comment]
Got it, thank you. Arrays weren't being setup properly in "implicit int" functions.

**Comment by zx70** [comment]
thank you!
I'd be very glad to have also a hint on the readbyte() problem I'm having with the trsdos  🙄

**Comment by suborb** [comment]
I think that's my bug too...

**Comment by zx70** [comment]
could be, but the cp/m version of the same function works. . it is puzzling me to death

**Comment by suborb** [comment]
Yeah, it's really odd. Compiling it, we get this (or something similar, I'm hacking it down at the moment):

```
        push hl  <--- save fastball paramter
        push    bc  <--- make space for struct TRSDOS_FILE *
        ld      hl,6    ;const   <--- Get hold of parameter, this should be +2
        add     hl,sp
        call    l_gint  ;
        pop     bc
        push    hl
```

That ld hl,6 should be ld hl,2. I'm trying to reproduce it in a different file, it's proving tricky though.

**Comment by suborb** [comment]
Oh, I'm so, so, very sorry, that's a terrible oversight by me.

Please rename the parameter from "handle" to "fd" and the it'll work as you expect.

**Comment by zx70** [comment]
so fast,  thanks!
I presume 'handle' is sort of reserved? 
don't tell me you have the 'fd' exception hardcoded somewhere  😫

**Comment by suborb** [comment]
No, it just adjusts the stack locations using the parameter names defined in the prototype (where it's fd) rather than at the function declaration (where the parameter is handle).

So fastcall parameters end up not being moved if there's a naming mismatch.

**Comment by zx70** [comment]
ook, that makes sense. :)  ..a warning, in the long term would suffice
