### ISSUE TITLE
 [classic] fcntl: readbyte() failing in some of the libraries

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1195]
Some of the implementations of readbyte() written in C may collide with zccz80 and the way it deals with the 'fastcall' parameter passing mode.
As Dom explained: "sccz80 adjusts the stack locations using the parameter names defined in the prototype (where it's fd) rather than at the function declaration (where the parameter is handle).
So fastcall parameters end up not being moved if there's a naming mismatch."

This incident keeps track of the only readbyte() function bugfixes to quickly recover the overall fcntl consistency.

**Comment by suborb** [comment]
I fixed the root problem last night :)

**Comment by zx70** [comment]
Dominic's magic..
