### ISSUE TITLE
(sccz80) Not promoting left hand integral type to double

### ISSUE THREAD

**Issue by fu-sen** [z88dk/z88dk#1212]
I am using the latest Nightly Build on Windows 10.

When I do make in **examples/g800**, it fails in **sin.c**:
![スクリーンショット 2019-07-01 19 47 37](https://user-images.githubusercontent.com/5434159/60430915-6dc1d800-9c39-11e9-87a3-5c3cef7b5543.jpg)

I investigated the cause:
[examples/g800/sin.c](https://github.com/z88dk/z88dk/blob/master/examples/g800/sin.c)
```
    y = (int)(24 * (1.0 - sin(x / 144.0 * 3.14 * 8)));
```
It seems that there was a problem with floating point calculations because "x" is at the beginning of the expression.
I rearranged the formula and added a decimal. As a result, it worked:
```
    y = (int)(24 * (1.0 - sin(3.14 * 8.0 * x / 144.0)));
```
I could send a pull request, but that would be an easy fix.

**Comment by suborb** [comment]
@fu-sen thanks for the heads up. I think it's a problem with not promoting the integer LHS to double when the RHS is already a double.

I'll get in a fix soon

**Comment by fu-sen** [comment]
Examples/g800/make works fine with the latest build updated:
![Uploading スクリーンショット 2019-07-02 18.36.14.jpg…]()

**Comment by fu-sen** [comment]
Examples/g800/make works fine with the latest build updated:
![スクリーンショット 2019-07-02 18 36 14](https://user-images.githubusercontent.com/5434159/60502401-b12f4b80-9cf8-11e9-8911-7b8f91b5e5c7.jpg)
