### ISSUE TITLE
(msx) The value of msx_type such as MSX2 is incorrect and MSX2+ / turbo R correspondence

### ISSUE THREAD

**Issue by fu-sen** [z88dk/z88dk#1220]
I discovered that the value of msx_type is strange except for MSX1 (mostly MSX2):
```
#include <stdio.h>
#include <msx.h>

main () {
   printf("%u", msx_type());
}
```
```
 zcc +msx -lmsxbios -create-app -bn msxtype msxtype.c
```
MSX1 (correct):
![msxtype_msx1](https://user-images.githubusercontent.com/5434159/60700693-c2b06780-9f33-11e9-8f38-94d36b2d2bb8.png)

MSX2 (The correct value is 2):
![msxtype_msx2](https://user-images.githubusercontent.com/5434159/60700729-d78cfb00-9f33-11e9-8d45-36e3c9333306.jpg)

I found the cause:
https://github.com/z88dk/z88dk/blob/master/libsrc/target/msx/msxbios/msx_type.asm:
```
ld	h,3
```
Therefore, 3(h)✕256+2(l=value of MSX2)=770

Also, increase the correspondence between MSX2+ and MSX turbo R to msx_type.
Many MSX emulators are supported by MSX2+, and also several MSX turbo R emulators.
MSX, 2, 2+ and turbo R have their value at $002d:
http://map.grauw.nl/resources/msxsystemvars.php

**Comment by zx70** [comment]
Thankyou for spotting it so precisely and for the further information !
At the moment I'm avoiding to extend this function, though.   If you think it can be useful I'd rather provide a pointer definition in the header file, or you can just define it yourself:
extern unsigned char  MSX2_SUBVER @0x002d;

There are at least two other ways to make a similar definition (probably this is the worse one) but I'm addicted to it   :)

**Comment by fu-sen** [comment]
Perhaps I think it's used internally, so I understand that suggestion.
It is a simple and ideal implementation.

**Comment by zx70** [comment]
My major concern is to avoid to ungroup the MSX2 machines family in msx_type().   I'm adding MSX2_SUBTYPE in the header file.

**Comment by fu-sen** [comment]
The implementation is fulfilled in response to this issue. I will test later.

**Comment by fu-sen** [comment]
My PC updated Nightly Build 20190706 and tried the following source "msxtype.c":
```
#include <stdio.h>
#include <msx.h>

main () {
   printf("msx_type()  =%u\n", msx_type());
   printf("MSX2_SUBTYPE=%u\n", MSX2_SUBTYPE);
}
```
MSX1 is mainly a cassette. On the other hand, MSXturboR has the cassette removed.
Created cassette tape image msxtype.cas file and disk BLOAD format msxtype.msx file:
```
zcc +msx -lmsxbios -create-app -bn msxtype msxtype.c
zcc +msx -lmsxbios -create-app -subtype=disk -bn msxtype msxtype.c
```
MSX1:
![Dropbox_0052](https://user-images.githubusercontent.com/5434159/60752865-e5ab4c00-a005-11e9-85a4-ff0126f8c852.jpg)
MSX2:
![Dropbox_0053](https://user-images.githubusercontent.com/5434159/60752877-f9ef4900-a005-11e9-91ff-0532f0afc885.jpg)
MSX2+:
![Dropbox_0054](https://user-images.githubusercontent.com/5434159/60752888-0d9aaf80-a006-11e9-825c-6106cb6e337f.jpg)
MSX turbo R:
![Dropbox_0055](https://user-images.githubusercontent.com/5434159/60752892-20ad7f80-a006-11e9-81bb-9de7fda79e14.jpg)

MSX is perfect!
I do not have the environment of SVI-318 and can not test, but this issue may be closed.

**Comment by zx70** [comment]
Thanks for testing
