### ISSUE TITLE
(pc6001/graphics.h) Not drawn in todraw() in graphic modes 1 and 2

### ISSUE THREAD

**Issue by fu-sen** [z88dk/z88dk#1222]
I have tried z88dk on some platforms.
I found a strange behavior in the mono graphic of PC-6001 in it:
```
#include <stdio.h>
#include <graphics.h>

void main() {
  clg();

  plot(10, 10);
  drawto(30, 30);

  while (!getk());
}
```
zcc +pc6001 -create-app -bn grptest grptest.c
![スクリーンショット 2019-07-07 13 43 57](https://user-images.githubusercontent.com/5434159/60764114-eacbd200-a0bd-11e9-8c69-27ca168525e5.jpg)
When drawto is set to plot, it draws normally.

Some other mono graphic commands will do strange things.

**Comment by suborb** [comment]
Looks like I forgot to update the last plotted coordinate variable when I added the extra modes.

There may be a few more ports that have the same problem even after this fix, if you find them let me know...

**Comment by fu-sen** [comment]
That is the reason, Because I am using Kokan BASIC(互換 BASIC=ごかんBASIC=compatible BASIC)
in consideration of copyright:
http://000.la.coocan.jp/p6/basic.html

**Comment by fu-sen** [comment]
I confirmed the code change. I will test after reflecting the Nightly Build tomorrow...

**Comment by zx70** [comment]
please ignore my last commit, I reverted the change already

**Comment by fu-sen** [comment]
My PC has been updated to Night Build 20190708.

The following results are obtained for grptest.c published in this issue. (correct):
![スクリーンショット 2019-07-08 13 14 50](https://user-images.githubusercontent.com/5434159/60782710-b9690a00-a182-11e9-83e1-97329834b188.jpg)

I was making a sine curve with mono graphic. The PC-6001 now works properly:
https://gist.github.com/fu-sen/4e079229d43a0aa6c9d40734c35fb2ab
![スクリーンショット 2019-07-08 13 01 31](https://user-images.githubusercontent.com/5434159/60782777-e9b0a880-a182-11e9-9c2f-8f1b89cfa3e4.jpg)

I have tried other platforms but I have not found the same problem. Therefore this issue is closed.

**Comment by fu-sen** [comment]
Unfortunately I reopened this issue.
After that I was able to try other modes (mode 1 and 2) with PC-6001ml2 compatible BASIC,

```
#include <graphics.h>
#include <math.h>
#include <stdio.h>
#include <sys/ioctl.h>

void main() {
  int mode = 1;
  int x, y;

  console_ioctl(IOCTL_GENCON_SET_MODE, &mode);

  clg();

  for (x=0; x<=getmaxx(); x+=2) {
    plot(x, getmaxy() / 2);
  }

  for (x=0; x<=getmaxx(); x++) {
    y = (int)((getmaxy() / 2) * (1.0 - sin(M_PI * 2.0 * x / getmaxx())));
    if (x==0){
      plot(x, y);
    } else {
      drawto(x, y);
    }
  }

  while (getk() < 1){}
}
```

mode 0 (correct):
![スクリーンショット 2019-07-09 18 45 35](https://user-images.githubusercontent.com/5434159/60879251-3d52ed00-a27c-11e9-92d8-7542fef63bb6.jpg)
mode 1:
![スクリーンショット 2019-07-09 18 46 18](https://user-images.githubusercontent.com/5434159/60879292-5491da80-a27c-11e9-949f-1e5db0fdc821.jpg)
mode 2:
![スクリーンショット 2019-07-09 18 46 59](https://user-images.githubusercontent.com/5434159/60879302-5a87bb80-a27c-11e9-8877-c82f37eedd5c.jpg)

I changed it to plot only without using drawto for trial.
```
  for (x=0; x<=getmaxx(); x++) {
    y = (int)((getmaxy() / 2) * (1.0 - sin(M_PI * 2.0 * x / getmaxx())));
      plot(x, y);
  }
```
It works:
![スクリーンショット 2019-07-09 18 55 19](https://user-images.githubusercontent.com/5434159/60879407-84d97900-a27c-11e9-8b25-63d904c08af6.jpg)
As a result, when in Mode 1 and 2, this problem is continuing.

**Comment by fu-sen** [comment]
I was able to confirm the solution of the problem.

Mode 1:
![pc-6001vw-mode1](https://user-images.githubusercontent.com/5434159/61021040-cbdd8080-a3da-11e9-94cb-57104e04bada.jpg)

Mode 2:
![pc-6001vw-mode2](https://user-images.githubusercontent.com/5434159/61021050-d39d2500-a3da-11e9-988d-7f36e9c8beec.jpg)


This will advance the development for PC-6001 using z88dk Thank you!
