### ISSUE TITLE
(g800) Text output of built-in font is incorrect

### ISSUE THREAD

**Issue by fu-sen** [z88dk/z88dk#1241]
It has a different possibility from the conventional report with g800, and I was a new issue.
But that is a simple and obvious bug.

chr.c:
```
#include <stdio.h>

void main() {
  printf(12);

  for (int c=32; c<127; c++) {
    printf("%c",c);
  }

  while(1){}
}
```
```
zcc +g800 -create-app -bn chr.ihx chr.c
```
and
```
zcc +g800 -create-app -clib=g850b -bn chr.ihx chr.c
```
![スクリーンショット 2019-07-20 00 23 06](https://user-images.githubusercontent.com/5434159/61546801-19b25280-aa85-11e9-86b7-b28f88350247.jpg)

If "-CLIB=g850", it can be displayed correctly:
```
zcc +g800 -create-app -clib=g850 -bn chr.ihx chr.c
```
![スクリーンショット 2019-07-20 00 25 43](https://user-images.githubusercontent.com/5434159/61546977-6bf37380-aa85-11e9-8d54-6c4c1cf3228a.jpg)

**Comment by fu-sen** [comment]
I was worried about the output character deviation, so I tried with a real Pocket Computer PC-G850V:
![IMG_20190720_110604_720](https://user-images.githubusercontent.com/5434159/61572868-72aed480-aadf-11e9-838e-2a612606b66e.jpg)
It produces slightly different output than the g800, but has the same problem.

**Comment by fu-sen** [comment]
I was able to reproduce the same display using IOCS call.
When I look closely at the output results, "RUN" is lit. That was a hint.
This part lights up when X coordinate is 24 or more

chrtest.c:
```
void put_chr(char posx, char posy, char chr)
{
#asm
    ld   ix,0
    add  ix,sp
    ld   a,(ix+2)       ; chr
    ld   d,(ix+4)       ; posy
    ld   e,(ix+6)       ; posx
    call 0be62h
#endasm
}

int key_codewait()
{
#asm
    call 0bcfdh
    ld   l,a
    ld   h,0
#endasm
}

main()
{
  for (int c=32; c<127; c++)
  {
    int x=(c-32)%64;
    int y=(c-32)/64;
    put_chr(x,y,c);
  }

  key_codewait();
}
```
```
zcc +g800 -create-app -o chrtest.ihx chrtest.c
```
![スクリーンショット 2019-07-21 18 17 26](https://user-images.githubusercontent.com/5434159/61589587-22bb3500-abe7-11e9-961e-a6fb86fd96ed.jpg)

Therefore, in the current Nightly build, the width of the text is incorrect at least other than "-CLIB=g850".

**Comment by zx70** [comment]
I think I found what happened.   To have a simple, generic support I was avoiding put_chr.
I simply replaced it with put_string, but outputting only one character.
it worked but the VT-ANSI emulation was not full (yet having the whole code inside to deal with coordinates).
I changed it, not remembering about this mess with the many different text resolutions (E200, G800, G815).
I'm now reverting it to the generic implementation, so different text resolutions, scrolling, etc won't be a problem anymore and some text program will be fairy usable on all the models without needing to recompile it.

**Comment by zx70** [comment]
I finally chose not to revert, the smaller resolution will still work also on the G850, but the text scrolling will happen sooner.
Please test again an report the results.

**Comment by fu-sen** [comment]
Yeah. It can be hoped for a solution.
I will test at Nightly Build after tomorrow.

**Comment by fu-sen** [comment]
My PC was updated to nioghtly Build 20190723 and I tested. It works well.

(24x4)
![スクリーンショット 2019-07-23 14 15 46](https://user-images.githubusercontent.com/5434159/61684772-75b2fa80-ad55-11e9-9f9c-960e41f71751.jpg)

-CLIB=g850 (36x8)
![スクリーンショット 2019-07-23 14 16 05](https://user-images.githubusercontent.com/5434159/61684804-8e231500-ad55-11e9-810b-d8f0c2a83e23.jpg)

-CLIB=g850b (24x6)
![スクリーンショット 2019-07-23 14 16 14](https://user-images.githubusercontent.com/5434159/61684818-9b400400-ad55-11e9-85db-142b0f032aef.jpg)
change "for (int c=32; c<192; c++)"
![スクリーンショット 2019-07-23 14 17 52](https://user-images.githubusercontent.com/5434159/61684826-a135e500-ad55-11e9-9fe4-ef98dd7a7a6b.jpg)

That is the perfect solution. This issue can be closed. Thank you!
