### ISSUE TITLE
8080 support - support Intel opcodes in z80asm

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#1246]

**Comment by pauloscustodio** [comment]
JP is unconditional jump in Zilog, but Jump if Positive in Intel!
In this implementation, JP is always the unconditional jump.

**Comment by suborb** [comment]
Nice, thank you @pauloscustodio - is it possible to add the extra 10 or so 8085 ones?

**Comment by pauloscustodio** [comment]
Sure.
