### ISSUE TITLE
Making the second operand of the ternary operator optional

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1257]
I just bumped into this *trivial* limit..  have you ever thought at supporting the "elvis operator" ?
I know it is not standard but, was it avoided for some particular reason or it just happened ?

**Comment by suborb** [comment]
Unless it's supported by sdcc there's no benefit to adding it since I'm trying to minimise the differences between sdcc and sccz80.

**Comment by zx70** [comment]
It wasn't even supported by gcc until the recent versions!
