### ISSUE TITLE
(classic) ftell() is broken

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1259]
The ftell() function makes the program exit abruptly.
I spotted a possible bug in the stack being unbalanced trying to preserve IX but it doesn't seem to suffice.   The C variant can't be built.

fdtell() works better (program doesn't crash).

**Comment by suborb** [comment]
I'll sort this one out this weekend. The function is marked as __SAVEFRAME__ so ix is automatically saved, however it's also saving ix itself - there's also the misplaced ENDIF as you spotted.

**Comment by zx70** [comment]
..removing the need for ix would be optional

**Comment by zx70** [comment]
Thank you Dom, I won't be able to test it for a while,  I think you can close the issue if it is fixed.

**Comment by zx70** [comment]
Works !
