### ISSUE TITLE
[sccz80] 2 bugs: '~' operator overflow and wrong line number reported on errors/warnings

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1260]
I'm adding my modified variant of the sq/usq tools in the new "z88dk-ext" repository.

While testing:
https://github.com/z88dk/z88dk-ext/blob/master/os-related/sq.c

I noticed I now need a workaround for the following program line:

    //code[root] = tcode & ((unsigned int)(~0) >> ((sizeof(int) * 8) - level));

..the line above overflows due to the way the complement operator is used: 

    Warning at file 'sq.c' line 1372: integer '-2147418112' out of range

The current workaround I'm using it to stick directly 65535 in place of (~0).

Now on the error message.  Reported line number 1372 is wrong, I discovered we have a workaround also here by enabling the *--c-code-in-asm* flag

**Comment by suborb** [comment]
I'll pick the sccz80 issue up this weekend, I think it's a type conversion issue again.
