### ISSUE TITLE
classic - no option to clean header files

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#1269]
There is no mechanism in `make clean` to remove the header files copied up for classic, so they remain in the tree as modified files, post clean. Files are copied by make here.
https://github.com/z88dk/z88dk/blob/9378f0aa3dbd4fcc1b3070f856b2fdc11baed6bf/include/_DEVELOPMENT/Makefile#L35

It would be nice if they could also be removed by a clean.

**Comment by suborb** [comment]
[Several months later]

I can't think of a nice way to do this, so I'm wondering if we just commit them then any changes will be genuine changes that should be committed.

**Comment by feilipu** [comment]
Makes sense.
