### ISSUE TITLE
(CP/M) - stdin/stdout limits

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1277]
General stdio
- [x] gets() shortcut to fgets_cons() to be removed   (..in the past I probably insisted to keep it like this)
- [x] fputs() malfunctions (only the first character is sent to file, the rest goes to stdout or gets lost)
- [x] ferror(), now available  (static makes sense and works with the tested programs, it could be extended to check an extra bit for explicit error conditions from external libraries)
- [x] simplicistic perror() implementation
- [x] scanf() bug seen in uudecode.c

CP/M specific (less critical)
- [x] fdgetpos() [->fgetpos()], now available, to be tested/checked
- [x] fdtell() [->ftell()], to be tested/checked
- [x] better fseek()

(original post follows..)
While testing the original "uudecode" program I met few limits in the file redirection and string manipulation functions.

The original file is here:
https://stjarnhimlen.se/snippets/uudecode.c

The workarounds I had to apply:
- scanf() was eating the whole text row, the trailing filename was lost, I replaced it with strtok()
- In my variant I optionally "reopen" stdin if a filename is provided.   If so, gets() was still reading from the console input;  I had to replace it with fgets().

I think part of problems could be addressed in stdio.h (new option to exclude simplifications?)

**Comment by zx70** [comment]
Not to open too many threads I add here:   I noticed that fdgetpos() is missing in the CP/M implementation.   I have working code snippets, but knitting them in a working function is not immediate (long params, passed by reference, FCB position to be identified in the file descriptor, etc..).

**Comment by zx70** [comment]
+ interesting hint found in an ancient C library for the CP/M

>	case SEEK_END:
>		/*
>		 * Close the file because CP/M doesn't know how big an open file is.
>		 * However, the fcb is still valid.
>		 */
>		setusr(fp->user);
>		fp->fcb.f_name[4] |= 0x80;	/* set parital close flag for MP/M */
>		bdos(CLSFIL, &fp->fcb);
>		fp->fcb.f_name[4] &= 0x7f;	/* clear parital close flag */
>		_Ceof(fp);
>		rstusr();
>	case SEEK_CUR:
>		pos += fp->offset + ((long)fp->fcb.f_record << 7);

**Comment by zx70** [comment]
I suspect fpos() is broken too, any sample program can easily show it :(

**Comment by zx70** [comment]
With the now reasonably good ferror() I'm testing the library with more programs.
Now it is fputs failing.  This workaround in stdio.h is not optimal but works:

- In <stdio.h> remove the fputs declarations
- #define fputs(a,b)	fprintf(b,"%s",a);

**Comment by zx70** [comment]
The "fputs" problem can be investigated by running arch/archx:

https://github.com/z88dk/z88dk-ext/blob/master/os-related/arch.c
https://github.com/z88dk/z88dk-ext/blob/master/os-related/archx.c

By replacing it with fprintf, the tools work correctly.
'arch.c' is an interesting piece of code, capable of cropping many text files in a single one and dinamically update such target archive afterwards.   The archive is in readable text form.

**Comment by zx70** [comment]
I try to summarize the topics open so far in this thread:

General stdio
- [ ] fgets() shortcut to fgets_cons() to be removed   (..in the past I probably insisted to keep it like this)
- [ ] fputs() malfunctions (see arch.c eating data)
- [ ] ferror(), now available  (static makes sense and works with the tested programs, it could be extended to check an extra bit for explicit error conditions from external libraries)
- [ ] simplicistic perror() implementation
- [ ] scanf() bug seen in uudecode.c

CP/M specific
- [ ] fdgetpos(), now available, to be tested/checked
- [ ] better fseek()

**Comment by zx70** [comment]
@suborb, fputs() problem found,  it is enough to save ix before calling fputc_callee. 
I was going to change the file in the repo, but I think the ticks count would change,  right?

**Comment by suborb** [comment]
The ticks count should change, but I don't think that's monitored so it's ok?

Don't forget to protect with `IF !__CPU_INTEL__ && !__CPU_GBZ80__`!

**Comment by zx70** [comment]
Oddly I wasn't forgetting :)   tnx

**Comment by zx70** [comment]
The new gets() permitting file redirection is obviously bigger (about 1,5K).
The old gets.asm is preserved in ndos.lib, now even more effective to save memory when file support is not necessary.

**Comment by zx70** [comment]
The way I updated lseek() is already enough to pass the simple test programs I could find, so I'm leaving it like this.   I'm sure it is not enough to deal with particular cases, e.g. random writes on big files but a good test program should be built (or found) first.

**Comment by zx70** [comment]
__SAVEFRAME__  decorator removed from fgetpos(), it picks the parameters with embedded assembly code and it was conflicting.

**Comment by zx70** [comment]
Fixing scanf() was easy.. I simply discovered that it is now in working order  :)
perror() should be target specific, in many cases such functionality is provided by the ROM or the OS, but it can be discussed in another topic.

**Comment by zx70** [comment]
@suborb, what's the IOEXTRA/ trampoline  thing in ftell?  should I replicate it to fgetpos?

**Comment by suborb** [comment]
`_IOEXTRA` is used alongside `funopen()` to allow a FILE to be created over other things. The idea was it would allow other devices (eg a different disc system) to be supported without having to hack away at the stdio code.

Yup, it probably ought to be mapped into the appropriate  `lseek` call.

**Comment by zx70** [comment]
I'm not sure I've tested it fully but it still works better than before  :)
