### ISSUE TITLE
[mz] [update: much slower load] Latest snapshots may have broken the mz target

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1282]
If I try to load the Cross Chase binary for the mz target the emulator now gets in an infinite loop while printing the pi character.

I am testing this with the emulator mz800emu-1.0.3-win32
which I had previously used successfully to test Cross Chase

The mz target is built (as previously) with:
```
mz:
	$(Z88DK_PATH)$(MYZ88DK) +mz $(SCCZ80_OPTS) \
	-D__MZ__ -clib=ansi -pragma-define:ansicolumns=32 -vn \
	-DFULL_GAME -DSOUNDS  -DEND_SCREEN -DBETWEEN_LEVEL \
	-DCONIO -DNO_INIT_GRAPHICS \
	-lndos -create-app -o $(BUILD_PATH)/FULL_mz.prg \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
	rm $(BUILD_PATH)/FULL_mz.prg
	mv $(BUILD_PATH)/FULL_mz.mzt $(BUILD_PATH)/FULL_mz.mzf
```
![image](https://user-images.githubusercontent.com/29057615/65285594-3d555000-db3d-11e9-8580-1ce16db846d1.png)

**Comment by zx70** [comment]
I may have not a perfectly clean z88dk setup but I seem to have problems on all the targets and different applications.
Still I can't understand the root cause, few first attempts to revert my recent changes didn't solve.

**Comment by zx70** [comment]
Not as serious as it looked, I incidently checked this issue on othello.c, on which I put a peculiar optimization 9 months ago (specified callee/fastcall header declarations for C functions within the game) , now crashing.
Did you do the same in your program ?

**Comment by zx70** [comment]
More detail on what I noticed while hunting for your bug:  I was forcing the __z88dk_callee mode for funtions requiring recursion.   It may be that now SCCZ80 is more effectife on such directives than 9 months ago, so the program behavior was compromised by my optimization.
I'm not expecting Fabrizio is having the same problem, but he worked had on optimizations, so you never know  :)

**Comment by Fabrizio-Caruso** [comment]
The problem is not fixed by snapshot 20/09/2019.
I compile with no optimization option so I suppose the compiler uses O2:
```
mz:
	$(Z88DK_PATH)$(MYZ88DK) +mz $(SCCZ80_OPTS) \
	-D__MZ__ -clib=ansi -pragma-define:ansicolumns=32 -vn \
	-DFULL_GAME -DSOUNDS  -DEND_SCREEN -DBETWEEN_LEVEL \
	-DCONIO -DNO_INIT_GRAPHICS \
	-lndos -create-app -o $(BUILD_PATH)/FULL_mz.prg \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
```
I confirm that Cross Chase works fine with other targets such as C128 (compiled with zsdcc), Spectrum (compiled with sccz80). 
I use default optimization options.

**Comment by Fabrizio-Caruso** [comment]
Ok! This issue is now different...
The game eventually loads correctly after a MUCH longer time and after printing zillion PI characters...

Snapshot 2018 09 21 loads the game immediately and prints different random looking characters
Recent snapshots and less recent snapshots such as 2019 01 01 display PI characters and load the game after a much longer time

**Comment by zx70** [comment]
It could have been broken also before.  I recently read about stack limits on the mz target.  Are you using the trick described here?
https://www.z88dk.org/forum/viewtopic.php?id=10993

**Comment by Fabrizio-Caruso** [comment]
Compiling with:
```
	-pragma-define:CLIB_EXIT_STACK_SIZE=0
```
does not fix the problem

**Comment by Fabrizio-Caruso** [comment]
On the other hand I have managed to fix it with a set of pragmas I use to same memory:
https://github.com/Fabrizio-Caruso/CROSS-CHASE/blob/master/src/cross_lib/cfg/z88dk/zpragma_clib.inc

**Comment by zx70** [comment]
-pragma-define:REGISTER_SP=0xd000  resolved for Fabrizio.
I'm tempted to force sp to that value,  it could still be overridden in case of reduced ram

**Comment by zx70** [comment]
ATM it is in the heading example in the wiki 
Target working
