### ISSUE TITLE
ansi_ROW/COLUMN missing on ZX81 in HR modes

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1299]
Building programs with:
-subtype=wrx -clib=wrxansi

I get the following errors:
Error at file 'stdio/ansi/zx81/text/f_ansi_char.asm' line 46: symbol 'ansi_ROW' not defined
Error at file 'stdio/ansi/zx81/text/f_ansi_char.asm' line 55: symbol 'ansi_COLUMN' not defined

I suppose those global variables should now be dynamically created by the common startup modules ?

**Comment by suborb** [comment]
I think they should be `console_x` and `console_y` - apologies for missing those in the big rename/reorg.

**Comment by zx70** [comment]
No problem, let me try to rework what's missing
