### ISSUE TITLE
[zx81][getk] key 32 (space) detected instead when two keys are pressed

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1301]
In the ZX81 target  `getk` detects character 32 (space) when two keys are pressed.

You can reproduce this by running this program and keeping two keys pressed.

```
#include <conio.h>
int main()
{
    while(1)
    {
        printf("ch: %d\n", getk());
    }
    return 0;
}
```

Compiled by:
```
getk_test:
	$(Z88DK_PATH)$(MYZ88DK) +zx81 \
	-compiler=sdcc \
	-create-app -o  $(BUILD_PATH)/getk_test.prg \
	$(SOURCE_PATH)/../test/getk_test.c
```

**Comment by zx70** [comment]
I'm guessing a possible fix, please check it tomorrow morning after the nightly build. 
It is based on the analisys of the ROM code,  but I couldn't test it.

**Comment by suborb** [comment]
@zx70 it didn't work! I've fixed it up based on what the ROM does so now a double key press results in 0 being returned.

**Comment by zx70** [comment]
Dom, your ability to proceed in multitasking is impressive  8|

**Comment by Fabrizio-Caruso** [comment]
@suborb you are superhuman! Thanks!
I have verified the fix! It does work!
