### ISSUE TITLE
Bug: # Improperly Substituted with + in ZSDCC Peephole Rules

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#1304]
I'm still very busy but I noted this change three months ago to the zsdcc peephole rules in libsrc/_DEVELOPMENT:

 	sdcc_peeph.0 	z80asm const expr operator removed; replace all # by + 	3 months ago
	sdcc_peeph.1 	z80asm const expr operator removed; replace all # by + 	3 months ago
	sdcc_peeph.2 	z80asm const expr operator removed; replace all # by + 	3 months ago
	sdcc_peeph.3 	z80asm const expr operator removed; replace all # by + 	3 months ago
	sdcc_peeph_cs.0 	z80asm const expr operator removed; replace all # by + 	3 months ago
	sdcc_peeph_cs.1 	z80asm const expr operator removed; replace all # by + 	3 months ago
	sdcc_peeph_cs.2 	z80asm const expr operator removed; replace all # by + 	3 months ago
	sdcc_peeph_cs.3 	z80asm const expr operator removed; replace all # by + 	3 months ago

This is an incorrect change.  The # in these files are seen by zsdcc not z80asm and they must remain # as this is how zsdcc denotes immediate values.

**Comment by suborb** [comment]
Thanks @aralbrec I think this should be easy to revert, I'm guessing it was just a bulk search and replace that caught them.

**Comment by suborb** [comment]
Reverted and hopefully without any side-effects!
