### ISSUE TITLE
(classic) [CP/M] - add stat()

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1306]
stat.h exists but is available only on z88

**Comment by zx70** [comment]
Small bug found, in sys/stat.h we have:

    #define S_IFMT	0170000	/* file type mask */
    #define S_IFLNK	0110000	/* symbolic link */
    #define S_IFREG	0100000	/* or just 000000, regular */
    #define S_IFBLK 	0060000	/* block special */
    #define S_IFDIR 	0040000	/* directory */
    #define S_IFCHR 	0020000	/* character special */
    #define S_IFPIPE 	0010000	/* pipe */

But the st_mode parameter is unsigned long:

    struct stat {
	int	st_mode;	/* Mode */
	time_t	st_atime;	/* Last access */
	time_t	st_mtime;	/* Last modification */
	time_t	st_ctime;	/* Last change?!?! */
	long	st_size;	/* Size */
	/* These two based on real values */
	int	st_blksize;	/* Blocksize */
	int	st_blocks;	/* # of blocks */
	/* Below here is fake */
	int	st_ino;		/* Inode */
	int	st_uid;		/* UID (not supported) */
	int	st_gid;		/* GID (not supported) */
	int	st_dev;		/* Device number */
	int	st_nlink;	/* number of links */
	int	st_rdev;	/* ? */
    };



I'm tempted to rework the constants rather than extending the variable type, you have up to Monday to claim. tick.. tick..

**Comment by zx70** [comment]
..in the meantime, this partial fix solves checks for regular files, e.g. :

    if ((statbuf.st_mode & S_IFMT/*0170000*/) != S_IFREG/*0100000*/) 
	fprintf(stderr, " -- not a regular file: unchanged");

**Comment by suborb** [comment]
Probably best to correct the st_mode - I've seen code that doesn't use the #define value when checking values.

**Comment by zx70** [comment]
good to know  :)

**Comment by ped7g** [comment]
Not sure what is the bug from the comment? (I would personally rather use `unsigned int` for flags and hexa formatting of constants, but even as posted, seems ok to me? (the signed/unsigned shouldn't matter for correctly written code, but if somebody is using `> 0`, they may get into trouble))

Or is the bug the `S_IFREG` being 0x8000 instead of 0x0000?

**Comment by zx70** [comment]
S_IFREG is expected to be 0100000 decimal (!)  for regular files.
It is not a Unix only condition, I found this same value even in the old Digital sources.
Surprisingly also values like "777" are not flags in hex form but decimal values too.
Since we try to permit portability sometimes we risk to waste a bit of memory and CPU and try to do the things the way they should be..  shortcuts to save memory can still be introduced by the programmers once they got a prototype up and running.

**Comment by zx70** [comment]
Ok, I'm surely missing something! 
They must be octal and not decimal values.
I must have a bad font or perhaps I'm missing something

**Comment by zx70** [comment]
Good ..  I'm officially ignorant!

"Leading zeros indicate that the number is expressed in octal, or base 8; thus, 010 = 8"

Thank you guys for switching by brain on  :)

**Comment by zx70** [comment]
So the bug was in the missing flag for regular files, both CP/M and Z88 are now fixed.

**Comment by ped7g** [comment]
That's why I hate octal in C/C++, it's so error prone, especially if you write also ASM code between the C sessions.... Also I had to count on fingers if that value 0100000 fits into 16b, while in hexa it's instantly obvious which bits are set.

**Comment by zx70** [comment]
Yes,  it's been so frustrating that I closed the issue as soon as I got something working. 
File date/ time for mp/m ii and other attempts to get the exact file size will wait  :)
