### ISSUE TITLE
Question: GameBoy timings

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#1316]
There is inconsistent information about gameboy instruction timings, in particular call, ret, jump and restart, in the references I found:
[1] https://www.pastraiser.com/cpu/gameboy/gameboy_opcodes.html
[2] http://marc.rawer.de/Gameboy/Docs/GBCPUman.pdf

call: 24 T in [1], 12 T in [2]
call cc: 12/24 T in [1], 12 T in [2]
ret: 16 T in [1], 8 T in [2]
ret cc: 8/20 T in [1], 8 T in [2]
rst: 16 T in [1], 32 T in [2]

Any idea what is correct?

**Comment by suborb** [comment]
There's a resource here: http://slack.net/~ant/old/gb-tests/

That has call cc at 12T (always), looking around some other emulators they seem to agree. Given that consensus I'd suggest the first link is incorrect (which is of course where I got the timings from in the first place!)

**Comment by pauloscustodio** [comment]
Ok. I will remove document [1] from techdocs and fix z80asm and ticks timings to use document [2].

I'll submit a PR for ticks.
