### ISSUE TITLE
sccz80 - const char* const 

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#1344]
sccz80 throws multiple errors  for this code sample:
```c
#define FF_VOLUMES      5
#define FF_VOLUME_STRS     "MD1","MD0","IDE0","SD0","SD1"
static const char* const VolumeStr[FF_VOLUMES] = {FF_VOLUME_STRS};    /* Pre-defined volume ID */
```
The second `const` reference (constant pointer declaration) is causing the problem.

**Comment by dikdom** [comment]
char* is one string, char** is the array of strings, or do I miss something?

**Comment by suborb** [comment]
I thought I’d fixed handling the second const at one point in time. I’ll take a look.

**Comment by feilipu** [comment]
@dikdom 
> char* is one string, char** is the array of strings, or do I miss something?

`static const char* const VolumeStr[FF_VOLUMES];`

Means `VolumeStr` is a constant pointer to arrays of characters (strings) that are constant and `static` in this situation means visible only within the file.

I read somewhere the way to understand these declarations. You just read from right to left and it becomes much easier to understand.

`static const char* VolumeStr[FF_VOLUMES];`

Means `VolumeStr` is a pointer to arrays of characters (strings) that are constant and `static` in this situation means visible only within the file.

`static char* const VolumeStr[FF_VOLUMES];`

Means `VolumeStr` is a constant pointer to arrays of characters (strings) that aren't constant and `static` in this situation means visible only within the file.

I do hope this is correct... :man_shrugging:
