### ISSUE TITLE
z80asm tests fail on Travis-CI

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#1362]

**Comment by pauloscustodio** [comment]
@suborb, I have removed the unstable tests from the main test target in z80asm and the build now passes Travis-CI checks in branch fix/1362.

Can you please check if this branch passes the nightly build? I'll merge to master after the check passes.

**Comment by suborb** [comment]
@pauloscustodio Thanks! That branch builds on the nightly machine.

**Comment by pauloscustodio** [comment]
Fixed in 7f154af641a5b0a5726ed6a21998bf879e3e29f2
