### ISSUE TITLE
For discussion: include .editorconfig at the top project level?

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#1372]
Most current source code editors support a format-code-on-save using a project-wide .editorconfig at the project root. See https://editorconfig.org/

This has the advantage (or disadvantage, depending on your personal belief) that the code looks the same, no matter who edited it. 

Shall we include such a project-wide configuration at the z88dk root? Proposed settings:
```
[*]
end_of_line = lf
indent_style = tab
indent_size = 4
trim_trailing_whitespace = true
insert_final_newline = true
```

**Comment by suborb** [comment]
I think at the moment there isn't a consistent style across src/ - it really depends on where the code was imported from. There's also around about 20 years of different editors getting in the way.

Perhaps this is best at a src/XXX level rather than top-level?
