### ISSUE TITLE
Debugging C source code

### ISSUE THREAD

**Issue by obiwanjacobi** [z88dk/z88dk#1387]
I am researching if (and how) it is possible to generate debugging symbol information that would allow me to relate addresses to C source code. The map file that seems to be the current best source of debugging symbol information is mainly focused at .asm files - by the looks of it.

Is my perception correct? 
Is there a way to compile my own debugger symbol file by using several existing files?
Do you have any (other) suggestions?

Context: I have a Z80 in-circuit-emulator that does debugging and I am trying to determine how feasible it is to write a debugger extension for VS-code for it based on z88dk sources.

**Comment by suborb** [comment]
Mapping assembler lines to code lines can be done with -gcline with sccz80. 

However it doesn't help with local variable locations (i.e. the stack relative position).

At this point in time, the z80asm object file format isn't rich enough to contain the debugging we need. I'm not sure if @pauloscustodio has thoughts in this area.

**Comment by pauloscustodio** [comment]
No thoughts and open to suggestions. As far as I know there is no standard object file with debugging info for z80 systems, and each system/emulator implements its own. Is there a particular setup we should target for? We might need some new pragmas to pass information from C to the assembler and linker, but this is the easy part.

**Comment by suborb** [comment]
I've not used it, but I feel like it's easiest to support the `cdb` format from sdcc. These are text files which could be processed to match whatever format is needed.

There's a definition here: https://github.com/roybaer/sdcc-wiki/wiki/CDB-File-Format

SDCC generates a `.adb` file containing type information and augments the output assembler with C records for line numbers and X records for end of function.

I think asxxx then appends L records for the addresses of labels and C/X records

**Comment by pjshumphreys** [comment]
If you use the cli options -m, -S and --c-code-in-asm you can get an assembly file with the original c source code embedded in comments and a map file to relate symbols to addresses in memory.

If you then use an assembly level debugger open next to the asm file in your editor you can follow along to know which c source code lines are getting executed.

--c-code-in-asm does break optimisations, but the results are probably good enough for debugging purposes.

**Comment by obiwanjacobi** [comment]
(not looked at the details of those switches you mention) 
Is there any address data in there?

**Comment by pjshumphreys** [comment]
In the .map file there is, together with the label in the .asm file each address maps to

**Comment by obiwanjacobi** [comment]
Only having addresses for the labels makes a lousy debugger...

**Comment by aralbrec** [comment]
An attempt to integrate the list files into an emulator for debugging purposes can be seen here:
https://www.youtube.com/watch?v=TmpHy_x2Fko

**Comment by suborb** [comment]
#1390 was raised to address this. I've started work on .adb support but I'm getting sidetracked by other things...
