### ISSUE TITLE
BUG crept in GFX lib?

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1397]
As forecasted by Dom I think I found something.
I initially thought to do some extra testing, but I'm busy this weekend, and I prefer to begin with this quick alert. 
At the moment all I know is that the GLOBE example fails drawing correctly few lines, I suppose it has to do with coordinates' ranges or sign/direction in relative position drawings.

**Comment by zx70** [comment]
tested on zx spectrum, sccz80/classic only

**Comment by suborb** [comment]
I've had a look and this isn't a graphics bug, but is a floating point bug.

It seems that this change/idea: 6701a84cd65c714bbad7bc9b38e8c50acc837ddc causes problems.

It also fails to work (at all) with sccz80+math32/math48 so something is wrong there too.
