### ISSUE TITLE
not compiling in 2.0 nightly (mac osx)

### ISSUE THREAD

**Issue by jsmolina** [z88dk/z88dk#1399]
Compile command is:

zcc +zx -v -startup=31 -DWFRAMES=3 -clib=sdcc_iy -Cz--screen=intro.scr -SO3 --max-allocs-per-node10000 @zproject.lst -pragma-include:zpragma.inc -o msnampac -create-app
....
zsdcpp -iquote"." -D__Z88DK -D__SPECTRUM -DSPECTRUM -D__SPECTRUM__ -D__Z80 -DZ80 -DWFRAMES=3 -D__SDCC -D__SDCC_IY -isystem"/usr/local/share/z88dk//include/_DEVELOPMENT/sdcc"  -D__SDCC  "game_zx.c" "/tmp/tmpozxELnSf.i2"
**sh: zsdcpp: command not found**

I didn't executed zsdcpp command, not sure from where is called.

**Comment by suborb** [comment]
Ah, a typo. Lovely:

    cd z88dk/bin
    mv zdcpp zsdcpp

Will fix it. -clib=sdcc_iy uses sdcc as the compiler which needs its own preprocessor (zsdcpp)
