### ISSUE TITLE
Unrecognised config option: INCLUDE alias.inc

### ISSUE THREAD

**Issue by jayacotton** [z88dk/z88dk#1415]
This showed up today after a git pull and build.

**Comment by suborb** [comment]
I think you might have an older zcc version somewhere in your path.

**Comment by jayacotton** [comment]
here is a version code
cc - Frontend for the z88dk Cross-C Compiler - v16128-c78bc0271-20200306

**Comment by jayacotton** [comment]
did a make install (lots of errors) but that cleaned up the include bug.
