### ISSUE TITLE
uthash.h and utstring.h missing

### ISSUE THREAD

**Issue by jayacotton** [z88dk/z88dk#1416]
after make clean; make

cc -O2 -MMD -Wall -I../../ext/uthash/src/ -g -pedantic -std=gnu99   -c -o callfunc.o callfunc.c
In file included from ccdefs.h:20,
                 from callfunc.c:9:
define.h:10:11: fatal error: uthash.h: No such file or directory
  #include "uthash.h"

**Comment by jayacotton** [comment]
I did an aggressive clean up and forced it to pull a new version of sccz80, this seems to fix the problem.

**Comment by jayacotton** [comment]
wrong again.

cc -O2 -MMD -Wall -I../../ext/uthash/src/ -g -pedantic -std=gnu99   -c -o callfunc.o callfunc.c
In file included from ccdefs.h:20,
                 from callfunc.c:9:
define.h:10:11: fatal error: uthash.h: No such file or directory
  #include "uthash.h"
           ^~~~~~~~~~
compilation terminated.

The ~/ext/uthash directory is empty.  Am I missing a package ?

**Comment by jayacotton** [comment]
Looks like parts of the ~/ext/* content is not delivered with a git pull of z88dk.

**Comment by suborb** [comment]
Yes. Ext/ is sub modules so you’ll need to pull those down.
