### ISSUE TITLE
z88dk compiled for 64-bit machines

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#1445]
I imagine it's potentially a lot of work and maybe not possible with the some of the old code in the codebase but has anyone actually looked at it?

I have been asked because the mac has ditched support for 32-bit code.  I am sure you can probably run it via virtual machine or something but it's probably less hassle if it were available as native code.

**Comment by suborb** [comment]
I think nightly is 64 bit for macOS now? I remember fiddling with some build flags a few months ago.

**Comment by Xalior** [comment]
I just pulled http://nightly.z88dk.org/z88dk-osx-20200413-baa8620-16209.zip and checked;

`darran@kimberlyᐉ ~ % file z88dk/bin/zcc
z88dk/bin/zcc: Mach-O 64-bit executable x86_64`

**Comment by suborb** [comment]
@Xalior thank you for confirming my slightly dodgy memory!
