### ISSUE TITLE
(classic) Add support for Mikro80

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#1452]
We'll start with this one:

- 8080 clone
- Character based 64x32 display
- 2k ROM @0xf800
- RAM fills the rest?
- Fixed font in ROM

Features:

- [x] Generic console
- [x] Firmware output
- [x] Firmware input
- [x] Inkey input
- [x] Lores graphics
- ~[ ] Interrupts~ -  no interrupt source

Available characters:

![image](https://user-images.githubusercontent.com/394721/80291097-7fcdb380-8742-11ea-8cb4-387fd0019576.png)

It looks like the block graphics aren't going to work nicely: The left hand side is 4x4, the right hand side 3x4

![image](https://user-images.githubusercontent.com/394721/80290925-f2d62a80-8740-11ea-907e-da951663dabe.png)

**Comment by zx70** [comment]
You're just magic  :)
.. in case you will run short of targets, I'm leaving behind the M10, the ZX 81 graphics extension to pseudo HRG is totally absorbing  (as I honestly expected to be)

**Comment by suborb** [comment]
Merged as #1453 - I suspect there will be a few more machines added which are similar.
