### ISSUE TITLE
#endasm at end of .c or included .asm file without newline causes SCCZ80 compilation error

### ISSUE THREAD

**Issue by dbolli** [z88dk/z88dk#1478]
A .c file with #endasm as the last line without a newline (i.e. regex #endasm\z ) causes a SCCZ80 compilation error but no error message.

e.g.
zcc +zxn -subtype=nex -v -O3 -startup=5 -clib=new -m -create-app --list progname.c -o progname -lm

PROCESSING progname.c
z88dk-ucpp -iquote"." -D__Z88DK -D__ZXNEXT -D__Z80 -DZ80 -D__Z80N -D__SCCZ80 -isystem"/Path/to/z88dk/lib/config//../..//include/_DEVELOPMENT/sccz80"  -DSCCZ80 -DSMALL_C -D__SCCZ80  "progname.c" "/tmp/tmpfrIuLhdq.i2"

is the only output displayed.

if the offending file is an .asm file added with #include in the .c file, linker errors occur

Error at file 'progname.opt' line 13: cannot read file 'z80_crt0.hdr'
                   ^ ---- 	INCLUDE "z80_crt0.hdr"
Error at file 'progname.opt' line 180: symbol 'l_gintspsp' not defined
                   ^ ---- 	call	l_gintspsp
Error at file 'progname.opt' line 183: symbol 'l_div_u' not defined
                   ^ ---- 	call	l_div_u

Older 1.x versions of zcc could handle this but the newer version doesn't.

Suggest that the lack of trailing newline after #endasm could be handled and
a warning message displayed at compilation as this issue is extremely difficult
to debug when it occurs (especially for code that compiled successfully in earlier
versions)

**Comment by suborb** [comment]
Thanks for the report.

It was a preprocessor issue. I've stuffed a newline in at the end if the file doesn't already end with one.
