### ISSUE TITLE
Visual Studio build - appmake fails

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#1480]
The build of appmake fails in Visual Studio 2015 (win32/z88dk.sln solution) with the error:

```
c:\users\paulo\git\z88dk\src\appmake\appmake.h(19): fatal error C1083: Cannot open include file: 'libgen.h': No such file or directory
```

**Comment by suborb** [comment]
I feared that would happen....

We use dirname() and basename() from there.

**Comment by aralbrec** [comment]
zcc uses [last_path_char](https://github.com/z88dk/z88dk/blob/master/src/zcc/zcc.c#L2242) to separate basename and dirname.
