### ISSUE TITLE
(z88dk_ticks) Proposal for some changes

### ISSUE THREAD

**Issue by PaintedBlck** [z88dk/z88dk#1483]
Dear developers of z88dk,

I am, since some time, a user of ticks. I'm an experienced command line debugger (all kinds of CPU's and debuggers) since a very long time. And I see a number of small changes that would make ticks more efficient. e.g.

* There is a **_problem with the output of the x command_** (wrong addresses at the start of some lines).

* The **_output is rather crowded_** and would benefit from some blank lines and/or intermediate dashed lines and/or some color (with ansi codes) here and there.

* The **_output of the reg command_** could be a little more structured, so to permit the user to find the info that he is looking for without scanning the entire output of the command. Again, some color would be beneficial.

* It would be nice to be able to **_give a number of commands on the same line_** (e.g. separated with a ";" as in the bash shell).

I am more than willing to make a proposal and a pull request for each of the above topics, so you can see what I mean. Is that ok for you?

Kind regards,
PB

**Comment by suborb** [comment]
Please feel free to!

A couple of things about colour:

1. It needs to work on both windows + *nix
2. Please detect whether stdin is interactive and disable colour if not
