### ISSUE TITLE
[feature quest/info][appmake] Some output file names are capitalized but not all. 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1487]
If I use appmake option "-create-app -o foo", I may get a small letter foo binary followed by capitalized FOO files (e.g., FOO.ROM).

On some targets (e.g., px4, px8, osca, etc.)  the appmake output file names are capitalized.
While on other targets (e.g., oz, newbrain) this is not the case.

It would be probably better to have either always capitalized or never capitalized.
Maybe I am wrong, though. As some systems may require capitalized file names.

**Comment by zx70** [comment]
Fabrizio,  It is a deliberate choice. 
APPMAKE normally leaves the filename unchanged,  but for the extension. 
In some case,  in example for files to be copied into ancient operating systems,  the lowercase characters prevent the program to be found (by the original OS  or some useful tool or emulator).   Similarly in some case corrections can be applied for the name length,  the symbols,  etc.
Do you have a specific case/ conflict in mind?

**Comment by Fabrizio-Caruso** [comment]
@z70, for instance the ones I have mentioned above (e.g., px4, px8, osca, etc.) but there are many more.
I am not at all sure this is an issue or a bad thing.
I am just wondering whether it was done on purpose on some targets to change the names to capital letters.

**Comment by Fabrizio-Caruso** [comment]
I am closing this non-issue. Sorry for the inconvenience.
