### ISSUE TITLE
[zsdcc][bug] Compiling with zsdcc produces corrupted binaries

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1504]
With the nightly snapshot from 2020/06/09 and some other recent ones, I get a corrupted binary for my game:
https://github.com/Fabrizio-Caruso/CROSS-CHASE/blob/master/src/makefiles/wip/Makefile.z88dk_wip_targets#L168

I get a correct game binary if I use SCCZ80 with -O0 and a corrupted binary if I use ZSDCC with -SO0.

I have attached the .lis, .map files produced by compiling with: --list -m --c-code-in-asm
[build_sccz80_O0.zip](https://github.com/z88dk/z88dk/files/4760094/build_sccz80_O0.zip)
[build_zsdcc_SO0.zip](https://github.com/z88dk/z88dk/files/4760093/build_zsdcc_SO0.zip)

**Comment by feilipu** [comment]
> I get a corrocted game binary if I use SCCZ80.

"corrupted" or "corrected" ?

It would be two different issues if there were problems across the two compilers, I'd guess...?
Unless the common element were something in the newlib or classiclib?

**Comment by Fabrizio-Caruso** [comment]
I have this situation:
SCCZ80 OK
ZSDCC KO

I am sorry I was misleading you with the previous issue where I thought it was an problem with the optimizer. The reason for my mistake is that the optimization was making the problem more visible whereas compiling with no optimization keeps the problem from appearing immediately in some cases. 

So I no longer now if I have observed multiple issuues.
What seems clear to me is that ZSDCC is buggy now.

**Comment by feilipu** [comment]
Potential fix in #1511. For review.

**Comment by suborb** [comment]
I've put a precompiled windows binary here: http://nightly.z88dk.org/misc/zsdcc.exe.r11556

**Comment by feilipu** [comment]
Any luck with the new binary?

**Comment by Fabrizio-Caruso** [comment]
@feilipu I have not managed to figure out how to use it. I though I could use it instead of zcc.

**Comment by Fabrizio-Caruso** [comment]
I have replaced the zsdcc.exe with the patched one.

Nope, the new binary still produces a totally broken binary: it just crashes at startup whereas it works fine with sccz80.
I wonder whether this only happens with the zx target as I don't see this corruptions with other targets.
[build.zip](https://github.com/z88dk/z88dk/files/4811593/build.zip)

This is my Makefile target:
```
spectrum_16k_light:
	$(Z88DK_PATH)$(MYZ88DK) +zx --list -m --c-code-in-asm   \
	$(INCLUDE_OPTS) -compiler=sdcc -SO0 \
	-zorg=24055 \
	-pragma-include:$(CFG_PATH)/z88dk/zpragma_clib.inc \
	-pragma-redirect:getk=getk_inkey \
	-DLESS_TEXT -DANIMATE_PLAYER \
	-DFORCE_NARROW -DNO_BLINKING \
	-DFORCE_GHOSTS_NUMBER=8 \
	-DNO_SLEEP -DNO_WALL \
	-DNO_MESSAGE -DNO_HINTS -DNO_CONTROL_INSTRUCTIONS -DNO_SET_SCREEN_COLORS \
	-DNO_TITLE_LINE -DNO_INITIAL_SCREEN \
	-DNO_RANDOM_LEVEL \
	-DSIMPLE_STRATEGY \
	-D__SPECTRUM__ \
	-DALT_MOVE \
	-lndos -create-app \
	-DCONIO \
	-DUDG_GRAPHICS \
	-pragma-redirect:fputc_cons=fputc_cons_generic \
	-o $(BUILD_PATH)/WIP_LIGHT_spectrum_16k.prg \
	$(CROSS_LIB_PATH)/display/init_graphics/z88dk/udg/udg_init_graphics.c \
	$(SOURCE_PATH)/graphics_data/z88dk/xchase.asm \
	$(LIGHT_FILES)
```

**Comment by feilipu** [comment]
You'll need to remove the `.r11556` from the file name so that it is an `zsdcc.exe` and then put it in your `z88dk/bin` folder (you should replace the existing `zsdcc.exe`, and keep the old one somewhere). Otherwise you should be using it identically to the existing build.

I haven't been able to test, so your test will be very interesting.

If you could, you can capture the `--list --c-code-in-asm` files which are `yourprogram.c.lis` with the standard zsdcc.exe and the new one, then we can see if there are any changes or differences between the two.

**Comment by Fabrizio-Caruso** [comment]
@feilipu  I have just done that. I have included the files in the zipped attachment.

**Comment by feilipu** [comment]
There's actually two different `.lis` files generated. The one you've included `WIP_LIGHT_spectrum_16k.lis` which includes the crt0 and other environment code, and the other(s) which are `myCcode.c.lis` which are your actual C compiled programs.

Not good news that it is still crashing, but still it would be good to compare the before/after for the `.c.lis` files.

**Comment by Fabrizio-Caruso** [comment]
@feilipu  sorry. I have now included all the files.
[lis.zip](https://github.com/z88dk/z88dk/files/4811712/lis.zip)

**Comment by Fabrizio-Caruso** [comment]
Sorry not all of them. I missed two... Going to upload them...

**Comment by Fabrizio-Caruso** [comment]
[lis.zip](https://github.com/z88dk/z88dk/files/4811743/lis.zip)

**Comment by feilipu** [comment]
Thanks. Those are the "after" files, I assume. I'll compare them with the "before" files you uploaded previously.
Cheers, Phillip

**Comment by Fabrizio-Caruso** [comment]
Yes, they are the binaries with the patched zsdcc version. In both cases, I get a corrupted binary.
I get a working game with SCCZ80.

**Comment by Fabrizio-Caruso** [comment]
@feilipu I do not see these problems on the ZX81 version of my game. Could this problem only affect some specific target libs?? Maybe it is just a problem with different registers used for the lib. Should I use some special options to reserve the x or y register for the lib code?

**Comment by feilipu** [comment]
I'm not sure, I'm sorry. Perhaps there are target specifics, but possibly also it might be a bug, of the type as per #1512 might indicate? Let me have a detailed look at the files tonight.

**Comment by feilipu** [comment]
OK, no surprises here. From what I see, with the exception of additional definitions, the assembly code in both sets of builds is identical. So, if it failed before, it will be still failing.

Is it a target related thing? You mentioned that other z88dk targets are working ok with the current builds?

I am not sure how to positively test the zsdcc peephole fixes in the new version, because as far as I can see they are never enabled when called via zcc. The z88dk peephole rules are always used, so there may be another issue (unrelated to optimisation) in zsdcc, or there may be a peephole rule issue that has been aggravated/activated by changing the compiler to r11556.

**Comment by feilipu** [comment]
I've been poking about, and humour me... try to add this  `--peep-file ""` to the command line, and see what happens, please.

**Comment by Fabrizio-Caruso** [comment]
@feilipu It still crashes.
I have included the .lis files, the .map and binary.
[lis.zip](https://github.com/z88dk/z88dk/files/4814347/lis.zip)

**Comment by Fabrizio-Caruso** [comment]
@feilipu the binary has also changed because I have modified one file. I have rechecked SCCZ80 OK, ZSDCC with and without the empty peep hole file which are both KO.

**Comment by feilipu** [comment]
It may be you've hit a similar issue as has been discovered in #1512.
If that is the case, since your code is much larger than the example, best to hold off until it is resolved. Unless you can see exactly where it goes wrong.

**Comment by feilipu** [comment]
Now #1512 has a fix, and there should have been a new nightly zsdcc generated (check with `-v` that it is r11690), you could try again.

I noted from the logs that there have been a few sdcc issues fixed between r11556 and r11690, so there's a good chance that, even if it is not the same issue as in #1512, someone has picked up the problem and it has been fixed.

**Comment by suborb** [comment]
Just as a note, the windows and macOS binaries of zsdcc are built manually and I've not got round to doing it yet.

**Comment by feilipu** [comment]
Any luck with the new binary? Or do we need to look further?

**Comment by Fabrizio-Caruso** [comment]
@felipu, the crash at start up still occurs if I use zsdcc instead of sccz80.

**Comment by feilipu** [comment]
I'm just looking at your readme and repo. There's a lot of code to understand before even beginning to understand where things go wrong.

Is it possible to cut out all the code related to libraries and game logic that isn't touched before the crash?
If we can bisect the issue down to a smaller section of code, then probably looking at the assembly produced will be much easier. Since it is happening at startup, it should be before most of the game logic is used.

If you can do a (disposable) repo clone, and cut out everything unnecessary, then we can focus on the broken things.

Another angle is to compare the binary produced by identical source, but with the old SDCC and the new SDCC. If you can do that with `-SO0 -O1` compiler options for each, then we can look at a diff and see where things diverge. I I can play with that once there's a limited code base (in the disposable repo) that I can use.

Ideally, with both angles covered getting to the faulty issue should be quick.

**Comment by Fabrizio-Caruso** [comment]
I will try to isolate the issue somehow. I am not sure I have done what you asked for. I just tested the latest nightly build.

**Comment by feilipu** [comment]
Yes the nightly build would be one option, using the current r11690 zsdcc and the old r9855 zsdcc across all your code. But then we'd see (and have to disqualify) every code generation improvement made over the past two years. A lot of work.

If we remove all the code that can't be touched before the user "press space" screen (for example), then there's a lot gone. Even better would be to isolate before the first screen is drawn (so all the graphics could be disqualified), if the crash happens really early.

**Comment by feilipu** [comment]
You could try the new nightly with #1577 to see if things are better now?

**Comment by Fabrizio-Caruso** [comment]
@feilipu indeed it seems better now. I am going to open a new issue about SCCZ80 which is producing wrong binaries where ZSDCC does the right thing.

**Comment by Fabrizio-Caruso** [comment]
I just tested the Spectrum build and it still fails...

**Comment by Fabrizio-Caruso** [comment]
@feilipu I am using snapshot 2020 10 06 and ZSDCC is still somehow broken:
```
spectrum_16k_light:
	$(Z88DK_PATH)$(MYZ88DK) +zx -v   \
	$(INCLUDE_OPTS) -compiler=sdcc -SO0 \
	-zorg=24055 \
	-pragma-include:$(CFG_PATH)/z88dk/zpragma_clib.inc \
	-pragma-redirect:getk=getk_inkey \
	-DLESS_TEXT -DANIMATE_PLAYER \
	-DFORCE_NARROW -DNO_BLINKING \
	-DFORCE_GHOSTS_NUMBER=8 \
	-DNO_SLEEP -DNO_WALL \
	-DNO_MESSAGE -DNO_HINTS -DNO_CONTROL_INSTRUCTIONS -DNO_SET_SCREEN_COLORS \
	-DNO_TITLE_LINE -DNO_INITIAL_SCREEN \
	-DNO_RANDOM_LEVEL \
	-DSIMPLE_STRATEGY \
	-D__SPECTRUM__ \
	-DALT_MOVE \
	-lndos -create-app \
	-DCONIO \
	-DUDG_GRAPHICS \
	-pragma-redirect:fputc_cons=fputc_cons_generic \
	-o $(BUILD_PATH)/WIP_LIGHT_spectrum_16k.prg \
	$(CROSS_LIB_PATH)/display/init_graphics/z88dk/udg/udg_init_graphics.c \
	$(ASSETS_PATH)/z88dk_xchase.asm \
	$(LIGHT_FILES)
	rm $(BUILD_PATH)/WIP_LIGHT_spectrum_16k.prg
	rm $(BUILD_PATH)/WIP_LIGHT_spectrum_16k_BANK_7.bin
```

If I use SCCZ80 it runs fine. If I use`  -compiler=sdcc -SO0` it is broken.

**Comment by feilipu** [comment]
Fabrizio, if this is still a problem, I found an issue with a wild`*` write to `(HL)` caused by one of our peepholes in SO2 and SO3. This issue #1811 has been around for a long time, but only became obvious recently (to me at least).

It is likely that this peephole 12 would be employed where you're incrementing a static variable by some amount not equal to one. Something like `my_variable+=0x0100;`

`*` by wild I mean writing to the address indicated by contents of `HL` without first setting the value of `HL`.

**Comment by feilipu** [comment]
Fabrizio, can you test with PR #1969, please?
Trying to see if issues have been resolved before 4.2.0 gets released.

**Comment by Fabrizio-Caruso** [comment]
I use Cygwin or Linux or any POSIX environment. First of all I need to see if the issue is still present and if I can reproduce it with my current code

**Comment by feilipu** [comment]
If you have a clone of the repository, you can switchto the PR branch `git switch zsdcc_v4.2.0`
and follow the [instructions to make z88dk and zsdcc](https://github.com/z88dk/z88dk/wiki/installation#linux--unix).
Specifically remember to `export BUILD_SDCC=1` so that zsdcc gets built with the new patch on the new version.

**Comment by Fabrizio-Caruso** [comment]
@feilipu I can promise I can compile Z88DK... It seems a long process. Anyway I need to reproduce the issue, first of all, to see if it is still valid or if my new code is also affected by it. I am working on it...

**Comment by feilipu** [comment]
Thanks. Let's see what shows up.

**Comment by Fabrizio-Caruso** [comment]
@feilipu , I have not managed to compile the new branch. It fails with:
```
In file included from ccdefs.h:23,
                 from callfunc.c:9:
define.h:10:11: fatal error: uthash.h: No such file or directory
   10 |  #include "uthash.h"
      |           ^~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: callfunc.o] Error 1
make[1]: Leaving directory '/home/fcaruso/z88dk/src/sccz80'
make: *** [Makefile:139: bin/sccz80] Error 2
```

**Comment by feilipu** [comment]
>    10 |  #include "uthash.h"

The uthash is part of a submodule that needs to be pulled in when cloning the repository. https://github.com/z88dk/z88dk/issues/1416 https://github.com/z88dk/z88dk/issues/1575

https://github.com/z88dk/z88dk/wiki/installation#linux--unix

`git clone  --recursive  https://github.com/z88dk/z88dk.git`

---

I've also been trying to build CROSSCHASE, but I'm finding that in my set up the compilation doesn't complete.

I have a problem writing to my `/tmp/` directory. Most of the compilation works fine (for both options), and for some other instructions you've provided, but it seems somehow the end of the `xl` python script seems to access the `/tmp/` directory in a different way and it is forbidden from writing into the directory. Probably something odd in my set up, but I haven't found out why I can't get things to complete, which is preventing me from going forward.

**Comment by Fabrizio-Caruso** [comment]
@feilipu , sorry, I will try to reclone it.
The xl python script is only running make and doing some clean-up. It probably builds the binaries and fails with the clean-up. Have you looked into the `build` directory? (same level as `src`)

**Comment by Fabrizio-Caruso** [comment]
@feilipu I have managed to run `build.sh` followed by `sudo make install`.

If I compile the test versino of Cross Chase I still get a buggy zsdcc version.

In order to see it crash, press I J K L keys multiple times.

It works fine if compiled with SCCZ80 and it crashes with SDCC

[build_2.zip](https://github.com/z88dk/z88dk/files/8055297/build_2.zip)

If I run `z88dk-zsdcc` -v I get
`
ZSDCC IS A MODIFICATION OF SDCC FOR Z88DK
Build: 4.1.14 #13006 (Linux) Feb 13 2022

sdcc website:
https://sourceforge.net/projects/sdcc/

patch details:
https://github.com/z88dk/z88dk/blob/master/src/zsdcc/sdcc-z88dk.patch

published under GNU General Public License (GPL)
`

**Comment by feilipu** [comment]
> Sorry if I bother you with this. Could you please paste the exact error you get when you run the xl script? I am trying to have Cross-Lib work on all POSIX environments.

No problem at all.  I didn't want to post my issue, because my environment is very old (upgraded like 5 times), and has all manner of inconsistencies. I'll post it as an issue on your github.

---
> In order to see it crash, press I J K L keys multiple times. It works fine if compiled with SCCZ80 and it crashes with SDCC.

It looks like the issue is still there. So now the fun to find out why.

The code doesn't fail if just looping right? Just when the direction keys are pressed?
So I guess the failure must be with that part of the code.

Which code would be responsible for that movement or redraw activity?

**Comment by Fabrizio-Caruso** [comment]
Maybe this source file affected by the bug but I am not sure:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/games/chase/move_player.c

If possible check if you have the binaries in the build directory to make sure we are using the very latest compiler from the branch with potential fixes.

**Comment by feilipu** [comment]
> If possible check if you have the binaries in the build directory

At this stage there's nothing in my `./build` directory. It is empty.

> make sure we are using the very latest compiler from the branch with potential fixes.

Your message above indicates you're using the newest zsdcc patch. So it is pretty clear the issue remains.
I'll try to read the assembly from your `move_player.c` code. Perhaps it might reveal something.

**Comment by feilipu** [comment]
Ok. I've got a recipe for getting down to the nuts and bolts.
The attached file has two command lines, one for generating a sdcc assembly file and one for generating a sccz80 assembly file.
Set up at the moment for just the `move_player.c`, but it could be any file of interest.
[cross_chase_debug_instructions.txt](https://github.com/z88dk/z88dk/files/8055402/cross_chase_debug_instructions.txt)
I hope that the command line is the same as is generated by the `xl` script.

The generated files look like this.
[move_player.sccz80.txt](https://github.com/z88dk/z88dk/files/8055406/move_player.sccz80.txt)
[move_player.sdcc.txt](https://github.com/z88dk/z88dk/files/8055407/move_player.sdcc.txt)
And this is where I'll start to look.

If we can get a finished binary onto a debugger, it would also be a better path forward.

**Comment by Fabrizio-Caruso** [comment]
The reason why I used `-SO0` is because we are debugging and I wanted to exclude bugs coming from peephole rules and other optimizations. When I build the normal games I use some optimization (`xl <game> <target>` does, e.g., `xl chase spectrum`, `xl horde spectrum`, etc.).

**Comment by Fabrizio-Caruso** [comment]
@feilipu --reserve-regs-iy seems to have fixed the issue ! THANKS!
I would suggest having this option by default.

**Comment by feilipu** [comment]
Great news.

But, I'm not entirely sure why it isn't automatically included by the zx target. I thought it was.

**Comment by Fabrizio-Caruso** [comment]
By the way, thanks for reporting the issue with xl. I had forgotten to include a command to generate the assets for those two test targets. It is now fixed. Would you please try to build my spectrum_test_sccz80 and spectrum_test_sdcc yourself and let me know if it is ok?

**Comment by feilipu** [comment]
Ah. `--reserve-regs-iy` is included if you use the [newlib alias](https://github.com/z88dk/z88dk/blob/master/lib/config/zx.cfg#L24). But not for classic library.
I'll defer to @suborb as to how and whether to add it to the alias.

Good to get this cleared up.
