### ISSUE TITLE
(math32/mbf32/math16?/cpcmath?) Floor/ceil implementations incorrect

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#1536]
At present these convert to a 32 bit integer and then back into a float to remove the fractional part.

This works well unless the integer value would take more than 4 bytes to describe. In this scenario we end up with floor(x) being significantly different to (x) with the result that, for example, ftoa() and ftoe() which end up printing garbage since they're not dividing by factors of 10. This shows up with paranoia doing `%.18e`

This also means that math32 `m32_modff()` is incorrect as well.

Spotted during the the dai32math work.

- [x] mbf32
- [x] math32 - floor/ceil
- [x] math32 - modf
- [x] math16

**Comment by feilipu** [comment]
Also noting from your commits that there are several missing intrinsic functions in math16 and math32 (for `codegen.c`)
I'll add them once the dai32math branch is merged.

**Comment by feilipu** [comment]
Reading math48, the algorithm to get integer is:
- Check whether all mantissa is integer by exp too big.
- Check whether no mantissa is integer by exp too small.
- Build mask by shifting by carry exp times.
- And mask and mantissa to get integer.

Frac, floor, ceil, all derivatives of this.

**Comment by feilipu** [comment]
Added the math16 routines, and streamlined the math32 routines. :+1:
