### ISSUE TITLE
String initializer generating unexpected code

### ISSUE THREAD

**Issue by durgadas311** [z88dk/z88dk#1540]
Considering the follow code "inits.c":
```
struct foo {
        char bar1[12];
        char bar2[12];
};

struct foo foofoo = {
        {"this"},
        "that",
};
```
C has normally considered `{"this"}` to mean the contents of an array of characters, and `"that"` to indicate the address of a string (constant). However, compiling this with `zcc +cpm -S --c-code-in-asm inits.c` produces the opposite interpretation of the two:
```
;struct foo foofoo = {
        C_LINE  6,"inits.c"
        SECTION data_compiler
._foofoo
;       {"this"},
        C_LINE  7,"inits.c"
        defw    i_1+0
        defs    10
;       "that",
        C_LINE  8,"inits.c"
        defm    "that"
        defb    0
        defs    7
;};
...
.i_1
        defm    "this"
        defb    0

```
As a side note, current GCC (x86_64 Linux) seems to understand that in both cases the destination is a character array and so "does the right thing" (`gcc -S inits.c`):
```
foofoo:
        .string "this"
        .zero   7
        .string "that"
        .zero   7
```
Previously, I would get an error from GCC if I did not use the form `{"this"}` in this case.

**Comment by suborb** [comment]
I keep promising to myself to rewrite the initialisation code since it's fragile and prone to bugs (see #1054 for another issue).

I'll add this to the test cases and fix this up - I know the line that's causing problems.

Similar to gcc the intent is to match the destination type and do the right thing.
