### ISSUE TITLE
Z88DK nightly fails to build.

### ISSUE THREAD

**Issue by KrzysztofJeszke** [z88dk/z88dk#1558]
`svn checkout -r 11722 https://svn.code.sf.net/p/sdcc/code/trunk/sdcc -q /tmp/sdcc`
`svn: E175012: Connection time is up`
`make: *** [Makefile:74: bin/zsdcc] Error 1`

**Comment by suborb** [comment]
I haven’t seen that one lately but yes sometimes the sdcc svn server is unreliable. 

I want to stop building sdcc all the time but I’ve not had the chance yet unfortunately. 

In terms of the build I think it’s only used for one of the z80asm tests so there’s not a hard dependency so we could remove it.

**Comment by pauloscustodio** [comment]
I'll have a look at the tests to see if I can skip it if sdcc is not compiled.

Another way is maybe to add the sdcc extraction to the .cache
