### ISSUE TITLE
z80asm: -reloc-info adds -O directory path twice

### ISSUE THREAD

**Issue by hpax** [z88dk/z88dk#1572]
As of z88dk f88e8abfe8a96205221148079432c30d88e04d34:

mkdir tmp && z80asm -Otmp -b -reloc-info -g -m -l base64b.asm
tmp/tmp/base64b.reloc: No such file or directory
z80asm -O`pwd`/tmp -b -reloc-info -g -m -l base64b.asm
/home/hpa/abc80/1m/sw/tmp//home/hpa/abc80/1m/sw/tmp/base64b.reloc: No such file or directory

**Comment by pauloscustodio** [comment]
Fixed. Thanks for reporting.
