### ISSUE TITLE
-reloc-info fails to recognize subtraction

### ISSUE THREAD

**Issue by hpax** [z88dk/z88dk#1574]
There appears to be no way to get z80asm to *not* emit a relocation for code like:

foo:
         ld bc,bar - foo
         nop
         nop
bar:

... this is *not* a relocatable expression as it contains the difference between two symbols in the same section, and thus it is absolute. However, the .reloc file contains a relocation entry for address +1 in this case; this produces incorrect result post-relocation.

**Comment by pauloscustodio** [comment]
Bug reproduced. Need to think of a way to fix.
