### ISSUE TITLE
[sccz80][bug][code generator][all targets] Corrupted binaries with SCCZ80 but OK with ZSDCC

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1582]
I am getting a corrupted generated binary if I compile with SCCZ80 in a recent snapshot but I do get the right result if I use ZSDCC.
This was working fine some time ago with both SCCZ80 and ZSDCC.
The problem does not exist in the Z88DK snapshot 2020 07 03.

This seems to concern all Z88DK targets. Tested with the very latest snapshot on both mc1000 and spectrum targets.

The following code (part of Cross Chase: https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/games/chase/level.c#L173) is supposed to display a spiral but if compiled with SCCZ80 in a recent Z88DK version, then it keeps on displaying the very same tile only horizontally and loops forever:
```
void spiral(register Character *characterPtr)
{
    uint8_t i;
    uint8_t j;
    characterPtr->_x = XSize/2;
    characterPtr->_y = YSize/2;
    for(i=0;i<2*MIN_SIZE-18;++i)
    {
        for(j=0;j<i/2;++j)
            {
                displayCharacter(characterPtr);        
                if(i&2)
                {
                    ++(*((uint8_t *) characterPtr + (i&1)));
                }
                else
                {
                    --(*((uint8_t *) characterPtr + (i&1)));                
                }
                #if SLOW_DOWN>0
                    DO_SLOW_DOWN(55);
                #endif
            }
    }
}
```
Wrong effect (and infinite loop):

![image](https://user-images.githubusercontent.com/29057615/95016154-6fa2f400-0651-11eb-9c59-2698bd441d06.png)

Correct effect (SCCZ80 in snapshot 2020 07 03 or any ZSDCC even in current snapshots):

![image](https://user-images.githubusercontent.com/29057615/95016321-a299b780-0652-11eb-814c-d7e5ca042ebf.png)

Moreover a warning when I compile with SCCZ80 produces a probably wrong warning:
```
games/chase/end_screen.c:92: warning 158: overflow in implicit constant conversion
```
which is about 
```
				for(ind=0;ind<254;++ind){};
```
where ind is defined as `uint8_t`.
This should be OK as ind can have a 255 value before overflowing.

**Comment by suborb** [comment]
The problem was caused by an optimisation rule that wasn't sufficiently qualified - I've remove it for now.

The warning looks like it's come from sdcc from than sccz80 - you raised it previously here: #1129

**Comment by Fabrizio-Caruso** [comment]
@suborb By the way, nightly builds are stuck at the 28th of September. Something is broken in the tool-chain.

**Comment by Fabrizio-Caruso** [comment]
@suborb you are right about the warning. Sorry for confusing SCCZ80 and ZSDCC on the warning issue.

**Comment by suborb** [comment]
> @suborb By the way, nightly builds are stuck at the 28th of September. Something is broken in the tool-chain.

Hopefully will be fixed tonight <fingers crossed>

**Comment by suborb** [comment]
@Fabrizio-Caruso  all good?

**Comment by Fabrizio-Caruso** [comment]
I confirm that the problem is solved. Thanks a lot for fixing it.

**Comment by OpenUAS** [comment]
Thx
