### ISSUE TITLE
[pencil2][psg_sound] PSG sound is broken (never stops)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1593]
PSG sound is broken (never stops).

I have attached the .rom file (zipped).

Disregard display corruption (it is my code and I can fix it).

[FULL_pencil2.zip](https://github.com/z88dk/z88dk/files/5349616/FULL_pencil2.zip)

**Comment by suborb** [comment]
Do you see this on any other SN76489 targets?

**Comment by Fabrizio-Caruso** [comment]
Gonna test it on the SMS...

**Comment by Fabrizio-Caruso** [comment]
No PSG nor bit-bang sound on the SMS (tested on Kega Fusion) unless I have done something wrong with the emulator or the code.

**Comment by suborb** [comment]
I'm going to close this one based on #1612

**Comment by Fabrizio-Caruso** [comment]
You are right. I have made a big mess with PSG.

**Comment by suborb** [comment]
No worries. Maybe hold off on any PSG work for the moment - I'm porting PSGlib (from the newlib +sms) to the SN76489 targets. This should give a framework to play music/effects on those machines.

For the AY819x based machines, there's WYZ (https://github.com/z88dk/z88dk/wiki/Classic-WYZ-Player) which can also handle effects.

The SN76489 will be well documented on the SMS development sites/forums if you want to just create adhoc effects as you're doing at the moment.
