### ISSUE TITLE
What is the status of curses ?

### ISSUE THREAD

**Issue by jayacotton** [z88dk/z88dk#1594]
Not a bug, but a question.

Wondering if curses have had any additional work in the last year.

**Comment by suborb** [comment]
If I remember correctly you're targeting +rc2014? If that's true then I'll hand over to @feilipu

**Comment by jayacotton** [comment]
Yes rc2014

**Comment by feilipu** [comment]
@jayacotton AFAIK, I don't think that newlib has curses support. Certainly, there's no `curses.h` file in the [appropriate place](https://github.com/z88dk/z88dk/tree/master/include/_DEVELOPMENT/proto). So at first pass, I'd say not in any of the newlib targets. But, if this is wrong, I'd stand corrected.

**Comment by feilipu** [comment]
Though, at a pinch, you can use `conio.h` using the `+cpm` target and classic library.

**Comment by jayacotton** [comment]
I'll try that.

**Comment by feilipu** [comment]
Putting `curses.h` and the implementation on the list.
