### ISSUE TITLE
[bic][cpm] What is the .dump binary produced for the bic subtype?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1595]
I cannot find any documentation on the CP/M BIC subtype. I guess it is for the BIC/A5105 system.
I use JKCEMU. I can understand German but I don't know how to load it.
I select the BIC target and click on Laden (Load). Then I have to select the type of file and possibly the start and end address.

**Comment by suborb** [comment]
It's a disc image (I really don't know why anadisk uses .dump as a suffix) - so you'll need to load CP/M and insert the .dump as the secondary drive.

**Comment by Fabrizio-Caruso** [comment]
I guess I need a BIC-specific CP/M boot disk...

**Comment by suborb** [comment]
They're built into the emulator!

* Click on disc icon
* Laufwerk 1
* Eject icon
* Andere Diskette einlegen
* BIC A5105 system disk

**Comment by Fabrizio-Caruso** [comment]
Thanks a lot!
