### ISSUE TITLE
[primo][question] What is the .pp file? How is it used with Mame? 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1600]
The doc says that the .pp file produced by appmake can be read by Mame.
I have tried cassette, quickload, cartridge. Nothing has worked so far.

**Comment by suborb** [comment]
It's a quikload file - I've just tried one out on primoa32 and primoa64 and it loads and runs correctly.

**Comment by Fabrizio-Caruso** [comment]
Thanks! This helps me reduce the tests I have to do.
I doesn't work with my binary with Mame 0.196. I need to try a simpler example.

**Comment by Fabrizio-Caruso** [comment]
If I try to quickload the attached file, PRIMOA32 (Mame 0.196) just does nothing.

[FULL_primo.zip](https://github.com/z88dk/z88dk/files/5360398/FULL_primo.zip)

**Comment by Fabrizio-Caruso** [comment]
I found the problem. Sorry. It just requires more memory.
