### ISSUE TITLE
[pacman][question] Meaning of the warnings

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1607]
If I try to compile for the packman target I get:
Warning: could not get the code ORG, binary ORG defaults to rombase = 0
WARNING: ROM chip file '../build/FULL_pacman_buffered.0d' is empty, it can probably be omitted.

Are these warning harmless?

I understand that I will have to rename the rom files as the ones Mame expects and put them in a (possibly zipped) folder which should be renamed as Mame expects.

**Comment by suborb** [comment]
Yup, they are both harmless. I've killed the CRT_ORG_CODE one which looked more ominous.
