### ISSUE TITLE
sccz80: address of function not equivalent to function name

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#161]
Test program:

```
#include <assert.h>

int a[10];

void dummy(int a);

void main(void)
{
	assert((unsigned int)a == (unsigned int)&a);
	assert(dummy == &dummy);
}
```

zcc +zx -vn -clib=sdcc_iy test.c -o test --list
zcc +zx -vn -clib=new test.c -o test --list

I'm testing two things here.

The first is not going to pass because sccz80 does not do multi-dimensional arrays.  An array name "a" should refer to the same address as the address of the array "&a".  They are not the same types though - an array name is type "int[10]" whereas the address of the array is type "int (*)[]".  I'm not sure if the distinction is meaningful or not but sdcc makes a distinction.

The second is testing the equivalence of a function name and the address of a function name.  Both should yield the function address and should be the same type "void (*)(int)".  The situation is similar to arrays where the array name is an alias for its address in memory.  The function name is also an alias for the function's address for the same reason (they are assembly language labels) and the c standard says the name of a function and the address of the function is equivalent.

**Comment by suborb** [comment]
Merged via PR #165
