### ISSUE TITLE
[qc10][appmake[cpm][bug] Appmake does not create a readble disk image

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1610]
I have tested the QC-10 disk image on Mame 0.196. 
It seems the image is malformd.
I did it while only using the floppy A: as I could not access B: (I don't know how to do it in CP/M without the ":" which is absent in Mame Input settings and it seems not to be mapable to any key)

![image](https://user-images.githubusercontent.com/29057615/96013924-1bb0c000-0e46-11eb-8009-c3872030af97.png)

**Comment by suborb** [comment]
A couple of points - use the takeda emulator - there's actually a colon on that one!

And, I sent you the wrong boot disk - I've got another CP/M disk that works with the generated z88dk discs. I'll send you the one I actually use!

**Comment by Fabrizio-Caruso** [comment]
Indeed it worked with the new image but I had to use Mame as I have not been able to get the Takeda emulator to start (I put the mame rom in the same folder) but I only got a black screen.

**Comment by suborb** [comment]
For reference, these files are the ones needed for takeda/qc10:

MD5 (FONT.ROM) = cfec7dafb50aef2fc2e6069eec881c9e
MD5 (IPL.ROM) = 7f8477b9fd041170467890d84d613f76
MD5 (MFONT.ROM) = 2d138de9e3bef43ac91af5637cc7fb3f
