### ISSUE TITLE
[cpc][bug?] Hello world

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1615]
I am struggling with a helloworld example with the CPC target:
```
#include<stdio.h>
int main() {

    printf("Hello World!\n");
    while(1){};
    return 0;
}
```
which just restarts the computer when run.

I am compiling it with (I have also tried without clib and pragma options):
```
cpc_hello:
	$(Z88DK_PATH)$(MYZ88DK) +cpc -lndos -pragma-define:REGISTER_SP=-1 -clib=ansi  -create-app -o$(BUILD_PATH)/HELLO_cpc.cpc  -vn \
	$(TEST_PATH)/helloworld.c
	$(TOOLS_PATH)/z88dk/cpc/2cdt.exe -n -r cross_chase $(BUILD_PATH)/HELLO_cpc.cpc  $(BUILD_PATH)/HELLO_cpc.cdt
...
```

**Comment by suborb** [comment]
I don't know what 2cdt is doing, however using the examples and tools within z88dk, taking a look at the ANSI library:

    cd examples/console
    zcc +cpm -clib=ansi ansitest.c -create-app -lndos -subtype=wav

Create a file that loads and work in Mame and Winape, loading is done by:

    |tape
    memory &1fff
    load "",&1200
    call &1200

The `|tape` is only needed on disc based systems.

A similar exercise can be done with world.c:

    zcc +cpc world.c -create-app -lndos -subtype=wav

And that loads and runs succesfully in mame.
