### ISSUE TITLE
[laser500][info] Code that documents bitmap modes on Laser500 by nippur72

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1616]
@nippur72 has shown me how bitmap modes are enabled and used on the Laser 500.

This may be useful for a possible implementation on the laser500:

https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/cross_lib/display/init_graphics/z88dk/laser500/laser500_bitmap_init_graphics.c

All this code is by @nippur72

**Comment by suborb** [comment]
There's been an implementation of the 320x192 screen mode (which seems to the the one you're using) in z88dk (as mode 2) for a couple of years.

**Comment by Fabrizio-Caruso** [comment]
Sorry for missing this
