### ISSUE TITLE
Should zsdcc use a final translation stage instead of mappings.i to target different assembler syntax?

### ISSUE THREAD

**Issue by spth** [z88dk/z88dk#1618]
SDCC currently uses mappings.i to support dsifferent assembler syntax. This has two problems:

1) When making a change in code generation and forgetting to use the correct macro, the resulting code stillo works with sdasz80, but not some of the other assemblers. Since this often only affects corner cases, it can take a while to get noticed. Doing the right thing here places a burden on those maintaining z80 code generation in SDCC.
2) The peephole rules that come with sdcc only work with sdas, as the mappings.i macro expansion happens in between code generation and the peepholeoptimizer.

An alternative would be to replace mappings.i by an additional assembler syntax translation stage (possibly implemented as another peephole optimizer rules file) after the normal peephole rules. What do z88dk developers think of such a change in SDCC?

**Comment by suborb** [comment]
We use the asz80 output and post-process the output into z80asm format: because of the reasons you enumerated above.

So, dropping support for other assemblers should have no effect on us.
