### ISSUE TITLE
[info/bug] Are optimization options possible on gb target? which ones?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1620]
If I compile my games for gb with SCZ80 and I pass -O3 I get some illegal identifier errors on the that do not make much sense to me. Should I use -SO3 instead?

**Comment by suborb** [comment]
-O3 is a bit of a misnomer: it's actually really -Os in that it tries to make the generated code smaller (rather than faster).

I certainly don't use -O3, and it appears it's got some rules that need qualifying on the gbz80 which I'll sort out.
