### ISSUE TITLE
classic: Amstrad CPC targets: stability problems ?

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#163]
We seem to have stability problems with the CPC target(s).
I could see output working by a sequence of fputc_cons calls, or minimal printf but nothing more, investigation needed.

**Comment by zx70** [comment]
Extra comment: tested in on the CPC464 emulation (MESS).
A very short initial part of the programs can be seen on output if I comment out the "EI" instructions on the CRT0 file.

**Comment by aralbrec** [comment]
I'll have a look at this.  The cpc was fixed recently and should be rock-solid.  I had no trouble running any cpc programs.

**Comment by zx70** [comment]
Correct myself.. tested on cpc664 and 6128, not cpc464.  ..is it relevant?

**Comment by suborb** [comment]
The 464 was relevant, fixed in e7bbebc0d6f5b6fbfc2ac6dbe8cadfec8878347a

**Comment by zx70** [comment]
forgot to close it myself,  well done,  Dominic  👍
