### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by hackneyc** [z88dk/z88dk#1646]
Hi,
Looks like uthash-dev package is also required to build?

I also had problems building from the 2.0 release package. It appears it is missing the submodules? A recursive clone of the repo from the 2.0 tag resolved this issue.

**Comment by suborb** [comment]
It shouldn't be - uthash is a submodule so if that's pulled it should be used.

The auto-generated zip files won't contain the submodules since they are just an automated snapshot of the repo, but the -src.tar.gz should contain them.
