### ISSUE TITLE
SOS library: missing objects?

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1652]
@suborb,  what is the point of excluding the SOS variables position during the library build?  (#ifdef BUILDING_SOSLIB)
https://github.com/z88dk/z88dk/blob/master/include/sos.h

The resulting libraries claaim for missing objects during the link process.

**Comment by suborb** [comment]
I'm not sure, I'm guessing it was so that the user could override them at compile time. However, the behaviour of that placement syntax has changed over the years. I have a feeling it's now file local by default?

**Comment by zx70** [comment]
I moved the exports here:  https://github.com/z88dk/z88dk/blob/master/libsrc/target/sos/sos/sos_variables.asm
I think it is consistent also when the sdcc compiler is involved
