### ISSUE TITLE
(sccz80) Literal arithmetic uses fp even for integral types

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1656]
I am trying to understand what goes on when I compile my code with an expression such as:
XSize-XSize/4-(XSize/5)

This seems to behave as I expect on all other compilers including GCC but it seems I am having a problem with Z88DK compilers.

In my case XSize is 32 and I can even replace XSize with 32 and I still get something wrong as if 32/5 were not evaluated as integer division. i.e., 32/5 = 6. The result I get looks a bit like 32/5 = 7.

If I replace XSize/4 with 8 and XSize/5 with 6, I get the right expected result under Z88DK.

This looks like a bug.
It can be reproduced with:
```
#include <stdio.h>
#define XSize 32
int main(void)
{
    printf("debug: %d\n", XSize-XSize/4-XSize/5);
    return 0;
}
```

If I compile with Z88DK I get 17 but if I compile with any other compiler I get 18.

Z88DK:
![image](https://user-images.githubusercontent.com/29057615/102143172-d91a5c80-3e63-11eb-9d12-858ef93e6647.png)

GCC:
![image](https://user-images.githubusercontent.com/29057615/102143213-e9323c00-3e63-11eb-9f07-b55d3c0a76b0.png)

**Comment by suborb** [comment]
Interesting. 

The expression folding is performed with floating point arithmetic and then converted to an int with a cast. Given the result is 17.6 it looks like we're truncating rather than rounding.

**Comment by Fabrizio-Caruso** [comment]
@suborb should the division between integer litterals rather be integer division?

**Comment by Fabrizio-Caruso** [comment]
@suborb It looks like GCC uses integer division to perform division between integer litterals (as normal C code)
    printf("debug 2: %d\n", XSize/5); -> 6
    printf("debug 2: %f\n", XSize/5); -> non-sense

**Comment by Fabrizio-Caruso** [comment]
@suborb If we assume that GCC (and all other compilers I have tried are correct), then the problem is not the rounding. 
The problem is that the wrong operation is performed on integer litterals.

**Comment by Fabrizio-Caruso** [comment]
If you apply the rounding and keep float operations on integer litterals, we will get errors elsewhere, i.e., when float fractions add up to an integer.

**Comment by suborb** [comment]
Yup, It's obviously not right and it'll propagate through all calculations.

I'll fix it, though I'm having a bit of time "away" from z88dk at the moment so it'll be a few days.

**Comment by Fabrizio-Caruso** [comment]
The problem seems fixed for me.
