### ISSUE TITLE
[probable bug][gb][gbz70] Probable bug in gb

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1666]
In my newest Cross-Lib-based game "Cross Snake", the following code:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/games/snake/snake.c#L55
fails by producing graphics glitches and corruptions once it is executed on the GB target and works find on all other targets (both Z88DK and other dev-kits).

If I skip this code, the whole game works fine even on the GB target.

I know this is not enough to open an issue. I will try to isolate it better.

The code does a copy of the snake_x and snake_y arrays into a snake_copy_x and snake_copy_y arrays in order to get a longer snake.
I suspect this operation is overwriting some memory.
@suborb could this be stack-related? Are arrays allocated next to the stack?
I also observe tiles being corrupted as if the tiles shape where overwritten.

**Comment by suborb** [comment]
There was a slightly dodgy optimisation rule. I've now fixed it and the snake can now grow on +gb!
