### ISSUE TITLE
Target CPM and code Intel 8080

### ISSUE THREAD

**Issue by sblendorio** [z88dk/z88dk#1670]
Hi, I compiled just an "Hello World":

    #include <stdio.h>
    
    void main(void) {
        printf("Vediamo se funziona\n");
    }

with this command line:

    zcc +cpm -m8080 test.c -o test.com

but, disassembling the ".com", I found specific Z-80 code (like LD BC and registers IX and IY). Trying to execute it on CP/M running on 8080, it does not run and hangs up the machine.

This is the .com file resulting: https://www.dropbox.com/s/fehqtae0nvxv9wb/test1.com?dl=0

This is the test I did:

![image](https://user-images.githubusercontent.com/2118813/104719621-0ab96880-572d-11eb-8616-779549cf810a.png)

The .com file was also tested on a real Intel 8080 machine with CP/M.
How can I get a compiled .com for CP/M for Intel 8080?

**Comment by suborb** [comment]
The 8080 target is specified using `-clib=8080`, so the command line should be:

```
zcc +cpm -clib=8080 test.c
```

**Comment by sblendorio** [comment]
IT WORKED! Thanks a  lot!
