### ISSUE TITLE
Add incbin directive as a synonym for binary

### ISSUE THREAD

**Issue by jblang** [z88dk/z88dk#1671]
To improve source compatibility with other assemblers (e.g., sjasm, pasmo, the other z80asm), it would be nice to have incbin as a synonym for binary to include a binary file.

Or alternatively, is there a pre-defined symbol that I could check using if directive to know if I am using z88dk z80asm and conditionally use the binary directive instead of incbin?

**Comment by pauloscustodio** [comment]
I will add INCBIN as a synonym to BINARY latter this week.

In the mean time, you could check for the define __CPU_Z80__ (assuming you are compiling for z80)
   ifdef __CPU_Z80__
   ...
