### ISSUE TITLE
Has generation of labels with regular expressions changed?

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#1678]
I just tried an old recipe, and I note that `z88dk-z80asm` now doesn't recognise my `.rex` file, and/or the options `-gpf` don't seem to work.

```sh
zcc +yaz180 -subtype=rom -SO3 -v -m -clib=sdcc_iy -llib/yaz180/ff -llib/yaz180/time --math32 --max-allocs-per-node2000000 @yabios.lst -gpf yabios.rex -o yabios -create-app
```
What did I miss?

**Comment by suborb** [comment]
Isn't the option:

```
 -gpf:yabios.rex
```

that is with a `:` or an `=` between the option and filename?

**Comment by feilipu** [comment]
Might have changed? But the version noted was working late last year.

Will try with a : tomorrow.

**Comment by feilipu** [comment]
Works as expected with a `:`. Thanks.
