### ISSUE TITLE
produced spurious 0-byte file "*___DEBUG.bin" after compilation

### ISSUE THREAD

**Issue by sblendorio** [z88dk/z88dk#1680]
I just pulled from github the latest version of z88dk.

Compiling something with a command like this:

    $ zcc +cpm demo.c -o exec.com

is produced on the disk a **0-byte** file named **exec___DEBUG.bin**, it didn't happen before PULLing latest version.

**Comment by suborb** [comment]
That was the result of some debugging experiments, I've stopped it from being generated now.
