### ISSUE TITLE
Stack position on CP/M

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1688]
Do I understand correctly regarding the SP initialization for the CP/M target?
Looking at the start-up code it seems to me we left it at -1.
I wonder if it should be lowered, e.g. referring to the higher byte of the BDOS vector call in the PSP (at position 0007h).

**Comment by zx70** [comment]
this probably answers already: 
https://www.z88dk.org/forum/viewtopic.php?t=11004

**Comment by suborb** [comment]
The -pragma-define:REGISTER_SP=NNNN has the following semantics:

* -1 leave as is
* +NNNN -> ld sp,
* -NNNN  -> ld sp,(NNNN)

So I don't think there's a need to change anything in the crt, but maybe some doc to explain how to do certain things.

**Comment by zx70** [comment]
Thankyou @suborb :)
I found the answer myself too, with an quick experimental check on the Bondwell2.
The stack is already properly initialized by the CP/M system, there's no need to force it.

![wb2_memmap](https://user-images.githubusercontent.com/10224992/106244560-6135a500-620b-11eb-95c4-f03675367073.png)
