### ISSUE TITLE
(zcc) opt-code-speed error for zsdcc

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#1697]
It appears that opt-code-speed has been made an sccz80 option only when it in fact also exists as an option for zsdcc.  I have some compiles that are no longer working for zsdcc as the option type has been changed from boolean to function.

Perhaps there is a way to allow no parameter so that the zsdcc option can be ticked and sccz80 can take a default action?

Edit: It looks like there wasn't any special treatment for opt-code-speed before the additions for sccz80 -- the option was likely passed to zsdcc as a default action for unknown options.

**Comment by suborb** [comment]
* Options which aren't recognised by zcc are passed through to the compiler
* Options prefixed with -Cs are passed through to sdcc
* Options prefixed with -Cc are passed through to sccz80

**Comment by suborb** [comment]
More command line fudging has been added.
