### ISSUE TITLE
Possible to execute (chain) to other programs a la execv() in cpm? 

### ISSUE THREAD

**Issue by tschak909** [z88dk/z88dk#1699]
Is there a method for chaining to other programs in CPM? I have looked through the existing headers, but wasn't 100% sure...
-Thom

**Comment by Xalior** [comment]
Have a look at https://github.com/z88dk/z88dk/issues/1627 and see if it’s any help :)

-Dx

**Comment by tschak909** [comment]
Yeah, I figured it out. closing this. :)
-Thom
