### ISSUE TITLE
z88dk: Cleanup windows build files

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#171]
There's a whole bunch of windows batch and solution files hanging around the place:

````
src/*/gccmake.bat
src/*/vscmake.bat
src/*/*.vcxproj
win32/*/*.vcxproj
````

The ones which are needed should remain, and the ones that aren't should be removed.

Given that z88dk compiles with Visual Studio Express and we're heavily dependent on a functioning make, that suggests the .bat files can be removed.

I'm guessing that the win32/*/*.vcxproj files are the ones that are actually used?

**Comment by pauloscustodio** [comment]
Correct. The .vcxproj files under win32 are used by Visual Studio. The bat files can be removed.
