### ISSUE TITLE
(classic) missing FP math subroutines invoking SDCC

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1719]
This is possibly simpler for @suborb than me.
I think it is just a matter of including those three functions on the 'classic' side ?

___uint2fs_callee, ___fsdiv_callee, ___fsmul_callee

ttt.c:709: warning 93: type 'double' not supported assuming 'float'
ttt.c:746: warning 93: type 'double' not supported assuming 'float'
ttt.c:700: warning 126: unreachable code
ttt.c:701: warning 126: unreachable code
ttt.c:794: warning 126: unreachable code
ttt.c:660: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
ttt.c:702: warning 126: unreachable code
ttt.c:703: warning 126: unreachable code
ttt.c:705: warning 126: unreachable code
ttt.c:792: warning 126: unreachable code
Error at file 'ttt.c' line 996: symbol '___uint2fs_callee' not defined
Error at file 'ttt.c' line 1002: symbol '___uint2fs_callee' not defined
Error at file 'ttt.c' line 1013: symbol '___fsdiv_callee' not defined
Error at file 'ttt.c' line 1020: symbol '___fsmul_callee' not defined
Errors in source file c:/z88dk/lib/config\..\..\\lib\target\zx\classic\spec_crt0.asm:
Error at file 'ttt.c' line 996: symbol '___uint2fs_callee' not defined

**Comment by suborb** [comment]
Two general purpose maths libraries work with sdcc and classic:

* `-lmath48`
* `--math32`

There's not much benefit to getting -lm working (it's got the same characteristics as math48) and the benefit of the some of the other libraries is that they work on an 8080, which isn't supported by sdcc.

**Comment by zx70** [comment]
Thank you !
