### ISSUE TITLE
(sam) (classic) Errors and issues in compiling other examples

### ISSUE THREAD

**Issue by dandoore** [z88dk/z88dk#1733]
*/examples/sound/etracker/*

_main.c_

Command line: zcc +sam main.c axel.asm -lm -v -lndos -create-app 

Works but slow (running at about 1/3 speed?)

*/examples/clisp/*

_clisp.c_

Command line: zcc +sam clisp.c -lm -v -lndos -create-app 
```
z88dk-z80asm -mz80 -b -d  -o"clisp" -m -s -L.   -I"C:\Users\xbox\AppData\Local\Temp\zcc00001D245C7E3" -D__SCCZ80 -L"d:\z88dk\lib\config\..\..\/lib/clibs" -I"d:\z88dk\lib\config\..\..\/lib" -l"genmath" -lndos -lsam_clib -lndos -l"z80_crt0"     "C:\Users\xbox\AppData\Local\Temp\zcc00001D245C7E4.o" "C:\Users\xbox\AppData\Local\Temp\zcc00001D245C7E2.o"
Error at file 'clisp.c::init::0::8' line 608: symbol 'time' not defined
Errors in source file d:\z88dk\lib\config\..\..\\lib\target\sam\classic\sam_crt0.asm:
Error at file 'clisp.c::init::0::8' line 608: symbol 'time' not defined
```

*/examples/console/*

_adv_a.c_

Command line: zcc +sam adv_a.c -lm -v -lndos -create-app -DPICS -DCOMPUTE_SCORE

No Graphics (black on black?) since 24th nightly build, previously graphics not displaying correctly compared to ZX Version same issue as */examples/graphics/marilyn.c* ?

*/examples/console/*

_vstone.c_

Command line: zcc +sam vstone.c -lm -v -lndos -create-app -clib=ansi -pragma-define:ansicolumns=80

With or without
```
 	int mode=3;
	console_ioctl(IOCTL_GENCON_SET_MODE,&mode);
```

Needs to display 80 columns (CSIZE 8x6) in MODE 3 to work but not supported?

_world.c_

Command line: zcc +sam world.c -lm -v -lndos -create-app
Command line: zcc +sam world.c -lm -v -clib=ansi -lndos -create-app

No output.

**Comment by suborb** [comment]
Yeah, I totally mucked up the graphics last night - my recompilation didn't pick up the optimisation I made so I assumed it work. Missing "and a" from the core graphics routines so it thinks every pixel is out of bounds :(

I thought etracker was slow, but didn't have a reference - can you let me know a good delay time - I'm guessing something like 20millis should be correct to match the interrupt. Unfortunately for me it sounds awful at 20millis, but I think that's because my laptop is practically a retro machine in itself and only runs emulators at a variable speed between 50-75% speed most of the time.

Regarding the graphics in Marilyn and presumably adv_a, the draw_profile does an odd compile time scaling based on the horizontal resolution of the screen. Since we configure the max dimension to match that of mode 3 the scaling takes things off screen in a weird way.  I think this also affects other targets that have variable width graphic modes where one of the modes is >= 320 pixels.

I suspect that when you switch to mode 3 everything appears correctly. @zx70 is it possible to call getmaxx() to do the scaling at runtime  inside draw_profile?

World.c is a great one (I'm laughing to be honest), it's got this line:

        printf("Hello world! %c\n",12);

The %c was originally a %d to do a little bit of maths for 8080 machines and (oddly) trim down the binary size. Unfortunately printing character 12 directly clears the screen! So of course nothing can be seen!

A few of the others are because there's no system clock for the SAM moment, though since I think there's an RTC module which I suspect would be better to hook up to?

80 column mode would be covered by #1707 - it probably makes sense to do it for the SAM only in mode 3.

**Comment by zx70** [comment]
Oops
. I wanted the screen to be cleared,  but the intention was to have it before printing

**Comment by dandoore** [comment]
> I thought etracker was slow, but didn't have a reference - can you let me know a good delay time - I'm guessing something like 20millis should be correct to match the interrupt. Unfortunately for me it sounds awful at 20millis, but I think that's because my laptop is practically a retro machine in itself and only runs emulators at a variable speed between 50-75% speed most of the time.

Here is the song running: https://www.youtube.com/watch?v=1e05RqzJQPY&t=90s
 
> The %c was originally a %d to do a little bit of maths for 8080 machines and (oddly) trim down the binary size. Unfortunately printing character 12 directly clears the screen! So of course nothing can be seen!

:)
 
> A few of the others are because there's no system clock for the SAM moment, though since I think there's an RTC module which I suspect would be better to hook up to?

Yes, there is a standard RTC's that is used - reffered to as the SamBus/DALLAS clocks - implementation details in clock.cpp https://github.com/simonowen/simcoupe/tree/master/Base if that helps.
 
> 80 column mode would be covered by #1707 - it probably makes sense to do it for the SAM only in mode 3.

Cool.

**Comment by zx70** [comment]
draw_profile() should be better now

**Comment by dandoore** [comment]
I've got a fix for etracker, the calling routine needs to be called once a frame so extarcting the `pause` function from the SamC libraries works a charm like this:
```
void pause(int c)
{
	#asm
	ei
	ld a,h
	or l
	ret z
	halt
	dec hl
	ld a,0x7f
	in a,(254)
	rrca
	ret nc
	jr $-11
	#endasm
}

<SNIP>

   // Just loop
   while  ( 1 ) {
#ifdef NO_INTERRUPT
       saa_etracker_play();
       pause(1);
#endif
```
pause is a handy fuction in other stuff too - can it be added in somewhere?

**Comment by suborb** [comment]
The other option is to get it to run on the interrupt, this seems to run okay with Mame but is deathly silent with Simcoupe so something is missing there. I'm a little baffled:

![image](https://user-images.githubusercontent.com/394721/112537739-f2a63b00-8da6-11eb-80ce-dca761b1fbb5.png)

![image](https://user-images.githubusercontent.com/394721/112537754-f639c200-8da6-11eb-8aff-c121e315336f.png)

Why is it reading 0xff if the debugger thinks there's a frame interrupt waiting?

I've just tried it out your version and it still sounds terrible on my machine with the % indicator bouncing around all over the place. You can do the same thing with:

```
#include <intrinsic.h>

intrinsic_halt()
```

**Comment by dandoore** [comment]
> 
> 
> The other option is to get it to run on the interrupt, this seems to run okay with Mame but is deathly silent with Simcoupe so something is missing there. I'm a little baffled:
> 
> ![image](https://user-images.githubusercontent.com/394721/112537739-f2a63b00-8da6-11eb-80ce-dca761b1fbb5.png)
> 
> ![image](https://user-images.githubusercontent.com/394721/112537754-f639c200-8da6-11eb-8aff-c121e315336f.png)
> 
> Why is it reading 0xff if the debugger thinks there's a frame interrupt waiting?

This is @simonowen, @stefandrissen and @frodete 's area - I know literally nothing about assembler :(

> I've just tried it out your version and it still sounds terrible on my machine with the % indicator bouncing around all over the place. You can do the same thing with:
> 
> ```
> #include <intrinsic.h>
> 
> intrinsic_halt()
> ```

Ah, that's neater - Under SimCoupé it's spot on in terms of timing.

**Comment by suborb** [comment]
Oh wow...I've not tracked down the right bit of the emulator source, but if I read the status port before I fiddle with HMPR it works ok.

And it sounds better if I hide the emulator window :) I'll update the example so it's interrupt driven.

**Comment by simonowen** [comment]
> ![image](https://user-images.githubusercontent.com/394721/112537739-f2a63b00-8da6-11eb-80ce-dca761b1fbb5.png)

In the image above the frame interrupt (F) is indeed active in the Status register, but the Events list in the bottom right also shows the end-of-interrupt even is due in 2 CPU cycles. It'll become inactive even before the next opcode byte is read, so the port read will show no interrupts are active.


> ![image](https://user-images.githubusercontent.com/394721/112537754-f639c200-8da6-11eb-8aff-c121e315336f.png)

In the image above you can see the pink dash where the F has disappeared, so the interrupt is no longer active.

I'm not sure I understand about hiding the window improving the sound. Is that in SimCoupe? Does it report that it's running at 100% speed? If you've built from source the Debug version might run a chunk slower, but I'd be surprised if it can't run at full speed on any system from the last 10 years  :)

**Comment by suborb** [comment]
Thanks @simonowen, totally didn't spot nor understand the events section, but yes, reading the register a little bit earlier fixed it. Obviously there's an omission in the Mame which doesn't emulate that behaviour.

I'm using a  1.1 binary that I downloaded a few years ago, the % result drops down to 70 at times which is when the sound becomes out of sync. 

To be honest, although it's an old machine (2012) it probably just needs a reinstall and cleanup since I have performance issues with most emulators.

**Comment by dandoore** [comment]
**/examples/console/**

_adv_a.c_

Fixed \o/

**/examples/sound/etracker/**

_main.c_

Command line: zcc +sam main.c axel.asm -lm -v -lndos -create-app

Working under interrupts but putting a basic printf("*") in the main loop results in corruption of the characters being printed:

![simc0107](https://user-images.githubusercontent.com/43847005/112607653-59f8d500-8e11-11eb-885b-293fb868a6aa.png)

I added the interrupt-driven routing to one of my other test program that is printing lines on the screen with draw() and that is unaffected though.

**Comment by suborb** [comment]
Looks like etracker uses af' as well so that will need to be saved on the interrupt.

**Comment by zx70** [comment]
I got back to draw_profile() to make its memory allocation dynamic using getmaxx() and getmaxy().  This will save lots stack space on the GSX target but it works also dynamically in those targets supporting video mode changes at runtime.

**Comment by suborb** [comment]
@zx70 that change doesn't seem to work for adv_a.c for the SAM, I'm guessing the stack is being adjusted incorrectly and we end up in space.

**Comment by zx70** [comment]
Probably I need to extend the test to more targets, thank you for alerting.

**Comment by zx70** [comment]
odd, the resolution is rather static on the SAM, it must be a stupid bug

**Comment by zx70** [comment]
Weekend time, if it's annoying to have it hanging around for a couple of days, feel free to revert.

**Comment by dandoore** [comment]
Etracker test is spot on:
![simc0111](https://user-images.githubusercontent.com/43847005/112719117-00ff6e80-8eef-11eb-8c7b-cecb5bfc6979.png)

I presume the issue with _clisp.c_ is just doen to support for RTC/time or is there more to it?

**Comment by zx70** [comment]
You can try building it by setting the -DNOTIMER flag.
There's almost no loss in excluding it.
You'd be rather interested in adding -DGRAPHICS.

**Comment by zx70** [comment]
@suborb , I think I understood what went wrong with draw_profile.
Stencil_render works on a single vector having the subsequent left and right sides of the picture, of 1 or 2 bytes depending on the horizontal rez.   Setting dynamically a different segment length (and reduce the stack space) in stencil_render  without instructing draw_profile accordingly will obviously mess up the pictures and probably crash.

It is then going to be an extra option in gfx/common, which I'll surely use for GSX ..ATM it is allocating 768x4=3Kbytes on stack, when (the bottom of) the memory is already bearing the GSX layer itself.

I'm sorry I didn't test it right,  I think I was trapped by an unexpected behavior of the ts2068, staying in standard zx mode.

**Comment by dandoore** [comment]
> You can try building it by setting the -DNOTIMER flag.
> There's almost no loss in excluding it.
Cool that works:
![simc0116](https://user-images.githubusercontent.com/43847005/112725102-5eef7e80-8f0e-11eb-84fc-0506e75db1dd.png)

> You'd be rather interested in adding -DGRAPHICS.

I shall give the turtle a run out :)

**Comment by zx70** [comment]
nope, draw_profile will stay like this,  it'll be eventually quoted in the GSX thread

**Comment by zx70** [comment]
I see you chose to build CLISP in SpecLisp mode:  be aware that it is not the way you should program in LISP nowadays,  it was an obscure, now totally forgotten dialect  :)

**Comment by dandoore** [comment]
Frames issue added to enhancement request  #1741
