### ISSUE TITLE
Problem getting calloc to work.

### ISSUE THREAD

**Issue by jayacotton** [z88dk/z88dk#1740]
Here is a build log:

$ make ping
zcc +cpm --list --c-code-in-asm  -Wall -pragma-include:zpragma.inc -DFRAM -c ping.c   
zcc  +cpm --list --c-code-in-asm  -Wall -pragma-include:zpragma.inc -DFRAM -c  w5500.c
zcc  +cpm --list --c-code-in-asm  -Wall -pragma-include:zpragma.inc -DFRAM   -c  dhcp.c
zcc  +cpm --list --c-code-in-asm  -Wall -pragma-include:zpragma.inc -DFRAM  -c  spi.c 
zcc  +cpm --list --c-code-in-asm  -Wall -pragma-include:zpragma.inc -DFRAM   -c  socket.c 
zcc  +cpm --list --c-code-in-asm  -Wall -pragma-include:zpragma.inc -DFRAM   -c  ethernet.c 
zcc  +cpm --list --c-code-in-asm  -Wall -pragma-include:zpragma.inc -DFRAM -DHOSTS -c  dns.c 
zcc +cpm --list --c-code-in-asm  -Wall -pragma-include:zpragma.inc -DFRAM -c  time.c 
zcc  +cpm --list --c-code-in-asm  -Wall -pragma-include:zpragma.inc -DFRAM -c libfram.c
zcc +cpm --list --c-code-in-asm  -Wall -pragma-include:zpragma.inc -DFRAM -DDEBUG -c libhost.c
zcc  +cpm -create-app -oping ping.o w5500.o dhcp.o spi.o socket.o ethernet.o dns.o time.o -lm libfram.o libhost.o 
Error at file 'calloc_callee.asm' line 27: symbol '_heap' not defined
Error at file 'free.asm' line 14: symbol '_heap' not defined
Errors in source file c:\cygwin64\home\lbmgm\projects\z88dk\lib\config\..\..\\lib\targ
et\cpm\classic\cpm_crt0.asm:
Error at file 'calloc_callee.asm' line 27: symbol '_heap' not defined
Error at file 'free.asm' line 14: symbol '_heap' not defined
make: *** [Makefile:68: ping] Error 1

In zpragma.inc
$ cat zpragma.inc 
#pragma output REGISTER_SP = 0xa000
#pragma output USING_amalloc

The bug is that _heap is undefined.  Now I did a test program to find out if calloc worked at all, and the test shows it 
to be correct.  So, I assume its my build environment or build scripts that are the problem.

The calloc is in the libhost.c file.  Main is in ping.c, it also includes malloc.h 

?? any ideas ??

**Comment by suborb** [comment]
`-pragma-include:zpragma.inc` is actually a linking option not a compilation option, so that needs to go on your link line.

**Comment by jayacotton** [comment]
Yep, that got it.
