### ISSUE TITLE
8080 portability

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1744]
I understand that the 8080 CPU needs specifically written code and protection  barriers (IF __CPU_INTEL__,  etc).
Do I have some automatic z80->8080 conversion facility, though ?   E.g.  JR instructions automatically switching to JP ?

What about DJNZ ?   I'm doing this:

IF __CPU_INTEL__
	dec b	; 8080 friendly code
	jr nz,skip_header
ELSE
	djnz skip_header
ENDIF

**Comment by suborb** [comment]
Yes, djnz, jr are converted correctly for 8080.

The protection is only needed for "missing" features - so 0xcb, 0xed pages and the index registers.
