### ISSUE TITLE
Much large code

### ISSUE THREAD

**Issue by varmfskii** [z88dk/z88dk#1746]
When producing a zxnext dot file from the code in https://gitlab.com/varmfskii/showsimg there is a 37% increase between the size of the code produced by the 2.1 release as opposed to the 2.0.

**Comment by suborb** [comment]
So, varying the sdcc versions but keeping the lib the same and looking at the size of the executable:

Today (12069) -> 10454
2.1 (12036) -> 10454
2.0 (11556) -> 10399

I'm not seeing a 37% increase in the code size, you're going to give me a hint!

**Comment by varmfskii** [comment]
When I build with 2.0 (including the libraries that shipped with 2.0):  7693 bytes.
with 2.1 and the current release: 10454 bytes
7693/10454 = 1.358 so 36%, not 37%



--

Theodore (Alex) Evans

Emory University CSI



________________________________
From: suborb ***@***.***>
Sent: Friday, April 2, 2021 11:48 AM
To: z88dk/z88dk ***@***.***>
Cc: Evans, Alex ***@***.***>; Author ***@***.***>
Subject: [External] Re: [z88dk/z88dk] Much large code (#1746)


So, varying the sdcc versions but keeping the lib the same and looking at the size of the executable:

Today (12069) -> 10454
2.1 (12036) -> 10454
2.0 (11556) -> 10399

I'm not seeing a 37% increase in the code size, you're going to give me a hint!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fz88dk%2Fz88dk%2Fissues%2F1746%23issuecomment-812637852&data=04%7C01%7Ctheodore.alexander.evans%40emory.edu%7C84f877250a6b4b1f122408d8f5ff7af5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637529824930487514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=brKUq5asf3E96D5HB1hMe%2BJwxh4OCsjtIS5tEnOCv1w%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADYA2EZKWJR27ODCOEU2WH3TGX7NTANCNFSM42JE5IRA&data=04%7C01%7Ctheodore.alexander.evans%40emory.edu%7C84f877250a6b4b1f122408d8f5ff7af5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637529824930497510%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1k%2BTRCYl4DpBC1V2AqfeQKdjnqA3ox7elN1CTBh1rM8%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).
