### ISSUE TITLE
Strange code generation bug for `uint8_t += uint8_t` (both on stack)

### ISSUE THREAD

**Issue by everslick** [z88dk/z88dk#1753]
How can code like:

```
// sz and len are uint8_t on the stack
printf("sz=%u, len=%u\n", sz, l);
sz += l;
printf("sz=%u, len=%u\n", sz, l);
```

ever produce output like:

![Screenshot from 2021-04-08 10-57-09](https://user-images.githubusercontent.com/1909551/113998266-32662b80-9859-11eb-88b0-0a79febe7cb5.png)

The code that shows the bug is here:

https://github.com/everslick/push/blob/master/src/cli.c#L185-L229

the offending line is this:

https://github.com/everslick/push/blob/master/src/cli.c#L215

I already shuffled the variables on the stack and reduced the stack size, by making buf[] smaller, to rule out stack corruption, but the bug does not look like stack corruption anyway.

it looks like the address of `l` is not calculated correctly and something else then `l` is added to `sz` instead. also whatever this 'something else' is, is not constant (but 13, 17 and 21).

**Comment by everslick** [comment]
Expected output:

![Screenshot from 2021-04-08 11-16-43](https://user-images.githubusercontent.com/1909551/114001121-ed8fc400-985b-11eb-9664-ec53d3783f54.png)

**Comment by suborb** [comment]
There's a mistake in z80rules.1

I've got other rules outstanding, but line 3830 currently has this:

        ld      hl,%1   ;const

It needs to be:

        ld      hl,%eval(%1 2-)   ;const

[Tabs are important] - I'll run through some more checks this evening to make sure it's actually correct.

**Comment by everslick** [comment]
fantastic! thank you!

**Comment by everslick** [comment]
I tried your fix, but it actually made things worse. now the `l` variable is 255 after each `+=`. if this is of any help to you.

Interestingly `sz` is now increased by double the value it should be e.g. if `l` is **3** `sz` increases by **6**.

**Comment by everslick** [comment]
I tried your fix, and it works flawlessly. Ignore my comment from 10 minutes ego, which i have since deleted. (i testet MY test code, without realizing).

**Comment by suborb** [comment]
That's great, the fix went in this commit: https://github.com/z88dk/z88dk/commit/030732620e7098322acc0a4b97c63440b38d3a94
