### ISSUE TITLE
(sam) (classic) Large array causes crash

### ISSUE THREAD

**Issue by dandoore** [z88dk/z88dk#1754]
The following code causes a crash when defining an array:

```
#include <stdio.h>

int main(void) {
	printf("Before...\n");
   	unsigned char array[1500];
	printf("After...\n");
}
```

Same code compiled under ZX works fine under FUSE.

**Comment by suborb** [comment]
It took me a while to find something that I knew I'd written: https://github.com/z88dk/z88dk/wiki/Platform--Sam-Coupe.md#the-stack

**Comment by dandoore** [comment]
Ah, I see - should I be using malloc() or something similar here instead?

**Comment by suborb** [comment]
Just use the pragma to increase the stack size if you're doing something quick and easy.

It looks like I've not set malloc up properly yet - thanks for the reminder.
