### ISSUE TITLE
(sam) (classic) Support for MODE3 'Fatpix"

### ISSUE THREAD

**Issue by dandoore** [z88dk/z88dk#1772]
SAM MODE 3 allows for pixels to be made double-wide via the FATPIX function, allowing horizontal and vertical pixels have the same thickness.

When FATPIX 1 is enabled the XRG (part of the graphics scaling subsystem's X range) is halved from 512 to 256, FATPIX 0 restores XRG to 512 note that the screen is not cleared or mode changed as per the attached:

![simc0132](https://user-images.githubusercontent.com/43847005/116697666-639acd00-a9bb-11eb-8b8c-a47415cb232f.png)

Use case is the conversion of 64 column programs with graphics from the ZX platforms to use MODE3 (in this case, [AITTT](http://www.marcellozaniboni.net/zxaittt/index.html) , where 64 column native MODE3 text is used but where the horizontal resolution is at 256 for graphics

**Comment by suborb** [comment]
I've added `sam_set_fatpix(int)` into `<arch/sam.h>` which should do what you want.

**Comment by dandoore** [comment]
Cool! Will check it out on the nightly :)

**Comment by dandoore** [comment]
Awsome, works like a charm - ignore the stuff on screen I haven't fixed yet :)

![simc0133](https://user-images.githubusercontent.com/43847005/116781612-dc615e00-aa7b-11eb-9ac6-94ae1c21d16d.png)
