### ISSUE TITLE
 +++ INVALID Z180 OPCODE @2D11H: DD 67 DD 2E 00 11 00 00

### ISSUE THREAD

**Issue by jayacotton** [z88dk/z88dk#1783]
This was hit on a Z180 running a 3d transformation, the bug seems to be in 
float16u                        = $2D0F ; addr, local, , float, code_fp, c/sccz80/float.asm:49
gonorm                          = $2D09 ; addr, local, , float, code_fp, c/sccz80/float.asm:45

I isolated it to
./math/genmath/c/sccz80/float.asm

The compiler was updated today.
zcc - Frontend for the z88dk Cross-C Compiler - v18239-ee5024b80-20210415

The program under development has never worked on z80 before.

**Comment by feilipu** [comment]
You'll be running into the genmath issues again, where the code contains [lots of z80 undocumented opcodes](https://github.com/z88dk/z88dk/blob/master/libsrc/math/genmath/c/sccz80/float.asm).

[genmath isn't z180 compliant](https://github.com/z88dk/z88dk/wiki/Classic--Maths-Libraries#-lm---48-bit-genmath---z80z80n), and will never be z180 compliant.

Best to use math48 for the maximum accuracy (40 bit mantissa) with sccz80, or math32 for maximum performance (IEEE single precision 24 bit mantissa) with either sccz80 or sdcc.

**Comment by jayacotton** [comment]
Switched to math48 and problem cleared away.

tnx
