### ISSUE TITLE
Still having issue with MSX2_SUBTYPE

### ISSUE THREAD

**Issue by vipoo** [z88dk/z88dk#1795]
I am not sure the solution to the PR https://github.com/z88dk/z88dk/pull/1787 is quite right.

I now find that I get this error:

```
Error at module 'hello2_c': symbol '_MSX2_SUBTYPE' already defined in module 'hello_c'
Errors in source file /home/dean/z88dk/lib/config/../..//lib/target/msx/classic/msx_crt0.asm:
Error at module 'hello2_c': symbol '_MSX2_SUBTYPE' already defined in module 'hello_c'
```

It seems that the symbol defined in `msx.h`

`__at(0x2d) unsigned char MSX2_SUBTYPE;`

is missing the extern, and as such the compiler complains the symbol is defined twice.

when i add extern to the line

`extern __at(0x2d) unsigned char MSX2_SUBTYPE;`

and attempt to use the reference I get:

```
Error at file 'hello.c' line 695: symbol '_MSX2_SUBTYPE' not defined
Errors in source file /home/dean/z88dk/lib/config/../..//lib/target/msx/classic/msx_crt0.asm:
Error at file 'hello.c' line 695: symbol '_MSX2_SUBTYPE' not defined
Error while reading string from /tmp/tmpXXV9TLMu.err
```

The only way i get a successful compile is to:

change msx.h to have

`extern __at(0x2d) unsigned char MSX2_SUBTYPE;`

and add a line to one of my source files:

`__at(0x2d) unsigned char MSX2_SUBTYPE;`

Dean.

**Comment by suborb** [comment]
I think static is the correct scoping to sort this out.

It looks like https://github.com/z88dk/z88dk/issues/36 was a change in sccz80 to keep this type of definition local to the file (so that they can be defined in header files as done here), but sdcc exports them. Pros and cons to both approaches.
