### ISSUE TITLE
[bug][sccz80] static const OK vs const static KO

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1801]
It seems SCCZ80 does not like `const static` but accepts `static const`.
This can be reproduced by compiling the following code with SCCZ80:
```
const static int foo = 42;

int main(void)
{
    return 0;
}
```

No problem with SDCC or any other compiler I am aware of.

**Comment by suborb** [comment]
We're fairly slack on standards at times...but:

> 6.11.5 Storage-class specifiers
>
> The placement of a storage-class specifier other than at the beginning of the declaration specifiers in a declaration is an obsolescent feature.

From my own experience, I've never not put the storage class at the beginning of the declaration.
