### ISSUE TITLE
[bug?][sdcc] overflow in implicit constant conversion

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1802]
I am getting unexpected warnings with SDCC (not with SCCZ80) like the one below:
`cross_lib/sound/z88dk/psg/ay-3-8910_psg_sounds.c:111: warning 158: overflow in implicit constant conversion`

The reported line seems to have no issue:
```
		for(j=0;j<(uint8_t) 150u;++j)
		{
		}
```
So maybe there is a problem with the reported line number.

I have added the cast and the "u" just to see if it could fix the problem. The problem exists also without the cast.

**Comment by suborb** [comment]
I suspect that this will be the same as #1129

**Comment by Fabrizio-Caruso** [comment]
@suborb Sorry, I had forgotten about that old issue...

**Comment by mianqi2016** [comment]
A cast "(unsigned char)" would be solution.
