### ISSUE TITLE
Option to remove memory prefix generated by --list

### ISSUE THREAD

**Issue by headkaze** [z88dk/z88dk#1825]
Is there an option to remove the prefix data from generated .lis files so it can be copy/pasted more easily?

ie.
`1308  027E  21 FA FF    	ld	hl, -6`
to
`ld	hl, -6`

If not can we have an option such as --list-no-prefix?

**Comment by feilipu** [comment]
You can stop the build process at the point where the assembly files are generated. This will give you the clean assembly listing that is desired.
