### ISSUE TITLE
missing files uthash and utarray

### ISSUE THREAD

**Issue by gek169** [z88dk/z88dk#1830]
the files uthash and utarray are not found during compilation.

![image](https://user-images.githubusercontent.com/6974902/128121879-4551ef63-1e07-496a-8fc7-3341d04f3050.png)

**Comment by suborb** [comment]
I suspect you've not added the submodules. Please take a look at README.md, the relevant snippet is below:

> Use GitHub and build it yourself. The z88dk repository uses git submodules, these are not automatically downloaded by git by default so you will have to either adjust your clone line, or retrieve them manually. To clone with submodules use git clone --recursive https://github.com/z88dk/z88dk.git. To add the submodules to an already existing clone use git submodule update --init --recursive. To build, the following instructions should be followed.

**Comment by gek169** [comment]
Ah. Thanks
