### ISSUE TITLE
(z80asm) Can't generate labels with > 255 characters

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#1856]
The debugging work that's going uses defc constants to encode the CDB debug information.

Unfortunately it looks like when we start to instrument structures, the length could exceed 255 fairly easily.

When this happens we end up with the fatal message: "too long for byte counted string".

@pauloscustodio is there any chance we could shift to word counted strings?

**Comment by pauloscustodio** [comment]
Work started; will replace all byte-counted strings in the object files by word-counted strings. Inside z80asm all identifiers are handled as allocated strings, i.e. there is no fixed length limit.

**Comment by desertkun** [comment]
C-can we consider ditching url encoding in favor for base64 encoding?

**Comment by suborb** [comment]
We'd still need support for labels > 255 characters (for large structs) so the encoding mechanism doesn't matter massively
