### ISSUE TITLE
newlib - strnchr typo?

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#1857]
https://github.com/z88dk/z88dk/blob/f9b8cf799c889a924af23819ae7f4054f383fa98/libsrc/_DEVELOPMENT/string/z80/asm_strnchr.asm#L59

@suborb 
Why do `cp d` when `d` is never set or referenced?

**Comment by suborb** [comment]
I was obviously on autopilot. 

The ld e,a is garbage as well.
