### ISSUE TITLE
z80asm - emulated indirect opcodes

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#1865]
From [here](https://github.com/z88dk/z88dk/pull/1863#discussion_r716020514).

As far as I can see `ld de,(**)` is not emulated for INTEL or GBZ80.
It throws a warning, and I can't otherwise find it.

`ld (**),de` would be a useful partner to be emulated for INTEL or GBZ80.
And one more `ld (de),*` to add for all CPUs to complete the set using `ex de,hl`.

@pauloscustodio Could it (they) be added to z80asm, please?

**Comment by pauloscustodio** [comment]
gbz80 lacks the `ld hl,(**)` and `ld (**),hl`; the only way to emulate would be through `a`

**Comment by feilipu** [comment]
Just for INTEL would suit me.

GBZ80 was just nice to have.

**Comment by pauloscustodio** [comment]
gbz80 also lacks `ex de,hl`, therefore `ld r,(de)` / `ld (de),r` / `ld (de),N` only implemented for the other CPUs

**Comment by feilipu** [comment]
Thanks :+1:
