### ISSUE TITLE
[cpc] border and background color setting

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1866]
Background color setting does not produce a color (after a clear screen) on the CPC target.
It looks like the clear screen is not properly filling the screen with white spaces and that is why background color + clear screen does not produce a colored background.
I am assuming that textbackground followed by clear screen should color the background. Is this correct?

I can try to reproduce some of the issues with a small example

```
#include<conio.h>
#include <sys/ioctl.h>

int main()
{
    int mode = 0;
    console_ioctl(IOCTL_GENCON_SET_MODE, &mode);

    textcolor(WHITE);    
    bordercolor(YELLOW);
    textbackground(RED); \
    clrscr();

    gotoxy(2,2);
    cprintf("hello world\n");
    while(1){};
    return 0;
}
```
which I compile with:
```
cpc_bgcolor:
	$(Z88DK_PATH)$(MYZ88DK) +cpc -lndos -pragma-define:REGISTER_SP=-1 	-pragma-redirect:fputc_cons=fputc_cons_generic   -create-app -subtype=dsk -o$(BUILD_PATH)/bgcolor  -vn \
	$(TEST_PATH)/helloworld_background_color.c
```
will just produce:
- no effect on the border
- background color is not applied after clearing the screen as I should on all targets

![image](https://user-images.githubusercontent.com/29057615/134861723-5b15498a-3845-496e-8ea8-7abe95ccfa93.png)

**Comment by Fabrizio-Caruso** [comment]
@suborb is this issue related to #1867? 
Maybe the border issue is the same but on the CPC I also see a problem with the background.

**Comment by suborb** [comment]
It's a fairly easy fix in the libraries to sort out the background - just give me a few days and I'll be able to do it.

**Comment by suborb** [comment]
Fixed by:: 79c034c11d6a0729e79659617a79105b2bc4a3fc

**Comment by Fabrizio-Caruso** [comment]
@suborb, your fix is ok for the border but not ok for the background because it uses a wrong color (blue instead of white)

![image](https://user-images.githubusercontent.com/29057615/135533179-41cd048b-842e-4d3b-8f0f-dcc74308b047.png)

**Comment by Fabrizio-Caruso** [comment]
@suborb The fix only fixes the border. The foreground looks better (no stripes) but it has a totally wrong color (blue instead of white):
![image](https://user-images.githubusercontent.com/29057615/135582338-6d868ac3-8f44-4282-b012-4d35f472ca4f.png)
