### ISSUE TITLE
sccz80/libs: Enable the sccz80 builtins

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#188]
sccz80 has 3 builtin functions (so far):

__builtin_memset
__builtin_strcmp
__builtin_strchr

which may well improve performance by reducing stack usage and calls.

These will need a __smallc prototype and then a copt shuffle to ensure the callee versions are called if the builtins aren't used (e.g. via function pointers, or memset doesn't have a literal size).

**Comment by aralbrec** [comment]
strcpy and memcpy would also be good candidates for built-ins

**Comment by suborb** [comment]
Sorry I've got fat fingers, it's strcpy() that I added, not strcmp(), I'll add memcpy() as well and a command line option to disable them as well.

**Comment by suborb** [comment]
This has now been merged in.
