### ISSUE TITLE
[ZX81] display plain capital letters (not inverse capitals)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1880]
I am not sure this is an issue but it may be an inconsistent behavior.

It looks like printf statements on the ZX81 target convert :
- capital letters to inverted capital letters and 
- snall letters to plain non-inverted capital letters

Wouldn't be more consistent to have the following?
- capital letters to plain capital letters
- small letters to inverted capital letteds

How do other targets with no small letters behave?

**Comment by suborb** [comment]
* +gal just converts everything to uppercase
* +mc1000 does likewise
* I'm guessing other mc6847 machines without an external chargen do the same

**Comment by suborb** [comment]
Well, the other machines only have uppercase (no inverse) so that explains the difference in behaviour.

**Comment by suborb** [comment]
Ah, input uses the same routines I suspect, so you might need to flip case on the check?
