### ISSUE TITLE
(svi) psg_channels() may cause crash

### ISSUE THREAD

**Issue by james7780** [z88dk/z88dk#1893]
psg_channels() may cause a crash on Spectravideo, as the top 2 bits of PSG register 7 must not be changed:

From http://www.samdal.com/svmemorybanks.htm:

"The switching of memory banks is done with the sound chip (AY-3-8910). There are two 8 bit I/O ports in the sound chip (port A and B). This has nothing to do with the production of sound, it's just an extra feature.

Register R7 is a multifunction /ENABLE register which controls three Noise/Tone mixers and the two general purpose I/O ports directions. The direction (input or output) of the two general purpose I/O ports is determined by the state of bits B7 (port B) and B6 (port A) of R7.

Port A is used for input, so bit 6 should be set to 0.
Port B is used for output, so bit 7 should be set to 1."

psg_channels() will work on MSX (and maybe in Spectravideo emulators), but for Spectravideo, it should be updated to keep the top 2 bits of PSG register 7 as they were.

**Comment by suborb** [comment]
Thanks, this one covered with the tracker players, but not with the direct hardware control.
