### ISSUE TITLE
Wrong #include path for libxml/parser.h in support/graphics/z80svg.c

### ISSUE THREAD

**Issue by danfe** [z88dk/z88dk#1897]
It is `#include <libxml2/libxml/parser.h>` which is wrong, as `xml2-config --cflags` already provides the `libxml2` part in its output.  Most likely this bug went unnoticed on GNU/Linux because `/usr/include`, where 3rd-party headers are installed on those systems, is searched by default, but it breaks the build on e.g. FreeBSD, where those go under `/usr/local/include`.  The following small patch fixes the bug:
```patch
-#include <libxml2/libxml/parser.h>
+#include <libxml/parser.h>
```

**Comment by suborb** [comment]
Sorry, I missed this one, thanks for the correction.
