### ISSUE TITLE
Request for ASSERT directive for z80asm

### ISSUE THREAD

**Issue by dbolli** [z88dk/z88dk#1898]
Other assemblers have an ASSERT (evaluated expression) e.g. (constant1 <= constant2) that throws an error if the assert fails which is useful e.g. for ensuring that code does not cross an address boundary.

Would be very useful if z80asm had this feature.

**Comment by pauloscustodio** [comment]
@dbolli thanks for the suggestion

**Comment by dbolli** [comment]
Works like a charm. Many thanks :)

defc ORGADDR = $6100

ASSERT ( ASMPC + $6100 > DFILE )			               # :dbolli:20211227 10:58:55 Works for pre-defined constant
ASSERT ( $ + $6100 >= START )			                  # :dbolli:20211227 10:58:55 Works for pre-defined label
ASSERT ( $ + ORGADDR <= $8000 )			               # :dbolli:20211227 10:58:55 Works for pre-defined constant
