### ISSUE TITLE
zsdcc: signed char not promoted to int prior to pointer arithmetic

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#191]
Reported to [sdcc](https://sourceforge.net/p/sdcc/bugs/2601/).

Example code:

```
unsigned char *p;
unsigned char *a;
signed char b;

void main(void)
{
    p = a + b;
}
```

zcc +z80 -vn -a -SO3 -clib=sdcc_iy test.c

Generated asm:

```
_main:
	ld	a,(_a)
	ld	hl,_b
	add	a, (hl)
	ld	(_p),a
	ld	a,(_a + 1)
	adc	a,0x00
	ld	(_p + 1),a
	ret
```

The instructions that add 8-bit signed char "b" to the 16-bit result are "add a,(hl)" and "adc a,0x00" where it can be seen this is an unsigned addition since "b" is not sign extended into 16-bits.

This bug was reported in the [forum](https://www.z88dk.org/forum/viewtopic.php?pid=15002#p15002).

Edit: It looks like it has been fixed already.  Just waiting for an updated at svn2github to try it out.

**Comment by aralbrec** [comment]
Sdcc 9880 fixes the bug.
I've updated the windows binary in [z88dk_sdcc_patch.zip](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/sdcc_z88dk_patch.zip)

**Comment by suborb** [comment]
Nightly for 20170426 will have this fix for Mac and Windows.
