### ISSUE TITLE
SDCC strange issue with this declaration 

### ISSUE THREAD

**Issue by nippur72** [z88dk/z88dk#1914]
SDCC, in the below code, if I move the `data` declaration (the one marked with *****) to the top of the function, then the function behaves incorrectly. I was not able to understand the reason, all I see is that the resulting `.lis` file has different register allocations. Perhaps it has something to do with optimizations? I've tried to remove the `-SO3` flag but the result was the same. It works normally in sccz80.

```c
void gr_erasepiece(sprite *p) {
   int px = p->x;
   int py = p->y;

   // are we erasing the "next" piece ?
   if(py==PIECE_IS_NEXT) {
      px = NEXT_X;
      py = NEXT_Y;
   }
   else {
      px += STARTBOARD_X;
      py += STARTBOARD_Y;
   }

   // ***********************************
   tile_offset *data = get_piece_offsets(p->piece, p->angle);   

   SLOT1_VIDEO_START();
   for(byte t=0; t<4; t++) {
      int x = px + data->offset_x;
      int y = py + data->offset_y;      
      data++;
      gr4_tile((byte)x,(byte)y,EMPTY_GR_CHAR,EMPTY_GR_COLOR,FONTS);
   }
   SLOT1_END();
}

typedef struct {
   byte offset_x;
   byte offset_y;
} tile_offset;

tile_offset *get_piece_offsets(byte piece, byte angle) {
   return &pieces_XY[(piece*sizeof(tile_offset)*4*2)+angle*4];
}
```

**Comment by suborb** [comment]
Sorry, I've not had a chance to investigate this one yet.

Could you add the definitions for sprite and the various preprocessor `#define`s?

**Comment by nippur72** [comment]
if it's easier for you to reproduce it, my repo has the whole source code (tetris game):

1) clone https://github.com/nippur72/laser500emu
2) the directory `software\tetris` contains the program that I compile with:
```
zcc +laser500 tetris500.c -o tetris500.bin -I..\lib500 -create-app -Cz--audio --list -m -s -DSDCC -compiler sdcc -SO3
```
the issue is located in `grboard.h`, uncomment line 159 and comment line 174.

I checked it again with latest night build `v19053-73554631a-20211230` and the issue is still there. If you play the game on my Laser 500 emulator you'll see dropping tetris pieces acting oddly (drag and drop the compiled `tetris500.bin` over the [emulator window](https://nippur72.github.io/laser500emu).

**Comment by suborb** [comment]
It looks like this is easiest to see from the mangled "next up" box.

I've gone back through some old sdcc versions, and the last working one I can find is r12069 which was in nightly builds from 22/4 to 29/4 this year.

There's been a fair amount of churn and hence codegen bugs in sdcc this year so I think the next thing to try is to upgrade: we're already pending one bug fix so let me try that.

If that doesn't solve it, then this issue will be difficult to report upstream: an issue which just uses prints the wrong values is easier to figure out.

**Comment by suborb** [comment]
Unfortunately, I can still reproduce the mangled "next up" box with the latest version of sdcc (r12831)

**Comment by feilipu** [comment]
Confirmed that the issue is still present with r13006.
Mangled "up next" box, and other overwrite issues.

![Screenshot from 2022-02-14 01-24-44](https://user-images.githubusercontent.com/3955592/153757610-7cddea41-f8e2-4c07-8af9-1744c9df0bb4.png)

**Comment by feilipu** [comment]
Added [SDCC issue 3322](https://sourceforge.net/p/sdcc/bugs/3322/).
