### ISSUE TITLE
z80asm .lis file lists incorrect bytes for REPTC macro directive

### ISSUE THREAD

**Issue by dbolli** [z88dk/z88dk#1928]
In the .lis file created by z80asm

	180   00D1              	REPTC var, 45
	181   00D1              	defb var
	182   00D1  35 00       	ENDR
	183   00D3              
	184   00D3  FF          	RST $38			; Make disassembly listing a bit clearer
	185   00D4              
	186   00D4              	DEFL myversion = 23
	187   00D4              	REPTC var, myversion
	188   00D4              	defb var
	189   00D4  33 00       	ENDR
	190   00D6              
	191   00D6  FF          	RST $38			; Make disassembly listing a bit clearer

Should be 34 35 at $00D1 and 32 33 at $00D4

In disassembly .lis file created by z88k-dis the bytes are shown correctly (i.e. they are assembled correctly)

                    INC     (HL)                            ;[6E82] 34
                    DEC     (HL)                            ;[6E83] 35
                    RST     $38                             ;[6E84] FF
                    LD      ($FF33),A                       ;[6E85] 32 33 FF

z80asm version from macOS nightly build

Z80 Module Assembler 19070-bab6a7b00-20220101

**Comment by pauloscustodio** [comment]
Problem solved, thanks for reporting.
