### ISSUE TITLE
cpm - time() not implemented for INTEL

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#1966]
Noted building [zmrx](https://github.com/codesmythe/zmtx-zmrx/blob/main/zmrx.c#L63) and zmtx for CP/M 8085 that the [`time()`](https://github.com/z88dk/z88dk/blob/master/libsrc/target/cpm/time/time.asm#L25) and [`clock()`](https://github.com/z88dk/z88dk/blob/master/libsrc/target/cpm/time/clock.asm#L29) functions are not implemented for INTEL.
Their implementation can be a stub since CP/M 2.2 doesn't have time related functions.

**Comment by zx70** [comment]
The current time() function includes support for MP/M II, it could be extracted from the Z80 version and used to stub it.
https://github.com/z88dk/z88dk/blob/a74550b04f4e824b3eae024e9a2f46fc234edae8/libsrc/target/cpm/time/time.asm#L148

**Comment by feilipu** [comment]
Added a stub for `INTEL` and for Z80 systems less than MP/M-II (i.e. CP/M 2.2) to quickly return 0.
- [x] `time()`
- [x]  `clock()`
