### ISSUE TITLE
mismatch between PREFIX and DESTDIR in makefile

### ISSUE THREAD

**Issue by rofl0r** [z88dk/z88dk#1985]
the makefile uses DESTDIR where PREFIX should be used, and makes it impossible to use DESTDIR as intended. https://www.gnu.org/prep/standards/html_node/DESTDIR.html

it should be `PREFIX = /usr/local` and DESTDIR later only used in the install target, as described in the above manual.

**Comment by danfe** [comment]
> makes it impossible to use DESTDIR as intended

In the FreeBSD port, I'm [patching the Makefile](https://cgit.freebsd.org/ports/tree/devel/z88dk/files/patch-Makefile) to mend this.

**Comment by suborb** [comment]
This broke the snap build, so I need to investigate

**Comment by suborb** [comment]
Snap file fixed in 03b4770abbe310f163a6a23298600eab6b3153a6 - closing
