### ISSUE TITLE
Parallel PRs

### ISSUE THREAD

**Issue by dikdom** [z88dk/z88dk#2009]
Is there a way to provide multiple (2) pull requests? I have currently one pending PR but in the meantime I have found issues with other target. Can I somehow provide fixes for the other target not interfering with the current pending one?
Thanks!

**Comment by ped7g** [comment]
yes, in your local git repository of your fork switch to upstream branch from where you want to start new set of changes, create new branch, modify sources, commit+push, then you can open pull request from the other branch.

**Comment by dikdom** [comment]
Thanks, I will do that!
