### ISSUE TITLE
Build fails on windows/msys2

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#2024]
Running ./build.sh in a Windows machine in the msys2 environment fails:
gcc -g -O2 -I../../ext/uthash/src/ -g -MMD -I../../ext/UNIXem/include   -c -o breakpoints.o breakpoints.c
breakpoints.c:9:10: fatal error: printf.h: No such file or directory
    9 | #include <printf.h>
      |          ^~~~~~~~~~
compilation terminated.
make[1]: Leaving directory '/home/T0071173/git/z88dk/src/ticks'

**Comment by desertkun** [comment]
Ooof that's my bad.

**Comment by desertkun** [comment]
Fixed in 2e07b55927e48fe5415c76e79649606ea001b268
