### ISSUE TITLE
ticks build fails in Windows with the Microsoft compiler Visual Studio

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#2035]
Build started...
1>------ Build started: Project: z88dk-ticks, Configuration: Debug Win32 ------
1>debugger_mi2.c
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\stdarg.h(23,1): warning C4005: 'va_copy': macro redefinition
1>C:\msys64\home\paulo\git\z88dk\src\ticks\debugger.h(8): message : see previous definition of 'va_copy'
1>C:\msys64\home\paulo\git\z88dk\src\ticks\debugger_mi2.c(15,10): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory

**Comment by desertkun** [comment]
Ugh, sorry for another problem. 

https://stackoverflow.com/a/28036816

Some windows shenanigans. I'll fix it in few hours.

**Comment by pauloscustodio** [comment]
Actually this is not on the MinGW build tools, but in the Microsoft compiler tool chain, which is used in the Visual Studio IDE.
I think you could just disable gdb integration if the system is built by Microsoft's compiler, as gdb will only work in the MinWG environment.

Use #ifdef _MSC_VER to detect the Microsoft compiler.

**Comment by desertkun** [comment]
Never realized we even support win32 directly. If that's the case, I would rather get the thing working again instead of cutting stuff off.

**Comment by suborb** [comment]
I've successfully used pthreads with visual studio before but I think disabling the gdb integration is probably the right approach.

The binaries in the kits are produced using mingw so that's end users sorted out.

So, the only users of the VS project files are people like Paulo who want to have a nice IDE to develop the binaries with.

**Comment by desertkun** [comment]
I see. Not sure how I would do that. Could you please fix this @suborb ?

**Comment by pauloscustodio** [comment]
@suborb, I found some articles about this, let me try to sort it out.

**Comment by pauloscustodio** [comment]
I managed to build z88dk-gdb on both Visual Studio and MinGW with extensive changes in the Visual Studio project files; I hope I did not break anything

**Comment by desertkun** [comment]
Feels like we would benefit from spending some time on extending the nightly build suite to include win32

**Comment by pauloscustodio** [comment]
> Feels like we would benefit from spending some time on extending the nightly build suite to include win32

I agree, opened a new issue #2036

**Comment by desertkun** [comment]
@pauloscustodio it seems nightly fails now

http://nightly.z88dk.org/report/buildreport-20220620

**Comment by pauloscustodio** [comment]
I may have broken something. Let me check tonight.

Regards,
Paulo Custódio

A segunda, 20/06/2022, 08:13, Alex Siryi ***@***.***>
escreveu:

**Comment by pauloscustodio** [comment]
Another attempt in solving this submitted; let's wait for tonight's build

**Comment by pauloscustodio** [comment]
Nightly still failing http://nightly.z88dk.org/report/buildreport-20220622

Now a result of some new z80asm tests that use a Perl module CPU::Z80::Assembler (I'm the author of this module)

@suborb, may I edit and commit the build script in the build repository?

**Comment by suborb** [comment]
I've fixed up the environment now so the build now works.

**Comment by pauloscustodio** [comment]
Thanks, you can disregard my pull request then.
Regards,
