### ISSUE TITLE
Extend github actions to also build in native Windows

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#2036]
Need to check compilation with the native Microsoft compilers in Windows.

**Comment by pauloscustodio** [comment]
@suborb, I am trying to setup a workflow to run a Visual Studio build in github actions and need a Microsoft developed action microsoft/setup-msbuild@v1.1

The build fails with:
microsoft/setup-msbuild@v1.1 is not allowed to be used in z88dk/z88dk. Actions in this workflow must be: within a repository owned by z88dk or created by GitHub.

Apparently the repository admin needs to select the “Allow all actions” option (see https://github.community/t/checkout-v2-error-actions-in-this-workflow-must-within-a-repository-owned-by-organization/136315).

Can you please change the setting?

**Comment by suborb** [comment]
@pauloscustodio you already had the power - I'm not too keen to allow anything arbitrary to run so I've added in a wildcard for that one.

**Comment by pauloscustodio** [comment]
Sorry, I did not realize I was admin... thanks.

**Comment by pauloscustodio** [comment]
Todo:
[ ] solve nightly build failure
[ ] implement workflow to simulate nightly
[ ] try to run tests with code built with msbuild - challenging as no Unix tools are available
[ ] workflow for cygwin compiler - I noticed it fails compilation with msys/gcc

**Comment by pauloscustodio** [comment]
@suborb, after a zillion attempts, I finally managed to compile the project in cygwin in a git workflow, but one of the tests is failing:
```
make -C testsuite
make[1]: Entering directory '/cygdrive/d/a/z88dk/z88dk/testsuite'
zcc +test -vn -a 01_cast_global_pointer.c -o 01_cast_global_pointer.opt.tmp1
diff -w 01_cast_global_pointer.opt.tmp2 results/01_cast_global_pointer.opt
16d15
< 	push	bc
make[1]: *** [Makefile:49: 01_cast_global_pointer.opt] Error 1
18d16
< 	pop	bc
22,23d19
< 	push	hl
make: *** [Makefile:224: testsuite] Error 2
< 	pop	bc
30,32c26
< 	add	hl,sp
< 	call	l_gint	;
< 	push	hl
---
> 	call	l_gintspsp	;
make[1]: Leaving directory '/cygdrive/d/a/z88dk/z88dk/testsuite'
```
It passes in my local cygwin environment.
Any ideas of what may be causing the different optimized code output?

**Comment by pauloscustodio** [comment]
Tried to reproduce by cloning again and following the exact same steps as in the git workflow and the test passes. In the git workflow it fails. 
What can be causing the difference? Any ideas?

**Comment by suborb** [comment]
Normally differences are due to the compiler and CPU issues, but here it just looks like some of the rules haven't fired.

Can you see what else is failing (make -k in testsuite) to see if there's a pattern?

**Comment by pauloscustodio** [comment]
Failing test solved! It was due to the incorrect setting of git's core.autocrlf, the source files had CR-LF line endings. Changed to input, and the testsuite passes.
Thanks anyway.

**Comment by suborb** [comment]
Grrrr - well done for tracking that one down!

**Comment by pauloscustodio** [comment]
Fix https://github.com/z88dk/z88dk/issues/2036 build and test on Windows

Create github workflows that run on push and pull requests for these different cases:
- cross-compiling to Windows on Ubuntu, to simulate the nightly build
- compiling and running the tests on Ubuntu, MacOS, Windows/MinGW and Windows/Cygwin
- compiling and running only the z80asm tests on Visual Studio x86 and x64 (AFAIK the z80asm tests are the only ones that rely only on Perl and are cross-platform)

In the process the following changes were necessary:
- create the different workflow files (obviously)
- work around a bug in UNIXem - you need to include both <unixem/glob.h> and <glob.h> on Windows, but only <glob.h> on Unix or Windows/Cygwin - had to define a new -D_CYGWIN to be passed to the C compiler if the architecture is Windows/Cygwin; this was done in src/Make.common, which is then included in the projects that need glob.h

It was a difficult and long task, and some workflows take more than one hour to run, but I think this will help us detect errors sooner, hopefully before merging to master.

**Comment by pauloscustodio** [comment]
Tests are failing after compile; this was not noticed because of the way they they were being called, not propagating the error status.

**Comment by desertkun** [comment]
Appreciate the effort; it's already been useful on my PR as it caught a windows error I would have missed otherwise.

**Comment by desertkun** [comment]
@pauloscustodio build-on-windows-cygwin job, it seems, takes forever to build the libraries. 
https://github.com/z88dk/z88dk/runs/7496003144?check_suite_focus=true
3 hours. Is than an error? ~30m on other jobs

**Comment by pauloscustodio** [comment]
No, not an error, just Cygwin being very slow at file I/O. For people running windows I recommend msys2 instead

**Comment by pauloscustodio** [comment]
Extend the build-on-windows-msbuild jobs to build also the Debug configuration, to detect failures in the compiler flags.
