### ISSUE TITLE
Discrepency between documentation and zcc code

### ISSUE THREAD

**Issue by Mokona** [z88dk/z88dk#2038]
Hello,

the Wiki says about "zcc" :

    The files can be either C files (.c) , preprocessed C files(.i), compiled C files (.asm),
    optimised compiled file (.opt) or assembled files (.o or .obj), any combination of them
    can be mixed together and the relevant processed done on them.

Which implies that both .o and .obj file suffixes should be recognized as object files.

The code in zcc.c and the actual experience seems to show that only .o suffixes are recognized as object files. Usage of an ".obj" file emits the "Filetype of ... unrecognized".

Am I missing something? And if not, what should be fixed?

**Comment by suborb** [comment]
I've taken the easy/standard option and updated the documentation1

**Comment by Mokona** [comment]
Thanks!
