### ISSUE TITLE
Target specific compiler binaries

### ISSUE THREAD

**Issue by desertkun** [z88dk/z88dk#2039]
Currently zcc requires +target option to specify a target, like `zcc +zx {args}` or `zcc +z88 {args}`. 
I wonder if we can afford to additionally generate `zcc-zx`, `zcc-z88` binaries (or simply bash scripts/symlinks) that would forward additional +target option internally.

The purpose of that is to make zcc more or less gcc compatible. CLion IDE, for example, calls the following on a compiler:
```
<compiler> -xc <some flags> -v -dD -E -D___CIDR_DEFINITIONS_END test-file.c
```
to test its capabilities.

This call is supposed to dump all definitions, and while flags like `-dD` could be addressed separately, unfortunately, there is no way to specify flags before `-xc` argument. I wonder if we can generate a bunch `zcc-<target>` binaries that would be each for specific target. This also could be a bunch of symlinks to `zcc`, and zcc could detect the target by the filename of the binary being run.

I want to write a CMake toolchain for zcc so it would be plug-n-play compatible with CMake, as long as you specify a toolchain file. While there appears to be progress with CMake alone, there is this issue that I need to address for things to work in plug-n-play manner.

What do you think @suborb @pauloscustodio ?

**Comment by desertkun** [comment]
No, its a binary that has to be chosen as a file.

**Comment by desertkun** [comment]
@suborb so I've investigated some more. CLion does this:
`zcc @argsfile somefilename`
argsfile contains some arguments, but it seems zcc only can expand @ argument into filenames to compile, and not in general list of arguments. 

Would I break too much of backwards compatibility, if I'd allow to pass any argument into @ and not just a filenames to compile?

**Comment by suborb** [comment]
There won't be an issue with zcc, but I do have a feeling that the @ file may be passed directly through to z80asm which probably doesn't exclude "options" from the lines.

**Comment by pauloscustodio** [comment]
Yes, z80asm needs an update to be able to handle options in @ files. I can take care of this.

**Comment by desertkun** [comment]
Here's my current messings: https://github.com/desertkun/z88dk/commit/29dc06673e8f6a84c2892aa38e5fcc4da38680ab

So war I was able to symlink some zcc-zx to zcc, and it picks it up and doesn't require +zx argument.
Also, I've "refactored" (slapped some more ugly spaghetti on top) `@` parsing, as we as implemented some `-dD` flags;

The ultimate example is 

args.txt
```
-xc -DBANANAS -fpch-preprocess -v @args2.txt -E -D___CIDR_DEFINITIONS_END
```

args2.txt
```
-dD
```

test (NO extension):
```
int main() {}
```

command line:
```
./zcc-zx @args.txt test
```

It supposed to dump preprocessor's #defines.

Note the absolute f-ckery with `-xc` as GCC has `-x` to specify language explicitly, while zcc has `-x filename` for archive creation. Luckily, `-xc` and `-x <archive>` are different things

All of this is required to turn it into "real" compiler that would work on CMake/CLion, that way we could put together an official toolchain file for CMake so all would be required is to include such a toolchain.

**Comment by pauloscustodio** [comment]
I've opened a new issue #2040 to track this in z80asm.
