### ISSUE TITLE
z80asm: allow options and filenames in @ files

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#2040]
Reference #2039.

Tasks:
- [x] Allow options and filenames to be freely mixed in the command line and in @ files
- [x] Allow filenames with spaces quoted with either single or double quotes
- [x] Allow more than one option/filename in each line of the @ file

The '--' option (to be able to have filenames starting with a dash) will only be available in the command line and not in @ files.

**Comment by desertkun** [comment]
Haha thanks for the effort
