### ISSUE TITLE
GFX: more fixes and improvements

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#2042]
I spotted a number of issues regarding the graphics functions.
In this record I'm recapping the enhancement areas.

- circle()  in narrow mode fixed (crashed)
- dcircle2 is not SMC anymore 
- draw line in narrow mode improved (was slow when drawing vertical lines)
- draw relative line in wide mode fixed (wrong internal labels)
- dline2 modified to be 8080 compatible (untested)
- zx81 Memotech WRX 64 rows mode : TV sync frequency changed to make it visible on EightyOne (needs tests on real hw)
- zx81 with G007 graphics:  ansi text mode fixed
- zx81:  zx_cls now resets the font pointer (i.e. enters in standard text mode when the gfx81udg mode was used)
- zx81: function name mismatch, rolltxt() in zx81.h but rollchr() is the real fn
- Turbo C BGI graphics emulation: + pattern filled shapes and more graphics functions
- Turbo C BGI graphics emulation: fixed the proportional text handling

**Comment by zx70** [comment]
![bgi4](https://user-images.githubusercontent.com/10224992/178705544-e30ea56a-0dd5-496c-941a-3c267beb832c.png)

**Comment by feilipu** [comment]
I've added some instructions on how to use `math32` floating point for the relevant graphics demonstrations.

The comparisons between `genmath` and `math32` are shown in below videos on SpecNext hardware.
- [fern with `genmath`](https://youtu.be/8fis7hTsrgE)
- [fern with `math32`](https://youtu.be/RO3pZce0G5k)
- [coswave with `genmath`](https://youtu.be/StUawzW3Q3I)
- [coswave with `math32`](https://youtu.be/DiSp4soCk_A)

**Comment by zx70** [comment]
@feilipu, those hints are very useful.
Sometimes I look for them as reminders  :D
... the zx81 math library was the only way to save enough space with the bgi demo

**Comment by feilipu** [comment]
Just realised I was looking at `coswave.c` and building `sinwave.c`... doh!
Anyway, the video is still useful.

**Comment by zx70** [comment]
In the examples header I try to put a bit of build possibilities. 
Maths, etc seems to be a good hint, please feel free to add  😉

**Comment by feilipu** [comment]
Been playing with [savage](https://github.com/z88dk/z88dk/master/examples/embedded/savage.c#L22) and other examples to check performance and accuracy.

The punchline is that when using SDCC there's no advantage to using `math48` floating point, as its additional accuracy is lost in compiler conversion to IEEE standard single precision. Use `math32`. 

When using SCCZ80 for accuracy `math48` is best, but for graphics (placing a pixel onto a screen) `math32` is substantially faster.

**Comment by zx70** [comment]
Your videos show the difference in speed very clearly. 
I didn't know that math48 was generally useless with SDCC, it is very interesting. 
I usually don't care much for the FP precision,  but there are cases where the precision matters.
In most of the cases I'm not sure  :D 
https://github.com/z88dk/z88dk-ext/tree/master/misc/fir

Yet z88dk is currently the best kit to address all the cases  ;)

**Comment by feilipu** [comment]
I've added a few notes to the [wiki](https://github.com/z88dk/z88dk/wiki/Classic--Maths-Libraries#size-of-floating-point-number) to draw attention to the relative merit of 6 byte vs 4 byte floating point formats, and their use with the two compilers. I hope that helps someone to build a more responsive game.

Just for interest on FIR, I had cause to use it for a [real-time low pass filter](https://github.com/feilipu/Goldilocks_Analogue_DAC_Library) on AVR hardware and did the calculations in fixed point 24.8 format. But again speed was more important than accuracy [for that case](https://github.com/feilipu/Arduino_FreeRTOS_Library/blob/master/examples/GoldilocksAnalogueTestSuite/GoldilocksAnalogueTestSuite.ino#L234).
