### ISSUE TITLE
Site http://nightly.z88dk.org/ is down

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#2057]

**Comment by suborb** [comment]
Sorted - thanks for the headup.

**Comment by pauloscustodio** [comment]
And now up again.

**Comment by suborb** [comment]
Apologies, first issue was a power cut and a failed fsck, the second one was unknown - I'm guessing temperature related so I've given it a good dust inside and out.

**Comment by pauloscustodio** [comment]
It appears to be down again.

**Comment by suborb** [comment]
Well, it's probably not heat related, just crappy Dell hardware it seems. I guess I need to find some old/new hardware to replace it.

Anyway, I've toggled the remote power switch and it should be back up.

**Comment by pauloscustodio** [comment]
Down again, detected because our github workflows download from it and fail.

**Comment by feilipu** [comment]
> Down again, detected because our github workflows download from it and fail.

Seems still down, as it was last night. Causing build failures.
