### ISSUE TITLE
[KC] clg() doesn't clear the screen

### ISSUE THREAD

**Issue by Hojoe42** [z88dk/z88dk#2067]
The clg() implementation for the target +kc is wrong. It copy the first byte of the screen. If the first byte is zero, the screen is empty, but if the first byte is not zero you got some nice patterns :-(

How to reproduce:
```
#include <graphics.h>
#include <conio.h>

char sprite[] =
{ 8, 8, 0x81, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff };

int main()
{
    clg();
    putsprite(spr_or, 0, 0, sprite);
    sleep(3);
    clg();
    return 0;
}
```
compile it with `zcc +kc --list -o clgdemo.bin -create-app clgdemo.c`
Start the program with JKCEmu System KC85/4 (http://www.jens-mueller.org/jkcemu/download.html).  
Normally the first clg() looks ok. Then putsprite() writes something in the first byte of the screen. The second clg() doesn't clear the screen.

[clg.patch.txt](https://github.com/z88dk/z88dk/files/9334024/clg.patch.txt) contains a fix. It sets the first byte to zero.

**Comment by suborb** [comment]
Thank you....good spot!
