### ISSUE TITLE
[KC] KC85/2..5 is not Robotron

### ISSUE THREAD

**Issue by Merilix** [z88dk/z88dk#2083]
Many library sources related to KC target are showing "; ... Robotron KC85/2..5" in the header section.
But the KC85/2..5 series was built by "VEB MPM" (short for "VEB Mikroelektronik „Wilhelm Pieck“ Mühlhausen"), a manufacturer not related to "Robotron" at all.

Not a big deal and nice project by the way.

**Comment by feilipu** [comment]
Reference "fact check" [Wikipedia DE on VEB WPM](https://de.wikipedia.org/wiki/VEB_Mikroelektronik_%E2%80%9EWilhelm_Pieck%E2%80%9C_M%C3%BChlhausen).
