### ISSUE TITLE
z88dk-z80asm: listing and symbol file not corresponding to ORG

### ISSUE THREAD

**Issue by wahajenius** [z88dk/z88dk#2114]
z88dk win32 v2.2 (19766-9ffe2042c-20220723)

Take the following file `example.asm`:

```
org $1234
foo: call foo
```

Assemble a binary:
```
z88dk-z80asm -s -l -m -b example.asm
```

The resulting binary `example.bin` is correct; hex dump:
```
CD 34 12
```

Map file `example.map` is also correct:
```
foo                             = $1234 ; addr, local, , example, , example.asm:2
__head                          = $1234 ; const, public, def, , ,
__tail                          = $1237 ; const, public, def, , ,
__size                          = $0003 ; const, public, def, , ,
```

But listing file `example.lis` is *not* correct:
```
example.asm:
     1                          org $1234
     2   000000 cd0000          foo: call foo
     3                          
```

This incorrectly lists the opcode bytes `cd0000` instead of `cd3412`, as if ORG was $0000.

Symbol file `example.sym` is similarly incorrect:
```
foo                             = $0000 ; addr, local, , , , example.asm:2
```
This too behaves as if it were assembled at ORG $0000.

Can the listing and symbol file be made consistent with the binary and map file, i.e. all of them taking the relocation address into account?

**Comment by pauloscustodio** [comment]
z88dk-z80asm is a relocating assembler and linker. What this means is that first the assembly files are compiled into an object file with every section assembled at ORG 0, and then a linker grabs all the needed object files, locates each section of each object in the address space and generates a binary image.
The list and symbol files are outputs of the assembly files, where ORG is 0.
The map file is an output of the linker, after each section of each object files has been assigned its own ORG.
This is the reason the files are as you describe.
