### ISSUE TITLE
"Undefined symbol: pic" when using math lib for Amstrad CPC

### ISSUE THREAD

**Issue by ColinPitrat** [z88dk/z88dk#2119]
Hello,

I've been trying to do a simple program using floating points on Amstrad CPC but compiling even the simplest thing fails with:

```
z80/init_floatpack.asm:127: error: undefined symbol: pic
  ^---- (pic)
z80/init_floatpack.asm:182: error: undefined symbol: pic
  ^---- (pic)
```

For example the following:

```
#include <cpc.h>

main()
{
  double_t a;
  a = 2.0;
}
```

generates the error when compiled with:

```
zcc +cpc -lmz -I${INCLUDE_PATH} -o test.bin test.c
```

**Comment by feilipu** [comment]
I think the firmware Pi and half Pi routines were [removed in this commit](https://github.com/z88dk/z88dk/commit/830e51579c9b1e2fd5f9552780c2f199148258a5), and replaced with other routines.

This means that the initialisation of the PIC (Pi Constant) location becomes irrelevant.
I'll remove it.

**Comment by feilipu** [comment]
Please re-open if this is not actually a fix.
