### ISSUE TITLE
lis file format (6 digit address)

### ISSUE THREAD

**Issue by maziac** [z88dk/z88dk#2120]
Hi,

is there some documentation available for the z80asm lis file format.
I'm especially interested in the 6 digit address format that was introduced here:
https://github.com/z88dk/z88dk/issues/429
for PHASE/DEPHASE.

The address is shown as 6 digit hex. For a 64k address space it would require only 4 digits.
So what are the additional 2 digits used for?

**Comment by pauloscustodio** [comment]
The upper byte was introduced when also allowing 32-bit addresses in ORG, to allow for banked binaries, where the upper byte was the bank number. The introduction in the list file may be considered useless, as the list file is produced in the assembly phase, and the ORG is only considered in the link phase, i.e. the list address upper byte is always zero. 
The same is not true for the map file, where addresses may contain 32-bit values.

May be considered a bug.
