### ISSUE TITLE
Galaksija: Apostrophe Character

### ISSUE THREAD

**Issue by kacsich** [z88dk/z88dk#2139]
Having just compiled the "Adventure A" game for the standard Galaksija, I noticed that the Galaksija's character set is missing the apostrophe sign. Console text output currently prints character 39 (or 103) instead of the apostrophe:

![image](https://user-images.githubusercontent.com/17122679/205456576-f82b148f-eed6-41c0-92fa-303043d38ac7.png)

I think a good workaround would be using the top-left block graphics character (character 129):

![image](https://user-images.githubusercontent.com/17122679/205456599-8816980d-c70d-4ece-8ee3-350e39f92dca.png)

Note: this applies only for text mode. In Galaksija Plus graphics mode, a custom font must be provided, so all characters are avalable.

**Comment by suborb** [comment]
Good suggestion - I've pushed a change that will do the mapping for the generic console.
