### ISSUE TITLE
"Full" Windows path with backslashes confuses #include ""

### ISSUE THREAD

**Issue by empathicqubit** [z88dk/z88dk#2154]
```
/c/z88dk/bin/zcc +ti8x -Wall -debug -g -O0 -S -o "build/src/main.i.asm" "Z:\UserProfiles\EmpathicQubit\tyzzy\src\main.c"

Z:\UserProfiles\EmpathicQubit\tyzzy\src\main.c: line 1: file '../3rdparty/z88dk-gdbstub/src/gdb.h' not found
Z:\UserProfiles\EmpathicQubit\tyzzy\src\main.c: line 2: file '../lib/debug-impl.h' not found
make: *** [Makefile:189: build/src/main.i.asm] Error 1
```

But this works:

```
/c/z88dk/bin/zcc +ti8x -Wall -debug -g -O0 -S -o "build/src/main.i.asm" "Z:\UserProfiles\EmpathicQubit\tyzzy\src/main.c"
```

Note the forward slash in the last path part

**Comment by suborb** [comment]
Just from code inspection I spot:

https://github.com/z88dk/z88dk/blob/master/src/ucpp/cpp.c#L679
https://github.com/z88dk/z88dk/blob/master/src/ucpp/cpp.c#L684

I think both the MSDOS and the non-AMIGA case need to be activated.

**Comment by empathicqubit** [comment]
so `if defined(MSDOS) || defined(WIN32)` ?

**Comment by empathicqubit** [comment]
No, actually there would need to be a third option for Windows since both / and \ can work
