### ISSUE TITLE
The cygwin build in GitHub Actions takes forever

### ISSUE THREAD

**Issue by empathicqubit** [z88dk/z88dk#2156]
You are probably already aware of this, but the cygwin build is very slow. There is one still running after two hours. With that in mind I think it would be better not to run it on every PR.

**Comment by desertkun** [comment]
Kind of defeats the purpose. The idea is to make sure everything compiles there.

**Comment by empathicqubit** [comment]
I had mentioned it because you ignored it before merging. Kind of defeats the purpose if you merge before it finishes.

Could you also try doing something like this? It will cut down on duplicate builds: https://github.com/python/cpython/pull/98009/files

**Comment by empathicqubit** [comment]
Okay, actually I read that wrong. Sorry. That one is on master.

**Comment by empathicqubit** [comment]
Still take a look at the concurrency stuff. I can add it if it makes sense to you.

**Comment by desertkun** [comment]
Either way that's something for @suborb to look into since I can only manage z88dk-gdb/ticks and maybe some sccz80, but that's it.
