### ISSUE TITLE
Binary larger when linking than compiling?

### ISSUE THREAD

**Issue by Dark-Schneider-666** [z88dk/z88dk#2194]
Hi,

Let's take this simple example code of hello world and then show the heap address (test.c):

```
#include <stdio.h>
#include <malloc.h>

long heap;

int main()
{
   puts("Hello World !");
	printf("%u", (unsigned int) &heap);
       return 0;
}
```

Well, if we compile it with:
`zcc +msx -subtype=msxdos2 test.c -o test.com`
The binary is smaller than if we do:
```
zcc +msx -subtype=msxdos2 -c test.c
zcc +msx -subtype=msxdos2 test.o -o test.com
```
Also the heap value confirms it being greater in the 2nd case.
Note: can use any other machine target like ZX the result is the same.

Should not be the same? Looks like when linking (2nd case) the
> and the linking capability means large bodies of code or data can be shared in libraries between projects with the linker only drawing out code and data that is actually used by a linking program.

is not working?

**Comment by suborb** [comment]
Have a read here: https://github.com/z88dk/z88dk/wiki/Classic--Pragmas

What you're running into is the concept behind this paragraph:

> An example of a compiler-generated pragma with the classic C library is sccz80's scan of printf format strings. sccz80 will keep track of what format specifiers are used and determine whether the compile can use a simple printf, medium printf or large printf implementation. This way the compiler can automatically reduce the size of the output binary by selecting the smallest printf implementation allowable.

Combined with:

> However, when using a makefile the project is normally split into many source files that are individually compiled to object files, as a result it's recommended that all #pragma statements should be located into a single file, say zpragma.inc and an linker option added: -pragma-include:zpragma.inc.

To fix it: https://github.com/z88dk/z88dk/wiki/Classic--Pragmas#configuring-printf-and-scanf-converters

**Comment by Dark-Schneider-666** [comment]
Nice, it was that.

What a mess to fall precisely in that case.

Thanks.
