### ISSUE TITLE
z80asm: remove '#' operator

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#221]
The '#' operator was used to force an expression to be computed at assembly time, as the linker was
not able to postpone address expressions to the link phase.

With the current linker I suspect this is no longer needed. Check and remove the operator if so.

**Comment by suborb** [comment]
The optimisation rules use # quite a lot to force a difference between effectively ld hl,NN and ld hl,(NN).

We generally fold up the expressions and stick them in parenthesis mod 65536 etc

Without the # operator we may end up in an ambiguous situation

**Comment by pauloscustodio** [comment]
Can we use a unary plus instead?

```ld hl,+(24)``` is ```ld ld,NN```

**Comment by suborb** [comment]
Sure, yup.

**Comment by zx70** [comment]
Opt files are so delicate..

**Comment by suborb** [comment]
This work is now folded into issue_221_remove_hash_constants
