### ISSUE TITLE
SDCC ignoring __smallc calling convention

### ISSUE THREAD

**Issue by Dark-Schneider-666** [z88dk/z88dk#2216]
I have this definition:
`extern void copy_ram_to_vram(vaddress dest, byte *source, size_t nbytes) __smallc;`
(note: vaddress is uint32_t)
The function is implemented in ASM, and with zscc80 works nice, but when compiled with SDCC it hangs just at my ASM functions. So when debugging I noticed SDCC always pass parameters as __z88dk_sdccdecl, from right to left.
I.e. when calling:
`copy_ram_to_vram(0x3800, 0x8000, 0x200);`
Compiled with zscc80 the stack within the function is:
```
06E2 <- returning address
0200
8000
3800
0000
```
Compiled with SDCC is:
```
05A2 <- returning address
3800
0000
8000
0200
```
So SDCC is ignoring the __smallc at declaration.

**Comment by feilipu** [comment]
See #2190 for a suggestion to resolve this.
