### ISSUE TITLE
zcc: Expecting constant expression when cast

### ISSUE THREAD

**Issue by RodrigoDornelles** [z88dk/z88dk#2220]
`error: Expecting constant expression`

mayable related #2150

what actually happened has too much context for me to show the code in the issue, and it's also being redone. (but it didn't give error with gcc, clang, smallc, cc65...)

basically any cast is prohibited in constant assignment, even when it's the same type, and it's enforcing to avoid warnings.

#### error 
```c
extern const uint8_t foo;
static const uint8_t* bar = (const uint8_t*const)&foo;
```

#### works fine

```c
extern const uint8_t foo;
static const uint8_t* bar = &foo;
```

**PS.** I'm using yesterday's night build (April 9)

**Comment by suborb** [comment]
Thanks for the issue - hopefully resolved from the next nightly.
