### ISSUE TITLE
zcc: Invalid pointer arithmetic when calculate number of structs (sizeof division)

### ISSUE THREAD

**Issue by RodrigoDornelles** [z88dk/z88dk#2221]
`fatal error: Invalid pointer arithmetic`

I have this problem, which is something quite common to use in C, but it is causing an error.

```c
struct foo {
    char bar[2];
};

static const struct foo z[] = {{4},{2}};
static const size_t y = sizeof(z)/sizeof(struct foo); ///< problem.
```

**Comment by suborb** [comment]
Thanks for the issue - hopefully resolved from the next nightly.
