### ISSUE TITLE
feature request: user defined warnings in preprocessor

### ISSUE THREAD

**Issue by RodrigoDornelles** [z88dk/z88dk#2224]
is a good feature in many compilers, to warn about failures and undefined behavior that can occur, or deprecated definitions (like freertos)

_it would be interesting to implement together, something like ` -Werror` that would make all warnings errors, if the user wants to. (many compilers have this option)_

#### msvc
currently compile, but not show message. (sillent)
```c
#pragma message("my advice!")
```

#### gcc/clang/cc65
not work, is the most commonly used, this pattern would be nice.
```c
#warning "my advice!"
```

**Comment by suborb** [comment]
I did think we had this feature already, but we might've lost it when we switch preprocessors.

Anyway, coming up....
