### ISSUE TITLE
(z80asm) Support ':' as instruction separator

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#2251]
It's quite common for other assemblers to support multiple instructions on the same line using either  ':' or '\'.

For example sjasmplus supports ':' and spasm-ng supports '\'

Supporting ':' at least would improve compatibility.

**Comment by pauloscustodio** [comment]
z80asm already supports a single backslash to separate statements (compatible with TASM).
I'll look into adding colon also.
