### ISSUE TITLE
[question/feature] How many UDGs are available on each target and subtarget?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2261]
When writing a multi-target game that uses UDGs, it would be important to know in advance which targets will support it if it uses X UDGs. 

Is this information already available? Does the feature header provide it already?
If not, it would nice to have it in the future.

**Comment by suborb** [comment]
It’s available as ‎__GENCON_MAX_UDGS in features.h

**Comment by Fabrizio-Caruso** [comment]
Thanks a lot!
