### ISSUE TITLE
No autocast result to function definition

### ISSUE THREAD

**Issue by Dark-Schneider-666** [z88dk/z88dk#2264]
I have this definitions:
`typedef uint8_t bool;`
`extern bool collide_check_u16(uint16_t x, uint16_t y, Rectangle_u16 *collision) __smallc __z88dk_callee;`
The returning values is like:
```
collide_return_false:
    ld l, 0
    ret
collide_return_true:
    ld l, 1
    ret
```
When doing something like:
`collide_draw_set(collide_check_u16(100, 90, &rect2) ? 8 : 7);`
It uses also the value at register H, so getting incorrect behavior, if instead I do:
`collide_draw_set((bool)collide_check_u16(100, 90, &rect2) ? 8 : 7);`
Works normally, using only register L.

If I set returning values like:
```
collide_return_false:
    ld hl, 0
    ret
collide_return_true:
    ld hl, 1
    ret
```
Then works with the 1st calling method, but is supposed to be an 8-bit returning value.

**Comment by suborb** [comment]
I think this is another manifestation of #2216

**Comment by Dark-Schneider-666** [comment]
I am using SmallC, should have indicated at title.

**Comment by suborb** [comment]
Ah, in that case it's working as expected: https://github.com/z88dk/z88dk/wiki/CallingConventions - return values with `__smallc` are in hl, or dehl

**Comment by Dark-Schneider-666** [comment]
Then I have to revise some of my asm code.

Thanks.
