### ISSUE TITLE
zsdcc: recent 9888 build does not apply peephole rules set by SO

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#228]
`zsdcc -v` will show the build you have.

The current build 9888 is not applying the peephole rules specified by -SO.  Going back to 9880 everything works fine.

The result is we get code generation like native sdcc with binaries several kb larger.  I'm not sure why 9888 is silently ignoring the rules yet.

**Comment by aralbrec** [comment]
The bug is a [faulty patch at sdcc](https://sourceforge.net/p/sdcc/bugs/2600/).
I'll commit fixes shortly and then the zsdcc binaries should be rebuilt.

**Comment by aralbrec** [comment]
Available at the [usual place](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/sdcc_z88dk_patch.zip) with win32 binaries.
Now aligned with sdcc 9897.

**Comment by aralbrec** [comment]
@suborb could you replace the win32 zsdcc binary in the nightly when you get a chance?  It's the broken one that is in there now (9888)

**Comment by suborb** [comment]
The next nightly should have it.
