### ISSUE TITLE
(z80asm) EQU hex constant handling

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#2286]
It looks like the following works:

```
aaa: EQU 12h
```

but:

```
bbb: EQU C0h
```

Doesn't. In fact any constant that starts with with a non-digit fails with:

```
 undefined symbol: C0h
```

**Comment by pauloscustodio** [comment]
Yes, C0h is a symbol, not a number, as it starts with a letter. You have to
write 0C0h.

A quarta, 31/05/2023, 21:02, suborb ***@***.***> escreveu:
