### ISSUE TITLE
Nightly builds not usable on OS X

### ISSUE THREAD

**Issue by stevesims** [z88dk/z88dk#2297]
On following the installation instructions and downloading the nightly build of z88dk, attempting to compile the simple C test file will result in a window appearing saying:
"zcc" can't be opened because Apple cannot check it for malicious software.

This can be worked around by allowing security exceptions within the Security & Privacy > General panel in System Preferences, however must be done individually for every tool _after_ it has been attempted to be run.

I believe that the root cause of this issue is the binaries in the build are not signed with a developer certificate.

**Comment by dbolli** [comment]
I don't get this error after compiling the nightly build on macOS but maybe try from Terminal.app

`sudo codesign --force --sign - /usr/local/bin/zcc`

**Comment by suborb** [comment]
They should be signed but they aren’t yet notarised. 

It’s the latter that’s needed to run without warning.

**Comment by stevesims** [comment]
Ah cool - thanks @dbolli and @suborb 

Yeah I should have written that I worked around the issue by re-building.  Good to know that one can also use `codesign` on the CLI.

I guess the docs could use a slight update to include this info

**Comment by suborb** [comment]
I added notarising into the build for 20230610 onwards - could one of you see if the binaries "just work" - it's quite tough for me to test since it since it uses by cert and my machines are signed in as me!

**Comment by dbolli** [comment]
Works for me based on nightly build for 20230611 👍

`
$ cd /path/to/z88dk/bin
$ ./zcc
zcc - Frontend for the z88dk Cross-C Compiler - v21219-d91677553e-20230611

Usage: ./zcc +[target] {options} {files}

Options:

   -v -verbose                  Output all commands that are run (-vn suppresses)
   -h -help                     Display this text
      -o                        Set the basename for linker output files
      -specs                    Print out compiler specs
[...]
$ ./z88dk-z80asm
Z80 Macro Assembler 21219-d91677553e-20230611
(c) InterLogic 1993-2009, Paulo Custodio 2011-2023
$ 
`

**Comment by suborb** [comment]
I'll close this one for the moment - please reopen if I break it in the future!
