### ISSUE TITLE
Compile z88dk as wasm

### ISSUE THREAD

**Issue by JasonMo1** [z88dk/z88dk#2330]
I'm going on a project, it need a dis-assembler runs on the web. So, how can I compile z88dk-dis into wasm?

**Comment by suborb** [comment]
I've not tried it, but I guess emscripten is probably the best thing to use!

**Comment by desertkun** [comment]
Yeah, you might want to use jsspeccy3 as an example on how this can be accomplished.

https://github.com/speccytools/jsspeccy3

**Comment by JasonMo1** [comment]
> 我没有尝试过，但我想 emscripten 可能是最好的选择！

The process has been killed by WSL😂

**Comment by JasonMo1** [comment]
> 是的，您可能希望使用 JSSPECCY3 作为如何实现此目的的示例。
> 
> https://github.com/speccytools/jsspeccy3

I have already implement the assembler, but we need a c compiler now.
