### ISSUE TITLE
Parallel (make -j X) builds not supported

### ISSUE THREAD

**Issue by AshleighTheCutie** [z88dk/z88dk#2331]
As the title says. Everything but `z88dk-z80asm` builds, making the entire software suite useless. The only modification I made to the `./build.sh` file is to have `make` use all 6 cores of the devboard (Odroid N2+ 2GB). It does this with all source code download forms, regardless of if it is downloaded with the `git clone --recursive` for the latest version, or the source tarball for v2.2. The full log can be found at: https://homesrv.ashleighhost.net/br/z88dk_1.log

```
make -C dev/z80asm_lib
make[2]: Entering directory '/home/ashleigh/z88dk/src/z80asm/dev/z80asm_lib'
rm -f z88dk-z80asm_lib.lst
<a fuckload of echos> 
../../z88dk-z80asm -l -xz88dk-z80asm-8080-.lib -m8080 @z88dk-z80asm_lib.lst
make[2]: ../../z88dk-z80asm: No such file or directory
make[2]: *** [Makefile:35: z88dk-z80asm-8080-.lib] Error 127
```

**Comment by ImperatorStorm** [comment]
Can reproduce in a clean Ubuntu arm64 vm.

**Comment by feilipu** [comment]
Pretty sure that multi-core is not fully complete yet.

Try leaving the `.build.sh` alone and building with single core , and report.

**Comment by suborb** [comment]
Superseded by #2419
