### ISSUE TITLE
[sc3000]bug/feature] Available RAM not used on SC3000 and even worse on SC3000 in BASIC  

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2342]
The current sc3000 target uses only 1k of RAM but the sc3000 has 2k work ram + up to 32k of ram when used with a BASIC cartridge.
In particular this is wrong or unnecessary:
https://github.com/z88dk/z88dk/blob/master/lib/target/sc3000/classic/rom.asm#L9C31-L9C31
https://github.com/z88dk/z88dk/blob/master/lib/target/sc3000/classic/rom.asm#L11

SC3000/SG1000 memory
1. work ram on the SC3000 without BASIC: 2K at $C000-$FFFF mirrored  every 2K.
https://github.com/franckverrot/EmulationResources/blob/master/consoles/sms-gg/Sega%20SC-3000%20hardware%20notes.txt#L156

2. extra ram on the SC3000 with BASIC Level III A : 16K at $8000-$BFFF, 32K with Level III B, 4K with Level II B, 0k with Level II A, etc....
https://github.com/franckverrot/EmulationResources/blob/master/consoles/sms-gg/Sega%20SC-3000%20hardware%20notes.txt#L167

3. work ram on the SG1000: 1K at $C000-$FFFF mirrored every 1K
https://www.smspower.org/Development/MemoryMap

IMHO we should have:

1. rom subtype: we should have RAM segments (DATA, BSS, RODATA) at  $C000-C7FF (2K) which should work for cartridges meant to be used on both SC3000 and SG1000 (if RAM used <= 1K).

RAM_Start  = $C000 (as it is now but only for rom subtype)
RAM_Length = $0800 (correct even though it was limited by Stack_Top  = $c400)
Stack_Top  = $c800 (or $c7fff depending on whether $c800 is used or not), which should work also on SG1000 because of mirroring.

2. normal sc3000 target: we should have RAM segments at $8000-$BFFF in order to use at least 4K of RAM (or 16K or 32K) because we are clearly assuming we have a BASIC cartridge inserted when we build a cassette image.

RAM_Start  = $8000 (only for BASIC)
RAM_Length, Stack_Top should depend on the BASIC cartridge used. Level II A has 0k. Level II B has 4k. Level III A has 16K. Level III B has 32K.
Ideally we should have sub-types but we can just support Level III B (32K), which may work on all other BASICs thanks to mirroring but this has to be double-checked. 
RAM_Length = $8000 (not sure it is ok with BASICs with less than 32k but it may work if it grows upwards)
Stack_Top      = $FFFF -> mirrored in BASIC III A (16k) to $BFFF and mirrored in BASIC II B (4k) to $8FFF

Symptoms of the problem :
In particular 3 out of my 7 Cross-Lib games fail: shoot (corrupted graphics), shuriken (black screen), snake (black screen).
On the other hand chase, bomber, horde, verbix work fine. The games that do not work are the ones that use about 1k or 2K of RAM.

Is there a way to produce a "map" file with all memory segments sizes and offsets?

**Comment by suborb** [comment]
I think this one is covered by #2343 so closing
