### ISSUE TITLE
[bug] sleep hangs the computer on multiple targets

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2345]
sleep hangs the computer on multiple targets.

For example the following code will just print 0 and 1 but never reach 2
```
#include <stdlib.h>
#include <stdio.h>

int main(void)

{
	short i;
	
	for(i=0;i<10;++i)
	{
		printf("%d\n", i);
		sleep(1);
	}
	while(1){};
	return 0;
}
```

I am getting this problem on multiple targets, e.g., zx and msx.

For example:
```
zcc +zx ./debug/test_sleep.c -create-app -o test_sleep -lndos
```

**Comment by suborb** [comment]
Sorry about that, should be good now.

**Comment by Fabrizio-Caruso** [comment]
@suborb There is no nightly build, though. The snapshots for both today and yesterday are missing. The build process might have failed.
