### ISSUE TITLE
[agon][bug] Wrong colors in mode 2

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2349]
In my games, some colors are mapped to the wrong color.
For example 
- red is shown as blue;
- yellow is shown as cyan.

**Comment by suborb** [comment]
It's known, see: https://z88dk.org/forum/viewtopic.php?p=21941#p21941

The emulator still doesn't support redefining colours so I probably ought to add a mapping in.

**Comment by suborb** [comment]
I've applied the following mappings:

```
        defb    $0      ;BLACK -> (#00 00 00)
        defb    12      ;BLUE -> (#00 00 ff)
        defb    10      ;GREEN -> (#00 ff 00)
        defb    14      ;CYAN -> (#00 ff ff)
        defb    9       ;RED -> (#ff 00 00)
        defb    13      ;MAGENTA -> (#ff 00 ff)
        defb    43      ;BROWN -> (#aa 55 55)
        defb    15      ;LIGHTGRAY -> (#ff ff ff)
        defb    15      ;DARKGRAY -> (#ff ff ff)
        defb    47      ;LIGHTBLUE -> (#aa aa ff)
        defb    2       ;LIGHTGREEN -> (#00 aa 00)
        defb    51      ;LIGHTCYAN -> (#aa ff ff)
        defb    1       ;LIGHTRED -> (#aa 00 00)
        defb    57      ;LIGHTMAGENTA -> (#ff 55 ff)
        defb    11      ;YELLOW -> (#ff ff 00)
        defb    15      ;WHITE -> (#ff ff ff)
```

Available colours are listed here: https://gist.github.com/astralaster/33a7c4ca85380925b306b2df37afbd19 - corrections/alterations welcome.

**Comment by Fabrizio-Caruso** [comment]
Thanks!
This is now fixed!
![image](https://github.com/z88dk/z88dk/assets/29057615/5e18c6de-4c4d-4526-b542-01e919380600)
