### ISSUE TITLE
Question: should z80asm be strict in parsing expressions enclosed in parenthesis?

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#235]
The z80asm parser needs to know if an expression has a pair of outer parenthesis in order to differentiate ```ld a,N``` from ```ld a,(NN)```. This is also used to raise a syntax error for the invalid ```ld b,(NN)```.

This mechanism is not applied today in other similar constructs, but I think it should. For instance, ```cp (NN)``` does not exist, and today the parentheses are ignored and the statement is interpreted as ```cp N```, instead of raising a syntax error.

In the z80asm_rabbit branch I've forced the later construct to raise a syntax error and got some errors compiling the library, in constructs like ```cp (XYZ) & 0xFF```.

I think the new form is better to force clarity in the code. I can volunteer to fix the few places where this appears in the library, by replacing the above with  ```cp +(XYZ) & 0xFF```.

Any objections?

**Comment by aralbrec** [comment]
nope

**Comment by pauloscustodio** [comment]
Decided on raising a warning instead of a syntax error.

**Comment by zx70** [comment]
Warning looks good for retro compatibility.  The error stop would be legitimate but I recently had to adjust an old z80asm program and even if the errors were relevant I wished not to have to fix them all to match with the recent z80asm  :)
