### ISSUE TITLE
[bee][bug] conio cursor positioning is broken

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2354]
Conio cursor position is broken. Tested on Nanowasp.org

This issue is reproduced by:
```
#include <conio.h>
int main()
{
   gotoxy(10,10);
   cprintf("hello world\n");
   gotoxy(10,13);
   cprintf("au revoir\n");
   return 0;
}
```

compiled with:
```
zcc +bee conio_test.c -create-app
```

**Comment by suborb** [comment]
This compilation flags here indicate that this program is using the ROM printer. conio.h only works with `--generic-console`, `-clib=ansi`, `-clib=ansi40` on the Microbee

**Comment by Fabrizio-Caruso** [comment]
@suborb Wichh cmpilation flags? You mean that no flags implies rom printer? Maybe you mean that for this specific target, no option implies rom printer.

**Comment by suborb** [comment]
Yes. The lack of flags. Sorry for the lack of explicitness.

**Comment by Fabrizio-Caruso** [comment]
Now, it looks more broken than before (in NanoWasp) if I just try to display ASCII characters without setting any video.

Characters were shown correctly before and there was just a problem with the cursor positioning.
I might need subtargets or different targets.

My Bomber game is shows a lot of glitched graphics:
![image](https://github.com/z88dk/z88dk/assets/29057615/90c82091-8fd1-42ba-b273-c41438ddd478)
