### ISSUE TITLE
[bee][bug][ansi40] Wrong horizontal position in ansi40 mode and maybe wrong YSize

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2355]
When compiling my Bomber game, the result has wrongly positioned characters in ansi40 mode (horizontal position is off):
![image](https://github.com/z88dk/z88dk/assets/29057615/9df2456a-0108-47fb-9334-390b69612904)

Moreover it looks like YSize might be wrong for whatever model Nanowasp emulates because I get better results by forcing YSize=24 but this problem may be a secondary effect of the wrong horizontal positioning.

I am compiling it with
```
microbee_40col:
	$(Z88DK_PATH)$(MYZ88DK) +bee $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-D__BEE__ -clib=ansi40  -vn   \
	-D__CONIO_GRAPHICS -D__NO_INIT_GRAPHICS -D_XL_NO_UDG \
	-lndos -create-app -o $(BUILD_PATH)/X$(GAME_NAME)_$@.prg  \
	$(FULL_FILES)
	rm -rf $(BUILD_PATH)/X$(GAME_NAME)_LIGHT_$@.prg
```

**Comment by suborb** [comment]
Similar to #2358 - how are you determining XSize?

**Comment by Fabrizio-Caruso** [comment]
@suborb I just take whatever default values XSize and YSize have. This works for all other 100 Z88DK targets.
I can try to write a minimal test.

**Comment by Fabrizio-Caruso** [comment]
Sorry, you are just right (as usual).
Please excuse me for this stupid non-issue.

**Comment by Fabrizio-Caruso** [comment]
@suborb So both clib=ansi40 and --generic-console work fine as long as I provide the right values for XSize and YSize.

On the other hand in Nanowasp I don't see redefined characters but I think you mentioned this. It does not crash, though. It just shows the characters as if they were not defined.

**Comment by Fabrizio-Caruso** [comment]
@suborb I may open an issue on the input. It seems the keyboard is using an overly long buffer, so that the games become unplayable as long as you keep any key pressed for just a second or less as the player will then just keep on moving on that direction for the next 20 or 30 seconds as if the key were still pressed.
