### ISSUE TITLE
[bee][generic-console] Display on bottom-most row is wrong or YSize is wrong

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2358]
When trying to display a line made of "=" characters on the bottom row with generic console, the entire line of "=" characters is display on the left-most column.

Maybe YSize is wrong or something is wrong with the display code.

This is what my game looks like:
![image](https://github.com/z88dk/z88dk/assets/29057615/04a9aa9f-dffb-4ec4-b941-82ce528a6e2e)

If I force YSize=24 I get the good result:
![image](https://github.com/z88dk/z88dk/assets/29057615/4594b7bc-8637-46bf-ba05-0b087c71eb20)

If necessary I can try to reproduce this with a minimal example.

**Comment by suborb** [comment]
How are you determining YSize? I'd recommend using screensize(&XSize,&YSize) - any #defines may well not match the screen mode.

**Comment by Fabrizio-Caruso** [comment]
In all 100 targets, I just use whatever value YSize is defined too by default. So I don't read YSize and I treat it as a constant.
If I do so, in the generic console, I get perfect horizontal positions for the characters. So I guess whatever value is given to XSize by default is correct. I am not so sure this is related to the other bug, which is about the horizontal positioning with clib=ansi40.

**Comment by suborb** [comment]
XSize and YSize are your preprocessor `#define`'s I think - I can see them being used at that level at least.

I can't spot any #defines on the z88dk side that define the screen size (impossible to do due to multiple screen modes).

So a minimal example would be good so we can track down where these values are coming from!

**Comment by suborb** [comment]
Aha... `cross_lib/display/display_target_geometry.h`

```
                  || defined(__MZ__) || defined(__BEE__) || defined(__X1__) \
                  || defined(__PCE__) || defined(__CPC__) || defined(__VG5K__)  \
                  || defined(__ENTERPRISE__) \
                  || defined(__FP1100__) \
                  || defined(__MULTI8__) \
                  || defined(__MO5__) || defined(__TO7__)
                #define YSize (25-Y_OFFSET)
```

**Comment by Fabrizio-Caruso** [comment]
Sorry, you are just right (as usual).
Please excuse me for this stupid non-issue.
