### ISSUE TITLE
ticks - r2ka mul emulation

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#2379]
I’m trying to get the Rabbit long 32_32x32 multiply working, which needs the unsigned 32_16x16 to be correctly added to the algorithm. But my uncommitted “improvements” lead to worse test outcomes. I’ve reworked the algorithm a dozen times, without results.

Looking at the ticks emulation algorithm, I’m not sure that handling signed register pairs by multiplying the MSB by 256 is correct. I think the sign extension is missing. Thoughts?

https://github.com/z88dk/z88dk/blob/9cd0fe8b1aa2cca406d52df06f8f6aeefe38ff36/src/ticks/ticks.c#L2929

**Comment by suborb** [comment]
That looks unsigned to me too since d,e etc are I think unsigned char. 

My fault - I probably just assumed it was unsigned multiplication.
