### ISSUE TITLE
Need macro to detect Z88DK

### ISSUE THREAD

**Issue by dfandrich** [z88dk/z88dk#2384]
I trolled the sources hard to find a reliable macro to use to detect when a program is being compiled against Z88DK's CLIB, but I wasn't able to find one. There are macros for the CPU and for the device, but none for CLIB itself. There ought to be one that would be suitable to fit on https://sourceforge.net/p/predef/wiki/Libraries/

I suggest defining a macro in `<features.h>`, perhaps `__Z88DK_CLIB_VERSION__` containing a version number, so portable programs can adapt to it.

**Comment by suborb** [comment]
Good suggestion, I think the easiest thing to add is presence macros of `__Z88DK_CLASSIC` and `__Z88DK_NEWLIB`
