### ISSUE TITLE
Mistake in crt_section.asm DE registers when CRT_MODEL=3 (zx0 compression)

### ISSUE THREAD

**Issue by Tronix286** [z88dk/z88dk#2399]
I am using custom 8080 RAM/ROM target with CRT_MODEL=3 DATA section compression. I think i found mistake in lib\crt\classic\crt_section.asm here:
```
ELIF ( __crt_model >= 2 )
    EXTERN	__ROMABLE_END_tail
    EXTERN	__DATA_head
    ld      hl,__ROMABLE_END_tail
    ld      de,__DATA_head
  IF ( __crt_model = 2)
    EXTERN  asm_dzx7_standard
    call    asm_dzx7_standard
  ELIF ( __crt_model = 3)
    EXTERN  asm_dzx0_standard
    call    asm_dzx0_standard
  ENDIF
ENDIF
```

at line `ld      de,__DATA_head` . When using zx0 decompression asm_dzx0_standart funcion called, but this function accept those parameters:
```
; Parameters (forward):
;   HL: source address (compressed data)
;   BC: destination address (decompressing)
;
; Parameters (backward):
;   HL: last source address (compressed data)
;   BC: last destination address (decompressing)
```

So, in my case line `ld      de,__DATA_head` must be changed to `ld      bc,__DATA_head`

BTW, zx7 decompression uses DE registers. So, maybe final patch to crt_section.asm looks like this:
```
ELIF ( __crt_model >= 2 )
    EXTERN	__ROMABLE_END_tail
    EXTERN	__DATA_head
    ld      hl,__ROMABLE_END_tail
  IF ( __crt_model = 2)
    EXTERN  asm_dzx7_standard
    ld      de,__DATA_head
    call    asm_dzx7_standard
  ELIF ( __crt_model = 3)
    EXTERN  asm_dzx0_standard
    ld      bc,__DATA_head
    call    asm_dzx0_standard
  ENDIF
ENDIF
```

**Comment by suborb** [comment]
Good spot - thank you. I've not taken your fix, but rather fixed the arguments on entry to the actual routines since  they can also be called by re-used (across CPUs) C stubs.
