### ISSUE TITLE
(z80asm) Trouble with defc label1 = label2

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#2418]
Trying to figure out exactly what's going on here. But take a look at stdio/_freopen1.c

All coming out of the example in this post: https://z88dk.org/forum/viewtopic.php?f=13&t=11849 - I'm using +test because it's easier to debug.

There's some jp optimisation going on in _freopen1.c, so there's `defc i_13 = i_9`. Because of the cleanup function, this ends up in the `code_crt_exit` section. When linked this seems to end up point to somewhere in `l_eq` which is "puzzling" since it's supposed to be local.

```
pc=0D98, [pc]=C3,    bc=0043,  de=0043,  hl=0047,  af=0045, ix=0000, iy=0000
sp=FE7A, [sp]=0047, bc'=0000, de'=0000, hl'=0000, af'=0040
f: S=0 Z=1 H=0 P/V=1 N=0 C=1
clockh=196A, clockhl=8298
                    jp        i_13_stdio__freopen1_c        ;[0d98] c3 03 02
pc=0203, [pc]=AF,    bc=0043,  de=0043,  hl=0047,  af=0045, ix=0000, iy=0000
sp=FE7A, [sp]=0047, bc'=0000, de'=0000, hl'=0000, af'=0040
f: S=0 Z=1 H=0 P/V=1 N=0 C=1
clockh=196A, clockhl=8298
i_13_stdio__freopen1_c:
                    xor       a                             ;[0203] af
```

```
l_eq:
                    or        a                             ;[01fd] b7
                    sbc       hl,de                         ;[01fe] ed 52
                    scf                                     ;[0200] 37
                    inc       hl                            ;[0201] 23
                    ret       z                             ;[0202] c8
                    xor       a                             ;[0203] af
                    ld        l,a                           ;[0204] 6f
                    ld        h,a                           ;[0205] 67
                    ret                                     ;[0206] c9
```

**Comment by suborb** [comment]
Moving the defc into the right section corrects the problem, but I'm confused as to what was actually happening.

**Comment by pauloscustodio** [comment]
> Moving the defc into the right section corrects the problem, but I'm confused as to what was actually happening.

The copied symbol was in a different section, so the address base was different on relocation. Fixed.
