### ISSUE TITLE
Documentation does not reflect current structure of object files

### ISSUE THREAD

**Issue by atirut-w** [z88dk/z88dk#2436]
The structure has changed quite a bit, according to the source codes:

https://github.com/z88dk/z88dk/blob/master/src/common/objfile.c#L1154-L1192

The stuff most obvious to me are CPU ID and IX-IY swap now comes first. This is also reflected in generated object files. I am quite sure there are other changes too, as some of the values in object files are *very* wrong.

**Comment by pauloscustodio** [comment]
Fixed, thanks for reporting.
