### ISSUE TITLE
const pointer confusion

### ISSUE THREAD

**Issue by dfandrich** [z88dk/z88dk#2438]
Compiling the following code:
```C
#include <string.h>
#include <stdio.h>
int main() {
    char a[16];
    const char *b = "ABC";
    const char * const *c;
    c = &b;
    strcat(strcpy(a, b), *c);
    puts(a);
    return 0;
}
```
results in the erroneous warning: `badconst.c:8:4: warning
 Converting type: const char const *  to const char * src [-Wincompatible-pointer-types]`. `const char const *`

The two types in this warning, `const char const *` and `const char *` are the same in C.

Furthermore, running the code compiled with `zcc +cpm -create-app  badconst.c` doesn't result in the expected output (which is `ABCABC`) but only one `ABC` then a weird wait for a character and weird input corruption on my CP/M emulator, implying something bad has happened. This is using commit f927c84d from a few weeks ago.

**Comment by suborb** [comment]
Apart from the two slow targets, the build has gone through so both of these issues should now be fixed.

Feel free to reopen if it's not solved for you.
