### ISSUE TITLE
[z9001] UDG KRT mode may be broken

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2447]
I have tried to build my Cross-Lib games for the Z9001 in mode 1, for which Z88DK is supposed to support UDG for KRT graphics.

Under JKCEMU emulator, characters are not redefined. Maybe I am doing something wrong. Maybe I am not setting the emulator correctly. 
This is what I get:
![image](https://github.com/z88dk/z88dk/assets/29057615/faf1b7c3-7d35-418d-9d8b-18c3183b0240)

This is what I should see:
![image](https://github.com/z88dk/z88dk/assets/29057615/30b9e733-3125-4394-9600-c9e9b42314af)

My gfx settings:
![image](https://github.com/z88dk/z88dk/assets/29057615/7409b52a-3433-4451-b890-381ab7d9f9b8)

Before I write a minimal example, could any of you confirm UDGs are supported and I only need to set the mode to 1 and nothing else?

**Comment by suborb** [comment]
That should be all that’s needed. 

The screenshot looks like the mode isn’t being changed at all!

I‘ll test in a bit.

**Comment by suborb** [comment]
My little test program shows this:

![image](https://github.com/z88dk/z88dk/assets/394721/e462e34c-b6b1-4b65-ab5d-41a5768cce61)

with jkcemu 0.9.7

**Comment by Fabrizio-Caruso** [comment]
@suborb, Sorry, is your example showing user-defined tiles?
What do I need to do to switch the mode?
The doc says I should use mode 1.
I do:
```
	void *param = &udgs;
	console_ioctl(IOCTL_GENCON_SET_FONT32, &param);
	int mode = __SCREEN_MODE;
	console_ioctl(IOCTL_GENCON_SET_MODE, &mode); 
```
where `__SCREEN_MODE` is 1. I have also tried 2.


My Makefile target is:
```
z9001: $(ASSETS_PATH)/z88dk_xchase.asm
	$(Z88DK_PATH)$(MYZ88DK) +z9001 $(SCCZ80_OPTS) $(INCLUDE_OPTS) -clib=ansi \
	-D__Z9001__ -vn  -D__SCREEN_MODE=1 -D_XL_NO_JOYSTICK  \
	-D__CONIO_GRAPHICS  -D__BIT_BANG_SOUND \
	-lndos -create-app -o $(BUILD_PATH)/X$(GAME_NAME)_$@.z80 \
	$(FULL_FILES) \
	$(CROSS_LIB_PATH)/display/init_graphics/z88dk/udg/udg_init_graphics.c \
	$(ASSETS_PATH)/z88dk_xchase.asm
```

**Comment by suborb** [comment]
So in my screenshot you can see it's using the ZX font and there's 3/4 of a smiling face.

In your screenshot it looks the the Z9001 default font is being used which suggests that the screen mode isn't being changed.

To try and figure out where it's going wrong, I've run a test where I don't change the emulated hardware (so left on "S/W Blockgrafik") but do switch mode and I end up with a blank screen.

So, the fact that you've got colour means that you've correctly switched the emulated hardware, but somehow this bit of code:

```
	void *param = &udgs;
	console_ioctl(IOCTL_GENCON_SET_FONT32, &param);
	int mode = __SCREEN_MODE;
	console_ioctl(IOCTL_GENCON_SET_MODE, &mode);
```

isn't being executed or taking effect.

Looking closer at your makefile:

```
z9001: $(ASSETS_PATH)/z88dk_xchase.asm
	$(Z88DK_PATH)$(MYZ88DK) +z9001 $(SCCZ80_OPTS) $(INCLUDE_OPTS) -clib=ansi \
```

Remove -clib=ansi and replace with --generic-console As is usual, the VT100 terminal only targets one screen mode, and for the z9001 it's the text screen mode.

**Comment by Fabrizio-Caruso** [comment]
Thanks for your replay.

If I replay -clib=ansi with --generic-console, nothing changes.
On the other hand, if I just remove -clib=ansi, I get some gibberish (with graphics) on the screen. 

I will need to see how I can reproduce this with a smaller example...

Within Cross-Lib I just do `xl bomber z9001` to compile the smallest of my games

![image](https://github.com/z88dk/z88dk/assets/29057615/1074c1d1-d9aa-4acb-9758-9abfe74a1c4a)

I have attached the binaries.
[Xbomber_z9001.zip](https://github.com/z88dk/z88dk/files/13444662/Xbomber_z9001.zip)

**Comment by suborb** [comment]
> Within Cross-Lib I just do xl bomber z9001 to compile the smallest of my games

Unfortunately that fails with the following for me (I think I've had this trouble in the past):

```
Traceback (most recent call last):
  File "./generate_assets.py", line 284, in <module>
    main()
  File "./generate_assets.py", line 279, in main
    generate_assets_from_dir(dir_name)
  File "./generate_assets.py", line 270, in generate_assets_from_dir
    generate_asset_from_template(dir_name, stripped_template_file_name)
  File "./generate_assets.py", line 263, in generate_asset_from_template
    process_a7800_160A_file()
  File "./generate_assets.py", line 202, in process_a7800_160A_file
    print("Asset has wrong length: " << len(source))
TypeError: unsupported operand type(s) for <<: 'str' and 'int'
make: *** [games/bomber/generated_assets/z88dk_xchase.asm] Error 1
```

> I have attached the binaries.

Can I have the .map as well?

**Comment by Fabrizio-Caruso** [comment]
@suborb Sorry for the stupid Python error.

I have fix it now. If you pull the latest version, it should now work for you.

I have attached the map files and the binaries produced by these Makefile targets:
```
z9001: $(ASSETS_PATH)/z88dk_xchase.asm
	$(Z88DK_PATH)$(MYZ88DK) +z9001  -m  $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-D__Z9001__ -vn  -D__SCREEN_MODE=1+32 -D_XL_NO_JOYSTICK  \
	-D__CONIO_GRAPHICS  -D__BIT_BANG_SOUND \
	-lndos -create-app -o $(BUILD_PATH)/X$(GAME_NAME)_$@.z80 \
	$(FULL_FILES) \
	$(CROSS_LIB_PATH)/display/init_graphics/z88dk/udg/udg_init_graphics.c \
	$(ASSETS_PATH)/z88dk_xchase.asm

z9001_generic_console: $(ASSETS_PATH)/z88dk_xchase.asm
	$(Z88DK_PATH)$(MYZ88DK) +z9001  -m  $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-D__Z9001__ -vn  -D__SCREEN_MODE=1+32 -D_XL_NO_JOYSTICK  \
	-D__CONIO_GRAPHICS  -D__BIT_BANG_SOUND \
	-lndos -create-app -o $(BUILD_PATH)/X$(GAME_NAME)_$@.z80 \
	$(FULL_FILES) \
	$(CROSS_LIB_PATH)/display/init_graphics/z88dk/udg/udg_init_graphics.c \
	$(ASSETS_PATH)/z88dk_xchase.asm
```

[build.zip](https://github.com/z88dk/z88dk/files/13447346/build.zip)

**Comment by suborb** [comment]
Thanks - I can now build and play.

```
--- a/src/Makefile_common
+++ b/src/Makefile_common
@@ -1919,7 +1919,7 @@ z9001_broken_gfx: $(ASSETS_PATH)/z88dk_xchase.asm
 # --generic-console
 z9001: $(ASSETS_PATH)/z88dk_xchase.asm
        $(Z88DK_PATH)$(MYZ88DK) +z9001  -m  $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
-       -D__Z9001__ -vn  -D__SCREEN_MODE=1+32 -D_XL_NO_JOYSTICK  \
+       -D__Z9001__ -vn  -D__SCREEN_MODE=1 -D_XL_NO_JOYSTICK --generic-console  \
        -D__CONIO_GRAPHICS  -D__BIT_BANG_SOUND \
        -lndos -create-app -o $(BUILD_PATH)/X$(GAME_NAME)_$@.z80 \
        $(FULL_FILES) \
@@ -1928,7 +1928,7 @@ z9001: $(ASSETS_PATH)/z88dk_xchase.asm

 z9001_generic_console: $(ASSETS_PATH)/z88dk_xchase.asm
        $(Z88DK_PATH)$(MYZ88DK) +z9001  -m  $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
-       -D__Z9001__ -vn  -D__SCREEN_MODE=1+32 -D_XL_NO_JOYSTICK  \
+       -D__Z9001__ -vn  -D__SCREEN_MODE=1 -D_XL_NO_JOYSTICK  \
        -D__CONIO_GRAPHICS  -D__BIT_BANG_SOUND \
        -lndos -create-app -o $(BUILD_PATH)/X$(GAME_NAME)_$@.z80 \
        $(FULL_FILES) \
```

![image](https://github.com/z88dk/z88dk/assets/394721/3d5869ff-166b-4f67-b7ae-f7a0196daffa)

**Comment by Fabrizio-Caruso** [comment]
@suborb ! So, something is wrong in my setup or very special in yours.
Which Makefile target did you use? Which settings did you use on the emulator?

Even with the latest JKCEMU (0.9.8.3), with KRT, I get gibberish on the screen:
![image](https://github.com/z88dk/z88dk/assets/29057615/652d0b29-d6ef-44d0-bf1d-9e972c8e0879)

**Comment by suborb** [comment]
So, if I run the binaries you attached last of all I can reproduce what you see.

I can see two problems in the binary which I think together are causing the issue:

1. The screen mode is incorrect (you added 32 to it)
2. The screen printer is using the firmware

I'm using the `xl bomber z9001` using my makefile changes above - can you try those and if it's still failing attach the binaries and map files again.

**Comment by Fabrizio-Caruso** [comment]
Thanks @suborb!
It works indeed! 
I still don't understand why I need `--generic-console` in this particular target and not in all the others.
My guess is that the standard console for this specific target is vt100/ansi, which is locked to one mode, which does not happen to support udg. Is this the reason?

**Comment by suborb** [comment]
Well you are! `--generic-console` is an alias for `-pragma-redirect:fputc_cons=fputc_cons_generic` which you are using for a lot of targets.

**Comment by Fabrizio-Caruso** [comment]
@suborb I should switch to the more readable `--generic-console`. 
My bad (as usual). Thanks for your patience and support
