### ISSUE TITLE
z80asm equate definition that is similar to asm z80 opcode instruction causes assembler error message

### ISSUE THREAD

**Issue by dbolli** [z88dk/z88dk#2466]
`
RLB	equ	$0B95	
`

results in error message

`
../z88dk-zx81-aszmic-equates.asm:310: error: syntax error
  ^---- RLB equ $0B95
      ^---- RLB equ 2965
`

workaround is to change asm equate definition to

`
ASZRLB	equ	$0B95		; :dbolli:20231213 22:41:47 Changed from RLB to avoid clash with z80asm RL B
`

This was not an issue in previous builds

**Comment by dbolli** [comment]
Many thanks, I will re-test when the next nightly build is posted 👍

**Comment by dbolli** [comment]
Re-tested successfully in nightly build 22119-d2a573ab97-20231226. Many thanks again 👍

**Comment by pauloscustodio** [comment]
Thanks for reporting.
