### ISSUE TITLE
(ci) msys2 build failing

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#2476]
```
z88dk-z80asm -d -O=adt-newlib/obj/z80/x -I/d/a/z88dk/z88dk/libsrc//../libsrc/ -mz80 -D__CLASSIC "/d/a/z88dk/z88dk/libsrc/_DEVELOPMENT//adt/*/c/sccz80/*.asm" "/d/a/z88dk/z88dk/libsrc/_DEVELOPMENT//adt/*/z80/*.asm"
error: pattern returned no files: /d/a/z88dk/z88dk/libsrc/_DEVELOPMENT//adt/*/c/sccz80/*.asm
make: *** [adt-newlib/adtnewlib.mak:21: adt-newlib/obj/newlib-z80-adt-newlib] Error 1
make: Leaving directory '/d/a/z88dk/z88dk/libsrc'
Error: Process completed with exit code 2
```

No real changes from our side, so a silent msys update?

**Comment by feilipu** [comment]
Seems more needy than a small child.

**Comment by pauloscustodio** [comment]
bisecting... it will take a while as it built OK in my msys system

**Comment by pauloscustodio** [comment]
For some unknown reason msys2 in the github infrastructure stopped accepting /d/xxx for path d:/xxx. Do the translation in z80asm.

**Comment by suborb** [comment]
Thanks Paulo, that's a worrying change from msys2

**Comment by pauloscustodio** [comment]
Win32 is not a well-behaved sw environment. If Visual Studio worked in Linux, I would have changed already, But Visual Studio (not VS Code) is by far the best free IDE for C++ development I have ever tried. I have also used Jetbrains on the Mac, but this one is not free.
