### ISSUE TITLE
z80asm - cli setting for DEFS - enhancement

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#248]
Currently it is possible to set the contents of a `DEFS` statement by [adding the byte format to the statement](https://github.com/z88dk/z88dk/blob/master/doc/z80asm.txt#L1662), with `0x00` being the default. But, I see no way to globally change the default `DEFS` fill byte from the command line.

There is a need to globally change this the default to allow different fill bytes to be set, without going through to change each `DEFS` statement individually. Often `0xFF` is used as a fill byte, but also `0xC9` or `0x76` can be useful options.

I'd like to request an enhancement to z80asm to set the default `DEFS` fill byte using the command line option (for example) `-fnn` where `nn` is the fill byte in hexadecimal.

**Comment by pauloscustodio** [comment]
I'll keep this open as an enhancement for the future.

In the meantime you can use the workaround of defining a fill constant in an include file and include it in each module before the ```defs```.
