### ISSUE TITLE
Request: Please update the AgonLight wiki re: ADL=1 (24 bit mode)

### ISSUE THREAD

**Issue by snakebyte69** [z88dk/z88dk#2481]
https://github.com/z88dk/z88dk/wiki/Platform---AgonLight
Does zcc support ADL=1 (24 bit mode)?
Please update the wiki as to which z88dk apps support 24bit mode

**Comment by suborb** [comment]
The information was already on the wiki and on the forum: https://www.z88dk.org/forum/viewtopic.php?p=22545#p22545

However, I've now cleaned it up and made it more obvious on the wiki page.
