### ISSUE TITLE
Merging the lib3d.lib into gfx

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#2515]
As it already happened with xlib.lib, I'd like to have lib3d.lib merged as part of the central library block (the graphics part is probably a good option).
It would enable the ixiy dependent targets.

**Comment by suborb** [comment]
It should be fairly easy to do. The main thing to watch out for is the .asm files and 8080/gbz80 variants.

**Comment by zx70** [comment]
If lib3d.lib becomes transparent also the Makefiles for the examples will need a fix.

**Comment by suborb** [comment]
@zx70 I've created a branch with the folding of lib3d into the main platform library.

If you want to sanity check that would be great.

**Comment by feilipu** [comment]
Just a thought (since this is a tidy up), there's [inconsistent use of capitalisation for the Type definitions](https://github.com/z88dk/z88dk/blob/fold_lib3d/include/lib3d.h#L146-L201). Sometimes they are capitalised `Vector_t`, and sometimes lower case `vector_t` (for example). Probably lower case should be used throughout, but either way is ok.

**Comment by suborb** [comment]
You probably need to rebuild z80asm or grab it from nightly.

**Comment by zx70** [comment]
Thank you.  While testing I'm pulling the correction @feilipu suggested in the pending branch.

**Comment by feilipu** [comment]
Fixed the build issue in example `showlib3d.c` (hopefully).

**Comment by zx70** [comment]
Thankyou @feilipu, my local setup is slowly building the libraries 😹 
It is very nice to try spotting those problems I'm aware of and discover they're solved already !
Those capital initials were something I kept untouched from the original Hitech C based SDK for the Sharp Wizard organizers for cross-compatibility.

**Comment by feilipu** [comment]
I was thinking to convert all z88dk references to the lowercase, and then (when clean) add in a define for the capitalised version so that we don't break user programs.

Ok?

**Comment by zx70** [comment]
I'd keep everything lowercase only, I noticed that this library was never used very much, we also have some redundancy with code coming from the MSX world and others which I tried to merge with partial success.
A local #define is not difficult to add, if it will be ever necessary.

I just noticed that OZDK is sort of surviving, which is definitely a good thing, for the Wizard it is still preferrable to z88dk (but for our larger library), it supports a well tested target specific memory model allowing bigger programs.

https://github.com/arpruss/ozdev

**Comment by feilipu** [comment]
Seems all good now. Still hung up on one build, that I'll restart.

**Comment by zx70** [comment]
The ZX81 and Lambda targets are now working well :)

There is still something not looking right with the non-z80 CPUs (perhaps my setup is wrong), but I think it we have a good progress already, enough for a pull.

The extra stuff I've found:

`
$ zcc +cpm -clib=8080 -create-app -lm -lgfxvti coswave.c
error: file not found: genmath_8080.lib
`


`
$ zcc +cpm -clib=8080 -create-app -lgfxvti showlib3d.c
video/vti/stdio/generic_console.asm:41: error: undefined symbol: __z80asm__ldir
  ^---- __z80asm__ldir
video/vti/stdio/generic_console.asm:109: error: undefined symbol: __z80asm__ldir
  ^---- __z80asm__ldir
lib3d/icos.asm:24: error: undefined symbol: __z80asm__sbc_hl_bc
  ^---- __z80asm__sbc_hl_bc
lib3d/isin.asm:23: error: undefined symbol: __z80asm__sbc_hl_de
  ^---- __z80asm__sbc_hl_de
lib3d/isin.asm:26: error: undefined symbol: __z80asm__sbc_hl_bc
  ^---- __z80asm__sbc_hl_bc
lib3d/isin.asm:41: error: undefined symbol: __z80asm__sbc_hl_de
  ^---- __z80asm__sbc_hl_de
lib3d/isin.asm:44: error: undefined symbol: __z80asm__sbc_hl_bc
  ^---- __z80asm__sbc_hl_bc
lib3d/isin.asm:63: error: undefined symbol: __z80asm__sbc_hl_de
  ^---- __z80asm__sbc_hl_de
`

**Comment by feilipu** [comment]
```
$ zcc +cpm -clib=8080 -create-app -lm -lgfxvti coswave.c
error: file not found: genmath_8080.lib

```
It could be made more intuitive, but genmath isn't 8080/85 supported. Try the Microsoft or Dai math libraries.

See the [Math Library Wiki](https://github.com/z88dk/z88dk/wiki/Classic--Maths-Libraries).

**Comment by suborb** [comment]
And the other errors are due to missing the z80asm libraries in lib/

**Comment by zx70** [comment]
Thank you sirs  :)
