### ISSUE TITLE
sms interrupt not work

### ISSUE THREAD

**Issue by moriyan6001** [z88dk/z88dk#253]
sms_crt0.asm
```
int_RASTER: 
    push    af 
    ld  a, ($BF) 
```
I think that it is "**in	a, ($BF)**" here.

*It is my first time to use issues, so I'm sorry if I used it wrong.

**Comment by aralbrec** [comment]
You're using it fine, this is what issues is for.

I see it now - this is in the classic library.  Thanks for reporting.
