### ISSUE TITLE
Thank you 🙂

### ISSUE THREAD

**Issue by AlexDev404** [z88dk/z88dk#2531]
Just wanted to extend my warm thanks to the maintainers working on this repository.
I'm currently working on an open-source Arduino board definition for the Z80 and Z8F082A (8/20/28 pin) and stumbled upon this very useful repository in search for a compiler.

Very amazed to see all the work you all put in and how well it compiles down into Z8 assembly.

Thanks once again for all of your hard work!
I'll make sure to put this it all into good use :)

**Comment by zx70** [comment]
You're welcome, let us know how your project is evolving, we have a forum too:   www.z88dk.org
