### ISSUE TITLE
ASSERT on Z80asm

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#2536]
I'm using 'assert' in assembly. It works, but I'd like to add a message explaining what's going on..
Is it feasible?

**Comment by dbolli** [comment]
Suggest this should only occur in -v verbose mode for brevity as normally assert just fails with an error message if the condition evaluates to false.

As per original [feature request](https://github.com/z88dk/z88dk/issues/1898) and [wiki doc page](https://github.com/z88dk/z88dk/wiki/Tool---z80asm---directives).

**Comment by pauloscustodio** [comment]
Solution: add string argument to ASSERT

```ASSERT expr, "message"```

now shows the message in the error if the expression is false.
