### ISSUE TITLE
[zx81][feature] WRX96 and/or WRX128 with centered display?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2545]
@zx70 
I have tried WRX64 and it is fast. It has two problems though:
1. the shown screen is obviously very small as expected
2. it only uses the top of the screen and not the center

Is there a way to center the display?

Given the speed gain, a better compromise between size and speed could be WRX96 and/or even WRX128.
Is it possible? Even better could the user chose the number of lines and the displayable screen vertical position?

Ideally a developer could choose which screen size provides the best compromise for them.

**Comment by zx70** [comment]
Moving the display at a lower position is not easy, it requires a properly calibrated delay on top (not as easy as it looks) and it would slow down the 64rows mode.

By the way I discovered I had left the space in the "-startup" options numberig for a 128 rows mode, it was left aside simply waiting for someone to explicitly ask for its implementation (and avoid a longer library build if useless) 🙈 

I just pulled in the wrx128 and arx128 modes (as usual a leading underscore will disable the HR picture persistence after the progam termination), it should be available in the 'nightly' repo tomorrow morning.
