### ISSUE TITLE
Unexpected z80asm macro formal parameter behavior?

### ISSUE THREAD

**Issue by ceharris** [z88dk/z88dk#2566]
I'm trying to write a macro that happens to include an expansion of another macro with formal parameters of the same name. 
Here's a simplified example of what I'm trying to do.

```
	macro setTOS x, y
	ld C, y
	ld B, x
	endm

	macro useSetTOS x, y
 	setTOS x, y
	endm


	org 0
	useSetTOS H, L
```
Assembling this example, I get these errors.
```
$ z88dk-z80asm macro-example1.asm
macro-example1.asm:13: error: undefined symbol: y
  ^---- y
macro-example1.asm:13: error: undefined symbol: x
  ^---- x
```

After experimenting a bit, I realized that if the formal parameter names used by the two macros are not the same, it works as expected, producing the expected machine code.
```
        macro setTOS x1, y1
        ld C, y1
        ld B, x1
        endm

        macro useSetTOS x, y
        setTOS x, y
        endm


        org 0
        useSetTOS H, L
```

Is the result from the first example above an expected behavior? It seems like an odd limitation, and it makes it difficult to convert code for other assemblers that apparently don't have this issue.

**Comment by suborb** [comment]
That does sound undesirable, I think @pauloscustodio is busy offline at the moment so please be patient!

**Comment by pauloscustodio** [comment]
Definitively a bug. I'll look into it.

**Comment by pauloscustodio** [comment]
Bug solved, thanks for reporting.

**Comment by ceharris** [comment]
Confirmed solved. Thanks for the quick turnaround!
