### ISSUE TITLE
Missing makefile.msd in msx examples

### ISSUE THREAD

**Issue by JensRestemeier** [z88dk/z88dk#2578]
The readme in https://github.com/z88dk/z88dk/tree/master/examples/msx promises a "makefile.msd" which doesn't seem to exist. I am not familiar with the history, if the readme is outdated or the makefile.msd got lost.

**Comment by suborb** [comment]
Thanks for the report. I think the README might be a little out of date - it's a lot easier to compile for msxdos than it was when it was written, so I've just removed the lines.
