### ISSUE TITLE
New MSX config for plain "bin" file.

### ISSUE THREAD

**Issue by JensRestemeier** [z88dk/z88dk#2579]
For my use case I required a plain binary that can be read with bload"",r , without being packaged into a disk image or cassette tape:
```
SUBTYPE		bin -Cz+msx -startup=1 -lndos
```
This adds a "bin" subtype that neither adds the --disk or --fmsx options.

**Comment by suborb** [comment]
Thanks, that's a sensible addition so I've added it.
