### ISSUE TITLE
CP/M File I/O Drops a Character Every 128 Bytes

### ISSUE THREAD

**Issue by jefftranter** [z88dk/z88dk#2588]
A simple test program that writes characters to a file shows that every 128th character is dropped.
Looking briefly at the code in z88dk/libsrc/target/cpm/fcntl/write.c, my suspicion is that the code waits until more than 128 bytes of data have been received before writing it out as a 128 byte sector, but it omits to write the character being written when the buffer became full.

**Comment by suborb** [comment]
Thanks for that, hopefully sorted now.

**Comment by jefftranter** [comment]
It is working now. Thanks!
