### ISSUE TITLE
Local labels getting assigned to wrong scope?

### ISSUE THREAD

**Issue by ceharris** [z88dk/z88dk#2599]
Consider this simple example:
```
foo:
	nop
@loop1:
	jp @loop1
@loop2:
	call bar
	jp @loop2

bar:
	ret
```

The label `@loop1` works as expected. However, the assembler complains about the second label:
```
demo1.asm:8: error: undefined symbol: bar@loop2
  ^---- bar@loop2
```

It seems to think the scope for `@loop2` is `bar`, not `foo`. 

Experimenting a bit, it seems to get confused by any non-local symbol referenced between the local label definition and a subsequent reference to the local label. For example:
```
FOOBAR = 1

foo:
@loop:
	ld a,(hl)
	cp FOOBAR
	inc hl
	jr nz,@loop
```

This results in a similar error.
```
demo2.asm:8: error: undefined symbol: FOOBAR@loop
  ^---- FOOBAR@loop
```

**Comment by ceharris** [comment]
Thanks for the quick fix, @pauloscustodio!  👍

**Comment by dbolli** [comment]
Agreed. Retested successfully in nightly build. Thanks @pauloscustodio 👍👋
