### ISSUE TITLE
[z88dk-z80asm]: allow different library file extensions than ".lib"

### ISSUE THREAD

**Issue by SvenMichaelKlose** [z88dk/z88dk#2606]
Unnecessarily limiting and confusing where it could have blended in easily (multi-compiler build set-up).

**Comment by pauloscustodio** [comment]
This is a legacy feature.

Question to the group: shall we change it to write library files with the name supplied without changing the extension to .lib? I suspect a great part of the tool chain will fail with this change.

**Comment by dbolli** [comment]
In my opinion library files should have a .lib extension for the same reason text files have a .txt extension and some image files have a .jpg extension.

**Comment by suborb** [comment]
Agree that they should have an extension. 

Maybe rules should be:

1. Use extension if provided. 
2. If no extension use .lib

Which works for creation.  

For usage the same rules could be applied.

**Comment by SvenMichaelKlose** [comment]
If that breaks builds: hell no! Was able to fix my build stuff quickly any way. Never mind.

**Comment by pauloscustodio** [comment]
The change is done in a branch and the CI is testing. Up to now everything is fine

**Comment by pauloscustodio** [comment]
Fixed and integrated. Thanks for reporting.
