### ISSUE TITLE
WYZ sound example seems to use a different format for effects than expected by the player

### ISSUE THREAD

**Issue by iratahack** [z88dk/z88dk#2609]
Playing music using the WYZ player works fine, but in the WYZ example application the sound effects do not seem to play correctly. It looks like the effects format may be different from what is expected by the player.

I couldn't find a way to export effects from WYZ tracker, any pointers to what was used to create effects.asm would be great.

**Comment by suborb** [comment]
It's a good question, I'm trying to figure out where I found the source. I have a feeling it was from a Spanish website, unfortunately both git and google are being very unhelpful.

The code looks broadly similar to upstream: https://github.com/AugustoRuiz/WYZPlayer/blob/main/original/FXPLAYER.ASM with an additional change to use the noise channel (which might be the bit causing trouble).

**Comment by suborb** [comment]
Forget all of that, it came in via this PR: https://github.com/z88dk/z88dk/pull/1430

**Comment by iratahack** [comment]
Great. I think I've got it updated now.

Is there a formatting standard used for C code?

**Comment by suborb** [comment]
> Is there a formatting standard used for C code?

Because it's a collection of tools with disparate histories there isn't a unifying standard. Generally it's 4 spaces rather tabs, and somewhere between K&R and 1TBS - function braces are on a separate line.

**Comment by iratahack** [comment]
> > Is there a formatting standard used for C code?
> 
> Because it's a collection of tools with disparate histories there isn't a unifying standard. Generally it's 4 spaces rather tabs, and somewhere between K&R and 1TBS - function braces are on a separate line.

Ah, ok. I made some updates to the sound sample apps but had the clang formatter enabled in VSCode so I need to go back and reformat them. Just hold off on that pull request. Also I'll close this issue.
