### ISSUE TITLE
No way to avoid automatic code replacement in z88dk-z80asm

### ISSUE THREAD

**Issue by BogdanTheGeek** [z88dk/z88dk#2621]
z80asm will replace invalid directives with valid code, without warning or an option to disable it.
```
cd0000            	sub hl, de
d511200019d1      	add hl, 32
```
I can see that it also links with `z88dk/lib/z88dk-z80asm.lib` by default, which is where I assume it find the symbol for that `sub` command.
`sjasmplus` does the same thing, but it does offer an option to get a warning when "fake" instructions are created with `--syntax=f`

**Comment by suborb** [comment]
See #2590
