### ISSUE TITLE
[hectorhr] RED color not shown (shown as black?)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2641]
On both the (emulated) Hector HR+ as well as the (emulated) Hector HRX, the RED color is not shown on my 9 games (I suppose it is shown as black). It should be shown as red or anything other than black. 
By the way the two Hector HR variants (HR+/HR2+ and HRX)  by default have different 4-color palettes but they both have red.

P.S.: Blue is shown as RED.
So I would suggest to map blue to green and red to red.

**Comment by suborb** [comment]
There's no mapping taking place, with the default palette we get this:

![image](https://github.com/user-attachments/assets/ac27039c-2400-44d7-b95c-27b7a4e4704f)

**Comment by Fabrizio-Caruso** [comment]
@suborb OK, no real problem. 
If I am not wrong, you also define macros for some integer values that "usually" do a reasonable mapping of the real colors.
In this very case: GREEN and WHITE are OK, BLACK not sure, RED goes to real BLACK, BLUE goes to real RED...
It is not a real issue indeed. I am using my own macros anyway.

**Comment by suborb** [comment]
With 4 colours, mapping is always going to be weird. I guess if we set up the palette to black, blue, red, white, then we could do this mapping:

* BLACK -> BLACK
* BLUE -> BLUE
* GREEN -> RED
* CYAN -> BLUE
* RED -> RED
* MAGENTA -> RED
* BROWN -> RED
* LIGHTGRAY -> WHITE
* DARKGRAY -> BLACK
* LIGHTBLUE -> BLUE
* LIGHTGREEN -> RED
* LIGHTCYAN -> BLUE
* LIGHTRED -> RED
* LIGHTMAGENTA -> RED
* YELLOW -> WHITE
* WHITE -> WHITE

Which is probably passable..

**Comment by suborb** [comment]
I've added in that mapping now (thanks for the poke) so you can remove your special magic!

**Comment by Fabrizio-Caruso** [comment]
I realize that any mapping done by constant values (I suppose macros) has a problem if it assumes it is using the default colors because the default colors are different on the HRX vs HR2+.

**Comment by suborb** [comment]
> I realize that any mapping done by constant values (I suppose macros) has a problem if it assumes it is using the default colors because the default colors are different on the HRX vs HR2+.

Yeah, the mapping goes hand-in-hand with having a "z88dk palette" which is setup on program start if gencon is used.
