### ISSUE TITLE
[m5][appmake][rom] Is appmake limiting rom size to 16kb instead of 20kb

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#2645]
I have been told (on the FB sord m5 group) that m5 can handle 20kb cartridges mapped at $2000-$6FFF.
Some of my games exceed the 16kb limit and would fit within 20kb.

appmake is enforcing a $2000-$5FFFF range (16kb):

```
rom: Embedded binary address range [8192,25875] exceeds ROM address range [8192,24575]
```

**Comment by suborb** [comment]
That’s on the config file: https://github.com/z88dk/z88dk/blob/9b164def8c4c395e8ac9c818aa0a83cbc42bbfd0/lib/config/m5.cfg#L18

change 16384 to 20480, report back on success and I’ll add a new rom20k subtype.

**Comment by suborb** [comment]
I guess this worked. So I've added -subtype=rom20k
