### ISSUE TITLE
stat() function always returns -1 on CP/M

### ISSUE THREAD

**Issue by jefftranter** [z88dk/z88dk#2649]
On the CP/M platform the function stat() in sys/stat.h always returns -1, making it unusable. The cause is this code in libsrc/target/cpm/fcntl/stat.c which calls the BDOS function CPM_CFS. According to the CP/M documentation on CP/M 2 the value returned has no meaning. Under CP/M 3 it returns $FF for error and 0 for success. I am using CP/M 2.2 and it fails in this case.

    /* Compute file size */
    if ( bdos(CPM_CFS,fc) != 0 ) {
               clearfcb(fc);
        return -1;
    }

See, for example, the documentation for BDOS function 35 (F_SIZE) at https://www.seasip.info/Cpm/bdos.html

A fix which works for me is to replace the above lines with simply:

    /* Compute file size */
    bdos(CPM_CFS,fc);

**Comment by suborb** [comment]
That seems like a sensible change if we've got those conditions - thank you.
