### ISSUE TITLE
sccz80: not calling ifix when casting float to integer

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#265]
Test program:

```
#pragma printf = "%f %d"

#include <stdio.h>

void main()
{
        volatile float x0, r, ux, tmp;

        x0 = 127.5;
        r = -1.587451;
        ux = 79.6875;

	printf("x0 = %f\n r = %f\nux = %f\n", x0, r, ux); 
	tmp = 0.001+x0+r*ux;
	printf("0.001+x0+r*ux = %f\n", tmp);
        printf("cast = %d (expected: 1)\n", (int)(tmp));
        printf("cast = %d (expected: 1)\n", (int)(0.001+x0+r*ux));
}
```

zcc +zx -vn test.c -o test.bin -lndos -lm -create-app --list --c-code-in-asm

When running, the last printf is incorrectly printing a value of "-27166".  A look at the source code generated and you can see there is no ifix call to cast the float in the printf to integer before it's pushed on the stack for the printf call.  The ifix call is there for the cast of tmp on the previous statement but if you turn tmp into an integer and do a calculation like `tmp = (int)(0.001+x0+r*ux);` the call to ifix will again be omitted.

**Comment by suborb** [comment]
Fixed by above commit
