### ISSUE TITLE
sccz80: floating point exception generated for test program

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#272]
```
#include <stdio.h>

#define FLOATCONST1 36.0
#define FLOATCONST2 0.5

void main()
{
        int x;

        x = (int) (FLOATCONST1 / FLOATCONST2);
        printf("x = %d (expected: 72)\n", x);
}
```

zcc +zx -vn -lndos -lmath48 -create-app --list --c-code-in-asm test.c -o test.bin

It seems to be the division by the constant 0.5 that causes the problem.  It could be the compiler is only parsing the "0" part of "0.5".

**Comment by suborb** [comment]
For some reason it was evaluating that constant expression using ints, so ended up with a division by zero.

**Comment by aralbrec** [comment]
Also looks resolved.
