### ISSUE TITLE
sccz80: special function registers not allowed to start with the letter S

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#275]
Yes you read that right :)

Special function registers cannot start with the letter 'S'

```
#include <stdlib.h>

__sfr __banked __at 254 SINCLAIR_ZX_SPECTRUM_BORDER;

int main(int argc, char *argv[])
{
        SINCLAIR_ZX_SPECTRUM_BORDER = 2;
        return 0;
}
```

zcc +zx -vn -lndos -create-app --list --c-code-in-asm test.c -o test.bin

Result:
```
sccz80:"zzz.c" L:7 Error:#42:Unknown symbol: SINCLAIR_ZX_SPECTRUM_BORDER
Compilation aborted
```

Change the name to anything that doesn't start with 'S' and it works fine.

**Comment by suborb** [comment]
Ah, it's a greedy matching for 'S' for signed. The same problem exists
with 'L' and 'U'.
On Mon, 3 Jul 2017, at 10:30 PM, aralbrec wrote:
> Yes you read that right :)


> Special function registers cannot start with the letter 'S'


> [code]
>  #include <stdlib.h>


> __sfr __banked __at 254 SINCLAIR_ZX_SPECTRUM_BORDER;


> int main(int argc, char *argv[])
>  {
>  SINCLAIR_ZX_SPECTRUM_BORDER = 2;
>  return 0;
>  }
>  [/code]


> zcc +zx -vn -lndos -create-app --list --c-code-in-asm test.c -o
> test.bin> Result:


> sccz80:"zzz.c" L:7 Error:#42:Unknown symbol:
> SINCLAIR_ZX_SPECTRUM_BORDER Compilation aborted
>> Change the name to anything that doesn't start with 'S' and it
> works fine.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/z88dk/z88dk/issues/275

**Comment by aralbrec** [comment]
I tried A-H and found they worked so stopped there and decided only S was a problem.  Only a little ways to go to L and I could probably have figured it out :)

Looks like things are working.
