### ISSUE TITLE
Cannot run/load my game MSX even with trivial main()

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#299]
I am trying to port my game
https://github.com/Fabrizio-Caruso/ASCII-CHASE/
to the msx target but I am not able to get it to start/load.

My game is "successfully" compiled with
zcc +msx -vn -D__MSX__ -DAMALLOC -lmalloc -lndos -create-app -o %deliverables%\msx_experimental.prg  <c files>

The compiled executable is about 20k.

If I try to load it with
bload"cas:",r

the result is always that the emulator gets stuck while loading and a "à" character appears on the screen
no matter which  emulator (bluemsx, fmsx), no matter which msx model and no matter how much RAM used in the emulators.

I can even put a trivial main file (test working if I do not include the rest of the code) such as:

int main()
{
    puts("\x16\x0A\x0C" "Hello, world!");   
    return 0;
}

(or something equivalent that works correctly if compiled alone) and I get similar problems.

So maybe the size of the executable (about 20k) is a problem 
(the emulators have been set with enough RAM).
Do I need to use some special options or configurations?

Remark: The game compiles and works fine with other targets (Spectrum and all CC65 targets).

  Fabrizio

**Comment by zx70** [comment]
AMALLOC is the lazy way to use malloc, it leaves a fixed percentage of the remaining space for stack and the remaining slice for malloc.  Honestly I don't remember if the msx version is smart enough to tune correctly the pointers in both msxdos and basic mode.
The malloc heap can be manually tuned but it can be tricky for beginners.

**Comment by Fabrizio-Caruso** [comment]
@zx70, could you please point me to a reference?
How should I configure the malloc heap to get it to work with the msx target?

**Comment by zx70** [comment]
https://www.z88dk.org/wiki/doku.php?id=library:memory_allocation#multiple_named_heap_malloc_library_malloc.h

I am not sure that malloc is your problem, btw you should first look at an msxbasic memory map, and see if you have enough free memory.

**Comment by zx70** [comment]
https://www.z88dk.org/wiki/doku.php?id=library:memory_allocation#multiple_named_heap_malloc_library_malloc.h

I am not sure that malloc is your problem, btw you should first look at an msxbasic memory map, and see if you have enough free memory.

**Comment by Fabrizio-Caruso** [comment]
My game takes up 20k in total and I am only allocating a few bytes.
The emulator is set up with plenty of memory.

**Comment by Fabrizio-Caruso** [comment]
My game takes up 20k in total and I am only allocating a few bytes.
The emulator is set up with plenty of memory.

No issue with other Z88DK targets (Spectrum and even VG 5000)
as well as all CC65 targets.

**Comment by Fabrizio-Caruso** [comment]
My game takes up 20k in total and I am only allocating a few bytes.
The emulator is set up with plenty of memory.

No issue with other Z88DK targets (Spectrum, CPC and even VG 5000)
as well as all CC65 targets.

**Comment by aralbrec** [comment]
I'm not too familiar with the msx target but the other thing you could do is make a cartridge.  That will give you 16k of code space and 16k of ram for variables.

**Comment by zx70** [comment]
#323 is taking care of the same topic, this is redundant
