### ISSUE TITLE
github: create a place to download windows and osx binaries from?

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#30]
For people who are using github rather than downloading the nightly packages should we be offering a place to download the windows and osx binaries from?

We have the nightly builds to pick up quick up-to-date packages but for people using git we will need some simple instructions and a way to get z88dk running.  I also made sure all the library binaries were committed for that purpose - maybe we can get the nightly build to update those as well?

**Comment by suborb** [comment]
I'd prefer not to have any auto-commits going on, especially not on binary files.

Perhaps the easiest is to clone and also download the nightly. The binaries can then be extracted from the nightly and put into place?

**Comment by pauloscustodio** [comment]
I would prefer to not have any binaries in the z88dk git repository. We can keep the nightly builds as now, and just add a URL to the README at the top of the repository.

I also do not like to have the z80 libraries committed to git - they can be generated from source and appear to git status always as modified, cluttering the development environment. Can we store a them together with the binaries and add a URL to the README also?

**Comment by aralbrec** [comment]
Ok let's remove that stuff but we'll have to add a simple write-up in the readme at the same time.

**Comment by aralbrec** [comment]
Have a look at the new readme.  Once some brief instructions for a github install are added I think we can get rid of all z80 binaries in the repository.

**Comment by suborb** [comment]
The readme looks good, lets kill the libraries.

**Comment by aralbrec** [comment]
It looks like that might wipe out your local copies of the libs.  You may have to re-acquire them as detailed on front page.
