### ISSUE TITLE
Odd newlib fgetpos.asm stack handling.

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#310]
Just noticed some odd stack handling in [szcc80](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/stdio/c/sccz80/fgetpos.asm#L23) and [sdcc_iy](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/stdio/c/sdcc_iy/fgetpos.asm#L24) for `fgetpos.asm`.

Seems to be different handling to the sdcc_ix mechanism, which has a mirrored (normal) stack `pop` and `push`.

Not sure if it is a bug, but flagged just in case.

**Comment by aralbrec** [comment]
That's deliberate.  Pushing/popping ix and iy adds 4 cycles and 1 byte.  As parameters are passed by value, once the right values are read there's no obligation to keep the values on the stack the same.
