### ISSUE TITLE
newlib: do a better job of mangling ifdef guards in header files

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#318]
A recent bug report has reminded that users may create header files of the same name as system header files.

The if-guards we are using are way too similar to what users may use for their own header files of the same name and it's possible they may define the same ones.

So we need to go in there and mangle them up some more.

**Comment by pauloscustodio** [comment]
Why not implement ```#pragma once```? It is supported by gcc, clang and msc and seams to be almost standard.

**Comment by aralbrec** [comment]
`#pragma once` is in zsdcpp but missing from zcpp.
