### ISSUE TITLE
z80asm: define macro naming the CPU used in the --cpu= option

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#320]
z80asm should predefine a macro to allow the code to ```IF``` around a block depending on the processor.

I'm thinking about defining ```__CPU_Z80__```, ```__CPU_Z80_ZXN__```, ```__CPU_Z180__```, ```__CPU_R2K__``` and ```__CPU_R3K__```.

Any opinions?

**Comment by suborb** [comment]
__CPU_Z80_Z180 etc feels a bit weird, maybe drop the _Z80_ bit?

**Comment by pauloscustodio** [comment]
Of course, agreed

**Comment by pauloscustodio** [comment]
Define one of the following constants, depending on the --cpu=xxx option:
```
__CPU_Z80__
__CPU_Z80_ZXN__
__CPU_Z180__
__CPU_R2K__
__CPU_R3K__
```
