### ISSUE TITLE
Appmake (-create-app option) broken in Aquarius

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#328]
It seems to me that there is no way to get the -create-app option to work with the Aquarius target.

For example none of the compile commands in
https://www.z88dk.org/wiki/doku.php?id=platform:aquarius
work.

You can build the .prg binary (which cannot be used) but
you always get the same error message:
"
Can't create the loader file
Building application code failed
"

**Comment by zx70** [comment]
Support given directly,  the problem seems to be consequence of invalid characters in the file name.  I suspect the current binary isn't able to handle the window's system variables when in %betweenpercentsymbols% form.
