### ISSUE TITLE
Are the rcmx_cpi & friends needed in the library?

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#359]
z80asm now includes the emulation libraries for CPI, CPIR, CPD and CPDR at the link phase if assembling for a Rabbit.

The source of these libraries is in src/z80asm/dev/z80asm_lib and they are deployed to the lib/ directory during install

I've found and fixed a bug in the output of the H and N flags in the CPIR and CPDR routines in commit c2bcbbfe389cca9c3d89d9605cf1bcb06c9c4756 

Should I update the copies in libsrc/z80_crt0s/z80_emu, or remove them and keep them only in the z80asm source tree?

**Comment by aralbrec** [comment]
z80asm will link these replacements last so it will be possible for the user or library to override them?

**Comment by suborb** [comment]
I think I adjusted all references to them to the z80asm version, but forgot to remove the rcmx versions. So they can go.

**Comment by pauloscustodio** [comment]
Yes, z80asm will search the z80asm-{cpu}-{ixiy}.lib last, allowing the user to override the __z80asm__xxx functions.
