### ISSUE TITLE
How to run a simple hello world on SVI target? I followed the instructions but no program is run.

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#362]
I am following the instructions in

https://github.com/z88dk/z88dk/wiki/Platform---Spectravideo

I can compile a simple hello world
```
#include <stdio.h>
int main()
{
	printf("Hello world\n");	
	while(1){}	
	return 0;
}
```
with 
zcc +svi  -vn -lndos -create-app -subtype=wav -o  %deliverables%\MINIMAL_svi %mypath%\test_a5200.c

Then I use BluMSX (correctly set as a SVI emulator) and use the suggested load command
bload"cas:",r

which loads and goes to the prompt command but nothing happens.

"run" or "list" have no effect.

**Comment by Fabrizio-Caruso** [comment]
Please close this as non-issue. I think I was doing something stupid.
Sorry for the inconvenience.
I may open a different SVI-related issue (cursor shown while displaying characters).

**Comment by zx70** [comment]
closing
