### ISSUE TITLE
_sc_cursor_pos already defined error in M5 and SC3000 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#364]
While trying to make my "universal" game work with the M5 and SC3000 I am getting the following error
"
symbol '_sc_cursor_pos' already defined in module 'C__Users_Brizio_Retro_ASCII_CHASE_merged_display_macros
"
I get no similar conio-related error with other targets.

In my code I include conio.h only in one header (display_macros.h) file which is protected from re-definitions by an #ifndef directive.

I do not understand why this symbol (only found in M5 and SC3000 conio.h) is causing a problem (and no the other symbols in conio.h).

**Comment by suborb** [comment]
See: https://github.com/z88dk/z88dk/commit/6287fb44e35f685ca5e577c22854413ada5fafa2#diff-92717702464f42f245313a5988b52a78 

I'll sort this out in the next couple of days.

**Comment by zx70** [comment]
Thanks for pointing it out, Dom.

**Comment by Fabrizio-Caruso** [comment]
Problem while compiling for the SORD M5:
PROCESSING CRT
z80asm   -s  --cpu=z80 -I"c:/z88dk//lib" -I"c:/z88dk/\lib"  "C:\Users\fcaruso\AppData\Local\Temp\zcc
638412.asm"
Error at file 'C:\Users\fcaruso\AppData\Local\Temp\zcc638412.asm' line 115: syntax error
1 errors occurred during assembly
Errors in source file c:/z88dk/\lib\m5_crt0.asm:
Error at file 'C:\Users\fcaruso\AppData\Local\Temp\zcc638412.asm' line 115: syntax error
                   ^ ---- _sc_cursor_pos        defw    0x70a6

**Comment by suborb** [comment]
Sorry, I thought I'd tested the m5 as well as sc3000.

It's missing a colon after pos on the highlighted line - if you just temporarily do it, I'll commit a change this evening.

**Comment by Fabrizio-Caruso** [comment]
No worries. I can wait for your commit and use tomorrow's snapshot.
