### ISSUE TITLE
Getk in Aquarius not detecting key releases

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#368]
It seems to me that the previously reported issue of the getk() function for the Aquarius target may come from that fact that it does not detect key releases: keeping the key pressed or even just pressing the same key twice is not detected.

**Comment by zx70** [comment]
I rewrote getk(), please let me know.

**Comment by Fabrizio-Caruso** [comment]
THANKS a lot! I will test it asap and let you know.

**Comment by Fabrizio-Caruso** [comment]
Problem fixed! Thanks a lot!!

**Comment by suborb** [comment]
I've just added inkey() and friends for the aquarius so you should now be able to handle multiple keypresses
