### ISSUE TITLE
Classic libsrc changes

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#380]
Classic libsrc has grown a bit and we've got extra libraries where we probably don't need them and duplicated code with newlib. So lets do some rationalisation.

Phase 1:

Reduce duplication:
* [x] Switch over to using newlib string functions
* [x] Remove stdio_new (it's confusing being there)
* [x] Pull in errno.h from newlib

Fold into core libraries:
* [x] Fold balloc 
* [x] Fold algorithm
* [x] Fold adt 
* [x] Fold debug 
* [x] Fold rect

Phase 2:

Not all of these will be done:

* [x] Use newlib ctype functions (the code is the same)
* [x] Use newlib stdlib functions
* [x] Switch to newlib adt
* [x] Use newlib balloc
* [x] Import newlib obstack
* [ ] ~Switch malloc to newlib allocation (assuming compatible/drop in)~ (see #113)
* [x] Create a fast integer math library that can be switched in

Phase sometime:

Sort out shared directories:

* [x] MSX
* [x] PSG
* [x] Graphics
* [x] Sound

Despite pulling in newlib, classic will still support compiling with sdcc with a single library and mixing of compiled code (with the floating point, char caveats)

**Comment by suborb** [comment]
Some notes (work continuing on Phase 2 in feature/classic_reorg_phase2 branch)

newlib adt depends on malloc (not u_malloc/u_free). Without switching classic allocation, we'll need to provide asm_realloc, asm_free to bridge to classic heap.

Additionally, the API is named differently. For compatibility we should introduce defc wrappers.

Balloc is automatically initialised with newlib. For compatibility we should provide the old method for classic as well as defc wrappers.

**Comment by zx70** [comment]
I am on the msx lib for other reason,  hope not to collide

**Comment by suborb** [comment]
I ended up getting distracted by sccz80 rather than sorting out the msx, psg directories, so you shouldn't be clashing!

**Comment by suborb** [comment]
e8f154c5c191605a56c961ee06308bb598ca6314 did stdlib (wrong issue number)
