### ISSUE TITLE
travis:  build errors due to no c99

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#382]
Half the builds by travis are failing because c99 mode is not enabled:

```
appmake.c:1228:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int i = 0; i < aligned->num; ++i)
```

Are we sticking to that?  Should I hoist those declarations to the top of a block?

**Comment by pauloscustodio** [comment]
I've moved z80asm to --std=gnu11
