### ISSUE TITLE
how to trap an existing function?

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#384]
What is the cleanest way for a programmer to trap an existing function (or portion)?
I'd like to suggest to disable the ansi scrollup functionality by simply trap the ANSI_scroll entry and replace it with a do_nothing one.

**Comment by suborb** [comment]
Use the same trick as is used for fputc_cons

**Comment by aralbrec** [comment]
The library functions are linked last so if the user provides a different version it will be used instead.

**Comment by zx70** [comment]
Thanks, I'll first try to prevent the scroll event to happen too soon, in case of trobles I have your hints.
A further possibility is to add a flag in the ansi engine and permit programs to enable/disable the scroll at runtime, but it sounds a bit useless.
