### ISSUE TITLE
classiclib: Investigate removing lib/*.opt files

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#39]
These were used to include the correct crt0 file when optimisation was turned on.

Now that optimised files are written to .asm they may not be necessary.

**Comment by aralbrec** [comment]
I don't think it's needed either.  If you remove it, there is code in zcc::copy_crt0_to_temp() that prefers the .asm to the .opt if it's found.  I wasn't sure what to do with that at the time.
