### ISSUE TITLE
Latest snapshot breaks CPC: blank screen at startup

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#395]
The code works but nothing is shown on the screen.

I  have tested it with both color and no color version of my game for the CPC.

**Comment by zx70** [comment]
It it resolved now?

**Comment by zx70** [comment]
I'm keeping the issue open because the snakes.c game is not visible.. colour problems.?

**Comment by zx70** [comment]
First small portion of cpcrslib is now merged in the current classic library.  Using the standard library edition is still possible,  the only conflict is in cpc.h, which had very few functions useful in conjunction with cpcrslib.  The high resolution graphics is now working at a full 640x200 monochrome resolution with an almost full coverage of the function list (it was 256x200 sometimes, 320x200 for other rom based stuff with limited coverage of the whole library).  Cp/m variant and greylib will require a serious reassessment,  but the new stuff worths the changes.

**Comment by zx70** [comment]
Fonts and non-tile-based sprites are now in.   In the latest commit I'm also correcting a bug on the font color settings, which was also compromising the code stability.

**Comment by zx70** [comment]
640x200 monochrome mode is now fully operational and respectably fast, I think *all* the graphics demos will be in working order by tomorrow morning.   
The CPCRSLIB is not totally included yet, the tile mode graphics have been improved in the years and there are two different, slightly incompatible versions around.  The code structure for 'tiles' could be kicked approaching it like we did with the ANSI VT options, I'm taking some time to think at it.
By the way, the current CPCRSLIB imported portion is now in a brand new, shiny shape.

**Comment by zx70** [comment]
lots of open points already,  the original claim is solved and the library is now reasonably extended and cleaned..     I still need to check the status of the cp/m version of the libraries, so I keep the issue open

**Comment by zx70** [comment]
I recently removed the 'startup=2' option  from the default cpc configuration. I couldn't succeed in running the graphics programs otherwise.    please advise if you find problems after this
