### ISSUE TITLE
library make failing on mingw

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#409]
Recent changes make my (very personal and bugged) mingw installation fail:

--- Building Z88 Library ---

C:/MinGW/bin/make gfxdeps
make[1]: Entering directory 'c:/z88dk/libsrc'
make[1]: Leaving directory 'c:/z88dk/libsrc'
C:/MinGW/bin/make -C ctype
make[1]: Entering directory 'c:/z88dk/libsrc/ctype'
process_begin: CreateProcess(NULL, z88dk-lstmanip -i c:/z88dk/libsrc//_DEVELOPMENT//ctype/ctype_sccz80.lst -p c:/z88dk/libsrc//_DEVELOPMENT/ -t, ...) failed.
make[1]: Makefile:14: pipe: No error
mkdir: missing operand
Try `mkdir --help' for more information.
make[1]: *** [Makefile:72: dirs] Error 1
make[1]: Leaving directory 'c:/z88dk/libsrc/ctype'
make: *** [Makefile:198: z88_clib.lib] Error 2
bash-3.1$

**Comment by suborb** [comment]
Dumb question: z88dk-lstmanip is compiled and in the path?

**Comment by zx70** [comment]
You are right, sorry   😊
