### ISSUE TITLE
sccz80: possible to introduce extern function declaration in block scope?

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#419]
One specific example I'm doing now with zsdcc:

```
void main(void)
{
{ extern void ZXN_NEXTREG_0x50(unsigned char) __preserves_regs(a,b,c,d,e,h,l,iyl,iyh) __z88dk_fastcall; ZXN_NEXTREG_0x50(a); };
```

The declaration of the function gives register preservation information and the invoke immediately follows.  This block is generated by a macro that is encoding a specific numerical register in the function name and is accepting a single parameter via z80 register (fastcall).

Post-processing then inlines assembly instructions to replace the function call generated by the compiler.

This particular code sequence is effectively inlining a `nextreg 0x50,variable` instruction.

I can't do the same with sccz80.  The function declaration is illegal within the block and although I can rely on K&R and just call some function in the C code like this `ZXN_NEXTREG_0x50(a);` I can't make the function fastcall or control the types so it's much less efficient.

**Comment by suborb** [comment]
I think I removed this feature earlier this year when I was adding the sdcc compatible function decorators.

I'll have a look at restoring it.
