### ISSUE TITLE
putsprite failing on msx (bluemsx)

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#427]
putsprite is oddly failing on the msx target,  garbled areas are filled, looks like the sprite data pointers are lost.
The same code works well on other targets (eg Spectravideo SVI)

**Comment by zx70** [comment]
I forgot to mention that the video access sequence is mostly working, eg. Chessboard.c draws the board then fails on putting the pieces on it.

**Comment by zx70** [comment]
I don't know if this is related to the same problem but I observed that the data stored in the "bss_clib" section is lost (set to 0) on the SVI target, but it is correctly loaded on the MSX.
Declaring it under "data_clib" would eventually solve also for the SVI.

**Comment by suborb** [comment]
Anything that's in bss_clib will be cleared on startup so that makes sense. Which data is misplaced?

**Comment by zx70** [comment]
They were two different situations,  but spotting the bss declarations to check possible misuses is an easy task,  thanks for the hint.

**Comment by zx70** [comment]
I think I'm hitting something serious on z80asm, I'm investigating to reduce the affected code and get a simpler test case.

**Comment by zx70** [comment]
I discovered that the "serious" stability problems are again connected to the sections.
I just updated {z88dk}/libsrc/stdio/ansi/msx/f_ansi_char.asm (mostly declared as smc_clib SECTION).
To get stable results on all the involved targets I had to comment out the "section" declaration in the file bottom:
;	SECTION bss_clib	
.chline_buffer
	defs 2

On the MTX target it had the very strange effect to alter the value of the parameter passed by  {z88dk}/libsrc/stdio/ansi/msx/f_ansi_attr.asm:
        SECTION data_clib
	PUBLIC	msx_attr
.msx_attr			defb $F1	; White on Black

Oddly commenting out the section declaration above seems to avoid the problem.

**Comment by zx70** [comment]
..could it be that on some target the data_clib and the bss_clib sections are overlapped ?

**Comment by suborb** [comment]
Have you got an example that I can compile and look at the .map file of?

For RAM compiles, the order is rodata, smc, data, bss, for ROM it's rodata (in ROM), then in RAM bss, smc, data.

**Comment by zx70** [comment]
ansitest.c:
zcc +mtx -subtype=mtx -lndos -create-app -clib=ansi  -startup=2 -pragma-define:ansicolumns=64 -Ca--map ansitest.c
I will try it too, but first the commented out section declaration must be restored.

**Comment by zx70** [comment]
__sgoioblk                      = $598D ; addr, public, , mtx_crt0, bss_crt, ../crt0_section.asm:133
__sgoioblk_end               = $59C9 ; addr, public, , mtx_crt0, bss_crt, ../crt0_section.asm:134

msx_attr                        = $598A ; addr, public, , f_ansi_attr, data_clib, stdio/ansi/msx/f_ansi_attr.asm:162

_errno                            = $598B ; addr, public, , _errno, bss_error, .....z80/_errno.asm:7

__smc_clib_tail                 = $598A ; const, public, def, , ,
__smc_user_head                 = $598A ; const, public, def, , ,
__smc_user_tail                 = $598A ; const, public, def, , ,
__data_clib_head                = $598A ; const, public, def, , ,

__data_clib_tail                = $598B ; const, public, def, , ,
__data_crt_head                 = $598B ; const, public, def, , ,
__data_crt_tail                 = $598B ; const, public, def, , ,
__data_compiler_head            = $598B ; const, public, def, , ,
__data_compiler_tail            = $598B ; const, public, def, , ,
__data_user_head                = $598B ; const, public, def, , ,
__data_user_tail                = $598B ; const, public, def, , ,
(...)

**Comment by suborb** [comment]
Maybe I'm getting something different from you - I'm using memu.

Regardless of where the msx_attr variable is located, nastiest runs correctly, but on exit ends up with a whole bunch of gibberish being output to the screen.

**Comment by zx70** [comment]
Ok,  it is now clear that removing BSS section declaration was simply permitting the last defs to be part of the SMC section and act as a workaround.

A fully functioning workaround:

Section smc_clib
(...)
nop
nop
SECTION bss_clib
.chline_buffer
defs 2

**Comment by zx70** [comment]
I'm now investigating the putsprite problem on the msx target in a similar way.

**Comment by zx70** [comment]
I use memu too, better to Clean up my current z88dk tree and work on a cleaner release

**Comment by zx70** [comment]
Ansitest clearly failed, here..

**Comment by zx70** [comment]
Example taken from clock.c
======================

Sprite data position  on MSX:
_roman_nums                     = $AFCE ; addr, public, , clock, data_compiler, clock.c:18
__rodata_clib_tail              = $AFCE ; const, public, def, , ,
__rodata_user_head              = $AFCE ; const, public, def, , ,
__rodata_user_tail              = $AFCE ; const, public, def, , ,
__rodata_font_head              = $AFCE ; const, public, def, , ,
__rodata_font_tail              = $AFCE ; const, public, def, , ,
(...)
__data_clib_head                = $AFCE ; const, public, def, , ,
__data_clib_tail                = $AFCE ; const, public, def, , ,
__data_clib_size                = $0000 ; const, public, def, , ,
__data_crt_head                 = $AFCE ; const, public, def, , ,
__data_crt_tail                 = $AFCE ; const, public, def, , ,
__data_crt_size                 = $0000 ; const, public, def, , ,
__data_compiler_head            = $AFCE ; const, public, def, , ,

Sprite data on SVI:
exitsp                          = $9B9A ; addr, public, , svi_crt0, bss_crt, c:/z88dk/lib/config\..\..\/lib/crt0_section.asm:142
exitcount                       = $9B9C ; addr, public, , svi_crt0, bss_crt, c:/z88dk/lib/config\..\..\/lib/crt0_section.asm:143
_roman_nums                     = $9A95 ; addr, public, , clock, data_compiler, clock.c:18
_x                              = $9B9D ; addr, public, , clock, bss_compiler, clock.c:1290
_y                              = $9B9F ; addr, public, , clock, bss_compiler, clock.c:1291

__smc_user_head                 = $9A93 ; const, public, def, , ,
__smc_user_tail                 = $9A93 ; const, public, def, , ,
__smc_user_size                 = $0000 ; const, public, def, , ,
__data_clib_head                = $9A93 ; const, public, def, , ,
__data_clib_tail                = $9A95 ; const, public, def, , ,
__data_clib_size                = $0002 ; const, public, def, , ,
__data_crt_head                 = $9A95 ; const, public, def, , ,
__data_crt_tail                 = $9A95 ; const, public, def, , ,
__data_crt_size                 = $0000 ; const, public, def, , ,

**Comment by zx70** [comment]
On the SVI the different data_clib_size may be saving it from crashing?

**Comment by aralbrec** [comment]
Got some bugs in compiles from the recent sccz80 changes too, maybe check on that as well.

**Comment by suborb** [comment]
On the MSX it seems to use graphics/putsprite2 but on the svi it's graphics/msx/putsprite is that right?

**Comment by suborb** [comment]
> Got some bugs in compiles from the recent sccz80 changes too, maybe check on that as well.

Can you let me know what they are and I'll fix them up/get some testcases in there.

**Comment by aralbrec** [comment]
I've opened a couple of issues

**Comment by zx70** [comment]
Dom, I found the putsprite2 error only this morning and then I saw your comment.    Yes,  it is the wrong file, I must have forgotten it in the list after some experiment, sorry !   :(

**Comment by zx70** [comment]
I'll play a bit more around te mtx before closing the issue,  but I must thank you for the support!

**Comment by zx70** [comment]
I'm taking too long with my extra experiments on the MTX and the bug connected to this topic is now solved,  I can open another issue if refreshing my z88dk copy won't help.
