### ISSUE TITLE
z80asm doesn't expand @ lines in .lst files

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#440]
I'm trying to come up with alternate ways of classic including newlib that don't use z88dk-lstmanip and allow reuse of the .lst files.

It seems that if an @ line is hit, then expand_environment_variables() isn't called, so I think after options.c:312 there needs to be a `filename = expand_environment_variables(filename);` 

Adding this in means that I can run a z80asm on a newlib lst file from classic and pick up the object files. 

Some other thoughts:

* I'm also wondering if I need to specify an output directory where object files are placed when assembling - this way I could do a -O obj/z80 and all the object files end up in that directory.
* Supporting globbing in .lst files would be great as well, that way I can have  a .lst file with obj/z80/*

**Comment by pauloscustodio** [comment]
> It seems that if an @ line is hit, then expand_environment_variables() isn't called, so I think after options.c:312 there needs to be a filename = expand_environment_variables(filename);

You're right. I'll build it in

> I'm also wondering if I need to specify an output directory where object files are placed when assembling - this way I could do a -O obj/z80 and all the object files end up in that directory.

Good idea. I need to check the implications as a lot of code is based on obj-file = asm-file-with-.o.  

Also: shall any relative path be discarded, or appended to the -O root? i.e. ```z80asm -O obj/z80 ctype/io.asm``` builds obj/z80/ctype/io.asm, or obj/z80/io.asm? - I think the first is more intuitive, but it may cause issues if an absolute path is given.

I've created #441 to follow this issue.

> Supporting globbing in .lst files would be great as well, that way I can have a .lst file with obj/z80/*

Good idea. I've created a new issue #442 . Do we have a globbing routine somewhere in z88dk, for the Win32 mortals that I could borrow?
