### ISSUE TITLE
z80asm: add command line option for specifying the output directory

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#441]
See #440

**Comment by suborb** [comment]
> Good idea. I need to check the implications as a lot of code is based on obj-file = asm-file-with-.o.

> Also: shall any relative path be discarded, or appended to the -O root? i.e. z80asm -O obj/z80 ctype/io.asm builds obj/z80/ctype/io.asm, or obj/z80/io.asm? - I think the first is more intuitive, but it may cause issues if an absolute path is given.

An example of how I'd use it is from the classic string directory:  `z80asm -O obj/z80 --cpu=z80 ../_DEVELOPMENT/string/string_sccz80.lst` where paths in the lst file are relative from ../_DEVELOPMENT/ 

In this case it's easier if the files are flattened, but in the generalised case this is wrong behaviour and will produce unexpected results if two files are named the same.

On the other hand, if we do include the directory tree then there are a couple of implications:

* z80asm has to create the directory tree inside the output directory
* The glob feature (#442) will have to support `**/*` 

The hybrid approach is of course to flatten the directory path into the output filename (e.g. strings_c_sccz80_strcmp.o), but then we run into max filename length issues on windows.

My sense of correctness leads me to think that the directory tree should be created within the output directory, though of course that does entail more work unfortunately.
