### ISSUE TITLE
z80asm: support globbing in command line and list files

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#442]
See #440

**Comment by suborb** [comment]
> Good idea. I've created a new issue #442 . Do we have a globbing routine somewhere in z88dk, for the Win32 mortals that I could borrow?

I think mingw supports glob.h. For Visual Studio we've got opendir and friends. In the past I've used unixem which is under a very permissive licence.

However, in #441 there's a discussion about a directory tree, in which case we need to support `**/*` and I'm not sure that the standard glob.h (on mingw or *nix) supports this globstar feature.
