### ISSUE TITLE
sleep function for newlib and zsdcc?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#446]
Is there a sleep function in newlib?

I have tried to implement it with an empty for loop with a volatile loop variable but the compiler optimizes it.

**Comment by aralbrec** [comment]
Yes sleep-like functions can be found in [z80.h](https://github.com/z88dk/z88dk/blob/master/include/_DEVELOPMENT/sdcc/z80.h):

```
extern void z80_delay_ms(uint16_t ms);   // delay in milliseconds
extern void z80_delay_tstate(uint16_t tstates);   // delay in cpu cycles
```

The minimum delay is 141T which is 0.035 milliseconds @ 4MHz.

**Comment by zx70** [comment]
It works also in classic mode,  I think
