### ISSUE TITLE
[INFO] How to compile for Spectrum 16k?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#451]
How to compile for Spectrum 16k?

It seems that my executable in its light version ( for the Spectrum does not work on the 16k model.
So I wonder whether it has to be compiled differently. Maybe it should be located in a different area in ram.

**Comment by zx70** [comment]
You should lower the ramptop.  Try with -zorg=24700,  you can't go lower than 24580, nor over 32768, I'm sorry but you have only 8k of program space on a 16k spectrum.

**Comment by Fabrizio-Caruso** [comment]
Thanks! :-( I need 11k... Maybe for the next game!
