### ISSUE TITLE
Question - relocate/remove CRT0 l_ code fragments?

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#461]
There are multiple [`l_do_something`](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/target/crt_page_zero_z80.inc#L333) code fragments in the `crt_page_zero_z180.inc`, and `crt_page_zero_z80.inc`.

These code fragments are also defined in the [l library section](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/l/z80/l_setmem_hl.asm).

Can the code fragments (all of them) be removed from a CRT0 initialisation, to allow space in PAGE0 for other purposes?

**Comment by aralbrec** [comment]
Yes they can be removed.  If they are not there, the linker will attach them as needed.  When they are there, the linker uses them instead of attaching code from the library.  It's an attempt to fill in the holes with common code.
