### ISSUE TITLE
newlib +vgl: ensure target is consistent with newlib structure

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#469]
This new target for the [V-Tech Genius Leader / PreComputer 1000/2000/4000](https://www.z88dk.org/forum/viewtopic.php?id=10055) was recently submitted by hotkey.  These kids machines were pervasive at one time and it's nice to see some attention paid to them for retro enthusiasts.  Thanks hotkey :)

Anyway an inspection is needed to make sure the target is consistent with newlib's structure as it is now.  There are a few issues with how asm is inlined that will prevent compilation using zsdcc and a few small additions were added to the terminals while hotkey was working on it that needs updating.

**Comment by hotkeymuc** [comment]
That's right. There are some routines that I am not sure where to put them, e.g. the LCD initialization which is directly invoked in the CRT at the moment.

Furthermore, the keyboard handling is the same for 1000/2000 and 4000, but using different memory addresses. At the moment they are implemented as separate drivers, but I am sure there is a clean way to boil them down to one "universal" driver -- or even a driver that selects the address at runtime, so we can compile once and run on every model.
