### ISSUE TITLE
Make problem on the MSX ans SVI targets

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#479]
The following sequence should be compiled specifically for the MSX and SVI targets.
The 'test' target should be the default for the remaining ones

make[1]: Entering directory 'c:/z88dk/libsrc/msx'
zcc +test -O2 -vn -Wn43  -c msx_blit.c
zcc +test -O2 -vn -Wn43  -c msx_blit_fill_vram.c
zcc +test -O2 -vn -Wn43  -c msx_blit_ram_vram.c
zcc +test -O2 -vn -Wn43  -c msx_calculate_side.c
zcc +test -O2 -vn -Wn43  -c msx_put_sprite_16.c
zcc +test -O2 -vn -Wn43  -c msx_put_sprite_8.c
zcc +test -O2 -vn -Wn43  -c msx_set_char.c
zcc +test -O2 -vn -Wn43  -c msx_set_char_attr.c
zcc +test -O2 -vn -Wn43  -c msx_set_char_color.c
zcc +test -O2 -vn -Wn43  -c msx_set_char_form.c
zcc +test -O2 -vn -Wn43  -c msx_set_mangled_mode.c
zcc +test -O2 -vn -Wn43  -c msx_set_sprite_16.c
zcc +test -O2 -vn -Wn43  -c msx_set_sprite_8.c
zcc +test -O2 -vn -Wn43  -c msx_set_sprite_mode.c
zcc +test -O2 -vn -Wn43  -c msx_vfill_v.c
make[1]: Leaving directory 'c:/z88dk/libsrc/msx'

**Comment by zx70** [comment]
.. can we use '+$(TARGET) in msx/Makefile ?
While we're on it,  is it possible to move the rs232 libraries away from any single clib?

**Comment by suborb** [comment]
Yes, take a look at stdlib/Makefile for how to do it.

They are there out of convenience that's all, trying to get as much
common stuff as possible, feel free to move the call back onto the
actual port.

On Sat, 28 Oct 2017, at 11:11 AM, Stefano wrote:
> .. can we use '+$(TARGET) in msx/Makefile ?
>  While we're on it,  is it possible to move the rs232 libraries away
>  from any single clib?> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/z88dk/z88dk/issues/479#issuecomment-340167168

**Comment by zx70** [comment]
I'm  tempted to port all the stuff into conditional asm, I'll take a deeper look.

**Comment by zx70** [comment]
I found a nearly perfect equivalence in the games folder.    I think we still depend on the pre - built libraries for most of the targets which is not ideal. 
Do you think we should begin where possible to force the test target?   Many of the funtions can be built correctly also by forcing the target specific definitions and trick the header files to pass the correct constants,  eg.  "-D__MSX__" etc..

**Comment by zx70** [comment]
I chose to restrict the build to C modules only in three different flavors, MSX, SVI and "test" (generic).
It should also save a (very little) bit of compilation time.   
I have the impression that this library part could be also built by SDCC, but it is another story  :)

**Comment by zx70** [comment]
Solved, thanks Dom!
