### ISSUE TITLE
classic +msx:  clock() missing

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#486]
From the forum:
https://www.z88dk.org/forum/viewtopic.php?id=10103

**Comment by zx70** [comment]
I can have a look

**Comment by zx70** [comment]
Simple standard clock() based on the Jiffy counter is now ready for MSX and Spectravideo SVI.
Please be aware that I left in time.h the default CLOCKS_PER_SEC set to 50 fps, but depending on the video output requirements it may be changed to 60.
Accurate timer values are 50.159Hz or 59.923Hz, and the "clock.c"  graphics demo runs faster than expected on BlueMSX unless the 50hz video timing is explicitly configured (automatic settings will go in 60hz mode).
