### ISSUE TITLE
Are the --reserve-regs-iy bug workarounds still needed?

### ISSUE THREAD

**Issue by spth** [z88dk/z88dk#487]
Originally, I posted this to the z88dk-dev list a few days ago, but it got no responses; I guess these days the GitHub issue tracker is the preferred way of communicating with z88dk developers.

Dear z88dk developers,

in the past, there were quite a few bugs in SDCC when using
--reserve-regs-iy. In current SDCC 3.6.9 #10136 these should be fixed,
and the generated code should be nearly as bug-free as when not using
--reserve-regs-iy.

Could you please check if you see any remaining --reserve-regs-iy issues?

You probably can drop the peephole rule workarounds that z88dk used to
work around the SDCC bugs.

Philipp

**Comment by suborb** [comment]
Sorry Philipp, I saw the message on the forum, but I can't answer, @aralbrec has been mainly doing the  sdcc work. He's been unusually quiet lately, so he may have new hardware to play with that's taking his time up.

**Comment by aralbrec** [comment]
Yes sorry, I've been quite busy the last several weeks and will continue to be for a while at least.

The rules we have been using to correct sdcc compile issues (most to do with reserve-regs-iy) can be seen here:

**Comment by feilipu** [comment]
Obsolete issue.
