### ISSUE TITLE
[NASCOM][conio] ansi/conio kbhit and getk not working properly (edit: gotoxy is OK) in Nascom target 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#504]
It seems that gotoxy from conio is ignored by the NASCOM target.

If I compile my game CROSS CHASE on this target I see a sequence of characters being displayed from left to write.

**Comment by zx70** [comment]
This is odd, I tried ansitest on it and it seems to work correctly.
Could it be that your games exceeds the NASCOM screen resolution ?
It is a small 48x16 text windows.

**Comment by Fabrizio-Caruso** [comment]
My game should work on any text resolution (big enough to contain about 20 characters). It does work fine with 24x16 and 20x19 resolutions and may even work with a resolution as low as 16x8.

**Comment by zx70** [comment]
I prepared examples/console/coniotest.c
It works on the ZX Spectrum (different resolutions) and Galaksija,  I already noticed it fails on the ZX81 in text mode but we now have a small test program to understand what's happening.

**Comment by zx70** [comment]
Fabrizio, could you run coniotest.c on the NASCOM ?

**Comment by Fabrizio-Caruso** [comment]
I can confirm the problems with the 2017/12/10 snapshot and my game BUT gotoxy worked once.
kbhit on the other hand never worked.
I know it seems weird but the compiler is not behaving deterministically.
I am now not able to get gotoxy to work with my game.
It looks like some memory leak is producing indeterministic behaviour.

**Comment by Fabrizio-Caruso** [comment]
Loading a compiled version of coniotest with Virtual Nascom produces a sort of reboot with the system asking for the number of pages and then a BASIC prompt.

**Comment by Fabrizio-Caruso** [comment]
The problem with the display was caused by a wrong compile line.
There are still problems with the keyboard input:
- kbhit() blocks the computer (see example below)
- getk() does not detect more than one key press when a key is kept pressed
``
		#include<conio.h>
		void WAIT_PRESS(void)
		{
			while(kbhit())
				cgetc();
			while(!kbhit())
			{ 
			}; 
			cgetc();
		}
``

**Comment by zx70** [comment]
I *could* have fixed it now, please try after the next valid build.

**Comment by zx70** [comment]
not fixed yet,  the  keyboard scanning code needs to be rewritten,  probably

**Comment by zx70** [comment]
to be continued in #590
