### ISSUE TITLE
[Galaksija][conio]  kbhit seems consuming the input

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#505]
If I compile my game CROSS CHASE for the Galaksija target I get a malfunctioning keyboard input:
teh game works as a turned-based game as if kbhit were consuming the input it is only supposed to detect.

**Comment by zx70** [comment]
I just rewrote getk(), please try again after the next nightly build.

**Comment by zx70** [comment]
While I was on it I added the joystick() and clock() functions.

**Comment by zx70** [comment]
Fabrizio,  is the new getk() satisfactory?

**Comment by Fabrizio-Caruso** [comment]
Issue fixed! Thanks for the support!

**Comment by zx70** [comment]
https://www.tablix.org/~avian/stuff/galaksija_clock.jpg
too cute to leave it unnoticed!
