### ISSUE TITLE
zsdcc: need update of nightly build

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#517]
I recently committed SO3 peephole optimization files that require changes to zsdcc.  The rule changes affect "-SO3 --opt-code-size" only, ie compiles with code size optimization on.

We still have to stick to revision 9958 until other problems are found.

Patch and windows executables can be found in [sdcc_z88dk_patch.zip](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/sdcc_z88dk_patch.zip)

**Comment by suborb** [comment]
I've just rebuilt so the nightly should have it.
