### ISSUE TITLE
Warnings on sccz80

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#526]
I'm opening this thread to help identifying few examples where the sccz80 warnings look inaccurate.
I want to point out that I perfectly see the benefit of this extra feature the way it works now, but it is still a bit annoying.

libsrc/regex.c
------------
sccz80:"regexp.c" L:755 Warning:Control reaches end of non-void function

	if (regmatch(prog->program + 1)) {
		(...)
		return(1);
	} else
		return(0);
}

**Comment by zx70** [comment]
c128/psg_volume.c
----------------

sccz80:"c128/psg_volume.c" L:17 Warning:Operation on different signedness!
sccz80:"c128/psg_volume.c" L:18 Warning:Operation on different signedness!

void psg_volume(unsigned char channel, unsigned char volume) {
	volumesid(volume*15/10,0);
}

..where volumesid expects "ushort", which should be mapped to "unsigned int".   Can the unused "channel" parameter part of the problem ?

**Comment by zx70** [comment]
The "end of non-void function" warning is probably an opportunity to slightly optimize the code making a default return value explicit, perhaps it can stay the way it is  ?

**Comment by Fabrizio-Caruso** [comment]
I get tons of 
"Warning:Operation on different signedness!"
on things like:
extern unsigned short ghostLevel;
extern unsigned char level;
...
unsigned short computeGhostSlowDown(void)
{
        if(ghostLevel<1000)
                return INITIAL_ENEMY_SLOWDOWN-level*200-ghostLevel*16;
        return 1000;
}

It may be a good warning but it should be possible to silence it. How?

**Comment by suborb** [comment]
@Fabrizio-Caruso I fixed that one in 5e8c191

**Comment by zx70** [comment]
The compilation experience looks much better now, I'm closing the issue.
