### ISSUE TITLE
can't build campus lisp

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#543]
sorry guys,  I must be missing something but I don't seem to be able to build clisp.c and see it run correctly.    after the prompt it becomes unstable,   it can be a simple low memory problem,  can you reproduce the problem ?
eg with sccz80 any instruction but nil creates an error condition.

**Comment by suborb** [comment]
I'll take a look this weekend. This example seems to be a bit of a canary - have we got an example program that generates output? I can add it to the tests to ensure it runs correctly.

**Comment by zx70** [comment]
thankyou for answering  :)
it is sadly the bit I have so far, I'm taking aside sdcc which may require extra tuning basing on the specific page by Alvin (the text looks garbled,  as if the keyboard echo for the literal elements was mapped to a bad font; numbers and direct output look good), I'd focus on sccz80.
I compiled it in many ways,  e.g. with '-DTINYMEM' and -O3 to try to save as much memory as possible. 
I also tried to move zorg.
everytime the any attempt to compute something, eg:
(* 3 4)
.. answers once with:
ERROR.
ILLEGAL FUNCTION CALL: ( . )

...the next attempts will get no answer.

**Comment by aralbrec** [comment]
For sdcc you have to compile clisp.c with `--fsigned-char` because by default it makes `char` unsigned but this program expects `char` to be signed.

I have a second version in the newlib examples that worked with both sccz80 and zsdcc so I will give those a try now.

**Comment by aralbrec** [comment]
Same thing happens in the newlib version - sccz80 reports that illegal function error.  The zsdcc compile crashes.  Looks like a lot of debugging ahead :-(

**Comment by zx70** [comment]
Well done, you're great as always !
...now I can add to clisp.c the optional turtle graphics functions I was keeping aside   :D

**Comment by zx70** [comment]
..is it impacting also zsdcc?  otherwise we can close it

**Comment by suborb** [comment]
I think @aralbrec suggests that it is. I've got: `Build: 3.6.5 #9897 (Mac OS X i386) May  4 2017` and it works ok. So if it's broken there's been a regression.

**Comment by zx70** [comment]
I think the same works also on the late builds.
I only have problems by typing alpha characters (garbled symbols are shown) , which happened also before,  my thought was that it was consequence of a memory overflow/ overlap.

**Comment by aralbrec** [comment]
The sccz80 compile works but an optimized zsdcc compile crashes.

Try `zcc +test -compiler=sdcc --reserve-regs-iy -SO3 --max-allocs-per-node200000 --opt-code-size --fsigned-char clisp.c`
(Make yourself a cup of coffee while that runs :)

It's going to be an issue in the peephole rules.  It crashes before printing anything so the initial bug is right at the beginning.

**Comment by zx70** [comment]
I built a zx version, but even if faulty  (as explained)  it is able to do some simple algebric operation.

**Comment by desertkun** [comment]
@suborb I think we have a regression

```
diff -w Issue_543_complement.opt.tmp2 results/Issue_543_complement.opt
12c12
< 	ld	hl,4	;const
---
> 	ld	hl,2	;const
14,16c14
< 	ld	e,(hl)
< 	inc	hl
< 	ld	d,(hl)
---
> 	call	l_glong2sp
18,19c16,17
< 	ld	d,h
< 	ld	e,l
---
> 	ld	de,28672
> 	call	l_long_and
make[1]: *** [Issue_543_complement.opt] Error 1
```

I wonder why CI doesn't catch this? It happens on my arm64 mac

**Comment by suborb** [comment]
There's no agents in CI building on arm64!

**Comment by suborb** [comment]
Continuing discussion on #2148
