### ISSUE TITLE
(Classic) CLIB ANSI sleep not sleeping or sleeping forever...

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#546]
If I use sleep in my game (when compiled for the Spectrum target with clib=ANSI, sleep seems to have no effect at all.

**Comment by suborb** [comment]
Which target?

**Comment by Fabrizio-Caruso** [comment]
Sorry! I get the problem on the Spectrum. I have corrected the issue title and content.

**Comment by Fabrizio-Caruso** [comment]
I am getting a similar related issue on the CPC: sleep sleeps much longer than expected.

**Comment by zx70** [comment]
Problem found, the " __z88dk_fastcall" suffixes must be removed in <stdlib.h>

**Comment by zx70** [comment]
Fabrizio, would you be so kind to refresh your z88dk copy at the next valid nightly build and confirm the fix ?

**Comment by zx70** [comment]
I just reverted the fix for the Z88 only.   It has its own native functions written in assembly and the fastcall mode is the correct one for its function variants.
