### ISSUE TITLE
[msx][sccz80][classic] msx/defs.h: line 37: macro 'putch' redefined unidentically

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#547]
With the msx target (classic, sccz80)
I am now getting this error:
msx/defs.h: line 37: macro 'putch' redefined unidentically

It seems to be triggered by
#include<msx/gfx.h>

**Comment by zx70** [comment]
I guess it is a conflict between msx.h and conio.h, I probably left putch in the msx library for retro compatibility reasons,   to be checked

**Comment by zx70** [comment]
Definition removed from "defs.h", it is incomplete and harmful rather than useful.
