### ISSUE TITLE
Warning "Unexpected text in #control line ignored" shown but no file name

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#558]
/cygdrive/c/z88dk/bin/zcc.exe +vz -O3 -vn -DSOUNDS -D__VZ__ -clib=ansi -lndos -create-app -o  build/LIGHT_vz200_16k.vz src/sleep_macros.c src/display_macros.c src/enemy.c src/invincible_enemy.c src/level.c src/character.c src/text.c src/missile.c src/strategy.c src/input_macros.c src/main.c
cpp: line 69, Warning: Unexpected text in #control line ignored

**Comment by suborb** [comment]
That message only appears in zcpp which is the old preprocessor. All ports should be switched over to use ucpp now. Hopefully the diagnostics with a recent build will give you the offending file.

**Comment by Fabrizio-Caruso** [comment]
Sorry! No warning shown on the new build.
