### ISSUE TITLE
[msx][conio] Display on coloum 0 broken (old issue) in 32 col color text mode1

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#559]
With the MSX target, in text 32 column text mode 1 (color text mode with predetermined colors for characters),
when trying to use display strings starting at column 0, e.g, gotoxy(0,...) printf(...)
the string is wrongly displayed truncated and in the below rom.

**Comment by zx70** [comment]
Does it work correctly in ansi-vt mode ?
I suppose so, and you are probably replicating the old macro for gotoxy now commented out,  right?

**Comment by Fabrizio-Caruso** [comment]
Yes, indeed @zx70.
