### ISSUE TITLE
[zx81] zx_setcursorpos + fputc_cons on low right corner triggers scroll

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#561]
How can display a character on just the low right corner of the screen?
It seems that any attempt to display a single character on the low right corner, triggers a scroll up.

**Comment by suborb** [comment]
I think several ports have this issue, the increment column row occurs after printing. This will then scroll as necessary.

Ideally, either: there should be a way to disable scrolling or the need to scroll should be when the next character is actually printed.

**Comment by aralbrec** [comment]
Yeah the check should be before the character is printed rather than after.

**Comment by suborb** [comment]
@Fabrizio-Caruso If you get a chance could you verify - I think I've fixed this now
