### ISSUE TITLE
Extra instructions produced when using #asm #endasm with __FASTCALL__

### ISSUE THREAD

**Issue by Ckirby101** [z88dk/z88dk#574]
The compiler will output extra pop bc instructions depending on the compile order.

With the following code Func1 & Func 2 are correct but Func3 will add an extra pop bc which will cause a crash..

If Func3 is moved BEFORE Func2 it will compile correctly.

`
void __FASTCALL__ Func1()
{

}

void __FASTCALL__ Func2(int x)
{
	#asm
	ld a,l
	#endasm
}

void __FASTCALL__ Func3()
{

}
`

And this is the tmp output file.. 

`;void __FASTCALL__ Func1()
	C_LINE	107,"iso.c"
;{
	C_LINE	108,"iso.c"

; Function Func1 flags 0x00000208 __smallc __z88dk_fastcall 
; void Func1()
._Func1
	C_LINE	108,"iso.c"
;}
	C_LINE	110,"iso.c"
	ret

;void __FASTCALL__ Func2(int x)
	C_LINE	112,"iso.c"
;{
	C_LINE	113,"iso.c"

; Function Func2 flags 0x00000208 __smallc __z88dk_fastcall 
; void Func2(int x)
; parameter 'int x' at 2 size(2)
._Func2
	push	hl
	C_LINE	113,"iso.c"
;	#asm
	C_LINE	114,"iso.c"
	C_LINE	114,"iso.c"
	C_LINE	116,"iso.c"
	ld a,l
	C_LINE	117,"iso.c"
;}
	C_LINE	119,"iso.c"
	pop	bc
	ret

;void __FASTCALL__ Func3()
	C_LINE	122,"iso.c"
;{
	C_LINE	123,"iso.c"

; Function Func3 flags 0x00000208 __smallc __z88dk_fastcall 
; void Func3()
._Func3
	C_LINE	123,"iso.c"
;}
	C_LINE	125,"iso.c"
	pop	bc
	ret

`

Notice the extra pop bc in Func3

compiled with

zcc +zx -m -clib=new -startup=31 iso.c -o build\racing -subtype=sna -create-app -no-cleanup --c-code-in-asm

**Comment by suborb** [comment]
Good spot, I think that's been there for a while. Hopefully the commit above should fix it.

**Comment by Ckirby101** [comment]
cheers m8..
