### ISSUE TITLE
[VG5K][sccz80] VG5K broken in latest snapshots

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#585]
Latest versions break VG5K (reset when I run my game)

There seems to be problems with other targets.

Confirmed working on 20171213.

**Comment by suborb** [comment]
I modularised the code as part of harmonising the pragmas between classic and new.

Unfortunately I moved the stack the wrong way for the atexit stack so depending on where sp is on startup it might have ended up pointing to ROM.

Predictably it didn't show up as a problem in any of the ports I tested against.

I've just committed, so hopefully that's now repaired. Apologies for that.

**Comment by Fabrizio-Caruso** [comment]
Problem solved! Thanks!
