### ISSUE TITLE
new c lib (+zx): Bifrost*L and Bifrost*H seem to misbehave at beginning of demos

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#59]
Two compiled demos for the zx spectrum:

[Bifrost*h demo](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/EXAMPLES/zx/demo_bifrosth/demo.tap)
[Bifrost*l demo](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/EXAMPLES/zx/demo_bifrostl/demo.tap)

I'm not sure why some of the tiles seem incorrect but both demos misbehave in the same way for two related but separate engines.  I am wondering if I have the wrong entry point for one of the subroutines - this is a possibility as the entry points were not clearly marked in the original source code.

**Comment by stefandrissen** [comment]
I think that your simply attempting to point to tiles that are not there - you are looping through 81 positions and expecting there to be 81 static images:

      for (f = 0; f < 81; ++f) {
            BIFROSTH_tilemap[f] = BIFROSTH_STATIC + f;
        }

**Comment by aralbrec** [comment]
I think you are right - there probably aren't 82 tiles defined given the rest of the program is limited to far fewer.  I'll confirm that tomorrow before closing, thanks!

**Comment by aralbrec** [comment]
There are only 34 tiles defined for both demos and those are the only ones that correctly display on the initial startup of both demos.  So the engine and program are behaving as expected.

Nothing to see here, move along!
