### ISSUE TITLE
copt: crashes for non-ascii input

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#593]
I thought this was an open issue already but I couldn't find it.

copt will crash if the input file contains non-ascii characters.  The specific report involves input with cyrillic characters in comments.

**Comment by aralbrec** [comment]
I'm not sure if the solution is as simple as opening the input file in binary mode so no processing of the text stream is done by stdio.

**Comment by suborb** [comment]
I'll fix this. This is due to this code in the install function:

        register char *s;
        int  i;
        for (i = 0; *s; i += *s++)
                ;
        i %= HSIZE;

       struct node *p = htab[i];

Where i ends up being a negative index if *s >= 128 which will be the case for there's a non ASCII utf8 character in there.
