### ISSUE TITLE
Enigma is giving incorrect results

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#608]
Running examples\console\enigma.c with HELLO as input should output RXSEC.
Recently it started giving a different output: AUTSR

Since enigma.c is not changed since a long time, something else has broken.

Test:
```
zcc +cpm -oenigma.bin enigma.c
cpm enigma.bin
```

I've confirmed the correct output when compiled on the PC with gcc.

**Comment by suborb** [comment]
Thanks - it looks like initialised [] char arrays didn't get their length set correctly so we ended up dividing by -1 and scaling accordingly based on the negative size of the array, not the size of the element.
