### ISSUE TITLE
For discussion: z80asm send errors to stderr instead of file.err

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#611]
Currently z80asm creates a file.err when there are compilation errors.

Proposal: remove the generation of .err files, send errors only to stderr 

Any comments?

**Comment by suborb** [comment]
zcc does some work to look up the source file for the error and show the line where the problem is. I think this includes a translation back to the original C file.

Without the .err files this isn't going to be possible.

However, one could argue that if z80asm were to report the line and print the offending assembler, then the user can look up the C file and line number themselves.

**Comment by pauloscustodio** [comment]
If zcc emits C_LINE statements, then z80asm will report errors in the original C file lines.

**Comment by suborb** [comment]
Yes, so at the moment, we parse the .err files and print the offending C source line.

Given that we use system() we can't capture stderr so can't do the same thing. I don't think we can even do it portably with popen()

**Comment by pauloscustodio** [comment]
Clear. Idea abandoned.

**Comment by suborb** [comment]
I have to admit that I'm not keen on the .err file, it's a little bit of QDOS hangover really.

The logic for printing the line could moved into z80asm though - it's currently in zcc.c::ShowErrors

**Comment by zx70** [comment]
is this issue connected to #688  ?

**Comment by pauloscustodio** [comment]
I think so although I did not yet investigate further. 

⁣Enviado por TypeApp ​

Em 15/04/2018, 22:13, em 22:13, Stefano <notifications@github.com> escreveu:

**Comment by pauloscustodio** [comment]
Starting work on this: showing offending assembly line after error, and getting rid of Perl generating source files.

While at ir: is the error message format carved in stone, or could we change to the more terse and more standard?
```
file:line: error: xxxx
```

**Comment by suborb** [comment]
A more standard format would be welcome - would be great if vscode etc would just be able to parse them.
