### ISSUE TITLE
[Enterprise] How to load the binary?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#634]
If I compile for the Enterprise I get a a.app file. 
The doc says I can load it with run"a.app" but I get a "Not a DOS disk" error.
Trying to mount a.app as a disk will produce an invalid format error.

I compile with
```
	$(Z88DK_PATH)$(MYZ88DK) +enterprise \
	-create-app \
	-lm -vn -lndos \
...
```

**Comment by suborb** [comment]
Follow the instructions here: http://ep128.hu/Ep_Emulator_eng.htm regarding setting up EPFileIO.rom

Then within the enterprise type: run "file:" 

A file selector should pop up and you should select the .app file that's created by z88dk

![enterprise](https://user-images.githubusercontent.com/394721/37231673-f0cdfa3c-23e3-11e8-8e3f-d6407c7146fb.png)
