### ISSUE TITLE
z80asm: symbol declared public and not defined should raise an error

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#649]
A symbol declared public and not defined should not be allowed.

Include files should use global - this either declares the symbol as public if defined, or as extern otherwise.

**Comment by pauloscustodio** [comment]
see also #650

**Comment by pauloscustodio** [comment]
Fails the library build: 
```
Error at file '../_DEVELOPMENT/z80/z80/asm_z80_pop_ei.asm' line 22: symbol 'asm0_z80_pop_ei' not defined
Error at file '../_DEVELOPMENT/z80/z80/asm_z80_pop_ei.asm' line 23: symbol 'asm_z80_pop_ei_jp' not defined
Error at file '../_DEVELOPMENT/z80/z80/asm_z80_pop_ei.asm' line 26: symbol 'asm0_cpu_pop_ei' not defined
Error at file '../_DEVELOPMENT/z80/z80/asm_z80_pop_ei.asm' line 27: symbol 'asm_cpu_pop_ei_jp' not defined
```

symbol is declared public but if-def does not include it's definition.

Should we fix the library, or revert to without this check?

**Comment by suborb** [comment]
Needs to be a noop. It isn’t actually called on the rabbit - ipset and ipres are used instead.

**Comment by aralbrec** [comment]
There may be library functions that call these routines to save and restore interrupt state so I filled in the rest of the rabbit equivalents.  In the end most of these lightweight subroutine calls should be inlined by the peepholers #595.

**Comment by pauloscustodio** [comment]
I've been fixing the library to pass the compilation, although I will need someone, maybe @aralbrec to check if my changes are correct. I'll request a peer-review before merge.

Anyway there is one I don't how to solve: 
```
z80asm  -xlib/sccz80/zx @target/zx/library/zx_sccz80.lst
Error at file 'arch/zx/bifrost2/z80/BIFROST2_INSTALL.asm' line 1042: symbol 'asm_BIFROST2_stop' not defined
```

The file BIFROST2_INSTALL.asm says that it is  Automatically Generated at Library Build Time. Where is the source?

**Comment by aralbrec** [comment]
> The file BIFROST2_INSTALL.asm says that it is Automatically Generated at Library Build Time. Where is the source?

It's made from the m4 file in the same directory:  `arch/zx/bifrost2/z80/BIFROST2_INSTALL.asm.m4`
