### ISSUE TITLE
Recently deleted files in graphics/text/ break build

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#668]
@zx70 
The recently deleted files in graphics/text break the build - both gfx128.lst and gfx9001.lst still use them.  I'm not sure what your plans are for these so I'm just going to temporarily restore those files to fix the build for now.

**Comment by aralbrec** [comment]
ok :)

**Comment by zx70** [comment]
many many thanks,  I had to clean the ace folder and I did it in the wrong place :(
the good news is that now things are slightly sorted out now (and that those files are now used also by the j. ace, for a 64x48 gfx option)
