### ISSUE TITLE
[ace] recent changes have broken conio (extra characters displayed)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#672]
The ACE target had a working conio implementation, which is no longer working correctly.

Extra characters are displayed.
![ace_bug](https://user-images.githubusercontent.com/29057615/38117599-2ff8f900-33b6-11e8-946a-265eb05c8091.jpg)

**Comment by zx70** [comment]
I just told Fabrizio the ACE target was let untouched, but it is not totally true..
While solving #667 I had to revive the base_graphics lablel I committed the single row number https://github.com/z88dk/z88dk/commit/a1a6ba4ebbfb11f1efc1be6f395fedc060734387 .

Fabrizio,  I can't imagine why this could compromise a thing but please try by removing from  lib/target/ace/classic/ace_crt0.asm the block of rows 127..129:

    ELSE

	    ld   hl,$2400
	    ld   (base_graphics),hl

**Comment by Fabrizio-Caruso** [comment]
The culprit was MY code (sort of):
```
-               #define cputc(c) printf("\x11%c%c",COLOR_BLACK,c)
+              #define cputc(c) fputc_cons(c)
```
which, used to work even though I was display a character with 
`printf("\x11%c%c",COLOR_BLACK,c) `

I have fixed it by just doing a straightforward ` fputc_cons(c)`.
