### ISSUE TITLE
newlib: libsrc/_DEVELOPMENT/EXAMPLES/zx/two_terminals is crashing

### ISSUE THREAD

**Issue by bog-dan-ro** [z88dk/z88dk#681]
Steps to reproduce:
 - compile the example (doesn't matter if you're using sccz80 or zsdcc)
- wait for `Enter some test` message
- keep letter `o` pressed until it crashes

sha1: 5fcbea66ad5f5ea

**Comment by aralbrec** [comment]
Thanks.  There was a change made to the fzx driver a couple of weeks ago.  I will check on it tomorrow.

**Comment by aralbrec** [comment]
The bug went back to October of last year and should be fixed now.

The terminal was also asking to scroll twice by a little, then more when making space for another character row so that was fixed too and should speed the scrolling up a little bit.

**Comment by bog-dan-ro** [comment]
I can confirm that it was fixed.
Thanks a lot for quick fix!
