### ISSUE TITLE
Build failure - missing optparse.h

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#684]
Build failed.

Missing `optparse.h` included from [`zobjcopy.h`](https://github.com/z88dk/z88dk/blob/master/src/zobjcopy/zobjcopy.h#L10)

```
make[1]: Entering directory '/home/phillip/Z80/z88dk/src/zobjcopy'
cc -g -O2 -Wall -std=gnu11 -MMD -I../common -I../../ext/uthash/src -I../../ext/optparse   -c -o zobjcopy.o zobjcopy.c
In file included from zobjcopy.c:6:0:
zobjcopy.h:10:22: fatal error: optparse.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'zobjcopy.o' failed
make[1]: *** [zobjcopy.o] Error 1
make[1]: Leaving directory '/home/phillip/Z80/z88dk/src/zobjcopy'
Makefile:85: recipe for target 'zobjcopy' failed
make: *** [zobjcopy] Error 2
```

**Comment by suborb** [comment]
You need to re-sync the submodules:

    git submodule update --init --recursive

**Comment by feilipu** [comment]
Fixed thanks.

Is there a "flag" or signal somehow that my clone needs this re-sync of submodules?
I never would have thought of that solution alone.

**Comment by suborb** [comment]
I'm not sure, it came in with this commit 52fbfbd1389881b2f9c16958473a6bf547cdaba8

so a new directory was created in ext
