### ISSUE TITLE
sam coupe

### ISSUE THREAD

**Issue by rogerjowett** [z88dk/z88dk#685]
https://www.youtube.com/watch?v=zsjTpFR0oYQ

please can it emulate the sam coupe yet?

**Comment by zx70** [comment]
Sorry I don't your post.   The link to the video shows (probably) a sequence of pictures loaded by the SAM Coupè to provide a "video stream".
What are you exactly proposing/asking to the z88dk team ?

**Comment by rogerjowett** [comment]
well i thought the z88dk was a z80 emulator is that not right?

**Comment by zx70** [comment]
not exactly, z88dk is a developemnent kit for the z80 (including a c compiler, an assembler and libraries) but it is targeted to extermal computers (or emulators).

**Comment by rogerjowett** [comment]
there are a lot of emulators for the zx spectrum about but on ly one sofar
is trying to model the uhf tv output

https://www.aptanet.org/eightyone/

https://sourceforge.net/projects/eightyone-sinclair-emulator/

**Comment by suborb** [comment]
Roger, you'll probably get a better response if you take your thoughts to https://worldofspectrum.org/forums/categories/emulators 

Thanks

**Comment by rogerjowett** [comment]
- Sorry, permission denied.
