### ISSUE TITLE
[ace] Create in_Inkey and friends implementation

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#686]
The ace keyboard is very similar to the ZX keyboards:

http://www.forums1.jupiter-ace.co.uk/prog_keyboardread.html

![screen shot 2018-04-11 at 11 59 06](https://user-images.githubusercontent.com/394721/38612820-c51da72e-3d7f-11e8-8853-c73cccb23a32.png)

Spectrum keyboard and ports is:

```
0x7ffe B, N, M, Symbol Shift, Space
0xbffe H, J, K, L, Enter
0xdffe Y, U, I, O, P
0xeffe 6, 7, 8, 9, 0
0xf7fe 5, 4, 3, 2, 1
0xfbfe T, R, E, W, Q
0xfdfe G, F, D, S, A
0xfefe V, C, X, Z, Caps Shift
```

**Comment by zx70** [comment]
joystick() ready

**Comment by zx70** [comment]
Further reference:
http://www.forums1.jupiter-ace.co.uk/hardware_ace_inteface.html
Often suggested: "multipress on keys 1 to 5", but I kept the number keys mapping as for the "Sinclair 1"/"Sinclair 2" joysticks.   Befor adjusting the sequence I'd like to find documentation on whether a Kempston interface could be adapted in a similar way to what someone did between the ZX81 and the Spectrum edge connectors.
