### ISSUE TITLE
rc2014: outstanding issues with aligned data and im2 vector table

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#709]
An im2 vector table issue was brought up here:
https://github.com/z88dk/z88dk/pull/677#issuecomment-382280898

This is an issue that applies to all targets in z88dk, namely in determining how the user can customize an im2 table while the library can at the same time offer a weak default.

The second issue is about aligned sections that can be potentially wasteful of memory:
https://github.com/z88dk/z88dk/pull/705#issuecomment-383757966

z80asm might be changing in how it's handling alignment as it seems alignment can be a property of a section (see https://github.com/z88dk/z88dk/wiki/Tool-zobjcopy ).  The current solution assume the `align` directive is applied at assemble time, ie to addresses that have not been patched by the linker.  So the memory map defines aligned sections such that the user can add stuff there assuming its address will be aligned but then must maintain that alignment by padding after the object.

**Comment by feilipu** [comment]
Closing this. 4 years old.
