### ISSUE TITLE
(copt) Copt should use ext/regex rather than a local copy of hs_regex

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#713]
Just a bit of housekeeping and consistency.

**Comment by suborb** [comment]
Quick test shows that the sdcc regex rules don't work when linked to the external regex library.

**Comment by aralbrec** [comment]
I modified copt some time ago to accept `\t` as the tab character.  Whitespace is significant in sdcc's output.

```
%"[ \t]*"1.%"(ASCII|ascii)"9%"[ \t]+"2%0
=
%1DEFM%2%0
```

**Comment by suborb** [comment]
Thanks, that was the problem.

It looks like zcc uses copt/regex so I suggest we move copt/regex upto ext
