### ISSUE TITLE
sinwave/coswave examples

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#715]
those 2examples had simple acceleration based on the picture symmetry .. not working anymore.

**Comment by suborb** [comment]
Odd:

![screen shot 2018-04-27 at 21 42 33](https://user-images.githubusercontent.com/394721/39384237-fc9ace5c-4a63-11e8-93a3-b7d829124f41.png)

**Comment by suborb** [comment]
First few coordinates with math48:

(0,214)
(-255,214)
(0,213)
(-255,213)
(0,179)
(-255,179)

with genmath:

(-1,214)
(-256,214)
(-1,213)
(-256,213)
(-1,179)
(-256,179)

On my mac:

(0,214)
(255,214)
(0,213)
(255,213)
(0,179)
(255,179)

I think this is in my court so I'll look at it.

**Comment by suborb** [comment]
Fixed - one of the branches wasn't swapping over the left and right hand sides of the subtraction when a constant was involved.

It's times like this that you realise how slow floating point on a z80 is:

```
% gcc sinwave.c
% time ./a.out > nix.out
0.004u 0.001s 0:00.00 0.0%	0+0k 0+0io 0pf+0w

% zcc +test sinwave.c -lm
% time ticks -w 600 a.bin > test.out
20.812u 1.281s 0:22.56 97.9%	0+0k 0+0io 56pf+0w

% zcc +test sinwave.c -lmath48
% time ticks -w 600 a.bin > test.out
18.615u 1.239s 0:20.22 98.1%	0+0k 0+0io 0pf+0w

% zcc +test sinwave.c -lmath48 -compiler=sdcc
% time ticks -w 600 a.bin > test.out
17.422u 1.098s 0:18.84 98.2%	0+0k 0+0io 2pf+0w
```

![screen shot 2018-04-27 at 22 27 56](https://user-images.githubusercontent.com/394721/39385960-4386cc16-4a6a-11e8-81ba-5e05796f333b.png)
