### ISSUE TITLE
sdcc build instructions out of date

### ISSUE THREAD

**Issue by periata** [z88dk/z88dk#730]
The documentation on building sdcc is out of date:

* It states that a patch must be downloaded from https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/sdcc_z88dk_patch.zip, but this file doesn't actually contain the patch (it has a readme.txt file that states the patch is now in "z88dk/src/zsdcc").
* The instructions state to run `patch -p0 < sdcc-z88dk.patch` from in the `sdcc-code` directory, but when I do so `patch` complains about being unable to find the files referenced; I need to be in the `sdcc-code/sdcc` directory for it to work.

**Comment by aralbrec** [comment]
It looks like the last patch was made from the wrong root directory.  Some updates to zsdcc have to be made anyway so I will make a new patch in the coming days.
