### ISSUE TITLE
[udg][feature] UDG support in VG5K and ACE

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#731]
It would be cool to have support for user-defined graphics in VG5K and ACE.

**Comment by suborb** [comment]
I’ve added support for changing the font on ace as well as being able to define up to 32 udgs. 

Sys/ioctl.h has the controls to define then. They overwrite the block graphics. 

In theory the same code will work on vdp targets (msx etc), zx and ace. 

To get inverse characters you’ll need to ioctl to raw mode. 

There are a few rough spots (the function name is awful) but some feedback would be useful.

**Comment by Fabrizio-Caruso** [comment]
@suborb Thanks!
The EF9345 is an odd chip but has a historical value at least in France (it was used in Minitel).
It was also used in TRS-80 MC-10 and its French clone the Aluce Matra 4k.
It is cool to have it supported.

**Comment by suborb** [comment]
Information transferred to #732
