### ISSUE TITLE
[mc-1000] Use the code_driver section

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#739]
The code_driver section is the first declared section and as such it will be located in low memory.

The mc-1000 needs to perform paging to access the video memory - at present video access code is in the crt0 and bloats the final executable if it's not needed.

**Comment by zx70** [comment]
I'm on it

**Comment by suborb** [comment]
@zx70 I think you still need to move them into the right section :)

**Comment by zx70** [comment]
Right.. !

**Comment by zx70** [comment]
interesting section !
a nice to have would be the opposite:  a section to link functions on bottom and an automatic filler in case a given 'quota' hasn't been reached (e.g.  must stay after 32768)
