### ISSUE TITLE
[sdcc][vg5k] Broken in 10/05/2018 version + Random size of the binary (changes after recompiling)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#744]
I am compiling with just -compiler=sdcc and the following pragma file
```
// move the stack to available memory
#pragma output REGISTER_SP = -1      // must be placed somewhere in the 16k ram

// halt program on exit, no need to play well with basic
#pragma output CRT_ON_EXIT = 0x10001

// eliminate the malloc heap
#pragma output CLIB_MALLOC_HEAP_SIZE = 0

// eliminate the stdio heap (no files can be opened)
#pragma output CLIB_STDIO_HEAP_SIZE = 0

// eliminate unused printf converters
#pragma printf = "%0u"    // placed used converters here, empty string if none
```

Remark: If I use the latest Z88dk snapshot I get a crash. If I get a previous but still recent version, I can sometimes get something working. The binary size is random.

I get this behavior without -S03 nor --max--allocs-pernode20000 nor -opt-code-size.
I perform make clean to remove .o files.
I compile my game and I get a binary of size X (which works in some cases)
I perform make clean again to remove .o files.
I recompile my game and I get again a working binary of size Y not equal to X (which works in some cases)

Recompiling the same unmodified code breaks or maybe fixes it... 

On the other hand, it

**Comment by Fabrizio-Caruso** [comment]
Remark: The very latest Z88DK snapshot (10/05/2018) produces crashes (when compiled with sdcc).

**Comment by suborb** [comment]
The crashes are I suspect because:

1. Interrupts are now enabled
2. The interrupts need ix to be unchanged from the system
3. SDCC is probably trampling ix (so iy in .asm)

vg5k is compiled with --IXIY so ix and iy are being swapped at the assembler stage.

Different binary sizes may well be due to pragma file being processed at different times and hence ending up with different printf formatters being dragged in.

**Comment by Fabrizio-Caruso** [comment]
@suborb  Adding --reserve-regs-iy  gets my game to work (it looks OK after playing for 1 min)
Is it enough?

I have no issue with sccz80.

**Comment by suborb** [comment]
It may be enough for your game at the moment, but the version of sdcc we're using doesn't always respect it.

When I get a chance I'll disassemble the ROM and see if the interrupt hook is viable.

**Comment by Fabrizio-Caruso** [comment]
@suborb what do I have to do to have a deterministic behavior (same binary with same source code).
I delete .o files. What else should I do?

**Comment by Fabrizio-Caruso** [comment]
@suborb it looks like the latest snapshots with vg5k produces larger binaries?
Is it caused by a recent change? Does it come from the newly added support for UDG?

**Comment by suborb** [comment]
I think ansifont_f6 is being pulled in now which would be unused, it'll be in an inadvertent side effect of defining the console size. It may affect more than one port. I'll work out a better solution, but for now you can put:

        ; Skip over font selection
        defc    DEFINED_ansifont = 1
        defc    ansifont = 0
        defc    ansifont_is_packed = 0

In lib/target/vg5k/classic/vg5k_crt0.asm

**Comment by suborb** [comment]
Regarding pragmas. Keeping them in a file called zpragma.inc, and then link the option `-pragma-include:zpragma.inc` should do it.

**Comment by Fabrizio-Caruso** [comment]
@suborb Thanks for your support! 
I only use pragma in a separate file. So the random size cannot be caused by pragmas.

My code should not be in the compiler. I would like to keep the two things separate.
Can I put vg5k_crt0.asm in my code without having to modify the compiler?
Otherwise I prefer to wait for a fix.

**Comment by Fabrizio-Caruso** [comment]
@suborb 
How should I translate some inline Assembly that works fine with sccz80?

So far no luck (I get crashes in sdcc), I have tried:
```
		#if defined(SDCC)
			__asm
		#else
			#asm
		#endif
		pop bc   ; bc = ret address
		pop hl   ; hl = int xy
		pop de  ; de = int chCol
		push de    ; now restore stack
		push hl
		push bc	
		;ld ix,0x47FA	
		call 0x0092	
		#if defined(SDCC)
			__endasm;
		#else
			#endasm
		#endif
```
which compiles but does not work.

**Comment by Fabrizio-Caruso** [comment]
If I try to modify the .crt file I get some errors:
```
Error at file 'c:\Z88DK\lib\config\..\..\\lib\target\vg5k\classic\vg5k_crt0.asm' line 106: symbol 'ansifont' already defined
Error at file 'c:\Z88DK\lib\config\..\..\\lib\target\vg5k\classic\vg5k_crt0.asm' line 107: symbol 'ansifont_is_packed' already defined
2 errors occurred during assembly
Errors in source file c:\Z88DK\lib\config\..\..\\lib\target\vg5k\classic\vg5k_crt0.asm:
Error at file 'c:\Z88DK\lib\config\..\..\\lib\target\vg5k\classic\vg5k_crt0.asm' line 106: symbol 'ansifont' already defined
                   ^ ---- defc    ansifont = 0
Error at file 'c:\Z88DK\lib\config\..\..\\lib\target\vg5k\classic\vg5k_crt0.asm' line 107: symbol 'ansifont_is_packed' already defined
                   ^ ---- defc    ansifont_is_packed = 0make: *** [Makefile:596: vg5k_full_sdcc] Error 1
```

**Comment by suborb** [comment]
Okay, I'll fix up the font thing tonight.

With the assembler - what's the complete function. I think the problem may be that you need to `ld iy,0x47FA` (remember ix and iy are swapped).

There's no need to have different start/end assembler tags based on the compiler, __asm and __endasm; will work for both.

**Comment by Fabrizio-Caruso** [comment]
@suborb 
When compiling with sdcc I get some expected warnings
```
src/vg5k/vg5k_graphics.c:207: warning 85: in function _draw_ch_aux unreferenced function argument : 'chCol'
src/vg5k/vg5k_graphics.c:207: warning 85: in function _draw_ch_aux unreferenced function argument : 'xy'
src/main.c:722: warning 126: unreachable code
src/main.c:400: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
```

**Comment by aralbrec** [comment]
Try this:

```
#if defined(ASM_DISPLAY)
	void _draw_ch_aux(int chCol, int xy)
	{		
		__asm

IF __SDCC

   pop bc
   pop de
   pop hl

   push hl
   push de
   push bc

ENDIF

IF __SCCZ80

		pop bc   ; bc = ret address
		pop hl   ; hl = int xy
		pop de  ; de = int chCol

		push de    ; now restore stack
		push hl
		push bc

ENDIF

		push ix

		;ld ix,0x47FA	
		
		call 0x0092

		pop ix

		__endasm;
	}
#endif
```

sdcc pushes parmeters in right to left order and uses ix as frame pointer so ix must be saved if it is modified.

The warnings are saying you have code that can never run on lines 126 and 110.

**Comment by aralbrec** [comment]
Ack.. the classic library does not generate defines depending on compiler... in the newlib it's done in the cfg file but maybe it should be done in zcc instead when "-compiler=sdcc" appears on the compile line.

**Comment by suborb** [comment]
I think zcc should do it. Sys/compiler.h toggles decorators according to the compiler.

**Comment by suborb** [comment]
Okay, I've done a bit of investigation. 

The interrupt calls $47d0 initially when this returns it expects ix to be set to $47FA. We could interpose but it would be a bit fiddly and the interrupt doesn't offer us a huge amount.

The ROM routine $0092 doesn't need ix to be set.

So I'm going to:

1. Disable interrupts (all it does is redraw the screen anyway)
2. Make generic_console refresh the screen itself rather than rely on the interrupt

Looking at the other ROM routines that are called, fgetc_cons() and getk() call $00aa. This will use ix to control debouncing and $(4891) for the scan code to ascii conversion table. So:

3. I'll ensure ix is set in these calls

**Comment by Fabrizio-Caruso** [comment]
@suborb The binary size for the VG5K target is now MUCH smaller when compiled with sdcc!

**Comment by suborb** [comment]
I think this is okay now, if it's not, then we can open another issue.
