### ISSUE TITLE
zcc: define macros to indicate which c compiler is used

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#745]
These macros are defined for the newlib in the target's cfg files.  Moving them to zcc will make these macros available to the classic library too.

From #744

**Comment by suborb** [comment]
Zcc already adds -D__SDCC and -DSCCZ80 -DSMALL_C -D__SCCZ80 as appropriate. What other ones do you need?

**Comment by aralbrec** [comment]
They need to be available in the assembler:

-D__SCCZ80 -Ca-D__SCCZ80 -Cl-D__SCCZ80
-D__SDCC -Ca-D__SDCC -Cl-D__SDCC
