### ISSUE TITLE
sccz80: Allow sccz80 to push arguments r->l

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#75]
We can use __smallc to indicate that the arguments are the classic way round which works nicely for libraries.

However, for user code this going to be awkward change.

**Comment by suborb** [comment]
At the moment, this works for most cases up to a certain level of nested function calls. The build is failing in savage.c. This following works:

a = exp(log(sqrt(a * a)));

Adding the atan() element fails:

a = atan(exp(log(sqrt(a * a))));

There's a bunch of valgrind errors which I don't think are the cause of the problem.

**Comment by aralbrec** [comment]
I have compile errors for vararg functions using sccz80.  Has there been a change in how vararg functions are handled?

Before the change, call to printf:

```
2462  05C4  21 28 00    	ld	hl,i_1+40
2463  05C7  E5          	push	hl
2464  05C8  3E 01       	ld	a,1
2465  05CA  CD 00 00    	call	printf
2466  05CD  C1          	pop	bc
```

After the change call to printf, note number of arguments is no longer in the A register:

```
2461  05C2  21 28 00    	ld	hl,i_1+40
2462  05C5  E5          	push	hl
2463  05C6  CD 00 00    	call	printf
2464  05C9  C1          	pop	bc
```

printf is declared with smallc attribute if that matters:

`extern int __LIB__ printf_unlocked(char *format,...) __smallc;
`

**Comment by suborb** [comment]
Oops, the check was the wrong way round so that r2l functions got an a, but l2r didn't.

**Comment by aralbrec** [comment]
Code generation is now identical to what it was before the change.

But I have a bug that is probably not related - the sudoku solver cannot solve puzzles under sccz80 compilation but it does under sdcc.  I'm going back in commits to see where this problem started.
