### ISSUE TITLE
(classic) amalloc not set up correctly for most targets

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#750]
The amalloc initialisation code needs hl to contain the highest memory address that the heap can extend to before it's called.

Unfortunately, most targets don't set this correctly.

**Comment by zx70** [comment]
Thankyou, I wasn't fully confident but I suspected it..
  https://github.com/z88dk/z88dk/issues/498#issuecomment-381204090

**Comment by suborb** [comment]
Yeah, I spent quite a while trying to debug random failures in ScottFree until I figured out it was the heap trashing the code.

I've fixed up a few of the targets that I know have different stack setups, for the rest of them I'm assuming that sp > BSS_END and we own the memory - I'm sure it's the wrong assumption, but we can fix them easily enough. The work around without changing the CRT is to add the option `-pragma-define:CRT_MAX_HEAP_ADDRESS=nnnnn`

**Comment by zx70** [comment]
ScottFree ..  :)
...years ago I got it running on real Microdrives (fcntl interfacing directly at sector level), loading speed wasn't worse than on the emulators and the files (which I uploaded from rs232 with simple BASIC commands) were perfectly read.   No need to say that also the ANSI VT emulation worked well .

Are you adapting it to the universal console ?

**Comment by suborb** [comment]
I was contemplating porting a curses game to the new console and then I got sidetracked by ScottFree again.

Ah, that's the example using a variable for the heap isn't it? My fix is just when you use -DAMALLOC 

I'll take a look at the variable variant code.

**Comment by zx70** [comment]
The problem I have is in {z88dk}/libsrc/lib3d/mesh_new.c
I temporairly removed the malloc() calls in the MSX examples and I'm using static buffers everywhere else.

**Comment by zx70** [comment]
I think the AMALLOC is now in a much better shape, but I can't say if it is fixed on all the targets.
Thoughts ?
