### ISSUE TITLE
[Classic] Create Casio PV-1000 target

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#753]
Info: http://www43.tok2.com/home/cmpslv/Pv1000/EnrPV1.htm

Limited graphical capability: 224 tiles that are ROM based (default from 0x0000 -> 0x1fff). Each tile is 8x8 but covers 32 bytes (see link for details). 32 tiles in the very limited RAM.

Supposedly 256x192, 8 colours (same as Spectrum), pixel based colouring (extrapolated from tileset configuration)

* Z80 @ 3.579
* 3k RAM, 0k ROM
* VDP: D65010G031
* Audio: On ports 0xf8, 0xf9, 0xfa - D65010G031
* Joysticks: 2x on 0xfd

Mess limits ROM size to 8k/16k however 32k should also be possible.

Alternate emulator: http://takeda-toshiya.my.coocan.jp/pv1000/index.html

---
Character set will have to be compiled into the CRT. It needs to be configurable, but we can supply a default one:

0x0a - 0x0f - Chequerboard and half chequerboard + inverse variants
0x10 - 0x1f - The 4x4 block matrix (white on black - can be used for low-res graphics)
0x20 - 0x7f - Standard character set (yellow on black)
0x80 - 0xdf - Available for user to predefine UDGs

0xe0 - 0xff - Possibly available depending on RAM overhead

---
Likely library availability:

- Generic console
- Low res graphics (@zx70 can you do this once the initial commit is in?)
- games.h (joystick)

Possible:

- Sound (if there's enough information out there)

Additional tools:

- font2pv1000 - converts 8x8 bitmaps into a format suitable for the PV-1000

**Comment by zx70** [comment]
cool, I'll have a crack at the PV-1000 graphics

**Comment by suborb** [comment]
Looking at it I think addressing the console directly will be quite neat - using vpeek and prints directly. That way we only have one set of code knowing about video ram layout etc

**Comment by suborb** [comment]
Sorry @zx70 couldn't resist doing this...

![screen shot 2018-05-21 at 21 54 45](https://user-images.githubusercontent.com/394721/40329517-aeb4795e-5d41-11e8-848f-6d59f03311c4.png)

**Comment by suborb** [comment]
I think bar any interrupt hooks and sound, that's PV-1000 finished.

So over to @Fabrizio-Caruso to make the 17th (?) game for this platform!

**Comment by Fabrizio-Caruso** [comment]
Thanks guys!

**Comment by zx70** [comment]
(hope it doesn't sound too gross in English)  ..I love that chunky crap  :)
