### ISSUE TITLE
z80asm: always crashes with vs2015 binaries

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#761]
z80asm crashes while building the zx library in branch `newlib_terminal_scroll_limit`.

Tested in windows.  The library can be built in windows by running "Winmake zx" from z88dk/libsrc/_DEVELOPMENT.  It can also be built in other systems by running "make TARGET=zx" from the same directory.

Edit: it crashes in the master branch too but passes on travis so must be windows only.  Binaries were built with VS2015.

**Comment by aralbrec** [comment]
Just to add, nothing compiles with z80asm currently using vs2015 binaries.

```
#include <stdio.h>

void main(void)
{
	printf("Hello World\n");
}
```

zcc +zx -v -clib=new test.c -o test -create-app

z80asm crashes at linking step

**Comment by pauloscustodio** [comment]
@aralbrec, I could not reproduce this in my Windows box. Can you post the z80asm executable where I can download it?
