### ISSUE TITLE
[question][OSCA] How to load the binary? 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#764]
I can compile my game for the OSCA but I cannot find any information on how to load the binary.
Any suggestion?

**Comment by zx70** [comment]
you must get an installed sdcard image.
once the emulator works an boots the FLOS operating system correctly,  then you can edit that disk image with your favourite FAT32 image editor (eg winimage) to add your exe file.

**Comment by Fabrizio-Caruso** [comment]
@zx70, I need to create an empty sdcard image and put the raw binary inside the image?
The emulator seems to have an option to load raw binary files but the option appears greyed.

**Comment by zx70** [comment]
no, appmake will create an EXE file for you, it will work similarly to msdos or cp/m

**Comment by Fabrizio-Caruso** [comment]
@zx70 None of the SD images supported by WinImage seem to be compatible with OSCA (emulator).
I have tried them all: ima, imz, flp, vfd. (img is not available)
The emulator (latest version) says [SD CARD] No volumes
a.exe or A.EXE always produce a "Unknown command" error.

Could you please give me the details on how I can test the OSCA target?
