### ISSUE TITLE
[einstein][appmake][question] The Tatung Einstein may use the same dsk as CPC

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#774]
While creating disk images for the Tatung Einstein with the recommended EDIP1E tool, I have seen that among the selectable formats one finds the "Extended CPC DSK", which seems to work (at least sometimes because this target freezes most times during the program load for a different reason).

If things are as they seem, we may get ready-to use disk images for the Tatung Einstein:
1. by compiling the einstein target to produce a raw binary
2. by running cpc app-make on the einstein binary to add the required header (in general it may be useful to have a way to select an appmake implementation from a different target)
3. by using cpcxfsw to insert the file with header into a disk image as I do for the cpc (see below)

```
...
	$(TOOLS_PATH)/cpcxfsw -nd FULL_cpc.dsk
	$(TOOLS_PATH)/cpcxfsw FULL_cpc.dsk -p build/FULL_cpc.cpc xchase
```

**Comment by zx70** [comment]
it seems a hint rather than a bug,  what are you asking exactly?

**Comment by Fabrizio-Caruso** [comment]
@zx70  indeed it is not bug. It is a hint and I am not sure it is a good one.
I just saw "Extended CPC DSK" as one of the options in EDIP1E and this made me think it the same disk format and appmake as CPC could be used.

**Comment by Fabrizio-Caruso** [comment]
I am closing this non-issue.
It is just a hint for a possible future feature (if my hint is right).
