### ISSUE TITLE
(classic) +m5 support rom target

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#777]
Cartridges load from $2000, there's a small header with address details of the true entry point.

They're really easy to load using the Takeda emulator so I'm going to make them the default type.

Similarly, I'm going to de-rom so that TMS9918 memory addresses are consistent across the various platforms.

Inkey support is worth doing as well.

**Comment by suborb** [comment]
I've got a hunch that the interrupt is reading the keyboard and making it beep when a key is pressed so I'll probably need to redirect the vector at $7002 and reimplement the timer.

**Comment by suborb** [comment]
@zx70 really, really dumb question. Where's the delete key? Is it the RESET key?

**Comment by zx70** [comment]
I couldn't answer,  glad to see you weren't waiting for me
