### ISSUE TITLE
[msx] Compiled examples won't run: "Bad file mode"

### ISSUE THREAD

**Issue by jannone** [z88dk/z88dk#786]
I have built z88dk from source (GitHub) and compiled the examples for the MSX computer.

When trying to run the .BIN resulting files on an MSX emulator, from the default BASIC environment, it gives a "Bad file mode" error, which could mean that the binary has an invalid internal format (i.e., it was not generated correctly)

TL;DR:
```
bload"ex1.bin",r
Bad file mode
Ok
```

Environment:
  * Mac OS High Sierra 10.13.4
  * OpenMSX v. 0.9.1 emulating MSX2 machine

**Comment by zx70** [comment]
Rafael !   It is great to see your post here :)  
examples/msx and examples/svi have a ready made makefile to build the examples..  try also to clean the built stuff and re-run it with the parameter:   COMPILER=sdcc
the speed boost on vpoke.c is impressive
