### ISSUE TITLE
[pps (sprinter)] Keys are wrongly detected

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#792]
Keys are wrongly detected.

I am going to provide a simple test.

**Comment by suborb** [comment]
@Fabrizio-Caruso have you got any more on this?

We just call the bios so it may have something to do with the emulator - if you run with the debug option on (it's an option in sprint.ini) then I think it logs the scan code to key value mapping.

**Comment by Fabrizio-Caruso** [comment]
I am going to isolate the problem to find out how keys are mapped.

**Comment by suborb** [comment]
I'm going to close this one since there's a lack of information and I haven't reproduced a problem.

**Comment by Fabrizio-Caruso** [comment]
Sorry, my fault! I will re-test it and let you know more.
