### ISSUE TITLE
[text background color][question]Default text background color

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#793]
If no text background color is explicitly set, it may be better to set it as the background.
In my game, for the Spectrum, I now get white text background on a black background.

When, for instance, I set the background color for the Spectrum target with:
			zx_colour(PAPER_BLACK|INK_WHITE);
I get white text background, which is maybe what one wants by default on a white background.

Should zx_colour also set the text background color

This seems a bug or unwanted behavior. I am getting this unwanted behavior on the Spectrum and not on other targets (msx, zx80, zx81, svi, etc.).

**Comment by suborb** [comment]
zx_colour() just clears the attributes on the spectrum screen, it has no interaction with the console. It does set the colour for the ROM printer which is possibly a bit weird.

Todo:

- Make 32/64 column use __zx_console_attr
- Make sure all read/writes to 23693 go to __zx_console_attr instead
- Verify that -pragma-redirect:__zx_console_attr=23693 works as expected.

**Comment by suborb** [comment]
Merged as #797
