### ISSUE TITLE
Missing .lst file within lst file doesn't error

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#795]
Issue #790 was caused by a missing a lst file that was included by another lst file. 

I would have expected the build to error, but it appears to have not done so.

**Comment by aralbrec** [comment]
If the list file is handed to zcc, the bug will be in zcc as it does its own list file processing.

**Comment by suborb** [comment]
This one is within z80asm - the library build for classic uses z80asm directly. Of course zcc might have the same bug!

**Comment by pauloscustodio** [comment]
Could not reproduce this in z80asm, both ';' and '#' are detected as comment chars.

**Comment by pauloscustodio** [comment]
Found it. Was a consequence of handling globs in list files.
