### ISSUE TITLE
[sc3000][sg1000/rom] Does not compile and produces "'-1' out of range"

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#808]
@suborb, I am now getting a different error with -subtype=rom

/cygdrive/c/z88dk/bin/zcc.exe +sc3000 -subtype=rom \
-O3 \
-DFULL_GAME -DEND_SCREEN -DBETWEEN_LEVEL \
-clib=ansi \
-pragma-define:ansicolumns=32 \
-vn -lndos -create-app \
-o build/FULL_sg1000.prg \
src/horizontal_missile.c src/rocket.c src/item.c src/end_screen.c \
src/missile.c src/invincible_enemy.c \
src/display_macros.c src/enemy.c src/level.c src/character.c src/text.c \
src/strategy.c src/input_macros.c src/main.c
Error at file 'c:/Z88DK/lib/../lib/target/sc3000/classic/rom.asm' line 72: integer '-1' out of range
Error at file 'c:/Z88DK/lib/../lib/target/sc3000/classic/rom.asm' line 74: symbol 'CODE_ALIGNMENT_ERROR' not defined
Error at file 'c:/Z88DK/lib/../lib/target/sc3000/classic/rom.asm' line 74: expected constant expression
3 errors occurred during assembly
Errors in source file c:\Z88DK\lib\config\..\..\\lib\target\sc3000\classic\sc3000_crt0.asm:
Error at file 'c:/Z88DK/lib/../lib/target/sc3000/classic/rom.asm' line 72: integer '-1' out of range
                   ^ ----         defs    $0066 - ASMPC
Error at file 'c:/Z88DK/lib/../lib/target/sc3000/classic/rom.asm' line 74: symbol 'CODE_ALIGNMENT_ERROR' not defined
                   ^ ----         defs    CODE_ALIGNMENT_ERROR
Error at file 'c:/Z88DK/lib/../lib/target/sc3000/classic/rom.asm' line 74: expected constant expression
                   ^ ----         defs    CODE_ALIGNMENT_ERROR
make: *** [Makefile:993: sg1000] Error 1

**Comment by suborb** [comment]
I sorted this one out earlier this evening, and actually ran it (since it wasn't midnight at the time!)
