### ISSUE TITLE
zsdcc: update to upstream sdcc 10423

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#809]
After a bout of manual patching, I've successfully built an update to the current sdcc for windows vs2015.

A patch can be found here:
https://drive.google.com/file/d/1imOy_Kr-dLfy1-MRALQPxmDgnzWezhj9/view?usp=sharing

There are problems in some compiles which I still have to look at and I still have to go back and make sure all the proper functions have been patched.

**Comment by spth** [comment]
To ease maintenance, and to increase the chance of some of the changes being merged upstream, I suggest to remove all cosmetic change (such as the indentation changes in src/z80/peep.c) from the patch.

Philipp

**Comment by Fabrizio-Caruso** [comment]
I hope my game would still work and compile

**Comment by feilipu** [comment]
Obsolete issue now.
