### ISSUE TITLE
[register][question] When is using the register keyword beneficial with sccz80 and/or zsdcc?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#811]
When is using the register keyword beneficial under sccz80 and/or zsdcc?

Under CC65 I know it produces better (smaller and faster) code when using in parameters that are pointers to structs.

**Comment by aralbrec** [comment]
sccz80 does not persist values in registers - something is done in a statement(s) and then registers are free again.

zsdcc already allocates to registers using an "optimal 8-bit register allocator" that Philip has written a paper or two about.  The register keyword is ignored.

**Comment by Fabrizio-Caruso** [comment]
Thanks
