### ISSUE TITLE
[zsdcc][zx81][vz200] --opt-code-size breaks the binaries

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#819]
On multiple targets I can see that if I compile with --opt-code-size (with ot without --max-allocs...) I get a malfunctioning binary. Maybe related to the issue about the positive effect of --max-allocs.

What I can see, when compiling the full version of my game, is:
--opt-code-size breaks the binary
--max-alloc... fixes the binary if --opt-code-size
-SO3 does not have any effect

So for example it looks like (only tested with zx81, vz200, svi and not all cases with all targets)
-SO3 -> KO
--opt-code-size -> KO
-SO3 --opt-code-size --max-alloc -> KO
--opt-code-size --max-alloc -> KO
--opt-code-size -SO3 -> KO
but
--max-alloc -> OK
-SO3 --max-alloc -> OK

**Comment by aralbrec** [comment]
Yes it might all come down to buggy code from the low max-allocs setting.  opt-code-size could be transforming the buggy code so it's not fixed in combination with max-allocs.

**Comment by spth** [comment]
Well, SDCC should never generate broken code, no matter how low --max-allocs-per-node is set. It might generate slower, bigger code that uses more memory, but the code should still work.
So if you can create a small reproducer that shows the problem also with current SDCC, please file a bug report with upstream SDCC.

Philipp

**Comment by feilipu** [comment]
Is this still the case?
Please check with r11311.

**Comment by zx70** [comment]
Fabrizio told me he's checking the new sdcc version.    reviving the topic

**Comment by Fabrizio-Caruso** [comment]
@zx70 This issue seems solved now! :-)
