### ISSUE TITLE
(classic) Add Samsung SPC-1000 support

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#833]
* Z80 @ 4Mhz
* MC6847
* AY-3-8910 @ 4MHz
* 64k RAM
* 32k ROM (Hudson Basic)
* Optional TMS9928A VDP w 16k - on 0xc800 (data) and 0xc801 (register)
* Joypad (on port A of the AY)

Bare bones:

- [x] Appmake support for +spc1000
- [x] Native console output
- [x] Inkey driver

Better:

- [x] Generic console
- [x] PSG support
- [ ] Joystick support

Best:

- [x] Graphics (hires monochrome)
- [x] Graphics (lores text - SPC-1000 has 16 blocky chars)
- [ ] Graphics (semi graphics - same as VZ? - 4x6 font?)
- [x] TMS9928A (standard msx library)

WiP in feature/spc1000 branch

Notes:

- Switch graphics mode on 0x2000
- Port 0xa000 banking control
- Same CRTC as MC-1000 and VZ-200
- VRAM via I/O? 0x0000 -> 0x1800 = 6k video screen + lower case character set 2k? - redefine by software?
- 256x192 hires available since there's enough VRAM

VDP support:

- [x] Allow an additional mode in generic_console_ioctl() that switches to the VDP
- ~VDP routines located in separate library (and just stubs in the main spc1000 library)~ CRT_ENABLE_VDP switches on the VDP
- [x] Console and graphics support need to detect mode and divert to VDP as appropriate
- "Silent" change mode ioctl that doesn't clear screen to switch back between (so we can actually have dual monitors)?

**Comment by suborb** [comment]
Merged as #834

**Comment by zx70** [comment]
I'v been looked for the Joystick code in the ROM (PSG instructions and BASIC keywords) but I wasn't able to recognize it (if it ever exists).
This code portion comes from the TS2068 technical manual (also not yet implemented in z88dk):

; joystick (player number = 1 or 2)
;Note that PSG Register 7, Bit 5 is assumed to be zero, enabling I/O Port A for input. If you
;ever use I/O Port A for output (R7,B6=1), you will want to clear Bit 6 prior to any input operation

LD A,OEH         ;Load A = 14
OUT A,(0F5H)    ;Address the joystick port
LD B,playerno
LD C,0F6H         ;Data Port address to C
IN A,(C)            ;Joystick data to A
CPL                  ;Complement to High Active
AND 8FH          ;Get significant bits
