### ISSUE TITLE
(classic) Add Bandai RX-78 support

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#842]
Some notes on this platform:

* SHARP LH0080A (Z80A) @ 4.1 MHz
* 8k IPL.ROM
* 14k RAM 0xb000 - 0xebff
* VRAM mapped at 0xec00 -> 0xffff 192x184 pixels
* SN76489A @ port 0xff
* Keyboard on 0xf4
* A mirrored(!) font is at 6951 (space) in IPL.ROM

Roms loaded to 0x2000 - bytes at 0x2000 should be 0x01, 0x00, 0x00 - only first byte checked

Vectors for rst calls in ROM:

0xe780 - rst8
0xe782 - rst10
0xe784 - rst18
0xe786 - rst30
0xe788 - rst38
0xe78a - nmi

0xeb71 - vector for start of font

Tasks:

- [x] Create appropriate ROM format that can be inserted into emulator
- [x] Native fputc_cons()
- [x] Generic console printing
- [x] Handle colour with generic console
- [x] Generic console vpeek (some issues around font mirroring still)
- [x] PSG support
- [x] Keyboard support
- [x] Joystick support
- [x] Hires graphics support

**Comment by suborb** [comment]
Work is in the feature/classic_rx78 - this up and running with a native fputc_cons()

**Comment by zx70** [comment]
"inverse on" sounds pertaining :D

**Comment by suborb** [comment]
Merged as #843
