### ISSUE TITLE
sccz80: When calling r2l add the '_' prefix to library functions

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#85]
This way the implementation can be shared with sdcc and we don't have duplicate library code.

**Comment by aralbrec** [comment]
We will still need to make a distinction for many cases.  sdcc only pushes one byte for a char argument and four for a float.  sdcc performs best when it is handling chars so I will be going through the new c lib to make sure it's getting as many functions as possible prototyped with char where appropriate.

**Comment by suborb** [comment]
I keep forgetting about that difference. Okay, I'll back this bit out and we'll have to stick with two differently named entry points.
