### ISSUE TITLE
OUT instruction in ZX Spectrum classic libraries

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#851]
This happens where a direct OUT instruction is used in the libraries:

Error at file 'stdio/ansi/spectrum/f_ansi_bel.asm' line 23: symbol '__PORT254COPY' not defined

What am I missing ?

**Comment by suborb** [comment]
I think you need to rebuild, I renamed it __SYSVAR_BORDCR on 2018-06-04 :)

**Comment by zx70** [comment]
:S   thankyou
