### ISSUE TITLE
z80asm: stringify numeric constant in defm

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#864]
I've come across the need to stringify a constant in a text string.

```
defc CORE_VERSION = 14010
defm "Requires Core v", CORE_VERSION, ' '+0x80
```

I'd like `CORE_VERSION` to be present as text instead of as numeric bytes.  A leading `#` as in the c pre-processor may be a good method:

```
defm "Requires Core v", #CORE_VERSION, ' '+0x80
```

Another way I can do this is with m4 but being able to do it in the assembler would be more convenient.

**Comment by zx70** [comment]
encoding the number with an expression on defb for every single digit is ..uhm.. less practical I suppose :)

**Comment by pauloscustodio** [comment]
OK. I'll put this in the preprocessor where I am working at the moment.

The hash is also used as prefix for hexadecimal numbers. I can check if the following word is a valid hexadecimal number, and stringify otherwise.

**Comment by pauloscustodio** [comment]
Commit e0d92ea03706a7c8466019742e6218f6d58fe6a2 has a partial fix. It will work if the number is defined as a macro (known at preprocessing time) but not if the constant is a DEFC (known at link time).
I.e. one has to write:
```
#define CORE_VERSION 14010
defm "Requires Core v", # CORE_VERSION, ' '+0x80
```
This commit is still in the z80asm_macros branch.

**Comment by pauloscustodio** [comment]
With the newly defined macro capability, this can be written as:
```
		defl CORE_VERSION = 14010
		defm "Requires Core v"
		reptc char, CORE_VERSION
		  defb char
		endr
		defm ' '+0x80
```

See macro documentation at https://github.com/z88dk/z88dk/wiki/Tool---z80asm---preprocessor
