### ISSUE TITLE
(z80asm) Not reporting invalid options

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#868]
In this post: https://www.z88dk.org/forum/viewtopic.php?pid=16685#p16685, Siggi is using `-IXIY` instead of `--IXIY` with the result that the ix and iy aren't swapped.

Can we issue a warning/diagnostic that an invalid option is being used.

**Comment by pauloscustodio** [comment]
The problem is that -IXIY is a valid option: adding directory XIY to the include path.

I will change it to be the same as --IXIY; if someone really needs directory XIY, they can write -I./XIY

**Comment by suborb** [comment]
Haha, good point!

It might be worth issuing a diagnostic message to indicate the mixed behaviour - adding both the XIY to the path and toggling the IXIY flag.
