### ISSUE TITLE
Instructions to patch and build sdcc don't work

### ISSUE THREAD

**Issue by Steve132** [z88dk/z88dk#872]
A large number of the chunks fail to patch when attempting to patch and build sdcc.  Can this be updated or some other process given?

**Comment by aralbrec** [comment]
The patch must be applied to sdcc 9958.  There are some details here:

**Comment by aralbrec** [comment]
The intention is not to be stuck at 9958 but to return to using the latest upstream sdcc as was done prior to 9958.

We may put zsdcc in as a submodule though with the source maintained at https://github.com/z88dk/zsdcc

As always, it's always a matter of free time and what is most pressing as to what gets done first.  This is not a static project - there are many things on the go and plenty more to do!
