### ISSUE TITLE
[SC3000][bug][keyboard] Keyboard input no longer working

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#873]
Keyboard input seems to be broken on the SC3000: 
1. my game waits for keyboard input forever.
2. if I disable the "wait for key" routine, my game starts and no key presses are detected

I compile it with:
```
sc3000_32k:
	$(Z88DK_PATH)$(MYZ88DK) +sc3000 \
	$(SCCZ80_OPTS) \
	-DFULL_GAME -DEND_SCREEN -DBETWEEN_LEVEL \
	-clib=ansi \
	-DCONIO -DNO_INIT_GRAPHICS \
	-pragma-define:ansicolumns=32 \
	-vn -lndos -create-app -Cz--audio \
	-o $(BUILD_PATH)/FULL_sc3000_32k.prg \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
	rm $(BUILD_PATH)/FULL_sc3000_32k.prg
	rm $(BUILD_PATH)/FULL_sc3000_32k.tap	
```

**Comment by suborb** [comment]
I can't reproduce this, the following works as expected:

    #include <stdio.h>
    int main()
    {

        while ( 1 ) {
        int k;
                while ( (k = getk())== 0)
                        ;
                printf("%d %c\n",k,k);
        }
    }

Compile lines tested:

    zcc +sc3000 getk.c -create-app -subtype=rom -clib=ansi
    zcc +sc3000 getk.c -create-app -subtype=rom

**Comment by Fabrizio-Caruso** [comment]
I will try to better isolate the issue in my code and provide more details.

**Comment by Fabrizio-Caruso** [comment]
@suborb 
If I include the very same code in one of the first functions called at start-up I get a frozen screen and no response to input:
```
void INIT_GRAPHICS(void)
{
	#if defined(__SC3000__)
		while ( 1 ) {
		int k;
				while ( (k = getk())== 0)
						;
				printf("%d %c\n",k,k);
		}
	#endif
...
```

I am compiling the game with:
```
sc3000_32k_udg:
	$(Z88DK_PATH)$(MYZ88DK) +sc3000 \
	$(SCCZ80_OPTS) \
	-DFULL_GAME -DEND_SCREEN -DBETWEEN_LEVEL \
	-DCONIO \
	-vn -lndos -create-app -Cz--audio \
	-DANIMATE_PLAYER \
	-DUDG_GRAPHICS \
	-clib=default -pragma-redirect:fputc_cons=fputc_cons_generic \
	-o $(BUILD_PATH)/FULL_sc3000_32k_udg.prg \
```

**Comment by suborb** [comment]
The big difference is that I’m using the rom subtype - I couldn’t find the appropriate basic - which is also compatible with the sg1000. 

If I remember correctly keyboard reading is a two stage process so there’s a possibility that the BASIC ROM is interfering. 

I don’t know the last time you had it working, but The major change on this target was at the end of may.

**Comment by Fabrizio-Caruso** [comment]
End of May could be the last time I tested the SC3000. It was even tested on real hardware! :-)

I am using Sega_BASIC_Level_3_V1_(SC-3000) as BASIC ROM.

**Comment by Fabrizio-Caruso** [comment]
The keyboard input now "works" in BASIC mode. It is the original rom routine. Not good for gaming but better than no input. 
I wonder why this routine interferes with the one you wrote for the rom mode.

**Comment by suborb** [comment]
I’m guessin

**Comment by Fabrizio-Caruso** [comment]
@suborb whay should I them do if I want to use BASIC mode (that is the most useful mode with real hardware) and the best keyboard input routine?

**Comment by Fabrizio-Caruso** [comment]
What may be failing in
https://github.com/Fabrizio-Caruso/CROSS-CHASE/blob/master/src/chase/main.c
is
```
...
				--lives;
				if(lives>0)
				{
					player._status = 1;
}
...
```

I am going to try a few things:
1. to compile without optimization 
2. change the code if something like "if(--lives>0)" and see if I get the same problem
3. maybe I will try to isolate the issue but it may be complicated

**Comment by Fabrizio-Caruso** [comment]
@aralbrec  
PROBLEM isolated:
KO: 	--lives; if(lives>0) ...
OK: 	if(--lives>0)...

the KO case is somehow miscompiled.

CC65, ZSDCC, GCC all compile the code correctly
