### ISSUE TITLE
[sord m5][sound] bitbang noise are wrong and very longs (few seconds)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#880]
PSG sound in M5 seem all wrong 

Bit bang sound seems ok except of all noise sound (explosions) which lock the computer for a few seconds with a slow and low pulsing sound/noise.

The keyboard sounds may be the culprit. How do I disable the keyboard from generating clicks/beeps?

**Comment by suborb** [comment]
@Fabrizio-Caruso did switching to getk_inkey() solve this issue?

**Comment by Fabrizio-Caruso** [comment]
@suborb 
This issue is superceded by #877, which covers similar issues for multiple targets.
