### ISSUE TITLE
[sord m5][beep] Beep from keyboard routine

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#881]
It would be nice to remove the beep produced by the rom keyboard routine.

Remark: I can mitigate it a bit by writing the value 1 into
0x703A (frequency)
0x703B (duration).

I fear that there is no way to avoid this beep with the rom routine :-(

**Comment by Fabrizio-Caruso** [comment]
Probable solution found:
```
POKE(0x701A,PEEK(0x701A)&0x7F);
```
seems to solve the issue.

Please consider this solution as an initialization of the keyboard routines.

**Comment by suborb** [comment]
Have you tried using getk_inkey()

**Comment by Fabrizio-Caruso** [comment]
@zx70 I don't know which targets have getk_inkey()... I will try it on the Sord M5 but I found a solution to disable the click anyway (unset bit 7 of 0x701A).
I tried on other targets and it was not found. I would need getk_inkey() for the SVI because the rom routine for the Spectravideo is not usable for games (keeping a key press is detect with a huge delay).

**Comment by suborb** [comment]
I’ve been doing them as problems arise with the firmware drivers. 

Given that there’s a problem with the svi I’ll tackle it next weekend.

**Comment by Fabrizio-Caruso** [comment]
@suborb  thanks!

Worst case is SC 3000 now no longer working in Basic mode since mid-May
#873

**Comment by suborb** [comment]
Yeah. As I mentioned I was focusing on the rom target. 

I didn’t delete the code so I’ll restore the basic mode key input and just use inkey for the rom mode.
