### ISSUE TITLE
[pc6001][psg] Frozen after start if psg code is used

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#883]
PC6001 freezes after loading if psg code is used.
It seems to work ok otherwhise.

**Comment by suborb** [comment]
Trying out psgtest.c in z88dk examples, this plays correctly for: PC6001 (.cas, .rom) PC6001mk2 (.cas, .rom)

**Comment by Fabrizio-Caruso** [comment]
Sorry for not being more specific: I get this issue with my game, which is occupying more memory.
I may try the TINY or LIGHT version of the game and let you know.
