### ISSUE TITLE
[sccz80][compiler][bug] Zero test / Wrong result

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#886]
SCCZ80 is producing a slightly wrongly behaving version of my game:
you get 6 lives instead of 5. 
Somehow the check on the number of lives is not executed at the right moment

I am getting the right result with ZSDCC and GCC.

**Comment by aralbrec** [comment]
Do you have a code fragment where the fail occurs?

**Comment by Fabrizio-Caruso** [comment]
@aralbrec  SCCZ80 seems to be compiling the KO cases as:
--lives; if(lives>0) = if(lives-->0)
which is wrong

**Comment by suborb** [comment]
I think there’s an error in the -O3 ruleset. It doesn’t seem to show up at the default level.
