### ISSUE TITLE
[spectrum][joystick] Joystick other than Sinclair1 broken

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#887]
It seems that only Sinclair joystick is working.
If I select 1 (for Kempson), joystick(1) detects an UP movement. 

Remark: Tested Fuse and EightOne emulator

**Comment by aralbrec** [comment]
On a real spectrum, reading kempston without a kempston interface attached will result in false directions being read.  On emulators, the kempston interface has to be enabled for it to work... was the testing on the emulators done with kempston explicitly enabled?

**Comment by Fabrizio-Caruso** [comment]
You are right! Sorry!
