### ISSUE TITLE
[pps][input] Keeping a key pressed slows down the computer significantly

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#900]
Keeping a key pressed slows down the computer significantly

Tested with my game Cross Chase

**Comment by suborb** [comment]
Sorry there's nothing we can do about this, this is an emulator issue, the following demonstrates the issue:

```
#include <stdio.h>

int main() {
        unsigned char i = 0;
        while ( 1 ) {
                i++;
                fputc_cons((i %32)+ 'A');
#asm
        ld      c,$31   ;SCANKEY
        rst     $10
#endasm
        }
}
```

The assembler calls directly into the emulator (it's the same code used by getk()) into the file estex.cpp so there's something slow in there. Pressing a key when not scanning the keyboard has no ill effect.

**Comment by suborb** [comment]
Ah, the problem is this line in sprint.cpp:

```
 if(D||E)
 {
  if(fdebug!=NULL) fprintf(fdebug,"\n>>> KBD #%2.2X #%2.2X (%c)\n",D,E,(E>32)?E:' ');
//  if(E&&!flag)
    delay(120);
 }
```

Where if there's a keypress then it pauses for a while!

**Comment by Fabrizio-Caruso** [comment]
Where is this code? The emulator?

**Comment by suborb** [comment]
Yes, it's the emulator source code.

I've got a version that's 64 bit clean and compiles on a Mac here: https://github.com/suborb/sprint

Shaos used to have a copy on GitHub, but I presume he's moved it to somewhere on gitlab: https://gitlab.com/shaos

**Comment by Fabrizio-Caruso** [comment]
Thanks @suborb for the investigation!
