### ISSUE TITLE
[eg2k][udg] Wrong characters and flashing cursor

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#901]
When compiling for the eg2k with redefined characters I get wrongly displayed letters and a flashing cursor in the top left corner.

I compile with:
```
eg2k_udg:
	$(Z88DK_PATH)$(MYZ88DK) +trs80 \
	-D__EG2K__ \
	-subtype=eg2000disk \
	$(SCCZ80_OPTS) \
	-D__EG2K__ \
	-DFULL_GAME  \
	-DEND_SCREEN -DBETWEEN_LEVEL \
	-DCONIO_VT52 \
	-DCONIO \
	-lndos \
	-DANIMATE_PLAYER \
	-DUDG_GRAPHICS \
	-DLESS_TEXT \
	-clib=default -pragma-redirect:fputc_cons=fputc_cons_generic \
	cross_lib/display/init_graphics/z88dk/udg/udg_init_graphics.c \
	cross_lib/display/graphics_data/z88dk/xchase.asm \
	chase/end_screen.c \
	$(FULL_FILES) \
	-create-app -o$(BUILD_PATH)/FULL_eg2k_udg.bin
```

![eg2k_1](https://user-images.githubusercontent.com/29057615/44661590-61626280-aa0b-11e8-97b9-3bc42825bd48.jpg)
![eg2k_2](https://user-images.githubusercontent.com/29057615/44661593-632c2600-aa0b-11e8-8084-54d71e074d09.jpg)

**Comment by suborb** [comment]
Sorry that was a bit of cleanup idiocy from me a while back.

Should now be restored, it looks like you need to switch to mode 1 to enable custom font (I'm not sure why I did it that way to be honest so I'll probably remove that unless I can think of a compelling reason to keep it)

Cursor is now disabled as well.
