### ISSUE TITLE
zsdcc: Bug in __smallc calling convention (chars pushed as single byte not word)

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#902]
When zsdcc calls functions with a char argument it only pushes a single byte on the stack.

For compatibility with sccz80 it should be pushing a word.

This has been present for a while and has been worked around by promoting chars to ints in classic function prototypes.

However, that's not a great solution when classic pulls in newlib code.

**Comment by spth** [comment]
Is this about char only? Also about unsigned char? signed char? How is the 8-bit value to be converted to the 16-bit value? Any value for the upper 8 bits allowed? Sign-extended? Zero-extended? Depends on the 8-bit type?

Philipp

**Comment by suborb** [comment]
Good questions. It affects both signed and unsigned char. Any value is permitted for the upper 8 bits.

**Comment by spth** [comment]
Assuming, that _Bool is 16-bit in __smallc calling convention, too, this is fixed in upstream SDCC as of today (so the fix will be in 3.8.0).

Philipp

**Comment by suborb** [comment]
Ah brilliant. Thank you Philipp. Apologies for not responding as well.

**Comment by suborb** [comment]
Closing this one now we're up to SDCC 3.8.5
