### ISSUE TITLE
[Bandai Rx-78 and Casio PV2000][question] How to test?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#903]
What do I need to test the rom that Z88DK creates?

I am using Takeda specific emulator.
Inserting the rom gives a black screen.

Do I need additional roms or settings?

**Comment by suborb** [comment]
I've got an ipl.rom, 8192 bytes: MD5 (ipl.rom) = f613b15c4b965013e4827d2ad79c7080

It is required because it detects whether a cartridge has been inserted and then jumps to it as well as handling the interrupt etc

**Comment by Fabrizio-Caruso** [comment]
I need a similar rom for the Casio PV 2000

**Comment by Fabrizio-Caruso** [comment]
and for the multi8...

**Comment by Fabrizio-Caruso** [comment]
and maybe others... Is MAME also a viable emulator for these systems?

**Comment by suborb** [comment]
I'll send you (via email) a zip file of my environment for these emulators that have the ROMs.

**Comment by suborb** [comment]
I’ll close this one since you’ve got the ROMs now.
