### ISSUE TITLE
[Bandai rx-87][video][bug] Image appears left-right mirrored + wrong colors

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#905]
Image appears left-right mirrored and colors are wrong (e.g., yellow appears as blue).

I am compiling my game (with re-defined characters)

**Comment by suborb** [comment]
The display on the rx78 is mirrored. The rom font is stored in the native format. 

There’s code to mirror fonts as they are being printed but my detection is obviously awful and doesn’t spot that your font isn’t in the ROM. 

I’ll fix it later this evening - it’s an easy one. And map the colours as well.
