### ISSUE TITLE
[spc1000][question] espc1000 emulator?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#906]
I don't understand which emulator can read the .spc file.
The doc (https://github.com/z88dk/z88dk/wiki/Platform-Samsung-SPC-1000)
provides no links and only mentions espc1000.
Googling for espc1000 finds nothing.
It does not seem to be part of Takeda emulators.
Could you provide a link to the emulator's page and info on the required extra files (roms, configs, etc.)

**Comment by suborb** [comment]
I've sent you an email with the emulators - I'm really not sure why they aren't public.
