### ISSUE TITLE
[mz2500][create-app] No create-app but it is mentioned in the doc.

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#909]
The doc mentions the -create-app
https://github.com/z88dk/z88dk/wiki/Platform---Sharp-MZ2500

but it is not recognized:
Unknown machine target "mz2500"

**Comment by suborb** [comment]
I think Stefano forgot to commit the file that hooks it in. I've added the hook so it should now be a recognised target.
