### ISSUE TITLE
correct pattern for ZX spectrum RS232?

### ISSUE THREAD

**Issue by tschak909** [z88dk/z88dk#915]
What's the correct programming pattern to use the RS232 functions?

I currently have 

`

void io_main(void)
{
  res=rs232_get(&ch[0]);
  if (res!=RS_ERR_NO_DATA)
    {
      ShowPLATO(&ch[0],1);
    }
}

// The keyboard functions are handled outside this loop, in keyboard_main();
// and keyboard_main() and io_main() are called in succession, repeatedly, without
// pause.

`

Which ultimately causes the borders to stay almost black, and prevents the keyboard from being read properly. I need to be able to read and process rs232 data, while also taking input from the keyboard.
(a la, a terminal program)

-Thom

**Comment by tschak909** [comment]
![platoterm_weird](https://user-images.githubusercontent.com/2759782/44771074-9536a880-ab2f-11e8-8c3a-c4aa010b7f64.gif)

**Comment by tschak909** [comment]
I'm setting it at 1200bps.

**Comment by tschak909** [comment]
well, ostensibly here, nothing is being recieved. at the screenshot above, I am just interacting with the virtual modem... What should I do here to try and deal with this problem? Do you have any example terminal code?

**Comment by zx70** [comment]
forgive my lack of precision,   but I don't have a real computer at hand. ..   this was the last piece of code where I used the rs232 functions:

https://www.z88dk.org/wiki/doku.php?id=examples:snippets:zxspectrum:opusdump

which serial library are you linking?  zx128? if1?
________________________________

**Comment by tschak909** [comment]
Am trying to use if1.  I do not have any hardware either, am just using
FUSE. Trying to support everything I can.

**Comment by zx70** [comment]
I think I tested the first lib implementation with the old Gerton Lunter's Z80 emulator,  then I moved to Real Spectrum.  Be sure to set up correctly the serial port redirection e.g. testing the communications with some basic command first or a known working emulator.   It is very long time this library wasn't checked,  so it could also be something broken.    also,  don't forget to initialize the driver

**Comment by zx70** [comment]
I see you are on FUSE, have you tried the '--rs232-handshake'  option ?

**Comment by desertkun** [comment]
@zx70 sorry for bringing up an old thread, but I am out of options on how to make my similar problem to resolve. I want to make RS232 on ZX Spectrum 128 I am emulating in FUSE to work, no luck. Maybe something missing?
Code:
```C
int main()
{
    if (rs232_init() != RS_ERR_OK) {
        printf("Error\n");
        return(2);
    }
    if (rs232_params(RS_BAUD_9600, RS_PAR_NONE) != RS_ERR_OK) {
        printf("Error\n");
        return(2);
    }

    printf("RS232 OK\n");

    rs232_put(SOH);
    rs232_put('t');
    rs232_put(EOT);

    printf("SEND OK\n");

    return 0;
}
``` 

I have compiled this and trying to run it on FUSE with following options: `Fuse app.tap --rs232-handshake --rs232-tx ./slave --rs232-rx ./slave`

I also have a `socat` running that emulates a serial port for me: `sudo socat pty,link=./master,raw,echo=0,user=<user> pty,link=./slave,raw,echo=0,user=<user>` which essentially creates a pair of interlinked serial files `master` and `slave`. I have verified that socat works with two instances of screen.

Now I am running screen on one side, and just COULDN't get the speccy to send anything to it. All I get is `(null): couldn't identify ./slave`.

Thanks I hope for your wisdom.

**Comment by zx70** [comment]
The Spectrum had, in its more common configurations, a simplified software driven RS232 interface.
I hardly believe the existing emulators are capable of catching the bit-banging loops and remapping them into valid RS232 commands, they rather trap specific entry locations in ROM, but our code drives the serial port directly both for flexibility (e.g. dealing with Spectrum 128 pages) and to prevent undesired BREAK effects when SPACE is pressed.   I'm afraid you need the real hardware to test your program.
Remember also to link in the correct RS232 library, Spectrum 128 and Interface 1 have different hardware.
