### ISSUE TITLE
[abc80][input][bug] Fail to detect key-releases - Keeps detecting last key pressed

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#926]
The ABC80 target has malfunctioning input:
It never detects key-release. Once a key is pressed down, it keeps detecting it as pressed down.

Tested with ABC80SIM Windows port by @zx70 

I compile it with the NO_WAIT option in order to get in-game because it would otherwise get stuck while waiting for a key-release before starting:
```
abc80_16k:
	$(Z88DK_PATH)$(MYZ88DK) +abc80 -lm -subtype=hex -zorg=49200 $(SCCZ80_OPTS) \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DNO_WAIT \
	-D__ABC80__ -clib=ansi -vn  -lndos -create-app -o a \
	$(LIGHT_FILES)
	rm a
	mv a.ihx $(BUILD_PATH)/LIGHT_abc80.ihx 
```

**Comment by suborb** [comment]
Make getk work in the same was fgetc_cons

This means we'll only get a single press for a keyboard.

The abc80 doesn't have autorepeat so since we're relying on the ROM to populate the address any consumers won't have autorepeat either.

To get autorepeat an inkey() is probably needed

**Comment by Fabrizio-Caruso** [comment]
@suborb 
The issue seems still present.
getk() does not detect keys pressed down.
getk_inkey() is not found.

Should I use something else?

**Comment by suborb** [comment]
As mentioned, the abc80 doesn't have autorepeat so it only registers one press no matter how long the key is held down for.

I've not implemented getk_inkey() for the ABC yet

**Comment by suborb** [comment]
I don't see much point implementing an inkey() driver:

- Only a single key press is detected
- I don't think the hardware supports autorepeat
- The two emulators behave differently (abcwin reports keyrelease by marking the character with 0x80, abc80sim doesn't)

Run the following example and you'll see what I mean:

```
#include <stdio.h>

int addr()  __naked {
#asm
        in      a,(56)
        ld      l,a
        ld      h,0
        ret
#endasm
}


main()
{
        int     lv = 0;
        printf("Hello world! %d\n",12);
        while ( 1) {
                int i = addr();
                if ( i != lv ) {
                        lv = i;
                        printf("i=%02x %c\n",i,i);
                }
        }
}
```

And I can't reproduce the getk() problem that you originally reported with the latest code, again, here's a snippet:

```
#include <stdio.h>

main()
{
        printf("Hello world! %d\n",12);
        while ( 1) {
                int i = getk();
                if ( i != 0 ) {
                        printf("i=%02x %c\n",i,i);
                }
        }
}
```
