### ISSUE TITLE
[spectrum][udg][bug/question] How can I use the new standad udgs?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#929]
I am getting 
- wrong font-size (64 columns), 
- wrong background colors, 
- wrong character colors and 
- no displayed udgs 
if I try to treat the Spectrum target like all the other udg-capable targets by compiling it with:
```
	$(Z88DK_PATH)$(MYZ88DK) +zx $(SCCZ80_OPTS) -v  \
	-DFULL_GAME \
	-DANIMATE_PLAYER \
	-DSOUNDS \
	-DEND_SCREEN -DBETWEEN_LEVEL \
	-D__SPECTRUM__ \
	-DALT_MOVE \
	-lndos -create-app \
	-DCONIO \
	-DUDG_GRAPHICS \
	-pragma-define:ansicolumns=32 \
	-pragma-redirect:fputc_cons=fputc_cons_generic \
	-o $(BUILD_PATH)/FULL_spectrum_48k.prg \
	$(CROSS_LIB_PATH)/display/init_graphics/z88dk/udg/udg_init_graphics.c \
	$(CROSS_LIB_PATH)/display/graphics_data/z88dk/xchase.asm \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
```
Removing -pragma-define:ansicolumns=32 has no effect.
Should I use clib=ansi, clib=default?

**Comment by suborb** [comment]
* By default the console starts up in 64 column mode. To switch issue the byte sequence 1,32
* UDGS are only displayed in 32 column mode 
* Colours are now mapped

Docs are the extensions to the console for the ZX are here: https://github.com/z88dk/z88dk/wiki/Platform---Sinclair-ZX-Spectrum#console-driver-modes

**Comment by Fabrizio-Caruso** [comment]
@suborb THANKS a lot! 
So, I will need something like: printf("%c%c",1,32); ?
Why not the same API as the one for targets with the 6847 when you use an explicit screen mode command?

**Comment by suborb** [comment]
The screen modes came later on - here it's the same screen mode but a different font size.

Having it in the stream means that it's possible mix both 64 and 32 column text on the same display.

Adding an ioctl probably does make sense - it would do a CLS at the same time (as does every other port).

**Comment by Fabrizio-Caruso** [comment]
How do I set the background for the Spectrum with a generic command? It is black by default on the other targets with udg-support (when black is available).

**Comment by suborb** [comment]
Have you tried textbackground() ?

**Comment by Fabrizio-Caruso** [comment]
Thanks! It does work for the Spectrum but not for the C128 (which does not have it)! 
Is there a cross-target solution for the border color?

**Comment by suborb** [comment]
There should be one for -subtype=ansi unless there’s a typo anywhere. You can always send the vt100 escape code. 

There’s bordercolour() - it may not be implemented on all targets though.
