### ISSUE TITLE
[wiki][installation] Tell that Windows install path should not contain spaces

### ISSUE THREAD

**Issue by nippur72** [z88dk/z88dk#930]
When installing for Windows it should be stated that the install path must not contain spaces. E.g.
```
C:\Program files (x86)\z88dk
```
won't work.

Also the suggested `test.c` should not contain apostrophes:
```
#include `<stdio.h>`   // wrong
#include <stdio.h>     // correct
```

**Comment by zx70** [comment]
Thanks for the 'heads up',  I corrected the wiki as suggested.
