### ISSUE TITLE
[c128][bug/question] Background color is grey

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#932]
Background color on the C128 starts grey.
How can I set it to black or any other color?

In the VIC-II registers are somewhere else because
	POKE(53281u,0);
is not changing the background color.

**Comment by zx70** [comment]
I chose the gray color to keep all the colors visible in ANSI mode (black included).
Should I change to black ?

For the record, the way to set the background color in Z80 ASM on a C128 is:


	ld	a,11		;dark grey
	ld	bc,$d020
	out	(c),a	;border
	inc	c
	out	(c),a	;& background

..the POKEable addresses are remapped to the OUT instruction only.

**Comment by Fabrizio-Caruso** [comment]
Black is what you get in most other targets.

The ideal solution is to provide some standard API to change the background color. Is there a way to do it in a generic way?

  Fabrizio

--
Inviato da myMail per Android

mercoledì, 12 settembre 2018, 03:51PM +02:00 da Stefano notifications@github.com<mailto:notifications@github.com>:


I chose the gray color to keep all the colors visible in ANSI mode (black included).
Should I change to black ?

For the record, the way to set the background color in Z80 ASM on a C128 is:

ld      a,11            ;dark grey
ld      bc,$d020
out     (c),a   ;border
inc     c
out     (c),a   ;& background


..the POKEable addresses are remapped to the OUT instruction only.

**Comment by Fabrizio-Caruso** [comment]
I would like to have a black background.
Poking into memory does not work. I guess it is bank switched.

**Comment by zx70** [comment]
it is not bank switched, with the Z80 you must use the OUT instruction (as for an I/O address).   the POKE access is disabled.

**Comment by zx70** [comment]
change applied   ;)

**Comment by Fabrizio-Caruso** [comment]
Thanks!
