### ISSUE TITLE
[einstein][appake] No Sector 1 error

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#943]
When building my game for the einstein I get a malformed disk: which produces a "NO Sector 1:" error

I have compiled my game with:
```
	$(Z88DK_PATH)$(MYZ88DK) +cpm -subtype=einstein -leinstein \
	$(SCCZ80_OPTS) \
	-pragma-define:ansicolumns=32 \
	...
	-clib=ansi \
	-create-app -o$(BUILD_PATH)/FULL_einstein.bin \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
```

@suborb 
![einstein](https://user-images.githubusercontent.com/29057615/45029247-567d8280-b048-11e8-92c3-31c7faf3f9e4.jpg)

**Comment by suborb** [comment]
I think it's a program size thing - looking at the directory entry for adv_a (which uses up the same disc space) it looks like the RC field is being calculated incorrectly and this is the cause of the error.

**Comment by suborb** [comment]
Hopefully sorted now, I can now load adva from disc so cross chase should be ok.

**Comment by Fabrizio-Caruso** [comment]
Things are worse now.
I can load APP.COM but it crashes with a corrupted screen.
<img width="613" alt="einsten2" src="https://user-images.githubusercontent.com/29057615/45083673-bc2b4680-b0fc-11e8-9a26-432a48b623ac.png">

**Comment by Fabrizio-Caruso** [comment]
This is memory-related because if I compile with sdcc and optimizations, I get a working game.

**Comment by suborb** [comment]
I've fixed it again (RC field again!) - I think it was only loading 8k of the program so it was potluck as to whether things appeared to work.
