### ISSUE TITLE
[attache][question][imageDisk] Open alternative for bin2imd? It cannot be run on Win 64 bit

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#953]
I am following the instructions in the doc on how to build floppy images for the attache target.

The recommended tool is imageDisk, which cannot be run under Windows 10 64 bit or Cygnwin 64 bit.

Are there alternatives that can be run under any Windows version and possibly under Linux?

**Comment by Fabrizio-Caruso** [comment]
Moreover the source files I have managed to find do not compile. It may be possible to fix them, though.

**Comment by suborb** [comment]
I haven't looked too deeply, but I suspect John Elliot's libdsk probably has something.

**Comment by suborb** [comment]
I've updated appmake so that there's an attache target. This reuses the +einstein code to create a compatible .dsk image that can be inserted directly into mame.

So there's no messing around with 3rd party tools.

**Comment by Fabrizio-Caruso** [comment]
@suborb Thanks a lot!

**Comment by Fabrizio-Caruso** [comment]
@suborb Osborne1 has a similar issue. The doc only suggests using bin2imd. Is it possible to apply the same code to this target?

**Comment by suborb** [comment]
I've not tested it (beyond verifying that cpmtools works on the image using the osborne1 format).

But `+cpm -subtype=osborne1` should now generate an osborne1 disc
