### ISSUE TITLE
Docker example error "sh: m4: not found"

### ISSUE THREAD

**Issue by gitowiec** [z88dk/z88dk#956]
Hi
I am absolute beginner with z88dk so excuse my ignorance. I am tring to run docker example as described in https://github.com/z88dk/z88dk/wiki/Docker-Usage. I encountered said error in topic.
My system is Ubuntu-Budgie 18.04 with Docker version 18.06.1-ce(, build e68fc7a).

It seems that I successfully build the *vanilla image* (there were some warnings but no warning stopped build process). I don't know if I need customized image so I just put customization away (I would like to write a program in C for ZX Spectrum)
Then I thought I will try to run an example *Compiling BlackStar SP1 example with sccz80:*
After I changed directory to `_DEVELOPMENT/EXAMPLES/zx/demo_sp1/BlackStar` and deleted *.tap files I run first command:
```bash
docker run -v ${PWD}:/src/ -it z88dk zcc +zx -v -startup=31 -DWFRAMES=3 -clib=new -O3 @zproject.lst -o blackstar -pragma-include:zpragma.inc
```
which gives me this output ending with error:
```
(..... a lot of compiler output)
sh: m4: not found
```
After few hours of digging into docker/alpine/apk options I managed to correct this issue with change in https://github.com/z88dk/z88dk/blob/f7517378ac5a08b35532040b17403fb714f8e312/z88dk.Dockerfile#L17
The problem is with `apk -t` it is forcing the packages installed in https://github.com/z88dk/z88dk/blob/f7517378ac5a08b35532040b17403fb714f8e312/z88dk.Dockerfile#L18 line to add them to "virtual package" `.build_deps` and then discard this package (uninstall) in line 40 https://github.com/z88dk/z88dk/blob/f7517378ac5a08b35532040b17403fb714f8e312/z88dk.Dockerfile#L40

And as seen above, examples using docker image need m4 to compile.

~~I am preparing pull request with `z88dk.Dockefile` correction. Just wait a second for it.~~
Here is pull request https://github.com/z88dk/z88dk/pull/958

**Comment by suborb** [comment]
Thank you for both the great explanation as to what was wrong and the actual fix.
