### ISSUE TITLE
[sprites][feature] Select color of each monochromatic sprite?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#961]
Monochromatic sprites by definition have one color but the screen may have different colors.
On some cases the color attributes can be set on each pixel like on the 4-color 128x64 mode of the VZ200 with no color clash.
On some other cases color attributes affect entire areas (8x8, 8x1, etc.) with possible color clash.

It would be cool to have standard APIs to set the color of sprites at least in those cases where color attributes do not produce color clash. Can I choose the color of a sprite on the VZ200?
Ideally cases with color clash should just be possible (it is up to the coder to decide what to do).
Z88DK already does a great just on text with conio where color is set even if color clash can show up.

So there is already code that is colorizing characters in bitmap mode. Couldn't this code be used to give sprites a color?

**Comment by zx70** [comment]
I tend to say no.  The monochrome sprites graphics can be already colorized on some target, under very particular circumstances (see wall.c) but the correct approach would be a parallel library for the different sprite mode (e.g. the sprite pack supports color sprites).   The monochrome sprites are as simple as possible to save size and/or speed and their size flexibility makes them not adequate for a generic extra layer able to add color..  I'd rather see as possible a generic 8x8 attribute change on the screen area for an interesting number of machines.

**Comment by Fabrizio-Caruso** [comment]
Z88DK has color sprites in the sprite pack? I have missed that..
Yes, I agree, a generic 8x8 API for color change for Spectrum, VDP and many other systems would be great.

**Comment by zx70** [comment]
the api is quite complete for the spectrum,  I'm tempted to port some of those functions keeping the zx_  prefix
