### ISSUE TITLE
[c128][improvement] The binaries take time to start

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#973]
C128 binaries take some time to start (a bunch of seconds).
I have no idea what it is doing.
@zx70 suggests it may be related to memory compressed sections.
Are these compressed sections really necessary?

I see that during this processing, the VIC is on.
One can get a little speed-up (about 7%) by just disabling the VIC and re-enabling it afterwards.
This is done by setting bit # 4 to 0 (off) or 1 (on) of VIC register $D011.

(I am well aware that this is not the same thing as fast mode for the 8502)

**Comment by zx70** [comment]
Fabrizio, I tried to run ADV_A with graphics enabled (rather big) and I didn't notice the delay you are claiming for.    perhaps your program does something different but I can't notice a delay on start-up with the z88dk examples. .   I wonder if a function you use is failing somehow..
