### ISSUE TITLE
[s-os][question] Cannot load .obj file

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#975]
I cannot load and run the .obj file produced by z88dk.

I build a 4k binary with:
```
	$(Z88DK_PATH)$(MYZ88DK) +sos \
	-O3
	-lndos \
...
	-create-app \
	$(CROSS_LIB_PATH)/display/alt_print/memory_mapped_alt_print.c \
	$(TINY_FILES)
```
I don't know how to enter the Monitor in most emulators.
I can with mz800emu but
#<space> a.obj
does nothing
#L a.obj
opens a menu that only allows loading mzf images.

**Comment by zx70** [comment]
s-os is an operating  system.   you need first to boot s-os, then load the z88dk generated program.
an s-os impldmentation including z z80 emulator exists and permits to avoid the hassle of transferring files on the target disk

**Comment by Fabrizio-Caruso** [comment]
@zx70  I know. I enter the monitor but the obj file cannot be loaded under mz800emu. So I wonder what is wrong.

**Comment by zx70** [comment]
I'm confused.   Are you providing the s-os mzf file or the z88dk obj?    In the latter case the mz800 monitor won't be able to load it:  s-os is mandatory.

**Comment by Fabrizio-Caruso** [comment]
@zx70 I would like to load the obj file.

**Comment by zx70** [comment]
I never tried with the MZ800, but I suppose you need an S-OS disk to boot.
The obj file should be copied onto it.

**Comment by Fabrizio-Caruso** [comment]
I just would like to know how to test the s-os target in its generic brand-less format, i.e., obj

**Comment by zx70** [comment]
try by  running the unix or windows port, I think it is  at the end of this section: http://www.retropc.net/ohishi/s-os/#3

**Comment by Fabrizio-Caruso** [comment]
@zx70  THANKS! It works fine! One more target!
