### ISSUE TITLE
[z88][appmake][bug] -create-app is not recognized

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#976]
I am trying to compile a simple "Hello World" example:
```
	$(Z88DK_PATH)$(MYZ88DK) +z88 $(SCCZ80_OPTS) -create-app \
	$(SOURCE_PATH)/../experiments/hello.c 
```
but I get an appmake error
```
appmake [+target] [options]

The z88dk application generator

This program is used to produce files which are suitable for use in
emulators or on the real hardware. Supported targets are:
...
```

**Comment by suborb** [comment]
A fully formed basic file emerges from the linking stage so -create-app isn't needed.

See examples/z88/Makefile or the wiki for example.

**Comment by Fabrizio-Caruso** [comment]
@suborb The wiki says that I need -create-app to create an app and no -create-app to create a basic file:
https://github.com/z88dk/z88dk/wiki/Platform---Cambridge-z88

**Comment by Fabrizio-Caruso** [comment]
@suborb I want to understand how to build an application and I am following the wiki:
"
Z88 Application Target
Z88dk can be used to create a z88 Applications that can be run from the Main Menu. Both good, bad and ugly applications can be constructed.
Command Line
zcc +z88 -create-app ...
...
"

**Comment by suborb** [comment]
Ah sorry, I've spotted the doc error now, it's missing `-subtype=app` to build an application.
