### ISSUE TITLE
[sms][bug/question] I cannot start the "hello world" example

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#977]
I cannot start the simple hello world example (the one in z88dk\libsrc\_DEVELOPMENT\EXAMPLES\sms\helloworld).
I compile it with:
```
	$(Z88DK_PATH)$(MYZ88DK) +sms -startup=1 -clib=new -O3 \
	-vn -pragma-include:$(CFG_PATH)/z88dk/zpragma_sms.inc \
	-create-app	\
	$(SOURCE_PATH)/../experiments/z88dk_hello.c 
```
where zpragma_sms.inc (same as the one in C:\z88dk\libsrc\_DEVELOPMENT\EXAMPLES\sms\helloworld)

I then get an a.sms file which I try to load into an emulator?
How?
I use Fusion364 I just get an empry grey screen.

**Comment by aralbrec** [comment]
<sigh> something has happened.  It's like the memory<->vram copy functions as I recall making a change a short while ago.  I'll have a look tonight.

**Comment by aralbrec** [comment]
It should be fixed in the Sep 19 build

**Comment by Fabrizio-Caruso** [comment]
@aralbrec 
@suborb 

Yes and no or maybe it is just me doing something wrong.
I can now start the hello world example.
Anything bigger produces a warning about the number bad pages.
I try to fix this by 
#pragma reqpag=BAD_PAGES
Where BAD_PAGES is the number of required extra pages.

I compile and now I get zero bad pages:
"
App will use 0 pages of bad memory
Safe data is 120
"
but an extra  a_bss_fardata.bin file is generated.

If I load and start the application I get a frozen screen at start up.

This is what I use for my game
```
	#include <dor.h>
	#pragma -no-expandz88
	
	#if !defined(TINY_GAME)
		#define BAD_PAGES 2
	#else
		#define BAD_PAGES 1
	#endif 
	#pragma -reqpag=BAD_PAGES
	
	#pragma printf = ""

	// #pragma redirect redrawscreen=_redrawscreen
	
	#define APP_INFO "by Fabrizio Caruso"
	#define APP_KEY  'X'
	#define APP_NAME "XChase"
	#define APP_TYPE AT_Good
	
	#include <application.h>
```

I don't understand when and if I need to redefine redrawscreen.
