### ISSUE TITLE
[z88][question] "Application will use 1 pages of bad memory"

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#978]
When compiling a simple "hello world" example I get:
"Application will use 1 pages of bad memory"

Is it a harmless warning? How can I prevent it?

/cygdrive/c/z88dk/bin/zcc.exe +z88 -O3 -D__Z88__ -create-app -subtype=app \
chase/../experiments/hello.c
Application will use 1 pages of bad memory
Safe data is 120

**Comment by suborb** [comment]
These are just informational messages relating to memory management - just ignore them.
