### ISSUE TITLE
[z88][bug?] Sprite glitches?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#986]
Sprites are wrongly displayed on the z88 target.

I am following @suborb's suggestion to define a window in my initialization code:
```
		static struct window win; /* Window structure */ 	
	
		win.graph=1; 
		win.width=255; 
		win.number='4'; 
		window(win); 
```

With the window definition above, the sprites are sort of displayed but very wrongly.

I must be missing some other important details on how to use sprites with this target.

![z88](https://user-images.githubusercontent.com/29057615/45943148-7966db00-bfe5-11e8-9859-8028110ea833.jpg)

**Comment by suborb** [comment]
I've replaced the self-modifying version of putsprite with the generic version that will work when in a ROM!

A quick test shows that it works as well as graphics in general working on the z88.

**Comment by Fabrizio-Caruso** [comment]
Yes, indeed it does work.
